/* AMAZON — Bags (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-bags-001',
    name:           'Luxury PU Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          42.32,
    originalPrice:  100.75,
    discount:       58,
    rating:         4.8,
    reviews:        10062,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-002',
    name:           'Canvas Tote Bag — Aesthetic Prints',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          35.32,
    originalPrice:  78.49,
    discount:       55,
    rating:         4.0,
    reviews:        8530,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-003',
    name:           'Laptop Backpack — Anti-Theft 15.6"',
    category:       'bags',
    subcategory:    'Totes',
    price:          24.66,
    originalPrice:  61.66,
    discount:       60,
    rating:         4.4,
    reviews:        20044,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "backpack", "totes", "purse"]
  },
  {
    id:             'ama-bags-004',
    name:           'Mini Crossbody Bag — Quilted Chain',
    category:       'bags',
    subcategory:    'Wallets',
    price:          70.69,
    originalPrice:  98.18,
    discount:       28,
    rating:         4.9,
    reviews:        10514,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-005',
    name:           'Rattan Summer Handbag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          48.6,
    originalPrice:  77.15,
    discount:       37,
    rating:         4.9,
    reviews:        6296,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-006',
    name:           'Clear Stadium Bag — PVC',
    category:       'bags',
    subcategory:    'Handbags',
    price:          15.82,
    originalPrice:  38.59,
    discount:       59,
    rating:         4.8,
    reviews:        8515,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-007',
    name:           'Large Slouchy Hobo Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          8.66,
    originalPrice:  13.32,
    discount:       35,
    rating:         4.3,
    reviews:        10648,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-008',
    name:           'Croc-Effect Tote Bag — Beige',
    category:       'bags',
    subcategory:    'Totes',
    price:          10.65,
    originalPrice:  19.02,
    discount:       44,
    rating:         4.4,
    reviews:        20477,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-009',
    name:           'Woven Bucket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          7.83,
    originalPrice:  12.84,
    discount:       39,
    rating:         4.8,
    reviews:        21308,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-010',
    name:           'Belt Bag — Nylon',
    category:       'bags',
    subcategory:    'Clutches',
    price:          57.58,
    originalPrice:  79.97,
    discount:       28,
    rating:         4.3,
    reviews:        16971,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-011',
    name:           'Flap Crossbody Bag — Brown',
    category:       'bags',
    subcategory:    'Handbags',
    price:          10.62,
    originalPrice:  24.13,
    discount:       56,
    rating:         4.5,
    reviews:        441,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-012',
    name:           'Structured Top Handle Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          21.47,
    originalPrice:  55.06,
    discount:       61,
    rating:         4.1,
    reviews:        13462,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-013',
    name:           'Travel Duffel Bag — Weekender',
    category:       'bags',
    subcategory:    'Totes',
    price:          64.52,
    originalPrice:  109.35,
    discount:       41,
    rating:         5.0,
    reviews:        493,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-014',
    name:           'Waist Fanny Pack — Black',
    category:       'bags',
    subcategory:    'Wallets',
    price:          10.55,
    originalPrice:  20.28,
    discount:       48,
    rating:         4.9,
    reviews:        14140,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "wallets", "bags", "purse", "pack"]
  },
  {
    id:             'ama-bags-015',
    name:           'Knitted Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          14.71,
    originalPrice:  19.11,
    discount:       23,
    rating:         4.7,
    reviews:        21119,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-016',
    name:           'Mini Camera Bag — Velvet',
    category:       'bags',
    subcategory:    'Handbags',
    price:          61.87,
    originalPrice:  82.49,
    discount:       25,
    rating:         4.3,
    reviews:        22880,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-017',
    name:           'Oversized Shopper Tote',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          77.07,
    originalPrice:  110.1,
    discount:       30,
    rating:         4.2,
    reviews:        23220,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-018',
    name:           'Baguette Bag — Satin',
    category:       'bags',
    subcategory:    'Totes',
    price:          39.33,
    originalPrice:  106.31,
    discount:       63,
    rating:         5.0,
    reviews:        756,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-019',
    name:           'Backpack Purse — Vegan Leather',
    category:       'bags',
    subcategory:    'Wallets',
    price:          79.91,
    originalPrice:  102.45,
    discount:       22,
    rating:         4.3,
    reviews:        19843,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-020',
    name:           'Transparent Beach Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          54.79,
    originalPrice:  78.27,
    discount:       30,
    rating:         4.6,
    reviews:        21424,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-021',
    name:           'Bamboo Handle Tote',
    category:       'bags',
    subcategory:    'Handbags',
    price:          20.53,
    originalPrice:  32.59,
    discount:       37,
    rating:         4.5,
    reviews:        19361,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-022',
    name:           'Convertible Backpack Handbag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          33.11,
    originalPrice:  87.14,
    discount:       62,
    rating:         4.5,
    reviews:        21246,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-023',
    name:           'Envelope Clutch Bag — Gold',
    category:       'bags',
    subcategory:    'Totes',
    price:          51.49,
    originalPrice:  114.43,
    discount:       55,
    rating:         4.6,
    reviews:        9044,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-024',
    name:           'Micro Mini Bag — Chain Strap',
    category:       'bags',
    subcategory:    'Wallets',
    price:          8.93,
    originalPrice:  14.4,
    discount:       38,
    rating:         4.9,
    reviews:        9529,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-025',
    name:           'Studded Leather Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          43.34,
    originalPrice:  114.04,
    discount:       62,
    rating:         4.0,
    reviews:        6245,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "crossbody", "clutches", "purse"]
  },
  {
    id:             'ama-bags-026',
    name:           'Geometric Structured Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          43.8,
    originalPrice:  109.49,
    discount:       60,
    rating:         4.4,
    reviews:        17614,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-027',
    name:           'Drawstring Bucket Bag — Cord',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          14.89,
    originalPrice:  20.12,
    discount:       26,
    rating:         4.5,
    reviews:        15972,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-028',
    name:           'Vintage Flap Shoulder Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          13.25,
    originalPrice:  22.45,
    discount:       41,
    rating:         5.0,
    reviews:        13967,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-029',
    name:           'Wicker Market Basket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          30.94,
    originalPrice:  51.56,
    discount:       40,
    rating:         4.1,
    reviews:        12339,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-030',
    name:           'Circle Bag — Wooden Handle',
    category:       'bags',
    subcategory:    'Clutches',
    price:          37.42,
    originalPrice:  56.7,
    discount:       34,
    rating:         4.2,
    reviews:        9593,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-031',
    name:           'Satin Evening Clutch — Pearl',
    category:       'bags',
    subcategory:    'Handbags',
    price:          40.73,
    originalPrice:  94.71,
    discount:       57,
    rating:         4.5,
    reviews:        16865,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "handbags", "bags", "clutch", "purse"]
  },
  {
    id:             'ama-bags-032',
    name:           'Doctor Bag — Brown Leather',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          68.08,
    originalPrice:  109.81,
    discount:       38,
    rating:         4.3,
    reviews:        23190,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-033',
    name:           'Graffiti Print Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          48.77,
    originalPrice:  66.81,
    discount:       27,
    rating:         4.6,
    reviews:        19980,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-034',
    name:           'Chain Handle Shoulder Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          19.16,
    originalPrice:  50.43,
    discount:       62,
    rating:         4.6,
    reviews:        17010,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-035',
    name:           'PVC Jelly Bag — Transparent',
    category:       'bags',
    subcategory:    'Clutches',
    price:          38.9,
    originalPrice:  64.84,
    discount:       40,
    rating:         4.8,
    reviews:        6000,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-036',
    name:           'Knot Handle Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          45.41,
    originalPrice:  108.13,
    discount:       58,
    rating:         4.5,
    reviews:        4665,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-037',
    name:           'Tassel Fringe Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          84.72,
    originalPrice:  117.66,
    discount:       28,
    rating:         4.7,
    reviews:        2033,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-038',
    name:           'Reversible Tote Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          13.23,
    originalPrice:  19.46,
    discount:       32,
    rating:         4.9,
    reviews:        20317,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-039',
    name:           'Large Raffia Beach Tote',
    category:       'bags',
    subcategory:    'Wallets',
    price:          45.62,
    originalPrice:  77.33,
    discount:       41,
    rating:         4.8,
    reviews:        18612,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-040',
    name:           'Phone Bag — Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          15.56,
    originalPrice:  33.11,
    discount:       53,
    rating:         4.8,
    reviews:        13006,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-041',
    name:           'Chic Mini Backpack',
    category:       'bags',
    subcategory:    'Handbags',
    price:          43.78,
    originalPrice:  109.46,
    discount:       60,
    rating:         4.4,
    reviews:        13116,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "handbags", "bags", "backpack", "purse"]
  },
  {
    id:             'ama-bags-042',
    name:           'Lock Clasp Structured Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          21.91,
    originalPrice:  35.91,
    discount:       39,
    rating:         4.1,
    reviews:        16013,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-043',
    name:           'Rope Handle Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          39.53,
    originalPrice:  87.85,
    discount:       55,
    rating:         4.6,
    reviews:        10495,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-044',
    name:           'Patchwork Denim Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          83.18,
    originalPrice:  112.41,
    discount:       26,
    rating:         4.9,
    reviews:        9995,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ama-bags-045',
    name:           'Woven Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          59.19,
    originalPrice:  79.99,
    discount:       26,
    rating:         4.6,
    reviews:        19469,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ama-bags-046',
    name:           'Feather Trim Evening Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          76.85,
    originalPrice:  99.8,
    discount:       23,
    rating:         4.6,
    reviews:        546,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ama-bags-047',
    name:           'Nylon Messenger Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          52.96,
    originalPrice:  85.42,
    discount:       38,
    rating:         4.2,
    reviews:        10113,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ama-bags-048',
    name:           'Half-Moon Crescent Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          30.46,
    originalPrice:  87.02,
    discount:       65,
    rating:         4.6,
    reviews:        13892,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ama-bags-049',
    name:           'Snakeskin Effect Clutch',
    category:       'bags',
    subcategory:    'Wallets',
    price:          25.32,
    originalPrice:  53.87,
    discount:       53,
    rating:         4.7,
    reviews:        12456,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tote", "handbag", "bags", "clutch", "purse", "wallets"]
  },
  {
    id:             'ama-bags-050',
    name:           'Double Zip Crossbody Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          22.11,
    originalPrice:  31.58,
    discount:       30,
    rating:         4.6,
    reviews:        13081,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BAGS050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  }
);
