/* AMAZON — Electronics (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-elec-001',
    name:           'Smart Watch Pro — Fitness Tracker',
    category:       'electronics',
    subcategory:    'Phones',
    price:          43.4,
    originalPrice:  58.65,
    discount:       26,
    rating:         4.5,
    reviews:        17990,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gadgets", "smart", "pro", "phones"]
  },
  {
    id:             'ama-elec-002',
    name:           'TWS Wireless Earbuds — Noise Cancelling',
    category:       'electronics',
    subcategory:    'Audio',
    price:          28.24,
    originalPrice:  74.32,
    discount:       62,
    rating:         4.5,
    reviews:        16948,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'ama-elec-003',
    name:           'Bluetooth 5.3 Over-Ear Headphones',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          40.97,
    originalPrice:  64.02,
    discount:       36,
    rating:         4.5,
    reviews:        7745,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "headphones"]
  },
  {
    id:             'ama-elec-004',
    name:           'Mini Projector for Home Cinema',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          77.32,
    originalPrice:  97.87,
    discount:       21,
    rating:         4.5,
    reviews:        18941,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "cinema", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-005',
    name:           'RGB Mechanical Gaming Keyboard',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          46.11,
    originalPrice:  87.0,
    discount:       47,
    rating:         4.9,
    reviews:        3046,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-006',
    name:           '3-in-1 Wireless Charging Pad — 15W',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          23.98,
    originalPrice:  64.81,
    discount:       63,
    rating:         4.2,
    reviews:        10235,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "pad", "electronics", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-007',
    name:           'Smart LED Bulb — Colour Changing WiFi',
    category:       'electronics',
    subcategory:    'Phones',
    price:          79.11,
    originalPrice:  118.08,
    discount:       33,
    rating:         4.8,
    reviews:        21038,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "bulb", "gadgets", "smart", "phones"]
  },
  {
    id:             'ama-elec-008',
    name:           'Xiaomi Power Bank 20000mAh',
    category:       'electronics',
    subcategory:    'Audio',
    price:          36.32,
    originalPrice:  75.66,
    discount:       52,
    rating:         4.8,
    reviews:        894,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "electronics", "20000mah", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-009',
    name:           'Portable Bluetooth Speaker — Waterproof',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          61.31,
    originalPrice:  91.51,
    discount:       33,
    rating:         4.0,
    reviews:        5683,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "speaker", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-010',
    name:           'Ring Light — 10" Selfie',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          63.82,
    originalPrice:  104.63,
    discount:       39,
    rating:         4.8,
    reviews:        16671,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "light"]
  },
  {
    id:             'ama-elec-011',
    name:           'Gaming Mouse — RGB Backlit',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          33.87,
    originalPrice:  54.63,
    discount:       38,
    rating:         4.2,
    reviews:        16805,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gaming", "gadgets", "mouse", "smart"]
  },
  {
    id:             'ama-elec-012',
    name:           'USB-C Hub — 7 Port',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          32.14,
    originalPrice:  45.27,
    discount:       29,
    rating:         4.3,
    reviews:        19476,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "accessories", "gadgets", "hub", "smart"]
  },
  {
    id:             'ama-elec-013',
    name:           'Webcam HD 1080p — Built-in Mic',
    category:       'electronics',
    subcategory:    'Phones',
    price:          66.16,
    originalPrice:  112.13,
    discount:       41,
    rating:         4.0,
    reviews:        8403,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gadgets", "smart", "1080p", "phones"]
  },
  {
    id:             'ama-elec-014',
    name:           'Smart Plug — Voice Control',
    category:       'electronics',
    subcategory:    'Audio',
    price:          51.4,
    originalPrice:  64.25,
    discount:       20,
    rating:         4.7,
    reviews:        3905,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["plug", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-015',
    name:           'Electric Toothbrush — Rechargeable',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          5.37,
    originalPrice:  15.33,
    discount:       65,
    rating:         4.2,
    reviews:        3268,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "toothbrush", "smart"]
  },
  {
    id:             'ama-elec-016',
    name:           'Noise Cancelling Earbuds',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          48.85,
    originalPrice:  75.15,
    discount:       35,
    rating:         4.6,
    reviews:        24120,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'ama-elec-017',
    name:           'Dash Cam — Front & Rear 4K',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          60.43,
    originalPrice:  102.43,
    discount:       41,
    rating:         4.1,
    reviews:        22097,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "cam"]
  },
  {
    id:             'ama-elec-018',
    name:           'Smart Scale — Body Fat Analysis',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          55.5,
    originalPrice:  102.77,
    discount:       46,
    rating:         4.6,
    reviews:        6568,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "scale", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-019',
    name:           'Portable SSD — 1TB',
    category:       'electronics',
    subcategory:    'Phones',
    price:          33.06,
    originalPrice:  71.88,
    discount:       54,
    rating:         4.2,
    reviews:        3774,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gadgets", "ssd", "smart", "phones"]
  },
  {
    id:             'ama-elec-020',
    name:           'HDMI Cable 4K — 2m',
    category:       'electronics',
    subcategory:    'Audio',
    price:          58.19,
    originalPrice:  79.71,
    discount:       27,
    rating:         5.0,
    reviews:        8085,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "4k", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-021',
    name:           'Smart Home Security Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          69.94,
    originalPrice:  90.83,
    discount:       23,
    rating:         5.0,
    reviews:        4425,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "camera"]
  },
  {
    id:             'ama-elec-022',
    name:           'Digital Photo Frame — Wi-Fi',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          60.58,
    originalPrice:  87.8,
    discount:       31,
    rating:         4.8,
    reviews:        14900,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["frame", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-023',
    name:           'Kids\' Tablet — 10" Android',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          16.79,
    originalPrice:  25.44,
    discount:       34,
    rating:         4.3,
    reviews:        5323,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "tablet", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-024',
    name:           'Wireless Gaming Controller',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          37.86,
    originalPrice:  72.8,
    discount:       48,
    rating:         4.9,
    reviews:        19008,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "controller"]
  },
  {
    id:             'ama-elec-025',
    name:           'Robot Vacuum Cleaner — Smart Map',
    category:       'electronics',
    subcategory:    'Phones',
    price:          19.37,
    originalPrice:  32.29,
    discount:       40,
    rating:         4.7,
    reviews:        18576,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gadgets", "smart", "cleaner", "phones"]
  },
  {
    id:             'ama-elec-026',
    name:           'Air Purifier — HEPA Filter',
    category:       'electronics',
    subcategory:    'Audio',
    price:          21.05,
    originalPrice:  35.08,
    discount:       40,
    rating:         4.1,
    reviews:        10177,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "electronics", "purifier", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-027',
    name:           'Smart Doorbell — HD Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          47.26,
    originalPrice:  84.4,
    discount:       44,
    rating:         4.4,
    reviews:        18480,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "doorbell"]
  },
  {
    id:             'ama-elec-028',
    name:           'Portable Projector Screen — 120"',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          28.07,
    originalPrice:  65.27,
    discount:       57,
    rating:         4.8,
    reviews:        18738,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["screen", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-029',
    name:           'Mini Keyboard — Bluetooth',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          20.23,
    originalPrice:  38.17,
    discount:       47,
    rating:         4.6,
    reviews:        24686,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-030',
    name:           'Action Camera — 4K Waterproof',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          7.77,
    originalPrice:  19.42,
    discount:       60,
    rating:         4.2,
    reviews:        17380,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "camera"]
  },
  {
    id:             'ama-elec-031',
    name:           'VR Headset — Standalone',
    category:       'electronics',
    subcategory:    'Phones',
    price:          10.12,
    originalPrice:  22.49,
    discount:       55,
    rating:         4.1,
    reviews:        11168,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'ama-elec-032',
    name:           'Laser Printer — Wireless',
    category:       'electronics',
    subcategory:    'Audio',
    price:          28.32,
    originalPrice:  41.04,
    discount:       31,
    rating:         4.1,
    reviews:        19155,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["printer", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-033',
    name:           'Smart TV Stick — 4K Streaming',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          36.14,
    originalPrice:  75.3,
    discount:       52,
    rating:         4.2,
    reviews:        1245,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["stick", "tech", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-034',
    name:           'Electric Hand Massager',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          21.76,
    originalPrice:  55.79,
    discount:       61,
    rating:         4.3,
    reviews:        9667,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "massager"]
  },
  {
    id:             'ama-elec-035',
    name:           'Foldable Phone Stand Holder',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          69.1,
    originalPrice:  86.38,
    discount:       20,
    rating:         4.3,
    reviews:        23533,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'ama-elec-036',
    name:           'Wireless Earbuds Case — Leather',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          26.99,
    originalPrice:  49.98,
    discount:       46,
    rating:         5.0,
    reviews:        4557,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "accessories", "case", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-037',
    name:           'Gaming Headset — Surround Sound',
    category:       'electronics',
    subcategory:    'Phones',
    price:          9.8,
    originalPrice:  16.07,
    discount:       39,
    rating:         4.4,
    reviews:        13071,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'ama-elec-038',
    name:           'LED Desk Lamp — USB Charging',
    category:       'electronics',
    subcategory:    'Audio',
    price:          46.21,
    originalPrice:  82.51,
    discount:       44,
    rating:         4.6,
    reviews:        17023,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "lamp"]
  },
  {
    id:             'ama-elec-039',
    name:           'Smart Thermostat — Wi-Fi',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          69.04,
    originalPrice:  87.39,
    discount:       21,
    rating:         4.5,
    reviews:        16204,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "thermostat"]
  },
  {
    id:             'ama-elec-040',
    name:           'Portable Power Station — 500W',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          69.83,
    originalPrice:  94.37,
    discount:       26,
    rating:         4.1,
    reviews:        8550,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "station", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-041',
    name:           'E-Reader — Backlit 6"',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          70.17,
    originalPrice:  115.03,
    discount:       39,
    rating:         4.9,
    reviews:        12677,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "e-reader"]
  },
  {
    id:             'ama-elec-042',
    name:           'Cable Management Box',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          51.0,
    originalPrice:  110.88,
    discount:       54,
    rating:         4.4,
    reviews:        12642,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "box", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-043',
    name:           'Smart Speaker — Voice Assistant',
    category:       'electronics',
    subcategory:    'Phones',
    price:          54.5,
    originalPrice:  92.38,
    discount:       41,
    rating:         4.7,
    reviews:        6648,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "speaker", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'ama-elec-044',
    name:           'Drawing Tablet — A5',
    category:       'electronics',
    subcategory:    'Audio',
    price:          68.15,
    originalPrice:  97.36,
    discount:       30,
    rating:         4.1,
    reviews:        3619,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "tablet", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-045',
    name:           'Solar Charger Panel — 20W',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          5.59,
    originalPrice:  14.34,
    discount:       61,
    rating:         4.2,
    reviews:        19356,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "panel"]
  },
  {
    id:             'ama-elec-046',
    name:           'USB Microphone — Podcast',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          34.82,
    originalPrice:  62.17,
    discount:       44,
    rating:         4.2,
    reviews:        3269,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "microphone", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-047',
    name:           'Car Phone Holder — Magnetic',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          41.39,
    originalPrice:  70.16,
    discount:       41,
    rating:         4.8,
    reviews:        6573,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'ama-elec-048',
    name:           'Smart Door Lock — Fingerprint',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          19.31,
    originalPrice:  33.87,
    discount:       43,
    rating:         4.2,
    reviews:        24319,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "electronics", "accessories", "lock", "gadgets", "smart"]
  },
  {
    id:             'ama-elec-049',
    name:           'Dash Cam Hardwire Kit',
    category:       'electronics',
    subcategory:    'Phones',
    price:          21.29,
    originalPrice:  57.54,
    discount:       63,
    rating:         4.1,
    reviews:        19725,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "tech", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'ama-elec-050',
    name:           'Screen Protector — Tempered Glass',
    category:       'electronics',
    subcategory:    'Audio',
    price:          58.81,
    originalPrice:  115.32,
    discount:       49,
    rating:         4.4,
    reviews:        6896,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0ELEC050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "protector"]
  }
);
