/* AMAZON — Flowers (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-flow-001',
    name:           'Luxury Rose Bouquet — 24 Stems',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          10.13,
    originalPrice:  27.38,
    discount:       63,
    rating:         4.4,
    reviews:        16497,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-002',
    name:           'Sunflower & Wildflower Mix Bunch',
    category:       'flowers',
    subcategory:    'Dried',
    price:          12.94,
    originalPrice:  16.8,
    discount:       23,
    rating:         4.2,
    reviews:        23251,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-003',
    name:           'Eternal Preserved Roses — Box',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          30.33,
    originalPrice:  61.89,
    discount:       51,
    rating:         4.2,
    reviews:        12340,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "roses", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-004',
    name:           'Dried Pampas Grass Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          32.15,
    originalPrice:  63.04,
    discount:       49,
    rating:         4.6,
    reviews:        7491,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ama-flow-005',
    name:           'Tulip Mixed Colours — 15 Stems',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          38.01,
    originalPrice:  97.45,
    discount:       61,
    rating:         4.2,
    reviews:        24483,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "colours", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-006',
    name:           'Orchid Plant — Pink Phalaenopsis',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          38.98,
    originalPrice:  99.95,
    discount:       61,
    rating:         4.5,
    reviews:        21796,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet", "plant"]
  },
  {
    id:             'ama-flow-007',
    name:           'Peony & Rose Arrangement',
    category:       'flowers',
    subcategory:    'Dried',
    price:          7.19,
    originalPrice:  20.54,
    discount:       65,
    rating:         4.7,
    reviews:        20724,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "dried", "arrangement", "bouquet"]
  },
  {
    id:             'ama-flow-008',
    name:           'Lavender Bundle — Dried',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          22.08,
    originalPrice:  55.19,
    discount:       60,
    rating:         4.4,
    reviews:        5560,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "floral", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-009',
    name:           'Succulent Mini Garden Set',
    category:       'flowers',
    subcategory:    'Plants',
    price:          56.11,
    originalPrice:  72.87,
    discount:       23,
    rating:         4.6,
    reviews:        18892,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "set", "bouquet"]
  },
  {
    id:             'ama-flow-010',
    name:           'Hydrangea Arrangement — Blue',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          12.35,
    originalPrice:  21.3,
    discount:       42,
    rating:         4.2,
    reviews:        21353,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "gift_sets", "arrangement", "bouquet"]
  },
  {
    id:             'ama-flow-011',
    name:           'Artificial Rose Garland — 2m',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          73.26,
    originalPrice:  96.39,
    discount:       24,
    rating:         4.3,
    reviews:        1954,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "garland", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-012',
    name:           'Birthday Balloon & Flower Box',
    category:       'flowers',
    subcategory:    'Dried',
    price:          13.53,
    originalPrice:  18.53,
    discount:       27,
    rating:         5.0,
    reviews:        14619,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-013',
    name:           'Spring Daffodil Bunch — Yellow',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          30.92,
    originalPrice:  41.79,
    discount:       26,
    rating:         4.4,
    reviews:        11851,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "bunch", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-014',
    name:           'Gypsophila (Baby\'s Breath) Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          48.0,
    originalPrice:  92.31,
    discount:       48,
    rating:         4.9,
    reviews:        12467,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ama-flow-015',
    name:           'Lily & Gerbera Mix Bouquet',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          59.01,
    originalPrice:  92.2,
    discount:       36,
    rating:         4.9,
    reviews:        21780,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-016',
    name:           'Dried Flowers Wreath — 30cm',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          58.2,
    originalPrice:  107.78,
    discount:       46,
    rating:         4.2,
    reviews:        12547,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "wreath", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-017',
    name:           'Cherry Blossom Stem — Artificial',
    category:       'flowers',
    subcategory:    'Dried',
    price:          48.29,
    originalPrice:  62.71,
    discount:       23,
    rating:         4.7,
    reviews:        8040,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "dried", "stem", "bouquet"]
  },
  {
    id:             'ama-flow-018',
    name:           'Faux Eucalyptus Garland',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          45.31,
    originalPrice:  58.09,
    discount:       22,
    rating:         4.5,
    reviews:        3823,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "artificial", "garland", "bouquet"]
  },
  {
    id:             'ama-flow-019',
    name:           'Annual Seeds Garden Pack',
    category:       'flowers',
    subcategory:    'Plants',
    price:          43.58,
    originalPrice:  75.13,
    discount:       42,
    rating:         4.8,
    reviews:        8550,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "bouquet", "pack"]
  },
  {
    id:             'ama-flow-020',
    name:           'Valentine Red Rose Bouquet — 12',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          68.86,
    originalPrice:  118.73,
    discount:       42,
    rating:         4.7,
    reviews:        17817,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-021',
    name:           'Chrysanthemum Spray — Mixed',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          11.44,
    originalPrice:  15.05,
    discount:       24,
    rating:         4.9,
    reviews:        20119,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "bouquet", "fresh", "spray"]
  },
  {
    id:             'ama-flow-022',
    name:           'Lotus Flower Floating Bowl Set',
    category:       'flowers',
    subcategory:    'Dried',
    price:          33.87,
    originalPrice:  91.53,
    discount:       63,
    rating:         4.3,
    reviews:        19400,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "dried", "set", "bouquet"]
  },
  {
    id:             'ama-flow-023',
    name:           'Tropical Foliage Arrangement',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          10.28,
    originalPrice:  17.42,
    discount:       41,
    rating:         4.8,
    reviews:        4003,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "artificial", "arrangement", "bouquet"]
  },
  {
    id:             'ama-flow-024',
    name:           'Bluebell Woodland Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          33.55,
    originalPrice:  55.0,
    discount:       39,
    rating:         4.6,
    reviews:        782,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'ama-flow-025',
    name:           'Carnation Bouquet — Rainbow',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          9.63,
    originalPrice:  17.51,
    discount:       45,
    rating:         4.6,
    reviews:        10038,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-026',
    name:           'Silk Artificial Orchid Stem',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          46.31,
    originalPrice:  79.84,
    discount:       42,
    rating:         4.8,
    reviews:        14026,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "fresh", "stem", "bouquet"]
  },
  {
    id:             'ama-flow-027',
    name:           'Boxed Infinity Roses — 9 Pack',
    category:       'flowers',
    subcategory:    'Dried',
    price:          32.05,
    originalPrice:  89.02,
    discount:       64,
    rating:         4.4,
    reviews:        1977,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "roses", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-028',
    name:           'Potted Jasmine Plant',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          79.69,
    originalPrice:  106.25,
    discount:       25,
    rating:         4.1,
    reviews:        13962,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "artificial", "bouquet", "plant"]
  },
  {
    id:             'ama-flow-029',
    name:           'Anemone & Ranunculus Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          22.43,
    originalPrice:  45.78,
    discount:       51,
    rating:         4.6,
    reviews:        7625,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'ama-flow-030',
    name:           'Flower Crown Making Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          72.4,
    originalPrice:  106.47,
    discount:       32,
    rating:         4.7,
    reviews:        12447,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-031',
    name:           'Wildflower Meadow Seed Mix',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          30.14,
    originalPrice:  38.64,
    discount:       22,
    rating:         4.1,
    reviews:        6172,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-032',
    name:           'Poppy Bunch — Orange & Red',
    category:       'flowers',
    subcategory:    'Dried',
    price:          16.99,
    originalPrice:  42.47,
    discount:       60,
    rating:         4.5,
    reviews:        10391,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-033',
    name:           'Wedding Buttonhole Kit — Rose',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          11.52,
    originalPrice:  16.23,
    discount:       29,
    rating:         4.0,
    reviews:        10214,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-034',
    name:           'Dried Protea & Ferns Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          20.42,
    originalPrice:  37.12,
    discount:       45,
    rating:         4.6,
    reviews:        14732,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ama-flow-035',
    name:           'Hanging Flower Ball — Silk',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          37.11,
    originalPrice:  54.57,
    discount:       32,
    rating:         4.1,
    reviews:        12053,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["ball", "floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-036',
    name:           'Daisy Chain Meadow Bunch',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          7.51,
    originalPrice:  12.11,
    discount:       38,
    rating:         4.6,
    reviews:        17220,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "bunch", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-037',
    name:           'Moss Terrarium Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          26.03,
    originalPrice:  52.06,
    discount:       50,
    rating:         4.5,
    reviews:        15084,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-038',
    name:           'Pressed Flower Bookmark Set',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          50.62,
    originalPrice:  117.72,
    discount:       57,
    rating:         4.7,
    reviews:        15413,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "artificial", "set", "bouquet"]
  },
  {
    id:             'ama-flow-039',
    name:           'Flower Frog Kenzan Holder',
    category:       'flowers',
    subcategory:    'Plants',
    price:          46.42,
    originalPrice:  116.06,
    discount:       60,
    rating:         4.4,
    reviews:        4907,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "holder", "bouquet"]
  },
  {
    id:             'ama-flow-040',
    name:           'Faux Wisteria Hanging Branch',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          50.62,
    originalPrice:  101.23,
    discount:       50,
    rating:         4.8,
    reviews:        13666,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "branch", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-041',
    name:           'Rose Petal Confetti — Biodegradable',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          7.08,
    originalPrice:  16.47,
    discount:       57,
    rating:         4.1,
    reviews:        9089,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "confetti", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-042',
    name:           'Ikebana Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          47.94,
    originalPrice:  68.49,
    discount:       30,
    rating:         4.1,
    reviews:        24798,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-043',
    name:           'Calla Lily Artificial Stems',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          24.81,
    originalPrice:  32.64,
    discount:       24,
    rating:         4.7,
    reviews:        16702,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "stems", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-044',
    name:           'Eucalyptus & White Rose Wreath',
    category:       'flowers',
    subcategory:    'Plants',
    price:          9.3,
    originalPrice:  25.82,
    discount:       64,
    rating:         4.4,
    reviews:        1204,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'ama-flow-045',
    name:           'Floral Foam Arrangement Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          30.72,
    originalPrice:  52.06,
    discount:       41,
    rating:         4.5,
    reviews:        787,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ama-flow-046',
    name:           'Edible Flower Mix — Microgreens',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          43.52,
    originalPrice:  117.62,
    discount:       63,
    rating:         4.5,
    reviews:        6466,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'ama-flow-047',
    name:           'Flower Subscription Box — Monthly',
    category:       'flowers',
    subcategory:    'Dried',
    price:          31.29,
    originalPrice:  65.19,
    discount:       52,
    rating:         4.6,
    reviews:        24968,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'ama-flow-048',
    name:           'Paper Flower Crafting Kit',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          34.24,
    originalPrice:  55.22,
    discount:       38,
    rating:         4.9,
    reviews:        12488,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ama-flow-049',
    name:           'Autumn Leaf Wreath — Door',
    category:       'flowers',
    subcategory:    'Plants',
    price:          43.19,
    originalPrice:  63.51,
    discount:       32,
    rating:         4.6,
    reviews:        14781,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'ama-flow-050',
    name:           'Festive Poinsettia Plant',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          66.9,
    originalPrice:  117.37,
    discount:       43,
    rating:         4.9,
    reviews:        12391,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0FLOW050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet", "plant"]
  }
);
