/* AMAZON — Men (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-men-001',
    name:           'Slim Fit Oxford Shirt — White',
    category:       'men',
    subcategory:    'Shirts',
    price:          42.23,
    originalPrice:  55.57,
    discount:       24,
    rating:         4.8,
    reviews:        11736,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shirt"]
  },
  {
    id:             'ama-men-002',
    name:           'Classic Polo Shirt — 5 Colours',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          59.88,
    originalPrice:  93.57,
    discount:       36,
    rating:         4.8,
    reviews:        22175,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "shirt"]
  },
  {
    id:             'ama-men-003',
    name:           'Men\'s Shalwar Kameez — Eid Edition',
    category:       'men',
    subcategory:    'Pants',
    price:          60.21,
    originalPrice:  79.23,
    discount:       24,
    rating:         4.6,
    reviews:        13079,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "kameez"]
  },
  {
    id:             'ama-men-004',
    name:           'Slim Fit Joggers — Stretch Fabric',
    category:       'men',
    subcategory:    'Suits',
    price:          8.79,
    originalPrice:  12.56,
    discount:       30,
    rating:         5.0,
    reviews:        2184,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "joggers"]
  },
  {
    id:             'ama-men-005',
    name:           'Oversized Graphic Tee',
    category:       'men',
    subcategory:    'Activewear',
    price:          26.03,
    originalPrice:  68.51,
    discount:       62,
    rating:         4.4,
    reviews:        24350,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "activewear", "tee"]
  },
  {
    id:             'ama-men-006',
    name:           'Linen Shirt — Short Sleeve',
    category:       'men',
    subcategory:    'Shorts',
    price:          79.25,
    originalPrice:  100.32,
    discount:       21,
    rating:         4.3,
    reviews:        10366,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "shirt"]
  },
  {
    id:             'ama-men-007',
    name:           'Cargo Trousers — Olive',
    category:       'men',
    subcategory:    'Outerwear',
    price:          74.27,
    originalPrice:  92.84,
    discount:       20,
    rating:         4.4,
    reviews:        9934,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "trousers", "outerwear"]
  },
  {
    id:             'ama-men-008',
    name:           'Chino Slim Fit Trousers',
    category:       'men',
    subcategory:    'Shirts',
    price:          59.01,
    originalPrice:  90.78,
    discount:       35,
    rating:         4.9,
    reviews:        6317,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "trousers"]
  },
  {
    id:             'ama-men-009',
    name:           'Zip-Up Hoodie — Grey Marl',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          69.94,
    originalPrice:  87.43,
    discount:       20,
    rating:         4.9,
    reviews:        1238,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["hoodie", "men", "fashion", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'ama-men-010',
    name:           'Merino Wool Crew Neck Jumper',
    category:       'men',
    subcategory:    'Pants',
    price:          66.28,
    originalPrice:  108.65,
    discount:       39,
    rating:         4.8,
    reviews:        7635,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "jumper"]
  },
  {
    id:             'ama-men-011',
    name:           'Denim Jacket — Dark Wash',
    category:       'men',
    subcategory:    'Suits',
    price:          22.46,
    originalPrice:  32.08,
    discount:       30,
    rating:         4.9,
    reviews:        16932,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "suits", "casual", "clothing"]
  },
  {
    id:             'ama-men-012',
    name:           'Puffer Gilet — Navy',
    category:       'men',
    subcategory:    'Activewear',
    price:          53.07,
    originalPrice:  88.45,
    discount:       40,
    rating:         5.0,
    reviews:        12116,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "gilet", "casual", "clothing", "activewear"]
  },
  {
    id:             'ama-men-013',
    name:           'Formal Dress Shirt — French Cuff',
    category:       'men',
    subcategory:    'Shorts',
    price:          21.98,
    originalPrice:  43.1,
    discount:       49,
    rating:         4.2,
    reviews:        16898,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "shirt"]
  },
  {
    id:             'ama-men-014',
    name:           'Tuxedo Suit — Black',
    category:       'men',
    subcategory:    'Outerwear',
    price:          50.42,
    originalPrice:  96.96,
    discount:       48,
    rating:         4.2,
    reviews:        14053,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "suit"]
  },
  {
    id:             'ama-men-015',
    name:           'Bomber Jacket — Khaki',
    category:       'men',
    subcategory:    'Shirts',
    price:          50.64,
    originalPrice:  99.3,
    discount:       49,
    rating:         4.6,
    reviews:        849,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "shirts", "casual", "clothing"]
  },
  {
    id:             'ama-men-016',
    name:           'Relaxed Fit Linen Trousers',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          38.25,
    originalPrice:  47.81,
    discount:       20,
    rating:         4.2,
    reviews:        21173,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "trousers"]
  },
  {
    id:             'ama-men-017',
    name:           'Henley Shirt — Long Sleeve',
    category:       'men',
    subcategory:    'Pants',
    price:          51.54,
    originalPrice:  99.11,
    discount:       48,
    rating:         4.2,
    reviews:        20543,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "shirt"]
  },
  {
    id:             'ama-men-018',
    name:           'Sherpa Fleece Jacket',
    category:       'men',
    subcategory:    'Suits',
    price:          72.07,
    originalPrice:  112.61,
    discount:       36,
    rating:         4.2,
    reviews:        18211,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "suits", "casual", "clothing"]
  },
  {
    id:             'ama-men-019',
    name:           'Roll-Neck Knit Jumper',
    category:       'men',
    subcategory:    'Activewear',
    price:          46.59,
    originalPrice:  58.97,
    discount:       21,
    rating:         4.7,
    reviews:        21748,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "activewear", "jumper"]
  },
  {
    id:             'ama-men-020',
    name:           'Slim Fit Suit — Charcoal',
    category:       'men',
    subcategory:    'Shorts',
    price:          33.8,
    originalPrice:  91.34,
    discount:       63,
    rating:         4.3,
    reviews:        24049,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "suit"]
  },
  {
    id:             'ama-men-021',
    name:           'Basketball Shorts',
    category:       'men',
    subcategory:    'Outerwear',
    price:          48.81,
    originalPrice:  88.75,
    discount:       45,
    rating:         4.0,
    reviews:        2260,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "outerwear"]
  },
  {
    id:             'ama-men-022',
    name:           'Running Tights — Full Length',
    category:       'men',
    subcategory:    'Shirts',
    price:          57.7,
    originalPrice:  77.97,
    discount:       26,
    rating:         4.5,
    reviews:        21517,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "tights"]
  },
  {
    id:             'ama-men-023',
    name:           'Tech Fleece Tracksuit',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          14.87,
    originalPrice:  36.26,
    discount:       59,
    rating:         4.9,
    reviews:        6730,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "tracksuit"]
  },
  {
    id:             'ama-men-024',
    name:           'Waterproof Hiking Jacket',
    category:       'men',
    subcategory:    'Pants',
    price:          54.72,
    originalPrice:  97.72,
    discount:       44,
    rating:         4.7,
    reviews:        11122,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "pants", "casual", "clothing"]
  },
  {
    id:             'ama-men-025',
    name:           'Flannel Plaid Shirt',
    category:       'men',
    subcategory:    'Suits',
    price:          9.14,
    originalPrice:  20.78,
    discount:       56,
    rating:         4.5,
    reviews:        18371,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "shirt"]
  },
  {
    id:             'ama-men-026',
    name:           'Muscle Fit T-Shirt Pack x5',
    category:       'men',
    subcategory:    'Activewear',
    price:          30.74,
    originalPrice:  85.39,
    discount:       64,
    rating:         5.0,
    reviews:        18451,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "x5", "activewear"]
  },
  {
    id:             'ama-men-027',
    name:           'Tweed Blazer — Herringbone',
    category:       'men',
    subcategory:    'Shorts',
    price:          54.43,
    originalPrice:  93.84,
    discount:       42,
    rating:         4.4,
    reviews:        10635,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "blazer"]
  },
  {
    id:             'ama-men-028',
    name:           'Leather Biker Jacket',
    category:       'men',
    subcategory:    'Outerwear',
    price:          19.3,
    originalPrice:  40.21,
    discount:       52,
    rating:         4.6,
    reviews:        13543,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "outerwear"]
  },
  {
    id:             'ama-men-029',
    name:           'Velour Tracksuit — Navy',
    category:       'men',
    subcategory:    'Shirts',
    price:          25.0,
    originalPrice:  37.88,
    discount:       34,
    rating:         4.7,
    reviews:        8222,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "tracksuit"]
  },
  {
    id:             'ama-men-030',
    name:           'Peacoat — Camel',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          16.62,
    originalPrice:  36.93,
    discount:       55,
    rating:         4.3,
    reviews:        15612,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["peacoat", "men", "fashion", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'ama-men-031',
    name:           'Lightweight Rain Mac',
    category:       'men',
    subcategory:    'Pants',
    price:          34.93,
    originalPrice:  67.17,
    discount:       48,
    rating:         4.1,
    reviews:        17722,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "mac"]
  },
  {
    id:             'ama-men-032',
    name:           'Military Overshirt',
    category:       'men',
    subcategory:    'Suits',
    price:          29.63,
    originalPrice:  38.48,
    discount:       23,
    rating:         4.3,
    reviews:        24494,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "overshirt"]
  },
  {
    id:             'ama-men-033',
    name:           'Chelsea Boot Cut Jeans',
    category:       'men',
    subcategory:    'Activewear',
    price:          9.94,
    originalPrice:  25.49,
    discount:       61,
    rating:         4.4,
    reviews:        5591,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "jeans", "casual", "clothing", "activewear"]
  },
  {
    id:             'ama-men-034',
    name:           'Structured Chore Coat',
    category:       'men',
    subcategory:    'Shorts',
    price:          12.0,
    originalPrice:  15.59,
    discount:       23,
    rating:         4.7,
    reviews:        21542,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "coat"]
  },
  {
    id:             'ama-men-035',
    name:           'Striped Rugby Shirt',
    category:       'men',
    subcategory:    'Outerwear',
    price:          63.18,
    originalPrice:  101.9,
    discount:       38,
    rating:         4.1,
    reviews:        21508,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "shirt"]
  },
  {
    id:             'ama-men-036',
    name:           'Longline Parka — Black',
    category:       'men',
    subcategory:    'Shirts',
    price:          60.08,
    originalPrice:  107.29,
    discount:       44,
    rating:         4.2,
    reviews:        15418,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "parka"]
  },
  {
    id:             'ama-men-037',
    name:           'Slim Taper Jeans — Indigo',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          12.36,
    originalPrice:  15.85,
    discount:       22,
    rating:         4.4,
    reviews:        4341,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "jeans", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'ama-men-038',
    name:           'Quarter Zip Sweatshirt',
    category:       'men',
    subcategory:    'Pants',
    price:          6.89,
    originalPrice:  19.69,
    discount:       65,
    rating:         4.6,
    reviews:        8048,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "sweatshirt"]
  },
  {
    id:             'ama-men-039',
    name:           'Hawaiian Short Sleeve Shirt',
    category:       'men',
    subcategory:    'Suits',
    price:          78.87,
    originalPrice:  111.09,
    discount:       29,
    rating:         4.9,
    reviews:        2767,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "shirt"]
  },
  {
    id:             'ama-men-040',
    name:           'Pleated Formal Trousers',
    category:       'men',
    subcategory:    'Activewear',
    price:          69.46,
    originalPrice:  86.83,
    discount:       20,
    rating:         4.2,
    reviews:        12242,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "trousers", "activewear"]
  },
  {
    id:             'ama-men-041',
    name:           'Corduroy Shirt Jacket',
    category:       'men',
    subcategory:    'Shorts',
    price:          51.11,
    originalPrice:  73.01,
    discount:       30,
    rating:         4.3,
    reviews:        22642,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "shorts"]
  },
  {
    id:             'ama-men-042',
    name:           'Ribbed Knit Turtleneck',
    category:       'men',
    subcategory:    'Outerwear',
    price:          52.85,
    originalPrice:  105.71,
    discount:       50,
    rating:         4.9,
    reviews:        22825,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "turtleneck"]
  },
  {
    id:             'ama-men-043',
    name:           'Cargo Shorts',
    category:       'men',
    subcategory:    'Shirts',
    price:          53.39,
    originalPrice:  87.53,
    discount:       39,
    rating:         4.7,
    reviews:        15004,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shorts"]
  },
  {
    id:             'ama-men-044',
    name:           'Double Breasted Waistcoat',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          82.67,
    originalPrice:  108.78,
    discount:       24,
    rating:         4.7,
    reviews:        14934,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "waistcoat", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'ama-men-045',
    name:           'Pique Polo — Long Sleeve',
    category:       'men',
    subcategory:    'Pants',
    price:          53.68,
    originalPrice:  111.84,
    discount:       52,
    rating:         4.5,
    reviews:        5268,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "polo"]
  },
  {
    id:             'ama-men-046',
    name:           'Slim Fit Tuxedo Trousers',
    category:       'men',
    subcategory:    'Suits',
    price:          8.2,
    originalPrice:  12.81,
    discount:       36,
    rating:         5.0,
    reviews:        3530,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "trousers"]
  },
  {
    id:             'ama-men-047',
    name:           'Padded Quilted Jacket',
    category:       'men',
    subcategory:    'Activewear',
    price:          47.37,
    originalPrice:  118.42,
    discount:       60,
    rating:         4.9,
    reviews:        19380,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "activewear"]
  },
  {
    id:             'ama-men-048',
    name:           'Lounge Set — Cotton',
    category:       'men',
    subcategory:    'Shorts',
    price:          87.27,
    originalPrice:  113.34,
    discount:       23,
    rating:         4.7,
    reviews:        23269,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "set"]
  },
  {
    id:             'ama-men-049',
    name:           'Stretch Slim Chinos',
    category:       'men',
    subcategory:    'Outerwear',
    price:          48.17,
    originalPrice:  80.29,
    discount:       40,
    rating:         4.8,
    reviews:        9658,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "casual", "clothing", "chinos", "outerwear"]
  },
  {
    id:             'ama-men-050',
    name:           'Relaxed Fit Jogger Shorts',
    category:       'men',
    subcategory:    'Shirts',
    price:          47.64,
    originalPrice:  62.69,
    discount:       24,
    rating:         4.9,
    reviews:        7697,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0MEN050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shorts"]
  }
);
