/* AMAZON — Toys (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-toys-001',
    name:           'STEM Building Blocks Set — 250 Pieces',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          22.94,
    originalPrice:  65.54,
    discount:       65,
    rating:         4.2,
    reviews:        5368,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ama-toys-002',
    name:           'Remote Control Car — Off-Road 4WD',
    category:       'toys',
    subcategory:    'Board Games',
    price:          14.65,
    originalPrice:  22.54,
    discount:       35,
    rating:         4.3,
    reviews:        14070,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "car", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-003',
    name:           'Diamond Painting Kit — Beginner',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          25.66,
    originalPrice:  50.32,
    discount:       49,
    rating:         4.6,
    reviews:        8593,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ama-toys-004',
    name:           'Magnetic Drawing Board',
    category:       'toys',
    subcategory:    'Educational',
    price:          7.49,
    originalPrice:  19.7,
    discount:       62,
    rating:         4.1,
    reviews:        19211,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "board", "toys", "educational", "play"]
  },
  {
    id:             'ama-toys-005',
    name:           'Wooden Balance Bike — 3-6 Years',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          21.62,
    originalPrice:  60.05,
    discount:       64,
    rating:         4.3,
    reviews:        14754,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "bike"]
  },
  {
    id:             'ama-toys-006',
    name:           'Interactive Robot Toy',
    category:       'toys',
    subcategory:    'STEM',
    price:          33.67,
    originalPrice:  49.52,
    discount:       32,
    rating:         4.1,
    reviews:        19692,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "toy", "stem"]
  },
  {
    id:             'ama-toys-007',
    name:           'Art & Craft Mega Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          12.92,
    originalPrice:  34.93,
    discount:       63,
    rating:         4.5,
    reviews:        13493,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ama-toys-008',
    name:           'Foam Nerf-Style Blaster',
    category:       'toys',
    subcategory:    'Board Games',
    price:          42.52,
    originalPrice:  111.89,
    discount:       62,
    rating:         4.6,
    reviews:        10587,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "blaster", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-009',
    name:           'Mini Drone — Beginner Friendly',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          16.22,
    originalPrice:  30.6,
    discount:       47,
    rating:         4.1,
    reviews:        6104,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["drone", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ama-toys-010',
    name:           'Kids\' Walkie Talkies — 1km Range',
    category:       'toys',
    subcategory:    'Educational',
    price:          28.67,
    originalPrice:  53.1,
    discount:       46,
    rating:         4.8,
    reviews:        10425,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["talkies", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ama-toys-011',
    name:           'Dollhouse — 3-Storey Wooden',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          14.5,
    originalPrice:  38.17,
    discount:       62,
    rating:         4.4,
    reviews:        9714,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["dollhouse", "kids", "games", "toys", "outdoor", "play"]
  },
  {
    id:             'ama-toys-012',
    name:           'Train Set — 130 Pieces',
    category:       'toys',
    subcategory:    'STEM',
    price:          37.91,
    originalPrice:  59.23,
    discount:       36,
    rating:         4.3,
    reviews:        4141,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ama-toys-013',
    name:           'Slime Making Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          17.04,
    originalPrice:  48.68,
    discount:       65,
    rating:         4.4,
    reviews:        1340,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ama-toys-014',
    name:           'Sensory Sand Tray',
    category:       'toys',
    subcategory:    'Board Games',
    price:          22.05,
    originalPrice:  42.41,
    discount:       48,
    rating:         4.2,
    reviews:        8909,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "tray", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-015',
    name:           'Bubble Machine — Automatic',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          10.75,
    originalPrice:  22.87,
    discount:       53,
    rating:         4.3,
    reviews:        19619,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "puzzles", "play", "machine"]
  },
  {
    id:             'ama-toys-016',
    name:           'Giant Floor Puzzle — 100 Pieces',
    category:       'toys',
    subcategory:    'Educational',
    price:          12.28,
    originalPrice:  17.29,
    discount:       29,
    rating:         4.0,
    reviews:        13542,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "educational", "play", "puzzle"]
  },
  {
    id:             'ama-toys-017',
    name:           'Pop It Fidget Toy Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          70.86,
    originalPrice:  90.84,
    discount:       22,
    rating:         4.6,
    reviews:        14710,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ama-toys-018',
    name:           'Water Balloons — Self-Sealing 100pk',
    category:       'toys',
    subcategory:    'STEM',
    price:          46.91,
    originalPrice:  61.72,
    discount:       24,
    rating:         4.9,
    reviews:        7339,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "balloons", "toys", "play", "stem"]
  },
  {
    id:             'ama-toys-019',
    name:           'Kinetic Sand Set — 3kg',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          31.61,
    originalPrice:  58.53,
    discount:       46,
    rating:         5.0,
    reviews:        20662,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ama-toys-020',
    name:           'Outdoor Trampoline — 10ft',
    category:       'toys',
    subcategory:    'Board Games',
    price:          23.18,
    originalPrice:  42.93,
    discount:       46,
    rating:         5.0,
    reviews:        712,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "trampoline", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-021',
    name:           'Foam Ball Pit + 200 Balls',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          57.33,
    originalPrice:  106.16,
    discount:       46,
    rating:         4.3,
    reviews:        20637,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "balls", "puzzles", "play"]
  },
  {
    id:             'ama-toys-022',
    name:           'Science Experiment Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          30.1,
    originalPrice:  51.89,
    discount:       42,
    rating:         4.1,
    reviews:        20908,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ama-toys-023',
    name:           'Perler Bead Set — 5000 Pieces',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          40.69,
    originalPrice:  101.72,
    discount:       60,
    rating:         4.6,
    reviews:        21057,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ama-toys-024',
    name:           'Sticker Activity Book',
    category:       'toys',
    subcategory:    'STEM',
    price:          20.34,
    originalPrice:  39.88,
    discount:       49,
    rating:         4.2,
    reviews:        9691,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "book", "games", "toys", "play", "stem"]
  },
  {
    id:             'ama-toys-025',
    name:           'Action Figure Set — 12 Characters',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          22.82,
    originalPrice:  35.65,
    discount:       36,
    rating:         4.6,
    reviews:        7122,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ama-toys-026',
    name:           'Play Kitchen Set',
    category:       'toys',
    subcategory:    'Board Games',
    price:          66.91,
    originalPrice:  85.78,
    discount:       22,
    rating:         4.7,
    reviews:        18730,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "board_games"]
  },
  {
    id:             'ama-toys-027',
    name:           'Magnetic Tiles Set — 60 Pieces',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          12.33,
    originalPrice:  19.57,
    discount:       37,
    rating:         4.3,
    reviews:        4057,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "puzzles", "play", "set"]
  },
  {
    id:             'ama-toys-028',
    name:           'Soft Play Crawl Tunnel',
    category:       'toys',
    subcategory:    'Educational',
    price:          27.66,
    originalPrice:  79.04,
    discount:       65,
    rating:         4.7,
    reviews:        24847,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "educational", "play", "tunnel"]
  },
  {
    id:             'ama-toys-029',
    name:           'Outdoor Swing — Timber Frame',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          13.24,
    originalPrice:  16.55,
    discount:       20,
    rating:         4.7,
    reviews:        13849,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "swing"]
  },
  {
    id:             'ama-toys-030',
    name:           'Bath Toy Set — Squirt Animals',
    category:       'toys',
    subcategory:    'STEM',
    price:          27.65,
    originalPrice:  79.01,
    discount:       65,
    rating:         4.9,
    reviews:        4359,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ama-toys-031',
    name:           'Wooden Stacking Tower',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          17.01,
    originalPrice:  37.8,
    discount:       55,
    rating:         4.6,
    reviews:        7118,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tower", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ama-toys-032',
    name:           'Finger Painting Kit — Washable',
    category:       'toys',
    subcategory:    'Board Games',
    price:          61.98,
    originalPrice:  108.73,
    discount:       43,
    rating:         4.2,
    reviews:        15768,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-033',
    name:           'Stuffed Animal Bundle — 5 Pack',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          59.28,
    originalPrice:  87.17,
    discount:       32,
    rating:         4.3,
    reviews:        1170,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ama-toys-034',
    name:           'Mini Basketball Hoop — Indoor',
    category:       'toys',
    subcategory:    'Educational',
    price:          50.59,
    originalPrice:  71.26,
    discount:       29,
    rating:         4.3,
    reviews:        16784,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "educational", "hoop", "play"]
  },
  {
    id:             'ama-toys-035',
    name:           'Kids\' Karaoke Machine',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          55.12,
    originalPrice:  96.7,
    discount:       43,
    rating:         4.5,
    reviews:        4901,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "machine"]
  },
  {
    id:             'ama-toys-036',
    name:           'Roller Skates — Adjustable',
    category:       'toys',
    subcategory:    'STEM',
    price:          57.79,
    originalPrice:  93.21,
    discount:       38,
    rating:         4.4,
    reviews:        23934,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skates", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'ama-toys-037',
    name:           'Toy Cash Register',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          63.24,
    originalPrice:  90.35,
    discount:       30,
    rating:         4.3,
    reviews:        23450,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "action_figures", "register"]
  },
  {
    id:             'ama-toys-038',
    name:           'Kids\' Binoculars',
    category:       'toys',
    subcategory:    'Board Games',
    price:          28.63,
    originalPrice:  75.33,
    discount:       62,
    rating:         4.4,
    reviews:        2461,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["binoculars", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-039',
    name:           'Sand Water Table',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          12.54,
    originalPrice:  34.82,
    discount:       64,
    rating:         4.6,
    reviews:        4541,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "table", "puzzles", "play"]
  },
  {
    id:             'ama-toys-040',
    name:           'Lacing & Threading Set',
    category:       'toys',
    subcategory:    'Educational',
    price:          64.22,
    originalPrice:  89.19,
    discount:       28,
    rating:         4.5,
    reviews:        17465,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "educational", "play", "set"]
  },
  {
    id:             'ama-toys-041',
    name:           'Giant Jenga — Outdoor',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          41.76,
    originalPrice:  70.78,
    discount:       41,
    rating:         4.5,
    reviews:        14688,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "jenga"]
  },
  {
    id:             'ama-toys-042',
    name:           'Playdough 12-Colour Set',
    category:       'toys',
    subcategory:    'STEM',
    price:          10.28,
    originalPrice:  12.85,
    discount:       20,
    rating:         4.8,
    reviews:        23094,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ama-toys-043',
    name:           'Solar System Model Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          63.01,
    originalPrice:  110.55,
    discount:       43,
    rating:         4.4,
    reviews:        1910,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ama-toys-044',
    name:           'Coding Robot for Kids',
    category:       'toys',
    subcategory:    'Board Games',
    price:          40.97,
    originalPrice:  107.81,
    discount:       62,
    rating:         4.4,
    reviews:        18188,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ama-toys-045',
    name:           'Fairy Garden Kit',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          38.36,
    originalPrice:  59.93,
    discount:       36,
    rating:         4.9,
    reviews:        6421,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ama-toys-046',
    name:           'Space Rover Build Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          44.01,
    originalPrice:  81.5,
    discount:       46,
    rating:         4.1,
    reviews:        2662,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ama-toys-047',
    name:           'Kids\' Archery Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          47.6,
    originalPrice:  113.34,
    discount:       58,
    rating:         4.2,
    reviews:        18699,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ama-toys-048',
    name:           'Board Game Bundle — 5 Games',
    category:       'toys',
    subcategory:    'STEM',
    price:          46.89,
    originalPrice:  79.47,
    discount:       41,
    rating:         4.4,
    reviews:        23520,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'ama-toys-049',
    name:           'Glow in Dark Stars Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          31.09,
    originalPrice:  55.52,
    discount:       44,
    rating:         4.4,
    reviews:        17828,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ama-toys-050',
    name:           'Rocket Launcher + Foam Rockets',
    category:       'toys',
    subcategory:    'Board Games',
    price:          41.36,
    originalPrice:  59.09,
    discount:       30,
    rating:         4.3,
    reviews:        23040,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0TOYS050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kids", "games", "toys", "play", "board_games", "rockets"]
  }
);
