/* AMAZON — Watches (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-watc-001',
    name:           'Smart Watch Pro — Fitness Tracker',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          12.31,
    originalPrice:  19.85,
    discount:       38,
    rating:         4.4,
    reviews:        20249,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "smart_watches", "pro"]
  },
  {
    id:             'ama-watc-002',
    name:           '3-in-1 Wireless Charging Pad',
    category:       'watches',
    subcategory:    'Analog',
    price:          35.29,
    originalPrice:  76.72,
    discount:       54,
    rating:         4.4,
    reviews:        4284,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "pad", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-003',
    name:           'Minimalist Leather Strap Watch — Rose Gold',
    category:       'watches',
    subcategory:    'Digital',
    price:          42.75,
    originalPrice:  92.94,
    discount:       54,
    rating:         4.1,
    reviews:        22239,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-004',
    name:           'Chronograph Men\'s Watch — Black',
    category:       'watches',
    subcategory:    'Luxury',
    price:          22.31,
    originalPrice:  36.58,
    discount:       39,
    rating:         4.7,
    reviews:        15808,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-005',
    name:           'Digital Sports Watch — Waterproof',
    category:       'watches',
    subcategory:    'Sport',
    price:          21.41,
    originalPrice:  31.96,
    discount:       33,
    rating:         4.7,
    reviews:        24296,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-006',
    name:           'Ladies\' Rose Gold Bracelet Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          12.59,
    originalPrice:  20.64,
    discount:       39,
    rating:         4.4,
    reviews:        273,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-007',
    name:           'Fossil-Style Analogue Watch — Silver',
    category:       'watches',
    subcategory:    'Analog',
    price:          9.54,
    originalPrice:  19.07,
    discount:       50,
    rating:         4.9,
    reviews:        3215,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-008',
    name:           'Smart Watch with ECG Monitor',
    category:       'watches',
    subcategory:    'Digital',
    price:          58.73,
    originalPrice:  119.86,
    discount:       51,
    rating:         4.9,
    reviews:        2964,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["monitor", "smartwatch", "timepiece", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-009',
    name:           'Retro Wooden Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          48.1,
    originalPrice:  117.31,
    discount:       59,
    rating:         4.6,
    reviews:        4829,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-010',
    name:           'Kids\' Cartoon Character Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          55.9,
    originalPrice:  81.02,
    discount:       31,
    rating:         4.7,
    reviews:        3146,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-011',
    name:           'Automatic Self-Winding Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          34.74,
    originalPrice:  65.55,
    discount:       47,
    rating:         4.7,
    reviews:        15171,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-012',
    name:           'Solar Powered Watch — Men\'s',
    category:       'watches',
    subcategory:    'Analog',
    price:          67.87,
    originalPrice:  91.71,
    discount:       26,
    rating:         4.5,
    reviews:        3777,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-013',
    name:           'Ultra-Thin Quartz Watch — Gold',
    category:       'watches',
    subcategory:    'Digital',
    price:          12.83,
    originalPrice:  16.45,
    discount:       22,
    rating:         4.3,
    reviews:        11158,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-014',
    name:           'Ceramic White Strap Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          29.81,
    originalPrice:  38.71,
    discount:       23,
    rating:         4.8,
    reviews:        23165,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-015',
    name:           'Military Tactical Watch — Green',
    category:       'watches',
    subcategory:    'Sport',
    price:          38.85,
    originalPrice:  76.17,
    discount:       49,
    rating:         4.5,
    reviews:        23382,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-016',
    name:           'Ladies\' Marble Dial Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          35.2,
    originalPrice:  55.0,
    discount:       36,
    rating:         4.6,
    reviews:        3082,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-017',
    name:           'Dual Time Zone Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          52.7,
    originalPrice:  73.19,
    discount:       28,
    rating:         4.3,
    reviews:        15263,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-018',
    name:           'Skeleton Mechanical Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          39.75,
    originalPrice:  65.17,
    discount:       39,
    rating:         5.0,
    reviews:        3690,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-019',
    name:           'Pearl Dial Dress Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          30.83,
    originalPrice:  39.52,
    discount:       22,
    rating:         4.7,
    reviews:        5179,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-020',
    name:           'Titanium Sports Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          5.64,
    originalPrice:  12.26,
    discount:       54,
    rating:         4.8,
    reviews:        20203,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-021',
    name:           'Fashion Alloy Quartz Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          38.21,
    originalPrice:  69.48,
    discount:       45,
    rating:         4.8,
    reviews:        20703,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-022',
    name:           'GPS Running Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          62.49,
    originalPrice:  84.44,
    discount:       26,
    rating:         4.1,
    reviews:        16653,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-023',
    name:           'Smart Band Fitness Tracker',
    category:       'watches',
    subcategory:    'Digital',
    price:          71.19,
    originalPrice:  116.71,
    discount:       39,
    rating:         4.5,
    reviews:        19384,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tracker", "smartwatch", "timepiece", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-024',
    name:           'Classic Pocket Watch — Bronze',
    category:       'watches',
    subcategory:    'Luxury',
    price:          21.76,
    originalPrice:  34.54,
    discount:       37,
    rating:         4.5,
    reviews:        11383,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-025',
    name:           'Mesh Strap Watch — Silver',
    category:       'watches',
    subcategory:    'Sport',
    price:          18.97,
    originalPrice:  23.71,
    discount:       20,
    rating:         4.4,
    reviews:        17451,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-026',
    name:           'Luminous Hands Dive Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          51.84,
    originalPrice:  71.02,
    discount:       27,
    rating:         4.6,
    reviews:        13854,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-027',
    name:           'Slim Profile Men\'s Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          12.1,
    originalPrice:  15.72,
    discount:       23,
    rating:         4.6,
    reviews:        9053,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-028',
    name:           'Heart Rate Monitor Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          40.54,
    originalPrice:  62.37,
    discount:       35,
    rating:         4.2,
    reviews:        14964,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-029',
    name:           'Minimalist NATO Strap Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          15.49,
    originalPrice:  39.72,
    discount:       61,
    rating:         4.2,
    reviews:        21890,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-030',
    name:           'Ladies\' Swarovski Crystal Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          14.49,
    originalPrice:  39.17,
    discount:       63,
    rating:         4.3,
    reviews:        4491,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-031',
    name:           'Square Face Stainless Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          34.71,
    originalPrice:  84.66,
    discount:       59,
    rating:         4.3,
    reviews:        7799,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-032',
    name:           'Leather Cuff Watch — Brown',
    category:       'watches',
    subcategory:    'Analog',
    price:          19.23,
    originalPrice:  24.98,
    discount:       23,
    rating:         4.5,
    reviews:        8201,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-033',
    name:           'Smart Watch Kids — Parental Control',
    category:       'watches',
    subcategory:    'Digital',
    price:          52.19,
    originalPrice:  102.33,
    discount:       49,
    rating:         4.8,
    reviews:        21995,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "kids", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-034',
    name:           'Marble Dial Ladies\' Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          11.62,
    originalPrice:  24.72,
    discount:       53,
    rating:         4.2,
    reviews:        8118,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-035',
    name:           'Men\'s Big Dial Bold Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          16.56,
    originalPrice:  28.55,
    discount:       42,
    rating:         4.9,
    reviews:        13627,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-036',
    name:           'Solar Atomic Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          11.03,
    originalPrice:  20.81,
    discount:       47,
    rating:         4.9,
    reviews:        24529,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-037',
    name:           'Watch Gift Set — His & Hers',
    category:       'watches',
    subcategory:    'Analog',
    price:          27.48,
    originalPrice:  34.78,
    discount:       21,
    rating:         4.9,
    reviews:        3796,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watches", "wristwatch", "set"]
  },
  {
    id:             'ama-watc-038',
    name:           'Vintage Pilot Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          14.49,
    originalPrice:  34.49,
    discount:       58,
    rating:         4.5,
    reviews:        19099,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-039',
    name:           'Gold Plated Chain Bracelet Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          33.81,
    originalPrice:  60.37,
    discount:       44,
    rating:         4.4,
    reviews:        22423,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'ama-watc-040',
    name:           'Enamel Face Ladies\' Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          61.06,
    originalPrice:  103.49,
    discount:       41,
    rating:         4.8,
    reviews:        10404,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-041',
    name:           'Men\'s Tourbillon Skeleton Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          6.33,
    originalPrice:  13.46,
    discount:       53,
    rating:         4.9,
    reviews:        943,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-042',
    name:           'Resin Sport Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          86.04,
    originalPrice:  113.21,
    discount:       24,
    rating:         4.8,
    reviews:        2022,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-043',
    name:           'Women\'s Charm Bracelet Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          40.07,
    originalPrice:  111.3,
    discount:       64,
    rating:         4.8,
    reviews:        2790,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-044',
    name:           'Digital Alarm Stopwatch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          16.92,
    originalPrice:  41.27,
    discount:       59,
    rating:         4.3,
    reviews:        18790,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "luxury", "stopwatch"]
  },
  {
    id:             'ama-watc-045',
    name:           'Classic Black Dial Men\'s Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          14.01,
    originalPrice:  18.19,
    discount:       23,
    rating:         4.3,
    reviews:        7959,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'ama-watc-046',
    name:           'Multi-Function Smart Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          11.55,
    originalPrice:  32.07,
    discount:       64,
    rating:         4.4,
    reviews:        21051,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'ama-watc-047',
    name:           'Womens\' Bangle Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          59.77,
    originalPrice:  101.3,
    discount:       41,
    rating:         4.1,
    reviews:        14809,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'ama-watc-048',
    name:           'Calatrava Style Dress Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          18.25,
    originalPrice:  25.0,
    discount:       27,
    rating:         4.3,
    reviews:        22568,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'ama-watc-049',
    name:           'Sport Chronograph — Red',
    category:       'watches',
    subcategory:    'Luxury',
    price:          60.96,
    originalPrice:  85.86,
    discount:       29,
    rating:         5.0,
    reviews:        4645,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "luxury", "chronograph"]
  },
  {
    id:             'ama-watc-050',
    name:           'Everyday Casual Watch — Unisex',
    category:       'watches',
    subcategory:    'Sport',
    price:          84.99,
    originalPrice:  113.32,
    discount:       25,
    rating:         4.0,
    reviews:        24320,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WATC050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  }
);
