/* AMAZON — Women (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-wome-001',
    name:           'Floral Boho Maxi Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          20.67,
    originalPrice:  31.8,
    discount:       35,
    rating:         4.7,
    reviews:        16893,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-002',
    name:           'Silk Satin Slip Dress — Midi',
    category:       'women',
    subcategory:    'Tops',
    price:          24.55,
    originalPrice:  45.46,
    discount:       46,
    rating:         4.2,
    reviews:        13007,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-003',
    name:           'Linen Wide-Leg Trousers',
    category:       'women',
    subcategory:    'Jeans',
    price:          27.87,
    originalPrice:  35.28,
    discount:       21,
    rating:         4.0,
    reviews:        20494,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "trousers", "women"]
  },
  {
    id:             'ama-wome-004',
    name:           'Ruched Bodycon Mini Dress',
    category:       'women',
    subcategory:    'Skirts',
    price:          27.61,
    originalPrice:  36.33,
    discount:       24,
    rating:         4.2,
    reviews:        19626,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-005',
    name:           'Cashmere V-Neck Sweater',
    category:       'women',
    subcategory:    'Activewear',
    price:          54.75,
    originalPrice:  97.76,
    discount:       44,
    rating:         4.1,
    reviews:        17015,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "sweater"]
  },
  {
    id:             'ama-wome-006',
    name:           'Oversized Blazer — Camel',
    category:       'women',
    subcategory:    'Swimwear',
    price:          31.33,
    originalPrice:  60.25,
    discount:       48,
    rating:         4.4,
    reviews:        8056,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "swimwear", "women", "blazer"]
  },
  {
    id:             'ama-wome-007',
    name:           'High-Waist Flare Jeans',
    category:       'women',
    subcategory:    'Outerwear',
    price:          13.01,
    originalPrice:  23.65,
    discount:       45,
    rating:         4.3,
    reviews:        12712,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "outerwear"]
  },
  {
    id:             'ama-wome-008',
    name:           'Velvet Wrap Blouse',
    category:       'women',
    subcategory:    'Dresses',
    price:          12.21,
    originalPrice:  16.96,
    discount:       28,
    rating:         4.8,
    reviews:        18928,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "blouse", "women"]
  },
  {
    id:             'ama-wome-009',
    name:           'Tie-Dye Co-ord Set',
    category:       'women',
    subcategory:    'Tops',
    price:          14.43,
    originalPrice:  18.26,
    discount:       21,
    rating:         4.5,
    reviews:        20346,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "set", "women"]
  },
  {
    id:             'ama-wome-010',
    name:           'Off-Shoulder Summer Top',
    category:       'women',
    subcategory:    'Jeans',
    price:          16.1,
    originalPrice:  37.44,
    discount:       57,
    rating:         4.3,
    reviews:        23793,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "top"]
  },
  {
    id:             'ama-wome-011',
    name:           'Knit Ribbed Cardigan',
    category:       'women',
    subcategory:    'Skirts',
    price:          25.36,
    originalPrice:  66.74,
    discount:       62,
    rating:         4.8,
    reviews:        17965,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "cardigan", "clothing", "style", "women"]
  },
  {
    id:             'ama-wome-012',
    name:           'Pleated Midi Skirt — Navy',
    category:       'women',
    subcategory:    'Activewear',
    price:          47.28,
    originalPrice:  118.21,
    discount:       60,
    rating:         4.7,
    reviews:        17669,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "skirt"]
  },
  {
    id:             'ama-wome-013',
    name:           'Corset Bralette Set',
    category:       'women',
    subcategory:    'Swimwear',
    price:          8.45,
    originalPrice:  12.25,
    discount:       31,
    rating:         4.6,
    reviews:        9742,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "swimwear", "set", "women"]
  },
  {
    id:             'ama-wome-014',
    name:           'Satin Pyjama Set',
    category:       'women',
    subcategory:    'Outerwear',
    price:          34.29,
    originalPrice:  76.19,
    discount:       55,
    rating:         4.2,
    reviews:        7083,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "set", "women", "outerwear"]
  },
  {
    id:             'ama-wome-015',
    name:           'Embroidered Kaftan Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          53.14,
    originalPrice:  118.1,
    discount:       55,
    rating:         4.2,
    reviews:        4735,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-016',
    name:           'Tailored Wide-Leg Trousers',
    category:       'women',
    subcategory:    'Tops',
    price:          53.16,
    originalPrice:  118.14,
    discount:       55,
    rating:         4.7,
    reviews:        12341,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "trousers", "women"]
  },
  {
    id:             'ama-wome-017',
    name:           'Printed Chiffon Blouse',
    category:       'women',
    subcategory:    'Jeans',
    price:          36.92,
    originalPrice:  53.51,
    discount:       31,
    rating:         4.8,
    reviews:        20926,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "blouse", "women"]
  },
  {
    id:             'ama-wome-018',
    name:           'Denim Jacket — Vintage Wash',
    category:       'women',
    subcategory:    'Skirts',
    price:          22.17,
    originalPrice:  43.47,
    discount:       49,
    rating:         4.7,
    reviews:        22781,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "jacket", "fashion", "clothing", "style", "women"]
  },
  {
    id:             'ama-wome-019',
    name:           'Smocked Sundress',
    category:       'women',
    subcategory:    'Activewear',
    price:          78.7,
    originalPrice:  104.93,
    discount:       25,
    rating:         4.9,
    reviews:        8990,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "sundress", "style", "activewear", "women"]
  },
  {
    id:             'ama-wome-020',
    name:           'Cropped Leather Jacket',
    category:       'women',
    subcategory:    'Swimwear',
    price:          27.27,
    originalPrice:  53.48,
    discount:       49,
    rating:         4.3,
    reviews:        23652,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "fashion", "clothing", "style", "swimwear", "women"]
  },
  {
    id:             'ama-wome-021',
    name:           'Asymmetric Hem Skirt',
    category:       'women',
    subcategory:    'Outerwear',
    price:          10.55,
    originalPrice:  25.12,
    discount:       58,
    rating:         4.4,
    reviews:        24805,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "skirt"]
  },
  {
    id:             'ama-wome-022',
    name:           'Puff-Sleeve Mini Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          76.93,
    originalPrice:  109.9,
    discount:       30,
    rating:         4.9,
    reviews:        15975,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-023',
    name:           'Striped Co-ord Shorts Set',
    category:       'women',
    subcategory:    'Tops',
    price:          68.64,
    originalPrice:  112.53,
    discount:       39,
    rating:         4.7,
    reviews:        6738,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "set", "women"]
  },
  {
    id:             'ama-wome-024',
    name:           'Halter Neck Maxi Dress',
    category:       'women',
    subcategory:    'Jeans',
    price:          64.65,
    originalPrice:  111.46,
    discount:       42,
    rating:         4.5,
    reviews:        11668,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-025',
    name:           'Floral Print Wrap Dress',
    category:       'women',
    subcategory:    'Skirts',
    price:          20.14,
    originalPrice:  51.64,
    discount:       61,
    rating:         4.9,
    reviews:        4517,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-026',
    name:           'Sequin Evening Gown',
    category:       'women',
    subcategory:    'Activewear',
    price:          36.22,
    originalPrice:  73.91,
    discount:       51,
    rating:         4.1,
    reviews:        15830,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "gown", "activewear", "women"]
  },
  {
    id:             'ama-wome-027',
    name:           'Sheer Organza Blouse',
    category:       'women',
    subcategory:    'Swimwear',
    price:          33.95,
    originalPrice:  62.87,
    discount:       46,
    rating:         4.7,
    reviews:        3968,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "blouse", "swimwear", "women"]
  },
  {
    id:             'ama-wome-028',
    name:           'Rib-Knit Crop Top',
    category:       'women',
    subcategory:    'Outerwear',
    price:          29.34,
    originalPrice:  37.61,
    discount:       22,
    rating:         4.3,
    reviews:        721,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "women", "top", "outerwear"]
  },
  {
    id:             'ama-wome-029',
    name:           'Belted Trench Coat',
    category:       'women',
    subcategory:    'Dresses',
    price:          80.22,
    originalPrice:  102.84,
    discount:       22,
    rating:         4.3,
    reviews:        20107,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "coat", "women"]
  },
  {
    id:             'ama-wome-030',
    name:           'Tiered Ruffled Midi Dress',
    category:       'women',
    subcategory:    'Tops',
    price:          26.19,
    originalPrice:  62.36,
    discount:       58,
    rating:         4.3,
    reviews:        24539,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-031',
    name:           'Lace Trim Slip Skirt',
    category:       'women',
    subcategory:    'Jeans',
    price:          43.37,
    originalPrice:  117.21,
    discount:       63,
    rating:         4.0,
    reviews:        4756,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "skirt"]
  },
  {
    id:             'ama-wome-032',
    name:           'Double-Breasted Blazer',
    category:       'women',
    subcategory:    'Skirts',
    price:          43.75,
    originalPrice:  68.36,
    discount:       36,
    rating:         4.6,
    reviews:        6725,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "blazer"]
  },
  {
    id:             'ama-wome-033',
    name:           'Broderie Anglaise Top',
    category:       'women',
    subcategory:    'Activewear',
    price:          26.95,
    originalPrice:  61.24,
    discount:       56,
    rating:         4.7,
    reviews:        13007,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "top"]
  },
  {
    id:             'ama-wome-034',
    name:           'Velvet Jumpsuit — Burgundy',
    category:       'women',
    subcategory:    'Swimwear',
    price:          63.43,
    originalPrice:  100.68,
    discount:       37,
    rating:         4.4,
    reviews:        15640,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jumpsuit", "clothing", "style", "swimwear", "women"]
  },
  {
    id:             'ama-wome-035',
    name:           'Seersucker Shorts Set',
    category:       'women',
    subcategory:    'Outerwear',
    price:          10.55,
    originalPrice:  20.68,
    discount:       49,
    rating:         4.3,
    reviews:        3417,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "set", "women", "outerwear"]
  },
  {
    id:             'ama-wome-036',
    name:           'Crinkle Cotton Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          64.51,
    originalPrice:  86.01,
    discount:       25,
    rating:         4.4,
    reviews:        24637,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-037',
    name:           'Cut-Out Bodycon Dress',
    category:       'women',
    subcategory:    'Tops',
    price:          40.69,
    originalPrice:  83.04,
    discount:       51,
    rating:         4.1,
    reviews:        18032,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-038',
    name:           'Paperbag Waist Trousers',
    category:       'women',
    subcategory:    'Jeans',
    price:          26.53,
    originalPrice:  34.01,
    discount:       22,
    rating:         4.4,
    reviews:        689,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "trousers", "women"]
  },
  {
    id:             'ama-wome-039',
    name:           'Floral Kimono Robe',
    category:       'women',
    subcategory:    'Skirts',
    price:          23.57,
    originalPrice:  30.61,
    discount:       23,
    rating:         4.3,
    reviews:        11687,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "robe", "clothing", "style", "women"]
  },
  {
    id:             'ama-wome-040',
    name:           'Suede Fringe Jacket',
    category:       'women',
    subcategory:    'Activewear',
    price:          95.33,
    originalPrice:  119.16,
    discount:       20,
    rating:         4.6,
    reviews:        23026,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "fashion", "clothing", "style", "activewear", "women"]
  },
  {
    id:             'ama-wome-041',
    name:           'Peplum Blouse — Ivory',
    category:       'women',
    subcategory:    'Swimwear',
    price:          69.78,
    originalPrice:  112.55,
    discount:       38,
    rating:         4.2,
    reviews:        21845,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "blouse", "swimwear", "women"]
  },
  {
    id:             'ama-wome-042',
    name:           'Plisse Pleated Maxi Dress',
    category:       'women',
    subcategory:    'Outerwear',
    price:          31.6,
    originalPrice:  56.42,
    discount:       44,
    rating:         4.7,
    reviews:        1749,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "dress"]
  },
  {
    id:             'ama-wome-043',
    name:           'Colour-Block Sweater',
    category:       'women',
    subcategory:    'Dresses',
    price:          42.83,
    originalPrice:  53.54,
    discount:       20,
    rating:         4.4,
    reviews:        7144,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "sweater"]
  },
  {
    id:             'ama-wome-044',
    name:           'Shacket — Oversized Flannel',
    category:       'women',
    subcategory:    'Tops',
    price:          19.38,
    originalPrice:  24.85,
    discount:       22,
    rating:         4.3,
    reviews:        19267,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "shacket", "clothing", "tops", "style", "women"]
  },
  {
    id:             'ama-wome-045',
    name:           'Ruffle Hem Cami Dress',
    category:       'women',
    subcategory:    'Jeans',
    price:          57.35,
    originalPrice:  110.28,
    discount:       48,
    rating:         4.4,
    reviews:        10002,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ama-wome-046',
    name:           'Button-Front Midi Skirt',
    category:       'women',
    subcategory:    'Skirts',
    price:          46.3,
    originalPrice:  74.68,
    discount:       38,
    rating:         5.0,
    reviews:        3948,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "skirt"]
  },
  {
    id:             'ama-wome-047',
    name:           'Lurex Knit Dress',
    category:       'women',
    subcategory:    'Activewear',
    price:          50.25,
    originalPrice:  82.38,
    discount:       39,
    rating:         4.1,
    reviews:        21430,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "dress"]
  },
  {
    id:             'ama-wome-048',
    name:           'Broderie Lace Midi Dress',
    category:       'women',
    subcategory:    'Swimwear',
    price:          30.99,
    originalPrice:  57.39,
    discount:       46,
    rating:         4.8,
    reviews:        9510,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "swimwear", "women", "dress"]
  },
  {
    id:             'ama-wome-049',
    name:           'Polka Dot Wrap Dress',
    category:       'women',
    subcategory:    'Outerwear',
    price:          20.47,
    originalPrice:  39.37,
    discount:       48,
    rating:         5.0,
    reviews:        5982,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "dress"]
  },
  {
    id:             'ama-wome-050',
    name:           'Power Shoulder Blazer Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          38.66,
    originalPrice:  84.05,
    discount:       54,
    rating:         4.0,
    reviews:        23775,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0WOME050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  }
);
