/* ALIEXPRESS — Bags (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-bags-001',
    name:           'Luxury PU Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          61.56,
    originalPrice:  116.15,
    discount:       47,
    rating:         4.2,
    reviews:        4498,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-002',
    name:           'Canvas Tote Bag — Aesthetic Prints',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          9.72,
    originalPrice:  24.31,
    discount:       60,
    rating:         4.8,
    reviews:        19698,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-003',
    name:           'Laptop Backpack — Anti-Theft 15.6"',
    category:       'bags',
    subcategory:    'Totes',
    price:          34.74,
    originalPrice:  73.92,
    discount:       53,
    rating:         4.2,
    reviews:        23110,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "backpack", "totes", "purse"]
  },
  {
    id:             'ali-bags-004',
    name:           'Mini Crossbody Bag — Quilted Chain',
    category:       'bags',
    subcategory:    'Wallets',
    price:          44.68,
    originalPrice:  85.92,
    discount:       48,
    rating:         4.4,
    reviews:        13027,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-005',
    name:           'Rattan Summer Handbag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          55.2,
    originalPrice:  102.22,
    discount:       46,
    rating:         4.6,
    reviews:        1141,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-006',
    name:           'Clear Stadium Bag — PVC',
    category:       'bags',
    subcategory:    'Handbags',
    price:          23.71,
    originalPrice:  62.4,
    discount:       62,
    rating:         4.3,
    reviews:        4386,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-007',
    name:           'Large Slouchy Hobo Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          44.48,
    originalPrice:  69.5,
    discount:       36,
    rating:         4.0,
    reviews:        19877,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-008',
    name:           'Croc-Effect Tote Bag — Beige',
    category:       'bags',
    subcategory:    'Totes',
    price:          49.35,
    originalPrice:  73.65,
    discount:       33,
    rating:         4.7,
    reviews:        16086,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-009',
    name:           'Woven Bucket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          63.79,
    originalPrice:  104.57,
    discount:       39,
    rating:         4.0,
    reviews:        862,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-010',
    name:           'Belt Bag — Nylon',
    category:       'bags',
    subcategory:    'Clutches',
    price:          16.68,
    originalPrice:  34.76,
    discount:       52,
    rating:         4.9,
    reviews:        18864,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-011',
    name:           'Flap Crossbody Bag — Brown',
    category:       'bags',
    subcategory:    'Handbags',
    price:          38.56,
    originalPrice:  62.2,
    discount:       38,
    rating:         4.4,
    reviews:        19455,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-012',
    name:           'Structured Top Handle Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          32.48,
    originalPrice:  56.98,
    discount:       43,
    rating:         4.3,
    reviews:        13101,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-013',
    name:           'Travel Duffel Bag — Weekender',
    category:       'bags',
    subcategory:    'Totes',
    price:          39.19,
    originalPrice:  68.76,
    discount:       43,
    rating:         4.9,
    reviews:        22497,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-014',
    name:           'Waist Fanny Pack — Black',
    category:       'bags',
    subcategory:    'Wallets',
    price:          70.13,
    originalPrice:  101.64,
    discount:       31,
    rating:         4.0,
    reviews:        524,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "wallets", "bags", "purse", "pack"]
  },
  {
    id:             'ali-bags-015',
    name:           'Knitted Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          31.52,
    originalPrice:  64.33,
    discount:       51,
    rating:         4.7,
    reviews:        14219,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-016',
    name:           'Mini Camera Bag — Velvet',
    category:       'bags',
    subcategory:    'Handbags',
    price:          26.01,
    originalPrice:  70.31,
    discount:       63,
    rating:         4.9,
    reviews:        13148,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-017',
    name:           'Oversized Shopper Tote',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          59.56,
    originalPrice:  79.41,
    discount:       25,
    rating:         4.7,
    reviews:        21322,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-018',
    name:           'Baguette Bag — Satin',
    category:       'bags',
    subcategory:    'Totes',
    price:          47.07,
    originalPrice:  66.29,
    discount:       29,
    rating:         4.2,
    reviews:        1461,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-019',
    name:           'Backpack Purse — Vegan Leather',
    category:       'bags',
    subcategory:    'Wallets',
    price:          44.3,
    originalPrice:  110.74,
    discount:       60,
    rating:         4.5,
    reviews:        19374,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-020',
    name:           'Transparent Beach Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          71.32,
    originalPrice:  116.91,
    discount:       39,
    rating:         4.8,
    reviews:        13207,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-021',
    name:           'Bamboo Handle Tote',
    category:       'bags',
    subcategory:    'Handbags',
    price:          63.58,
    originalPrice:  99.35,
    discount:       36,
    rating:         4.1,
    reviews:        8154,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-022',
    name:           'Convertible Backpack Handbag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          66.29,
    originalPrice:  116.29,
    discount:       43,
    rating:         4.4,
    reviews:        19041,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-023',
    name:           'Envelope Clutch Bag — Gold',
    category:       'bags',
    subcategory:    'Totes',
    price:          73.17,
    originalPrice:  101.62,
    discount:       28,
    rating:         4.3,
    reviews:        16494,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-024',
    name:           'Micro Mini Bag — Chain Strap',
    category:       'bags',
    subcategory:    'Wallets',
    price:          74.91,
    originalPrice:  111.8,
    discount:       33,
    rating:         4.1,
    reviews:        5333,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-025',
    name:           'Studded Leather Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          20.23,
    originalPrice:  45.98,
    discount:       56,
    rating:         4.5,
    reviews:        17290,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "crossbody", "clutches", "purse"]
  },
  {
    id:             'ali-bags-026',
    name:           'Geometric Structured Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          81.06,
    originalPrice:  112.58,
    discount:       28,
    rating:         4.2,
    reviews:        1389,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-027',
    name:           'Drawstring Bucket Bag — Cord',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          24.15,
    originalPrice:  44.72,
    discount:       46,
    rating:         4.3,
    reviews:        11403,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-028',
    name:           'Vintage Flap Shoulder Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          56.41,
    originalPrice:  108.48,
    discount:       48,
    rating:         4.4,
    reviews:        1811,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-029',
    name:           'Wicker Market Basket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          14.33,
    originalPrice:  38.73,
    discount:       63,
    rating:         4.6,
    reviews:        9904,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-030',
    name:           'Circle Bag — Wooden Handle',
    category:       'bags',
    subcategory:    'Clutches',
    price:          25.48,
    originalPrice:  33.97,
    discount:       25,
    rating:         4.0,
    reviews:        5518,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-031',
    name:           'Satin Evening Clutch — Pearl',
    category:       'bags',
    subcategory:    'Handbags',
    price:          30.69,
    originalPrice:  85.25,
    discount:       64,
    rating:         4.9,
    reviews:        15662,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "handbags", "bags", "clutch", "purse"]
  },
  {
    id:             'ali-bags-032',
    name:           'Doctor Bag — Brown Leather',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          82.86,
    originalPrice:  115.09,
    discount:       28,
    rating:         4.6,
    reviews:        24500,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-033',
    name:           'Graffiti Print Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          69.79,
    originalPrice:  104.17,
    discount:       33,
    rating:         4.2,
    reviews:        23500,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-034',
    name:           'Chain Handle Shoulder Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          44.05,
    originalPrice:  97.9,
    discount:       55,
    rating:         4.3,
    reviews:        14686,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-035',
    name:           'PVC Jelly Bag — Transparent',
    category:       'bags',
    subcategory:    'Clutches',
    price:          36.88,
    originalPrice:  54.23,
    discount:       32,
    rating:         4.8,
    reviews:        8081,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-036',
    name:           'Knot Handle Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          79.56,
    originalPrice:  99.45,
    discount:       20,
    rating:         4.7,
    reviews:        14952,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-037',
    name:           'Tassel Fringe Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          6.44,
    originalPrice:  15.34,
    discount:       58,
    rating:         4.3,
    reviews:        16186,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-038',
    name:           'Reversible Tote Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          65.69,
    originalPrice:  93.84,
    discount:       30,
    rating:         4.3,
    reviews:        24253,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-039',
    name:           'Large Raffia Beach Tote',
    category:       'bags',
    subcategory:    'Wallets',
    price:          17.47,
    originalPrice:  24.61,
    discount:       29,
    rating:         4.9,
    reviews:        13166,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-040',
    name:           'Phone Bag — Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          83.1,
    originalPrice:  115.41,
    discount:       28,
    rating:         4.5,
    reviews:        10773,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-041',
    name:           'Chic Mini Backpack',
    category:       'bags',
    subcategory:    'Handbags',
    price:          5.74,
    originalPrice:  14.71,
    discount:       61,
    rating:         4.7,
    reviews:        3153,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "handbags", "bags", "backpack", "purse"]
  },
  {
    id:             'ali-bags-042',
    name:           'Lock Clasp Structured Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          47.25,
    originalPrice:  94.5,
    discount:       50,
    rating:         4.7,
    reviews:        4650,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-043',
    name:           'Rope Handle Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          10.8,
    originalPrice:  25.12,
    discount:       57,
    rating:         4.8,
    reviews:        24571,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-044',
    name:           'Patchwork Denim Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          81.64,
    originalPrice:  114.99,
    discount:       29,
    rating:         4.1,
    reviews:        10100,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'ali-bags-045',
    name:           'Woven Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          26.02,
    originalPrice:  42.65,
    discount:       39,
    rating:         4.7,
    reviews:        23387,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'ali-bags-046',
    name:           'Feather Trim Evening Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          67.4,
    originalPrice:  114.23,
    discount:       41,
    rating:         4.5,
    reviews:        3321,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'ali-bags-047',
    name:           'Nylon Messenger Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          15.18,
    originalPrice:  26.64,
    discount:       43,
    rating:         4.6,
    reviews:        17845,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'ali-bags-048',
    name:           'Half-Moon Crescent Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          66.6,
    originalPrice:  105.72,
    discount:       37,
    rating:         4.4,
    reviews:        19276,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'ali-bags-049',
    name:           'Snakeskin Effect Clutch',
    category:       'bags',
    subcategory:    'Wallets',
    price:          18.26,
    originalPrice:  45.65,
    discount:       60,
    rating:         4.7,
    reviews:        12314,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tote", "handbag", "bags", "clutch", "purse", "wallets"]
  },
  {
    id:             'ali-bags-050',
    name:           'Double Zip Crossbody Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          38.04,
    originalPrice:  105.68,
    discount:       64,
    rating:         4.4,
    reviews:        8924,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  }
);
