/* ALIEXPRESS — Crafts (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-craf-001',
    name:           'Diamond Painting Kit — Full Drill 40×50',
    category:       'crafts',
    subcategory:    'Painting',
    price:          19.63,
    originalPrice:  28.05,
    discount:       30,
    rating:         4.9,
    reviews:        15338,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-002',
    name:           'Resin Art Kit — UV Resin + Moulds',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          59.81,
    originalPrice:  99.69,
    discount:       40,
    rating:         4.5,
    reviews:        24051,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-003',
    name:           'Aesthetic Journaling Kit — Washi Tapes',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          60.33,
    originalPrice:  104.01,
    discount:       42,
    rating:         4.2,
    reviews:        15172,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-004',
    name:           'Watercolour Paint Set — 48 Colours',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          31.58,
    originalPrice:  85.36,
    discount:       63,
    rating:         4.8,
    reviews:        14706,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-005',
    name:           'Macramé Wall Hanging Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          19.59,
    originalPrice:  27.98,
    discount:       30,
    rating:         4.9,
    reviews:        19889,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-006',
    name:           'Embroidery Starter Kit — Floral',
    category:       'crafts',
    subcategory:    'DIY',
    price:          34.51,
    originalPrice:  65.12,
    discount:       47,
    rating:         5.0,
    reviews:        15908,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-007',
    name:           'Lino Printing Starter Set',
    category:       'crafts',
    subcategory:    'Painting',
    price:          87.41,
    originalPrice:  115.01,
    discount:       24,
    rating:         4.8,
    reviews:        19411,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-008',
    name:           'Candle Making Kit — Soy Wax',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          79.97,
    originalPrice:  102.52,
    discount:       22,
    rating:         4.4,
    reviews:        20397,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-009',
    name:           'Pottery Air Dry Clay Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          59.72,
    originalPrice:  86.55,
    discount:       31,
    rating:         4.5,
    reviews:        5240,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-010',
    name:           'Leather Craft Tooling Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          8.86,
    originalPrice:  24.61,
    discount:       64,
    rating:         4.4,
    reviews:        20382,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-011',
    name:           'Cross-Stitch Bookmark Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          86.61,
    originalPrice:  118.65,
    discount:       27,
    rating:         4.3,
    reviews:        7103,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-012',
    name:           'Acrylic Pour Painting Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          53.16,
    originalPrice:  91.66,
    discount:       42,
    rating:         4.2,
    reviews:        5710,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-013',
    name:           'Needle Felting Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          52.92,
    originalPrice:  86.75,
    discount:       39,
    rating:         4.7,
    reviews:        23639,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-014',
    name:           'Calligraphy Pen & Ink Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          8.71,
    originalPrice:  14.52,
    discount:       40,
    rating:         4.4,
    reviews:        23079,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-015',
    name:           'Soap Making Kit — Natural',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          15.57,
    originalPrice:  19.96,
    discount:       22,
    rating:         4.6,
    reviews:        1411,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-016',
    name:           'Origami Paper Set — 200 Sheets',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          28.0,
    originalPrice:  68.29,
    discount:       59,
    rating:         4.3,
    reviews:        3688,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-017',
    name:           'Knitting Starter Kit — Beginner',
    category:       'crafts',
    subcategory:    'Resin',
    price:          36.72,
    originalPrice:  53.22,
    discount:       31,
    rating:         4.2,
    reviews:        7648,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-018',
    name:           'Crochet Hook Set + Yarn Bundle',
    category:       'crafts',
    subcategory:    'DIY',
    price:          49.13,
    originalPrice:  100.27,
    discount:       51,
    rating:         4.4,
    reviews:        1814,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-019',
    name:           'Jewellery Making Kit — Beads',
    category:       'crafts',
    subcategory:    'Painting',
    price:          15.58,
    originalPrice:  26.87,
    discount:       42,
    rating:         4.5,
    reviews:        21748,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-020',
    name:           'Tie-Dye Kit — Spiral',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          9.04,
    originalPrice:  25.83,
    discount:       65,
    rating:         4.2,
    reviews:        20533,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-021',
    name:           'Painting by Numbers — Landscape',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          55.16,
    originalPrice:  72.58,
    discount:       24,
    rating:         4.6,
    reviews:        22370,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["numbers", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-022',
    name:           'Block Printing Ink Set',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          26.62,
    originalPrice:  55.45,
    discount:       52,
    rating:         4.6,
    reviews:        2849,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-023',
    name:           'Scrapbook Kit — 200 Stickers',
    category:       'crafts',
    subcategory:    'Resin',
    price:          30.03,
    originalPrice:  57.75,
    discount:       48,
    rating:         4.4,
    reviews:        11541,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-024',
    name:           'Pressed Flower Art Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          46.5,
    originalPrice:  61.18,
    discount:       24,
    rating:         4.4,
    reviews:        16488,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-025',
    name:           'Glass Painting Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          5.53,
    originalPrice:  13.16,
    discount:       58,
    rating:         4.2,
    reviews:        23953,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-026',
    name:           'Wool Felting Supplies Bundle',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          16.49,
    originalPrice:  22.59,
    discount:       27,
    rating:         4.5,
    reviews:        10654,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-027',
    name:           'Punch Needle Rug Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          76.15,
    originalPrice:  104.31,
    discount:       27,
    rating:         4.4,
    reviews:        6647,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-028',
    name:           'Marbling Paper Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          38.23,
    originalPrice:  56.22,
    discount:       32,
    rating:         4.1,
    reviews:        18441,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-029',
    name:           'Silk Screen Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          46.6,
    originalPrice:  59.74,
    discount:       22,
    rating:         4.4,
    reviews:        7428,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-030',
    name:           'Decoupage Set + Papers',
    category:       'crafts',
    subcategory:    'DIY',
    price:          6.56,
    originalPrice:  12.38,
    discount:       47,
    rating:         4.4,
    reviews:        8554,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["papers", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-031',
    name:           'Weaving Loom Kit — Beginner',
    category:       'crafts',
    subcategory:    'Painting',
    price:          18.19,
    originalPrice:  25.62,
    discount:       29,
    rating:         4.3,
    reviews:        2372,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-032',
    name:           'Zentangle Art Pens Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          86.92,
    originalPrice:  112.88,
    discount:       23,
    rating:         4.8,
    reviews:        24039,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-033',
    name:           'Linoleum Block Carving Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          8.9,
    originalPrice:  19.34,
    discount:       54,
    rating:         4.1,
    reviews:        23029,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-034',
    name:           'Alcohol Ink Art Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          42.44,
    originalPrice:  96.45,
    discount:       56,
    rating:         4.7,
    reviews:        14419,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-035',
    name:           'Mandala Drawing Stencil Set',
    category:       'crafts',
    subcategory:    'Resin',
    price:          12.0,
    originalPrice:  20.34,
    discount:       41,
    rating:         4.8,
    reviews:        3958,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-036',
    name:           'Rubber Stamp Making Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          59.48,
    originalPrice:  100.81,
    discount:       41,
    rating:         4.4,
    reviews:        18953,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-037',
    name:           'Reusable Stencil Set — 40 Piece',
    category:       'crafts',
    subcategory:    'Painting',
    price:          67.97,
    originalPrice:  84.96,
    discount:       20,
    rating:         4.5,
    reviews:        18385,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-038',
    name:           'Air Dry Clay Tool Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          45.95,
    originalPrice:  91.91,
    discount:       50,
    rating:         4.1,
    reviews:        14471,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-039',
    name:           'Mixed Media Art Journal',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          13.65,
    originalPrice:  18.2,
    discount:       25,
    rating:         4.3,
    reviews:        23697,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["journal", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-040',
    name:           'Bookbinding Kit — Hardcover',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          39.63,
    originalPrice:  107.1,
    discount:       63,
    rating:         4.8,
    reviews:        17490,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-041',
    name:           'Batik Wax Resist Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          19.49,
    originalPrice:  37.49,
    discount:       48,
    rating:         4.4,
    reviews:        17313,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-042',
    name:           'Pyrography Wood Burning Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          72.1,
    originalPrice:  104.5,
    discount:       31,
    rating:         4.3,
    reviews:        14967,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-043',
    name:           'Paper Quilling Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          43.87,
    originalPrice:  79.76,
    discount:       45,
    rating:         4.6,
    reviews:        24402,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-044',
    name:           'Shrink Plastic Art Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          33.08,
    originalPrice:  78.75,
    discount:       58,
    rating:         4.2,
    reviews:        13796,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ali-craf-045',
    name:           'Enamel Painting Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          7.39,
    originalPrice:  13.44,
    discount:       45,
    rating:         4.2,
    reviews:        2847,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-046',
    name:           'Gilding Flakes Set — Gold',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          25.24,
    originalPrice:  61.56,
    discount:       59,
    rating:         5.0,
    reviews:        15124,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-047',
    name:           'Linocut Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          34.11,
    originalPrice:  92.19,
    discount:       63,
    rating:         4.0,
    reviews:        16202,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-048',
    name:           'Botanical Illustration Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          41.33,
    originalPrice:  111.71,
    discount:       63,
    rating:         4.3,
    reviews:        1498,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-049',
    name:           'Copper Tooling Craft Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          37.04,
    originalPrice:  77.17,
    discount:       52,
    rating:         4.0,
    reviews:        17023,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ali-craf-050',
    name:           'Felt Sewing Starter Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          53.94,
    originalPrice:  117.26,
    discount:       54,
    rating:         4.1,
    reviews:        1621,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  }
);
