/* ALIEXPRESS — Electronics (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-elec-001',
    name:           'Smart Watch Pro — Fitness Tracker',
    category:       'electronics',
    subcategory:    'Phones',
    price:          32.86,
    originalPrice:  91.29,
    discount:       64,
    rating:         4.0,
    reviews:        11894,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gadgets", "smart", "pro", "phones"]
  },
  {
    id:             'ali-elec-002',
    name:           'TWS Wireless Earbuds — Noise Cancelling',
    category:       'electronics',
    subcategory:    'Audio',
    price:          63.4,
    originalPrice:  85.67,
    discount:       26,
    rating:         4.7,
    reviews:        24199,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'ali-elec-003',
    name:           'Bluetooth 5.3 Over-Ear Headphones',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          52.2,
    originalPrice:  88.48,
    discount:       41,
    rating:         4.9,
    reviews:        9590,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "headphones"]
  },
  {
    id:             'ali-elec-004',
    name:           'Mini Projector for Home Cinema',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          73.99,
    originalPrice:  93.66,
    discount:       21,
    rating:         4.4,
    reviews:        14187,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "cinema", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-005',
    name:           'RGB Mechanical Gaming Keyboard',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          13.97,
    originalPrice:  18.88,
    discount:       26,
    rating:         4.5,
    reviews:        1179,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-006',
    name:           '3-in-1 Wireless Charging Pad — 15W',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          11.58,
    originalPrice:  28.25,
    discount:       59,
    rating:         4.6,
    reviews:        3880,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "pad", "electronics", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-007',
    name:           'Smart LED Bulb — Colour Changing WiFi',
    category:       'electronics',
    subcategory:    'Phones',
    price:          70.1,
    originalPrice:  111.27,
    discount:       37,
    rating:         4.7,
    reviews:        7730,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "bulb", "gadgets", "smart", "phones"]
  },
  {
    id:             'ali-elec-008',
    name:           'Xiaomi Power Bank 20000mAh',
    category:       'electronics',
    subcategory:    'Audio',
    price:          47.81,
    originalPrice:  103.93,
    discount:       54,
    rating:         4.2,
    reviews:        8932,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "electronics", "20000mah", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-009',
    name:           'Portable Bluetooth Speaker — Waterproof',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          71.84,
    originalPrice:  101.19,
    discount:       29,
    rating:         4.6,
    reviews:        23901,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "speaker", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-010',
    name:           'Ring Light — 10" Selfie',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          58.82,
    originalPrice:  101.41,
    discount:       42,
    rating:         4.3,
    reviews:        11782,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "light"]
  },
  {
    id:             'ali-elec-011',
    name:           'Gaming Mouse — RGB Backlit',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          43.32,
    originalPrice:  69.87,
    discount:       38,
    rating:         4.6,
    reviews:        16524,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gaming", "gadgets", "mouse", "smart"]
  },
  {
    id:             'ali-elec-012',
    name:           'USB-C Hub — 7 Port',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          60.15,
    originalPrice:  78.12,
    discount:       23,
    rating:         4.4,
    reviews:        22597,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "accessories", "gadgets", "hub", "smart"]
  },
  {
    id:             'ali-elec-013',
    name:           'Webcam HD 1080p — Built-in Mic',
    category:       'electronics',
    subcategory:    'Phones',
    price:          28.35,
    originalPrice:  42.96,
    discount:       34,
    rating:         4.8,
    reviews:        18556,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gadgets", "smart", "1080p", "phones"]
  },
  {
    id:             'ali-elec-014',
    name:           'Smart Plug — Voice Control',
    category:       'electronics',
    subcategory:    'Audio',
    price:          79.3,
    originalPrice:  105.74,
    discount:       25,
    rating:         4.5,
    reviews:        10691,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["plug", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-015',
    name:           'Electric Toothbrush — Rechargeable',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          39.19,
    originalPrice:  48.99,
    discount:       20,
    rating:         4.3,
    reviews:        19744,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "toothbrush", "smart"]
  },
  {
    id:             'ali-elec-016',
    name:           'Noise Cancelling Earbuds',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          39.55,
    originalPrice:  94.17,
    discount:       58,
    rating:         5.0,
    reviews:        4974,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'ali-elec-017',
    name:           'Dash Cam — Front & Rear 4K',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          54.68,
    originalPrice:  77.01,
    discount:       29,
    rating:         4.8,
    reviews:        7514,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "cam"]
  },
  {
    id:             'ali-elec-018',
    name:           'Smart Scale — Body Fat Analysis',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          24.99,
    originalPrice:  38.45,
    discount:       35,
    rating:         4.0,
    reviews:        2865,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "scale", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-019',
    name:           'Portable SSD — 1TB',
    category:       'electronics',
    subcategory:    'Phones',
    price:          15.91,
    originalPrice:  26.51,
    discount:       40,
    rating:         4.6,
    reviews:        12130,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gadgets", "ssd", "smart", "phones"]
  },
  {
    id:             'ali-elec-020',
    name:           'HDMI Cable 4K — 2m',
    category:       'electronics',
    subcategory:    'Audio',
    price:          56.5,
    originalPrice:  85.6,
    discount:       34,
    rating:         4.3,
    reviews:        530,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "4k", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-021',
    name:           'Smart Home Security Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          44.35,
    originalPrice:  73.92,
    discount:       40,
    rating:         4.8,
    reviews:        10868,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "camera"]
  },
  {
    id:             'ali-elec-022',
    name:           'Digital Photo Frame — Wi-Fi',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          37.1,
    originalPrice:  92.75,
    discount:       60,
    rating:         4.6,
    reviews:        4564,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["frame", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-023',
    name:           'Kids\' Tablet — 10" Android',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          60.56,
    originalPrice:  91.76,
    discount:       34,
    rating:         4.9,
    reviews:        16161,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "tablet", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-024',
    name:           'Wireless Gaming Controller',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          9.31,
    originalPrice:  16.33,
    discount:       43,
    rating:         4.7,
    reviews:        10250,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "controller"]
  },
  {
    id:             'ali-elec-025',
    name:           'Robot Vacuum Cleaner — Smart Map',
    category:       'electronics',
    subcategory:    'Phones',
    price:          6.9,
    originalPrice:  18.65,
    discount:       63,
    rating:         4.5,
    reviews:        16850,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gadgets", "smart", "cleaner", "phones"]
  },
  {
    id:             'ali-elec-026',
    name:           'Air Purifier — HEPA Filter',
    category:       'electronics',
    subcategory:    'Audio',
    price:          22.66,
    originalPrice:  58.11,
    discount:       61,
    rating:         4.8,
    reviews:        24180,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "electronics", "purifier", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-027',
    name:           'Smart Doorbell — HD Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          43.13,
    originalPrice:  56.01,
    discount:       23,
    rating:         4.9,
    reviews:        6113,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "doorbell"]
  },
  {
    id:             'ali-elec-028',
    name:           'Portable Projector Screen — 120"',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          31.38,
    originalPrice:  87.16,
    discount:       64,
    rating:         4.6,
    reviews:        5211,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["screen", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-029',
    name:           'Mini Keyboard — Bluetooth',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          12.1,
    originalPrice:  19.52,
    discount:       38,
    rating:         4.4,
    reviews:        7588,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-030',
    name:           'Action Camera — 4K Waterproof',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          77.58,
    originalPrice:  110.83,
    discount:       30,
    rating:         4.1,
    reviews:        13194,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "camera"]
  },
  {
    id:             'ali-elec-031',
    name:           'VR Headset — Standalone',
    category:       'electronics',
    subcategory:    'Phones',
    price:          19.68,
    originalPrice:  28.11,
    discount:       30,
    rating:         4.1,
    reviews:        3783,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'ali-elec-032',
    name:           'Laser Printer — Wireless',
    category:       'electronics',
    subcategory:    'Audio',
    price:          41.09,
    originalPrice:  60.42,
    discount:       32,
    rating:         4.6,
    reviews:        5329,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["printer", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-033',
    name:           'Smart TV Stick — 4K Streaming',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          46.34,
    originalPrice:  92.69,
    discount:       50,
    rating:         4.3,
    reviews:        20573,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["stick", "tech", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-034',
    name:           'Electric Hand Massager',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          28.14,
    originalPrice:  52.12,
    discount:       46,
    rating:         4.4,
    reviews:        5867,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "massager"]
  },
  {
    id:             'ali-elec-035',
    name:           'Foldable Phone Stand Holder',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          39.51,
    originalPrice:  84.06,
    discount:       53,
    rating:         4.6,
    reviews:        22545,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'ali-elec-036',
    name:           'Wireless Earbuds Case — Leather',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          35.22,
    originalPrice:  100.64,
    discount:       65,
    rating:         4.9,
    reviews:        7051,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "accessories", "case", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-037',
    name:           'Gaming Headset — Surround Sound',
    category:       'electronics',
    subcategory:    'Phones',
    price:          21.94,
    originalPrice:  33.75,
    discount:       35,
    rating:         4.3,
    reviews:        7574,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'ali-elec-038',
    name:           'LED Desk Lamp — USB Charging',
    category:       'electronics',
    subcategory:    'Audio',
    price:          67.76,
    originalPrice:  86.87,
    discount:       22,
    rating:         4.6,
    reviews:        9011,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "lamp"]
  },
  {
    id:             'ali-elec-039',
    name:           'Smart Thermostat — Wi-Fi',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          57.02,
    originalPrice:  114.04,
    discount:       50,
    rating:         4.2,
    reviews:        13359,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "thermostat"]
  },
  {
    id:             'ali-elec-040',
    name:           'Portable Power Station — 500W',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          9.94,
    originalPrice:  16.3,
    discount:       39,
    rating:         4.7,
    reviews:        14771,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "station", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-041',
    name:           'E-Reader — Backlit 6"',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          52.96,
    originalPrice:  89.76,
    discount:       41,
    rating:         4.6,
    reviews:        1120,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "e-reader"]
  },
  {
    id:             'ali-elec-042',
    name:           'Cable Management Box',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          49.87,
    originalPrice:  103.89,
    discount:       52,
    rating:         4.9,
    reviews:        23726,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "box", "accessories", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-043',
    name:           'Smart Speaker — Voice Assistant',
    category:       'electronics',
    subcategory:    'Phones',
    price:          13.74,
    originalPrice:  28.05,
    discount:       51,
    rating:         4.4,
    reviews:        15142,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "speaker", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'ali-elec-044',
    name:           'Drawing Tablet — A5',
    category:       'electronics',
    subcategory:    'Audio',
    price:          47.19,
    originalPrice:  84.27,
    discount:       44,
    rating:         4.5,
    reviews:        15400,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "tablet", "electronics", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-045',
    name:           'Solar Charger Panel — 20W',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          77.21,
    originalPrice:  113.54,
    discount:       32,
    rating:         4.5,
    reviews:        6126,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "panel"]
  },
  {
    id:             'ali-elec-046',
    name:           'USB Microphone — Podcast',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          63.4,
    originalPrice:  91.89,
    discount:       31,
    rating:         4.6,
    reviews:        13506,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "microphone", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-047',
    name:           'Car Phone Holder — Magnetic',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          8.66,
    originalPrice:  17.33,
    discount:       50,
    rating:         4.3,
    reviews:        7979,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'ali-elec-048',
    name:           'Smart Door Lock — Fingerprint',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          41.39,
    originalPrice:  58.3,
    discount:       29,
    rating:         4.1,
    reviews:        7629,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "electronics", "accessories", "lock", "gadgets", "smart"]
  },
  {
    id:             'ali-elec-049',
    name:           'Dash Cam Hardwire Kit',
    category:       'electronics',
    subcategory:    'Phones',
    price:          31.47,
    originalPrice:  74.94,
    discount:       58,
    rating:         4.5,
    reviews:        10155,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "tech", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'ali-elec-050',
    name:           'Screen Protector — Tempered Glass',
    category:       'electronics',
    subcategory:    'Audio',
    price:          31.6,
    originalPrice:  43.29,
    discount:       27,
    rating:         4.4,
    reviews:        20758,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "protector"]
  }
);
