/* ALIEXPRESS — Flowers (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-flow-001',
    name:           'Luxury Rose Bouquet — 24 Stems',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          39.55,
    originalPrice:  82.4,
    discount:       52,
    rating:         4.1,
    reviews:        14591,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-002',
    name:           'Sunflower & Wildflower Mix Bunch',
    category:       'flowers',
    subcategory:    'Dried',
    price:          14.59,
    originalPrice:  33.94,
    discount:       57,
    rating:         4.3,
    reviews:        2900,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-003',
    name:           'Eternal Preserved Roses — Box',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          42.11,
    originalPrice:  113.81,
    discount:       63,
    rating:         4.2,
    reviews:        20154,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "roses", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-004',
    name:           'Dried Pampas Grass Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          12.93,
    originalPrice:  27.52,
    discount:       53,
    rating:         5.0,
    reviews:        14145,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ali-flow-005',
    name:           'Tulip Mixed Colours — 15 Stems',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          28.43,
    originalPrice:  58.03,
    discount:       51,
    rating:         5.0,
    reviews:        1202,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "colours", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-006',
    name:           'Orchid Plant — Pink Phalaenopsis',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          46.98,
    originalPrice:  71.18,
    discount:       34,
    rating:         4.3,
    reviews:        20852,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet", "plant"]
  },
  {
    id:             'ali-flow-007',
    name:           'Peony & Rose Arrangement',
    category:       'flowers',
    subcategory:    'Dried',
    price:          69.95,
    originalPrice:  107.62,
    discount:       35,
    rating:         4.3,
    reviews:        2960,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "dried", "arrangement", "bouquet"]
  },
  {
    id:             'ali-flow-008',
    name:           'Lavender Bundle — Dried',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          43.76,
    originalPrice:  87.52,
    discount:       50,
    rating:         4.5,
    reviews:        24315,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "floral", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-009',
    name:           'Succulent Mini Garden Set',
    category:       'flowers',
    subcategory:    'Plants',
    price:          19.52,
    originalPrice:  27.5,
    discount:       29,
    rating:         4.1,
    reviews:        24455,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "set", "bouquet"]
  },
  {
    id:             'ali-flow-010',
    name:           'Hydrangea Arrangement — Blue',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          10.83,
    originalPrice:  17.75,
    discount:       39,
    rating:         4.8,
    reviews:        21787,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "gift_sets", "arrangement", "bouquet"]
  },
  {
    id:             'ali-flow-011',
    name:           'Artificial Rose Garland — 2m',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          20.58,
    originalPrice:  34.3,
    discount:       40,
    rating:         4.3,
    reviews:        8968,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "garland", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-012',
    name:           'Birthday Balloon & Flower Box',
    category:       'flowers',
    subcategory:    'Dried',
    price:          32.08,
    originalPrice:  65.46,
    discount:       51,
    rating:         4.5,
    reviews:        2882,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-013',
    name:           'Spring Daffodil Bunch — Yellow',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          5.11,
    originalPrice:  13.45,
    discount:       62,
    rating:         4.5,
    reviews:        20494,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "bunch", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-014',
    name:           'Gypsophila (Baby\'s Breath) Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          37.77,
    originalPrice:  102.07,
    discount:       63,
    rating:         4.4,
    reviews:        16845,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ali-flow-015',
    name:           'Lily & Gerbera Mix Bouquet',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          28.08,
    originalPrice:  43.88,
    discount:       36,
    rating:         4.8,
    reviews:        7870,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-016',
    name:           'Dried Flowers Wreath — 30cm',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          48.53,
    originalPrice:  93.33,
    discount:       48,
    rating:         4.7,
    reviews:        15354,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "wreath", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-017',
    name:           'Cherry Blossom Stem — Artificial',
    category:       'flowers',
    subcategory:    'Dried',
    price:          54.41,
    originalPrice:  89.2,
    discount:       39,
    rating:         4.5,
    reviews:        16207,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "dried", "stem", "bouquet"]
  },
  {
    id:             'ali-flow-018',
    name:           'Faux Eucalyptus Garland',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          80.93,
    originalPrice:  105.1,
    discount:       23,
    rating:         4.4,
    reviews:        23069,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "artificial", "garland", "bouquet"]
  },
  {
    id:             'ali-flow-019',
    name:           'Annual Seeds Garden Pack',
    category:       'flowers',
    subcategory:    'Plants',
    price:          17.87,
    originalPrice:  45.83,
    discount:       61,
    rating:         4.3,
    reviews:        712,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "bouquet", "pack"]
  },
  {
    id:             'ali-flow-020',
    name:           'Valentine Red Rose Bouquet — 12',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          62.78,
    originalPrice:  92.32,
    discount:       32,
    rating:         4.1,
    reviews:        24119,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-021',
    name:           'Chrysanthemum Spray — Mixed',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          12.59,
    originalPrice:  18.25,
    discount:       31,
    rating:         4.1,
    reviews:        12909,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "bouquet", "fresh", "spray"]
  },
  {
    id:             'ali-flow-022',
    name:           'Lotus Flower Floating Bowl Set',
    category:       'flowers',
    subcategory:    'Dried',
    price:          37.1,
    originalPrice:  84.32,
    discount:       56,
    rating:         4.9,
    reviews:        13050,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "dried", "set", "bouquet"]
  },
  {
    id:             'ali-flow-023',
    name:           'Tropical Foliage Arrangement',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          43.28,
    originalPrice:  81.66,
    discount:       47,
    rating:         4.5,
    reviews:        12663,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "artificial", "arrangement", "bouquet"]
  },
  {
    id:             'ali-flow-024',
    name:           'Bluebell Woodland Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          35.89,
    originalPrice:  64.09,
    discount:       44,
    rating:         4.4,
    reviews:        14860,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'ali-flow-025',
    name:           'Carnation Bouquet — Rainbow',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          41.7,
    originalPrice:  92.67,
    discount:       55,
    rating:         5.0,
    reviews:        20163,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-026',
    name:           'Silk Artificial Orchid Stem',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          38.81,
    originalPrice:  102.14,
    discount:       62,
    rating:         4.6,
    reviews:        4769,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "fresh", "stem", "bouquet"]
  },
  {
    id:             'ali-flow-027',
    name:           'Boxed Infinity Roses — 9 Pack',
    category:       'flowers',
    subcategory:    'Dried',
    price:          30.98,
    originalPrice:  81.53,
    discount:       62,
    rating:         4.3,
    reviews:        7570,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "roses", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-028',
    name:           'Potted Jasmine Plant',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          6.16,
    originalPrice:  15.41,
    discount:       60,
    rating:         4.8,
    reviews:        7374,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "artificial", "bouquet", "plant"]
  },
  {
    id:             'ali-flow-029',
    name:           'Anemone & Ranunculus Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          55.75,
    originalPrice:  74.33,
    discount:       25,
    rating:         4.7,
    reviews:        15478,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'ali-flow-030',
    name:           'Flower Crown Making Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          19.46,
    originalPrice:  44.23,
    discount:       56,
    rating:         4.4,
    reviews:        933,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-031',
    name:           'Wildflower Meadow Seed Mix',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          18.31,
    originalPrice:  26.53,
    discount:       31,
    rating:         4.2,
    reviews:        14043,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-032',
    name:           'Poppy Bunch — Orange & Red',
    category:       'flowers',
    subcategory:    'Dried',
    price:          21.07,
    originalPrice:  32.41,
    discount:       35,
    rating:         4.2,
    reviews:        19200,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-033',
    name:           'Wedding Buttonhole Kit — Rose',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          21.56,
    originalPrice:  46.86,
    discount:       54,
    rating:         4.9,
    reviews:        11540,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-034',
    name:           'Dried Protea & Ferns Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          30.68,
    originalPrice:  66.7,
    discount:       54,
    rating:         4.1,
    reviews:        1581,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'ali-flow-035',
    name:           'Hanging Flower Ball — Silk',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          39.78,
    originalPrice:  92.51,
    discount:       57,
    rating:         4.8,
    reviews:        5308,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["ball", "floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-036',
    name:           'Daisy Chain Meadow Bunch',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          76.45,
    originalPrice:  115.84,
    discount:       34,
    rating:         4.9,
    reviews:        10766,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "bunch", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-037',
    name:           'Moss Terrarium Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          42.6,
    originalPrice:  71.0,
    discount:       40,
    rating:         4.7,
    reviews:        13335,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-038',
    name:           'Pressed Flower Bookmark Set',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          19.74,
    originalPrice:  56.41,
    discount:       65,
    rating:         5.0,
    reviews:        20515,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "artificial", "set", "bouquet"]
  },
  {
    id:             'ali-flow-039',
    name:           'Flower Frog Kenzan Holder',
    category:       'flowers',
    subcategory:    'Plants',
    price:          4.69,
    originalPrice:  12.02,
    discount:       61,
    rating:         4.2,
    reviews:        14220,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "holder", "bouquet"]
  },
  {
    id:             'ali-flow-040',
    name:           'Faux Wisteria Hanging Branch',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          65.22,
    originalPrice:  81.53,
    discount:       20,
    rating:         4.5,
    reviews:        8657,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "branch", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-041',
    name:           'Rose Petal Confetti — Biodegradable',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          39.28,
    originalPrice:  64.39,
    discount:       39,
    rating:         4.4,
    reviews:        9543,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "confetti", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-042',
    name:           'Ikebana Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          14.43,
    originalPrice:  31.37,
    discount:       54,
    rating:         4.0,
    reviews:        17468,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-043',
    name:           'Calla Lily Artificial Stems',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          57.88,
    originalPrice:  81.52,
    discount:       29,
    rating:         4.0,
    reviews:        578,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "stems", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-044',
    name:           'Eucalyptus & White Rose Wreath',
    category:       'flowers',
    subcategory:    'Plants',
    price:          29.01,
    originalPrice:  82.89,
    discount:       65,
    rating:         4.3,
    reviews:        1487,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'ali-flow-045',
    name:           'Floral Foam Arrangement Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          31.35,
    originalPrice:  89.56,
    discount:       65,
    rating:         4.4,
    reviews:        18473,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'ali-flow-046',
    name:           'Edible Flower Mix — Microgreens',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          24.52,
    originalPrice:  40.2,
    discount:       39,
    rating:         4.5,
    reviews:        7619,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'ali-flow-047',
    name:           'Flower Subscription Box — Monthly',
    category:       'flowers',
    subcategory:    'Dried',
    price:          40.93,
    originalPrice:  116.93,
    discount:       65,
    rating:         4.7,
    reviews:        20757,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'ali-flow-048',
    name:           'Paper Flower Crafting Kit',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          19.75,
    originalPrice:  30.38,
    discount:       35,
    rating:         4.4,
    reviews:        24557,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'ali-flow-049',
    name:           'Autumn Leaf Wreath — Door',
    category:       'flowers',
    subcategory:    'Plants',
    price:          74.63,
    originalPrice:  113.07,
    discount:       34,
    rating:         4.5,
    reviews:        24724,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'ali-flow-050',
    name:           'Festive Poinsettia Plant',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          8.89,
    originalPrice:  15.87,
    discount:       44,
    rating:         4.9,
    reviews:        23727,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet", "plant"]
  }
);
