/* ALIEXPRESS — Home (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-home-001',
    name:           'Bohemian Throw Pillow Covers — Set of 4',
    category:       'home',
    subcategory:    'Furniture',
    price:          35.13,
    originalPrice:  97.57,
    discount:       64,
    rating:         4.8,
    reviews:        1994,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "furniture", "covers", "decor"]
  },
  {
    id:             'ali-home-002',
    name:           'LED Desk Lamp with USB Charging Port',
    category:       'home',
    subcategory:    'Kitchen',
    price:          24.95,
    originalPrice:  37.8,
    discount:       34,
    rating:         4.6,
    reviews:        19294,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "port", "decor"]
  },
  {
    id:             'ali-home-003',
    name:           'Non-Stick Cookware Set — 5 Pieces',
    category:       'home',
    subcategory:    'Decor',
    price:          7.24,
    originalPrice:  14.47,
    discount:       50,
    rating:         4.2,
    reviews:        16029,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-004',
    name:           'Aesthetic Bedding Set — King Size',
    category:       'home',
    subcategory:    'Bedding',
    price:          48.5,
    originalPrice:  101.05,
    discount:       52,
    rating:         4.9,
    reviews:        15978,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ali-home-005',
    name:           'Aesthetic Acrylic Desk Organiser Set',
    category:       'home',
    subcategory:    'Lighting',
    price:          50.5,
    originalPrice:  112.23,
    discount:       55,
    rating:         5.0,
    reviews:        19411,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "lighting", "decor"]
  },
  {
    id:             'ali-home-006',
    name:           'Fairy Lights — 10m USB Warm White',
    category:       'home',
    subcategory:    'Storage',
    price:          19.9,
    originalPrice:  48.54,
    discount:       59,
    rating:         5.0,
    reviews:        2370,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["lights", "storage", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-007',
    name:           'Cute Ceramic Mug Set — 2 Pack',
    category:       'home',
    subcategory:    'Furniture',
    price:          41.68,
    originalPrice:  104.2,
    discount:       60,
    rating:         4.6,
    reviews:        5828,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ali-home-008',
    name:           'Minimalist Wall Clock — Silent Quartz',
    category:       'home',
    subcategory:    'Kitchen',
    price:          12.89,
    originalPrice:  25.27,
    discount:       49,
    rating:         4.4,
    reviews:        22072,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["clock", "kitchen", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-009',
    name:           'LED Strip Lights — 5m RGB Smart',
    category:       'home',
    subcategory:    'Decor',
    price:          13.17,
    originalPrice:  18.55,
    discount:       29,
    rating:         4.7,
    reviews:        9551,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["lights", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-010',
    name:           'Bamboo Bathroom Organiser',
    category:       'home',
    subcategory:    'Bedding',
    price:          42.18,
    originalPrice:  105.46,
    discount:       60,
    rating:         4.8,
    reviews:        17969,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["organiser", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ali-home-011',
    name:           'Velvet Storage Ottoman Cube',
    category:       'home',
    subcategory:    'Lighting',
    price:          27.45,
    originalPrice:  78.43,
    discount:       65,
    rating:         4.6,
    reviews:        23877,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "lighting", "cube", "decor"]
  },
  {
    id:             'ali-home-012',
    name:           'Woven Seagrass Basket — Large',
    category:       'home',
    subcategory:    'Storage',
    price:          56.77,
    originalPrice:  118.28,
    discount:       52,
    rating:         4.7,
    reviews:        13591,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "basket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-013',
    name:           'Floating Wall Shelves — Set of 3',
    category:       'home',
    subcategory:    'Furniture',
    price:          36.93,
    originalPrice:  67.14,
    discount:       45,
    rating:         4.5,
    reviews:        6235,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "decor", "interior", "living", "furniture", "shelves"]
  },
  {
    id:             'ali-home-014',
    name:           'Diffuser & Essential Oil Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          43.58,
    originalPrice:  79.23,
    discount:       45,
    rating:         4.0,
    reviews:        5107,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-015',
    name:           'Faux Fur Throw Blanket — Grey',
    category:       'home',
    subcategory:    'Decor',
    price:          31.61,
    originalPrice:  58.53,
    discount:       46,
    rating:         4.4,
    reviews:        16610,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-016',
    name:           'Boho Macramé Wall Hanging',
    category:       'home',
    subcategory:    'Bedding',
    price:          54.76,
    originalPrice:  84.25,
    discount:       35,
    rating:         4.3,
    reviews:        24177,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "hanging", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ali-home-017',
    name:           'Vintage Table Lamp — Rattan',
    category:       'home',
    subcategory:    'Lighting',
    price:          45.61,
    originalPrice:  114.02,
    discount:       60,
    rating:         4.7,
    reviews:        11752,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "lamp", "lighting", "decor"]
  },
  {
    id:             'ali-home-018',
    name:           'Glass Candle Holder Set',
    category:       'home',
    subcategory:    'Storage',
    price:          60.99,
    originalPrice:  115.07,
    discount:       47,
    rating:         4.4,
    reviews:        7857,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-019',
    name:           'Kitchen Herb Planter — 3 Pots',
    category:       'home',
    subcategory:    'Furniture',
    price:          42.59,
    originalPrice:  77.44,
    discount:       45,
    rating:         4.8,
    reviews:        23613,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "planter", "living", "furniture", "decor"]
  },
  {
    id:             'ali-home-020',
    name:           'Anti-Fatigue Kitchen Mat',
    category:       'home',
    subcategory:    'Kitchen',
    price:          19.76,
    originalPrice:  26.35,
    discount:       25,
    rating:         4.6,
    reviews:        616,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "mat", "decor"]
  },
  {
    id:             'ali-home-021',
    name:           'Peel & Stick Wallpaper — Botanical',
    category:       'home',
    subcategory:    'Decor',
    price:          33.19,
    originalPrice:  59.27,
    discount:       44,
    rating:         4.8,
    reviews:        1145,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "wallpaper", "decor"]
  },
  {
    id:             'ali-home-022',
    name:           'Smart Plug Power Strip',
    category:       'home',
    subcategory:    'Bedding',
    price:          56.54,
    originalPrice:  88.34,
    discount:       36,
    rating:         4.1,
    reviews:        24111,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "strip", "bedding", "decor"]
  },
  {
    id:             'ali-home-023',
    name:           'Linen Shower Curtain — White',
    category:       'home',
    subcategory:    'Lighting',
    price:          38.74,
    originalPrice:  82.42,
    discount:       53,
    rating:         4.2,
    reviews:        3434,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "curtain", "lighting", "decor"]
  },
  {
    id:             'ali-home-024',
    name:           'Over-Door Towel Rail',
    category:       'home',
    subcategory:    'Storage',
    price:          39.81,
    originalPrice:  57.7,
    discount:       31,
    rating:         4.6,
    reviews:        18462,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "home", "interior", "living", "rail", "decor"]
  },
  {
    id:             'ali-home-025',
    name:           'Plant Pot Set — Pastel Terracotta',
    category:       'home',
    subcategory:    'Furniture',
    price:          41.04,
    originalPrice:  77.43,
    discount:       47,
    rating:         4.7,
    reviews:        4247,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ali-home-026',
    name:           'Wooden Serving Board',
    category:       'home',
    subcategory:    'Kitchen',
    price:          36.83,
    originalPrice:  50.45,
    discount:       27,
    rating:         4.8,
    reviews:        15960,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "board", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-027',
    name:           'Spice Rack — Rotating Turntable',
    category:       'home',
    subcategory:    'Decor',
    price:          27.59,
    originalPrice:  74.56,
    discount:       63,
    rating:         4.5,
    reviews:        24422,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "rack", "decor"]
  },
  {
    id:             'ali-home-028',
    name:           'Bed Tray Laptop Desk',
    category:       'home',
    subcategory:    'Bedding',
    price:          51.72,
    originalPrice:  77.2,
    discount:       33,
    rating:         4.5,
    reviews:        6754,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "desk", "bedding", "decor"]
  },
  {
    id:             'ali-home-029',
    name:           'Velvet Curtains — Blackout Grey',
    category:       'home',
    subcategory:    'Lighting',
    price:          69.12,
    originalPrice:  94.68,
    discount:       27,
    rating:         4.5,
    reviews:        22262,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "curtains", "lighting", "decor"]
  },
  {
    id:             'ali-home-030',
    name:           'Decorative Wicker Mirror',
    category:       'home',
    subcategory:    'Storage',
    price:          42.29,
    originalPrice:  66.08,
    discount:       36,
    rating:         4.1,
    reviews:        16629,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "home", "interior", "living", "mirror", "decor"]
  },
  {
    id:             'ali-home-031',
    name:           'Stainless Steel Water Bottle — 1L',
    category:       'home',
    subcategory:    'Furniture',
    price:          35.26,
    originalPrice:  48.97,
    discount:       28,
    rating:         4.4,
    reviews:        22855,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "furniture", "bottle", "decor"]
  },
  {
    id:             'ali-home-032',
    name:           'Bamboo Cutting Board Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          53.68,
    originalPrice:  82.58,
    discount:       35,
    rating:         4.3,
    reviews:        21023,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-033',
    name:           'Shower Caddy — 3 Tier',
    category:       'home',
    subcategory:    'Decor',
    price:          60.94,
    originalPrice:  84.64,
    discount:       28,
    rating:         4.9,
    reviews:        8046,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "decor", "interior", "living", "caddy"]
  },
  {
    id:             'ali-home-034',
    name:           'Framed Print Wall Art Set',
    category:       'home',
    subcategory:    'Bedding',
    price:          76.85,
    originalPrice:  98.52,
    discount:       22,
    rating:         4.9,
    reviews:        6311,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ali-home-035',
    name:           'Laundry Basket — Woven Rope',
    category:       'home',
    subcategory:    'Lighting',
    price:          23.92,
    originalPrice:  31.47,
    discount:       24,
    rating:         4.3,
    reviews:        21539,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["basket", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'ali-home-036',
    name:           'Electric Kettle — Rose Gold',
    category:       'home',
    subcategory:    'Storage',
    price:          14.74,
    originalPrice:  30.09,
    discount:       51,
    rating:         4.2,
    reviews:        12040,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "home", "kettle", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-037',
    name:           'Air Fryer — 5.5L Digital',
    category:       'home',
    subcategory:    'Furniture',
    price:          13.42,
    originalPrice:  25.32,
    discount:       47,
    rating:         4.5,
    reviews:        4052,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "furniture", "fryer", "decor"]
  },
  {
    id:             'ali-home-038',
    name:           'Robot Mop & Vacuum Combo',
    category:       'home',
    subcategory:    'Kitchen',
    price:          92.24,
    originalPrice:  119.79,
    discount:       23,
    rating:         4.6,
    reviews:        4264,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "combo", "decor"]
  },
  {
    id:             'ali-home-039',
    name:           'Weighted Blanket — 8kg',
    category:       'home',
    subcategory:    'Decor',
    price:          95.33,
    originalPrice:  119.16,
    discount:       20,
    rating:         4.1,
    reviews:        2920,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-040',
    name:           'Cordless Stick Vacuum',
    category:       'home',
    subcategory:    'Bedding',
    price:          29.99,
    originalPrice:  66.64,
    discount:       55,
    rating:         4.3,
    reviews:        16321,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["vacuum", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ali-home-041',
    name:           'Under-Bed Storage Boxes',
    category:       'home',
    subcategory:    'Lighting',
    price:          25.42,
    originalPrice:  33.01,
    discount:       23,
    rating:         4.5,
    reviews:        8958,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["boxes", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'ali-home-042',
    name:           'Memory Foam Pillow — Contour',
    category:       'home',
    subcategory:    'Storage',
    price:          25.89,
    originalPrice:  68.14,
    discount:       62,
    rating:         4.1,
    reviews:        14575,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "pillow", "home", "interior", "living", "decor"]
  },
  {
    id:             'ali-home-043',
    name:           'Ceramic Dinner Set — 16 Piece',
    category:       'home',
    subcategory:    'Furniture',
    price:          68.17,
    originalPrice:  96.02,
    discount:       29,
    rating:         4.6,
    reviews:        3017,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ali-home-044',
    name:           'Knife Block Set — 7 Piece',
    category:       'home',
    subcategory:    'Kitchen',
    price:          80.17,
    originalPrice:  105.49,
    discount:       24,
    rating:         4.7,
    reviews:        16805,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-045',
    name:           'Bath Mat Set — Non-Slip',
    category:       'home',
    subcategory:    'Decor',
    price:          32.4,
    originalPrice:  92.57,
    discount:       65,
    rating:         4.6,
    reviews:        15888,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ali-home-046',
    name:           'Smart Colour Bulb Set — 4 Pack',
    category:       'home',
    subcategory:    'Bedding',
    price:          21.65,
    originalPrice:  45.1,
    discount:       52,
    rating:         4.6,
    reviews:        6907,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ali-home-047',
    name:           'Blackout Roller Blind',
    category:       'home',
    subcategory:    'Lighting',
    price:          56.2,
    originalPrice:  78.05,
    discount:       28,
    rating:         4.2,
    reviews:        22838,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["home", "interior", "living", "lighting", "blind", "decor"]
  },
  {
    id:             'ali-home-048',
    name:           'Essential Oil Diffuser — Ultrasonic',
    category:       'home',
    subcategory:    'Storage',
    price:          46.18,
    originalPrice:  109.95,
    discount:       58,
    rating:         4.0,
    reviews:        17842,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["storage", "home", "interior", "living", "diffuser", "decor"]
  },
  {
    id:             'ali-home-049',
    name:           'Handheld Garment Steamer',
    category:       'home',
    subcategory:    'Furniture',
    price:          49.73,
    originalPrice:  101.49,
    discount:       51,
    rating:         4.0,
    reviews:        23728,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["steamer", "home", "interior", "living", "furniture", "decor"]
  },
  {
    id:             'ali-home-050',
    name:           'Kitchen Towel Set — Cotton',
    category:       'home',
    subcategory:    'Kitchen',
    price:          48.42,
    originalPrice:  112.61,
    discount:       57,
    rating:         4.3,
    reviews:        22424,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  }
);
