/* ALIEXPRESS — Jewelry (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-jewe-001',
    name:           '925 Silver Minimalist Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          36.78,
    originalPrice:  73.57,
    discount:       50,
    rating:         5.0,
    reviews:        9696,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-002',
    name:           'Dainty Layered Gold Chain Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          28.53,
    originalPrice:  40.76,
    discount:       30,
    rating:         4.2,
    reviews:        10320,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-003',
    name:           'Gold Plated Jhumka Earrings Set',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          51.65,
    originalPrice:  66.22,
    discount:       22,
    rating:         4.5,
    reviews:        6955,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ali-jewe-004',
    name:           'Stacking Rings Set — 10 Piece',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          27.89,
    originalPrice:  59.34,
    discount:       53,
    rating:         4.1,
    reviews:        13808,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ali-jewe-005',
    name:           'Pearl Stud Earrings — Classic',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          31.44,
    originalPrice:  69.86,
    discount:       55,
    rating:         4.4,
    reviews:        10955,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-006',
    name:           'Statement Hoop Earrings — Gold',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          29.78,
    originalPrice:  70.91,
    discount:       58,
    rating:         4.1,
    reviews:        8094,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-007',
    name:           'Crystal Tennis Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          21.3,
    originalPrice:  28.4,
    discount:       25,
    rating:         4.5,
    reviews:        3019,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-008',
    name:           'Vintage Cameo Brooch',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          47.51,
    originalPrice:  103.29,
    discount:       54,
    rating:         4.5,
    reviews:        6520,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "brooch", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'ali-jewe-009',
    name:           'Turquoise Beaded Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          22.79,
    originalPrice:  38.63,
    discount:       41,
    rating:         4.4,
    reviews:        24170,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-010',
    name:           'Anklet Set — Gold Chain',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          47.48,
    originalPrice:  83.3,
    discount:       43,
    rating:         4.9,
    reviews:        19889,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ali-jewe-011',
    name:           'Heart Locket Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          8.26,
    originalPrice:  12.14,
    discount:       32,
    rating:         4.7,
    reviews:        2546,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-012',
    name:           'Evil Eye Charm Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          11.08,
    originalPrice:  24.08,
    discount:       54,
    rating:         4.6,
    reviews:        16863,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-013',
    name:           'Opal Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          56.84,
    originalPrice:  113.68,
    discount:       50,
    rating:         4.7,
    reviews:        24422,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-014',
    name:           'Rose Gold Infinity Bracelet',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          39.12,
    originalPrice:  69.86,
    discount:       44,
    rating:         5.0,
    reviews:        8144,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-015',
    name:           'Diamond CZ Stud Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          16.84,
    originalPrice:  30.07,
    discount:       44,
    rating:         4.3,
    reviews:        1155,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-016',
    name:           'Name Initial Letter Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          41.36,
    originalPrice:  84.4,
    discount:       51,
    rating:         4.1,
    reviews:        6398,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-017',
    name:           'Geometric Triangle Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          21.54,
    originalPrice:  58.21,
    discount:       63,
    rating:         4.7,
    reviews:        3614,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-018',
    name:           'Twisted Bangle Set — 5 Pack',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          58.1,
    originalPrice:  89.38,
    discount:       35,
    rating:         4.3,
    reviews:        17642,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ali-jewe-019',
    name:           'Floral Hair Pins Set',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          34.11,
    originalPrice:  74.16,
    discount:       54,
    rating:         4.1,
    reviews:        17715,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ali-jewe-020',
    name:           'Moon & Stars Choker',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          58.01,
    originalPrice:  79.46,
    discount:       27,
    rating:         4.3,
    reviews:        23408,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["choker", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-021',
    name:           'Cluster Ring — Pink Tourmaline CZ',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          53.92,
    originalPrice:  117.22,
    discount:       54,
    rating:         4.1,
    reviews:        13999,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["ring", "accessories", "necklaces", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-022',
    name:           'Tassel Drop Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          45.54,
    originalPrice:  56.93,
    discount:       20,
    rating:         4.8,
    reviews:        9827,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-023',
    name:           'Layered Satellite Necklace',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          27.48,
    originalPrice:  42.93,
    discount:       36,
    rating:         4.7,
    reviews:        18718,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "jewelry", "necklace", "earrings", "gold"]
  },
  {
    id:             'ali-jewe-024',
    name:           'Charm Bracelet — Starter',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          53.89,
    originalPrice:  109.98,
    discount:       51,
    rating:         4.8,
    reviews:        11133,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-025',
    name:           'Bar Pendant Necklace — Engraved',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          31.44,
    originalPrice:  42.48,
    discount:       26,
    rating:         4.3,
    reviews:        15962,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-026',
    name:           'Snake Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          17.86,
    originalPrice:  23.2,
    discount:       23,
    rating:         4.1,
    reviews:        10472,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-027',
    name:           'Vintage Pearl Necklace — Multi-Strand',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          9.27,
    originalPrice:  21.55,
    discount:       57,
    rating:         4.5,
    reviews:        9714,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-028',
    name:           'Leaf Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          30.69,
    originalPrice:  61.38,
    discount:       50,
    rating:         4.4,
    reviews:        10282,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-029',
    name:           'Birthstone Ring — Personalised',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          10.08,
    originalPrice:  12.76,
    discount:       21,
    rating:         4.3,
    reviews:        11876,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-030',
    name:           'Celestial Sun Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          38.04,
    originalPrice:  61.35,
    discount:       38,
    rating:         4.7,
    reviews:        20708,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-031',
    name:           'Crystal Choker Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          60.67,
    originalPrice:  116.68,
    discount:       48,
    rating:         4.3,
    reviews:        12127,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-032',
    name:           'Emerald CZ Cocktail Ring',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          62.09,
    originalPrice:  108.93,
    discount:       43,
    rating:         4.8,
    reviews:        12606,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-033',
    name:           'Gold Hoop Set — 3 Pairs',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          38.29,
    originalPrice:  87.03,
    discount:       56,
    rating:         4.8,
    reviews:        5402,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ali-jewe-034',
    name:           'Cuff Bangle — Hammered Gold',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          53.03,
    originalPrice:  98.21,
    discount:       46,
    rating:         4.3,
    reviews:        24822,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "bangle", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-035',
    name:           'Seed Bead Friendship Bracelet',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          81.88,
    originalPrice:  103.65,
    discount:       21,
    rating:         4.9,
    reviews:        24946,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-036',
    name:           'Safety Pin Earrings',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          10.79,
    originalPrice:  24.52,
    discount:       56,
    rating:         4.1,
    reviews:        19622,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-037',
    name:           'Mismatched Statement Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          42.67,
    originalPrice:  77.58,
    discount:       45,
    rating:         4.6,
    reviews:        13063,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-038',
    name:           'Charm Bangle — Pandora Style',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          63.11,
    originalPrice:  83.04,
    discount:       24,
    rating:         4.2,
    reviews:        23289,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "bangle", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'ali-jewe-039',
    name:           'Blue Topaz Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          53.69,
    originalPrice:  71.59,
    discount:       25,
    rating:         4.2,
    reviews:        14786,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-040',
    name:           'Stud Earrings Gift Set',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          16.35,
    originalPrice:  26.37,
    discount:       38,
    rating:         4.9,
    reviews:        13348,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ali-jewe-041',
    name:           'Ear Cuff — No Piercing Required',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          52.19,
    originalPrice:  70.53,
    discount:       26,
    rating:         4.6,
    reviews:        6061,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "cuff", "gold"]
  },
  {
    id:             'ali-jewe-042',
    name:           'Link Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          51.57,
    originalPrice:  67.85,
    discount:       24,
    rating:         4.4,
    reviews:        21531,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ali-jewe-043',
    name:           'Freshwater Pearl Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          35.92,
    originalPrice:  64.14,
    discount:       44,
    rating:         4.8,
    reviews:        18113,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-044',
    name:           'Crystal Headband — Bridal',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          45.64,
    originalPrice:  108.67,
    discount:       58,
    rating:         4.9,
    reviews:        2921,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "headband", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-045',
    name:           'Vintage Art Deco Ring',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          58.71,
    originalPrice:  115.12,
    discount:       49,
    rating:         4.1,
    reviews:        11129,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["ring", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-046',
    name:           'Flower Stud Earrings — Enamel',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          41.07,
    originalPrice:  63.18,
    discount:       35,
    rating:         4.8,
    reviews:        18514,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-047',
    name:           'Rhinestone Bib Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          22.28,
    originalPrice:  33.25,
    discount:       33,
    rating:         4.5,
    reviews:        11812,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-048',
    name:           'Asymmetric Dangle Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          65.73,
    originalPrice:  104.34,
    discount:       37,
    rating:         4.1,
    reviews:        15270,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ali-jewe-049',
    name:           'Gold Plated Coin Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          64.14,
    originalPrice:  106.9,
    discount:       40,
    rating:         4.3,
    reviews:        1570,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ali-jewe-050',
    name:           'Stackable Thin Band Rings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          80.2,
    originalPrice:  105.52,
    discount:       24,
    rating:         4.5,
    reviews:        8164,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["rings", "accessories", "anklets", "silver", "jewelry", "gold"]
  }
);
