/* ALIEXPRESS — Kids (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-kids-001',
    name:           'Dinosaur Print Pyjama Set',
    category:       'kids',
    subcategory:    'Girls',
    price:          14.18,
    originalPrice:  39.4,
    discount:       64,
    rating:         4.5,
    reviews:        16073,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-002',
    name:           'Bunny Ear Hooded Sweatshirt',
    category:       'kids',
    subcategory:    'Boys',
    price:          36.6,
    originalPrice:  69.06,
    discount:       47,
    rating:         4.1,
    reviews:        24548,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "sweatshirt", "boys", "girls"]
  },
  {
    id:             'ali-kids-003',
    name:           'Rainbow Tutu Dress',
    category:       'kids',
    subcategory:    'Baby',
    price:          27.36,
    originalPrice:  49.74,
    discount:       45,
    rating:         4.8,
    reviews:        11891,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "baby", "dress", "girls"]
  },
  {
    id:             'ali-kids-004',
    name:           'School Uniform Shirt 3-Pack',
    category:       'kids',
    subcategory:    'School Wear',
    price:          31.97,
    originalPrice:  54.19,
    discount:       41,
    rating:         4.5,
    reviews:        8957,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "3-pack", "boys", "girls"]
  },
  {
    id:             'ali-kids-005',
    name:           'Denim Dungarees — Blue',
    category:       'kids',
    subcategory:    'Toys',
    price:          25.07,
    originalPrice:  36.34,
    discount:       31,
    rating:         4.7,
    reviews:        1954,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "dungarees", "boys", "girls"]
  },
  {
    id:             'ali-kids-006',
    name:           'Floral Smocked Dress',
    category:       'kids',
    subcategory:    'Footwear',
    price:          9.33,
    originalPrice:  25.22,
    discount:       63,
    rating:         4.5,
    reviews:        6261,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "boys", "dress", "girls"]
  },
  {
    id:             'ali-kids-007',
    name:           'Bear Appliqué Knit Jumper',
    category:       'kids',
    subcategory:    'Girls',
    price:          78.27,
    originalPrice:  105.77,
    discount:       26,
    rating:         4.9,
    reviews:        23690,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "jumper", "girls"]
  },
  {
    id:             'ali-kids-008',
    name:           'Cartoon Print T-Shirt Set',
    category:       'kids',
    subcategory:    'Boys',
    price:          11.46,
    originalPrice:  14.5,
    discount:       21,
    rating:         4.4,
    reviews:        4340,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-009',
    name:           'Leggings 5-Pack — Bright Mix',
    category:       'kids',
    subcategory:    'Baby',
    price:          43.93,
    originalPrice:  109.83,
    discount:       60,
    rating:         4.9,
    reviews:        1021,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "5-pack", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-010',
    name:           'Striped Long-Sleeve Tee',
    category:       'kids',
    subcategory:    'School Wear',
    price:          69.67,
    originalPrice:  118.09,
    discount:       41,
    rating:         4.4,
    reviews:        14136,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "boys", "tee", "girls"]
  },
  {
    id:             'ali-kids-011',
    name:           'Sherpa-Lined Puffer Jacket',
    category:       'kids',
    subcategory:    'Toys',
    price:          13.45,
    originalPrice:  25.87,
    discount:       48,
    rating:         4.1,
    reviews:        2072,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["jacket", "children", "kids", "toys", "boys", "girls"]
  },
  {
    id:             'ali-kids-012',
    name:           'Fairy Wings Costume Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          87.38,
    originalPrice:  112.02,
    discount:       22,
    rating:         4.8,
    reviews:        11099,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-013',
    name:           'Cotton Romper — Newborn',
    category:       'kids',
    subcategory:    'Girls',
    price:          44.1,
    originalPrice:  76.04,
    discount:       42,
    rating:         4.7,
    reviews:        19682,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "romper", "boys", "girls"]
  },
  {
    id:             'ali-kids-014',
    name:           'Velvet Party Dress — Red',
    category:       'kids',
    subcategory:    'Boys',
    price:          50.71,
    originalPrice:  84.51,
    discount:       40,
    rating:         4.1,
    reviews:        15952,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ali-kids-015',
    name:           'Camouflage Cargo Shorts',
    category:       'kids',
    subcategory:    'Baby',
    price:          51.44,
    originalPrice:  65.12,
    discount:       21,
    rating:         4.1,
    reviews:        15989,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "shorts", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-016',
    name:           'Embroidered Denim Jacket',
    category:       'kids',
    subcategory:    'School Wear',
    price:          58.54,
    originalPrice:  114.78,
    discount:       49,
    rating:         4.2,
    reviews:        15394,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["jacket", "children", "kids", "school_wear", "boys", "girls"]
  },
  {
    id:             'ali-kids-017',
    name:           'Ballet Wrap Cardigan',
    category:       'kids',
    subcategory:    'Toys',
    price:          20.74,
    originalPrice:  47.14,
    discount:       56,
    rating:         4.2,
    reviews:        3075,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "cardigan", "toys", "boys", "girls"]
  },
  {
    id:             'ali-kids-018',
    name:           'Superhero Cape Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          42.94,
    originalPrice:  91.36,
    discount:       53,
    rating:         5.0,
    reviews:        212,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-019',
    name:           'Floral Swimsuit — UV50+',
    category:       'kids',
    subcategory:    'Girls',
    price:          18.15,
    originalPrice:  41.26,
    discount:       56,
    rating:         4.6,
    reviews:        7491,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "swimsuit", "boys", "girls"]
  },
  {
    id:             'ali-kids-020',
    name:           'Cosy Fleece Onesie — Animal Print',
    category:       'kids',
    subcategory:    'Boys',
    price:          17.12,
    originalPrice:  46.28,
    discount:       63,
    rating:         4.8,
    reviews:        16170,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "onesie", "boys", "girls"]
  },
  {
    id:             'ali-kids-021',
    name:           'Rainbow Knit Cardigan',
    category:       'kids',
    subcategory:    'Baby',
    price:          46.6,
    originalPrice:  78.99,
    discount:       41,
    rating:         4.2,
    reviews:        12735,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "cardigan", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-022',
    name:           'Football Kit Set',
    category:       'kids',
    subcategory:    'School Wear',
    price:          24.7,
    originalPrice:  37.42,
    discount:       34,
    rating:         4.2,
    reviews:        2990,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-023',
    name:           'Tropical Print Board Shorts',
    category:       'kids',
    subcategory:    'Toys',
    price:          63.98,
    originalPrice:  96.94,
    discount:       34,
    rating:         4.5,
    reviews:        22174,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "shorts", "boys", "girls"]
  },
  {
    id:             'ali-kids-024',
    name:           'Tiered Frill Skirt',
    category:       'kids',
    subcategory:    'Footwear',
    price:          51.96,
    originalPrice:  98.04,
    discount:       47,
    rating:         4.8,
    reviews:        6430,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "boys", "skirt", "girls"]
  },
  {
    id:             'ali-kids-025',
    name:           'School Cardigan — Navy',
    category:       'kids',
    subcategory:    'Girls',
    price:          48.7,
    originalPrice:  79.84,
    discount:       39,
    rating:         4.1,
    reviews:        11992,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "cardigan", "boys", "girls"]
  },
  {
    id:             'ali-kids-026',
    name:           'Jungle Print Playsuit',
    category:       'kids',
    subcategory:    'Boys',
    price:          78.18,
    originalPrice:  107.1,
    discount:       27,
    rating:         4.1,
    reviews:        22316,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "playsuit", "girls"]
  },
  {
    id:             'ali-kids-027',
    name:           'Stars & Stripes Hoodie',
    category:       'kids',
    subcategory:    'Baby',
    price:          17.66,
    originalPrice:  28.95,
    discount:       39,
    rating:         4.2,
    reviews:        15958,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["hoodie", "children", "kids", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-028',
    name:           'Princess Dress-Up Gown',
    category:       'kids',
    subcategory:    'School Wear',
    price:          48.02,
    originalPrice:  114.34,
    discount:       58,
    rating:         4.9,
    reviews:        23346,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "gown", "boys", "girls"]
  },
  {
    id:             'ali-kids-029',
    name:           'Waterproof Splash Suit',
    category:       'kids',
    subcategory:    'Toys',
    price:          22.08,
    originalPrice:  52.56,
    discount:       58,
    rating:         5.0,
    reviews:        20492,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "boys", "suit", "girls"]
  },
  {
    id:             'ali-kids-030',
    name:           'Gingham Smock Dress',
    category:       'kids',
    subcategory:    'Footwear',
    price:          21.46,
    originalPrice:  27.16,
    discount:       21,
    rating:         4.4,
    reviews:        4353,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "boys", "dress", "girls"]
  },
  {
    id:             'ali-kids-031',
    name:           'Denim Shorts — Distressed',
    category:       'kids',
    subcategory:    'Girls',
    price:          27.74,
    originalPrice:  48.67,
    discount:       43,
    rating:         4.3,
    reviews:        570,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "shorts", "boys", "girls"]
  },
  {
    id:             'ali-kids-032',
    name:           'Pom-Pom Hat & Scarf Set',
    category:       'kids',
    subcategory:    'Boys',
    price:          25.76,
    originalPrice:  32.2,
    discount:       20,
    rating:         4.7,
    reviews:        14182,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-033',
    name:           'Quilted Vest — Pink',
    category:       'kids',
    subcategory:    'Baby',
    price:          41.2,
    originalPrice:  76.3,
    discount:       46,
    rating:         4.8,
    reviews:        2985,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "vest", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-034',
    name:           'Floral Print Skort',
    category:       'kids',
    subcategory:    'School Wear',
    price:          58.87,
    originalPrice:  115.44,
    discount:       49,
    rating:         4.9,
    reviews:        15780,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "boys", "skort", "girls"]
  },
  {
    id:             'ali-kids-035',
    name:           'Stripe Rib Knit Jumper',
    category:       'kids',
    subcategory:    'Toys',
    price:          80.27,
    originalPrice:  113.05,
    discount:       29,
    rating:         4.9,
    reviews:        7404,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "boys", "jumper", "girls"]
  },
  {
    id:             'ali-kids-036',
    name:           'Cosy Teddy Fleece Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          41.14,
    originalPrice:  55.6,
    discount:       26,
    rating:         4.7,
    reviews:        13966,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-037',
    name:           'Dinosaur Hooded Towel Robe',
    category:       'kids',
    subcategory:    'Girls',
    price:          41.55,
    originalPrice:  94.44,
    discount:       56,
    rating:         4.9,
    reviews:        23326,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "robe", "boys", "girls"]
  },
  {
    id:             'ali-kids-038',
    name:           'Sequin Mermaid Dress',
    category:       'kids',
    subcategory:    'Boys',
    price:          13.62,
    originalPrice:  26.19,
    discount:       48,
    rating:         4.4,
    reviews:        4961,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ali-kids-039',
    name:           'Sports Jogger Set',
    category:       'kids',
    subcategory:    'Baby',
    price:          84.06,
    originalPrice:  107.77,
    discount:       22,
    rating:         4.1,
    reviews:        8785,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "set", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-040',
    name:           'Bunny Embroidery Blouse',
    category:       'kids',
    subcategory:    'School Wear',
    price:          37.68,
    originalPrice:  47.1,
    discount:       20,
    rating:         4.3,
    reviews:        15208,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "blouse", "boys", "girls"]
  },
  {
    id:             'ali-kids-041',
    name:           'Tie-Dye Shorts Set',
    category:       'kids',
    subcategory:    'Toys',
    price:          54.34,
    originalPrice:  108.68,
    discount:       50,
    rating:         4.8,
    reviews:        12521,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-042',
    name:           'Monster Truck Tee',
    category:       'kids',
    subcategory:    'Footwear',
    price:          40.87,
    originalPrice:  58.38,
    discount:       30,
    rating:         4.9,
    reviews:        15975,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "boys", "tee", "girls"]
  },
  {
    id:             'ali-kids-043',
    name:           'Floral Wrap Dress — Baby',
    category:       'kids',
    subcategory:    'Girls',
    price:          28.58,
    originalPrice:  51.97,
    discount:       45,
    rating:         4.7,
    reviews:        9797,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ali-kids-044',
    name:           'Patchwork Denim Jacket',
    category:       'kids',
    subcategory:    'Boys',
    price:          30.96,
    originalPrice:  56.3,
    discount:       45,
    rating:         4.6,
    reviews:        15241,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["jacket", "children", "kids", "boys", "girls"]
  },
  {
    id:             'ali-kids-045',
    name:           'Fruit Print Swimsuit',
    category:       'kids',
    subcategory:    'Baby',
    price:          18.19,
    originalPrice:  28.88,
    discount:       37,
    rating:         5.0,
    reviews:        24559,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "swimsuit", "boys", "baby", "girls"]
  },
  {
    id:             'ali-kids-046',
    name:           'Corduroy Dungarees — Rust',
    category:       'kids',
    subcategory:    'School Wear',
    price:          53.61,
    originalPrice:  99.28,
    discount:       46,
    rating:         4.1,
    reviews:        4535,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "school_wear", "dungarees", "boys", "girls"]
  },
  {
    id:             'ali-kids-047',
    name:           'Glitter Tulle Skirt',
    category:       'kids',
    subcategory:    'Toys',
    price:          47.42,
    originalPrice:  68.73,
    discount:       31,
    rating:         4.7,
    reviews:        2728,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "toys", "boys", "skirt", "girls"]
  },
  {
    id:             'ali-kids-048',
    name:           'Animal Print Velour Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          42.64,
    originalPrice:  112.2,
    discount:       62,
    rating:         4.2,
    reviews:        17793,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ali-kids-049',
    name:           'Organic Cotton Babygrow',
    category:       'kids',
    subcategory:    'Girls',
    price:          60.3,
    originalPrice:  80.4,
    discount:       25,
    rating:         4.6,
    reviews:        21779,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "babygrow", "kids", "boys", "girls"]
  },
  {
    id:             'ali-kids-050',
    name:           'Birthday Girl Sash Dress',
    category:       'kids',
    subcategory:    'Boys',
    price:          22.94,
    originalPrice:  55.94,
    discount:       59,
    rating:         5.0,
    reviews:        9884,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  }
);
