/* ALIEXPRESS — Shoes (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-shoe-001',
    name:           'Women\'s Platform Sneakers — White',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          36.13,
    originalPrice:  46.32,
    discount:       22,
    rating:         4.3,
    reviews:        21986,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ali-shoe-002',
    name:           'Chunky Platform Loafers — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          13.92,
    originalPrice:  29.01,
    discount:       52,
    rating:         4.5,
    reviews:        1543,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes"]
  },
  {
    id:             'ali-shoe-003',
    name:           'Men\'s Casual Sneakers — White',
    category:       'shoes',
    subcategory:    'Flats',
    price:          41.12,
    originalPrice:  54.83,
    discount:       25,
    rating:         4.3,
    reviews:        13245,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ali-shoe-004',
    name:           'Ankle Strap Block Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          16.61,
    originalPrice:  28.15,
    discount:       41,
    rating:         4.5,
    reviews:        18612,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-005',
    name:           'Bata Comfort Sandals — Women\'s',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          65.16,
    originalPrice:  97.25,
    discount:       33,
    rating:         4.6,
    reviews:        8103,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-006',
    name:           'Chelsea Boots — Tan Leather',
    category:       'shoes',
    subcategory:    'Sport',
    price:          31.65,
    originalPrice:  43.35,
    discount:       27,
    rating:         4.3,
    reviews:        19498,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-007',
    name:           'High Top Canvas Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          18.54,
    originalPrice:  50.12,
    discount:       63,
    rating:         4.1,
    reviews:        9889,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'ali-shoe-008',
    name:           'Stiletto Heeled Mules',
    category:       'shoes',
    subcategory:    'Heels',
    price:          42.75,
    originalPrice:  112.49,
    discount:       62,
    rating:         4.6,
    reviews:        2484,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'ali-shoe-009',
    name:           'Running Trainers — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          43.12,
    originalPrice:  68.45,
    discount:       37,
    rating:         4.4,
    reviews:        20372,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'ali-shoe-010',
    name:           'Strappy Kitten Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          50.45,
    originalPrice:  107.35,
    discount:       53,
    rating:         4.4,
    reviews:        3519,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-011',
    name:           'Slip-On Loafers — Suede',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          24.18,
    originalPrice:  45.63,
    discount:       47,
    rating:         4.8,
    reviews:        9039,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-012',
    name:           'Combat Boots — Lace Up',
    category:       'shoes',
    subcategory:    'Sport',
    price:          39.55,
    originalPrice:  50.06,
    discount:       21,
    rating:         4.2,
    reviews:        4935,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-013',
    name:           'Wedge Espadrilles — Nude',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          40.11,
    originalPrice:  51.42,
    discount:       22,
    rating:         4.5,
    reviews:        872,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'ali-shoe-014',
    name:           'Pointed Toe Pumps — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          34.4,
    originalPrice:  83.91,
    discount:       59,
    rating:         4.9,
    reviews:        21502,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "pumps"]
  },
  {
    id:             'ali-shoe-015',
    name:           'Kids\' Light-Up Trainers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          54.71,
    originalPrice:  85.48,
    discount:       36,
    rating:         4.0,
    reviews:        17251,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'ali-shoe-016',
    name:           'Hiking Boots — Waterproof',
    category:       'shoes',
    subcategory:    'Boots',
    price:          16.29,
    originalPrice:  25.45,
    discount:       36,
    rating:         4.7,
    reviews:        14143,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-017',
    name:           'Ballet Flats — Blush Pink',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          60.11,
    originalPrice:  109.29,
    discount:       45,
    rating:         4.6,
    reviews:        4179,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-018',
    name:           'Over-Knee Boots — Tan',
    category:       'shoes',
    subcategory:    'Sport',
    price:          44.0,
    originalPrice:  57.14,
    discount:       23,
    rating:         4.7,
    reviews:        14746,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-019',
    name:           'Knit Sock Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          18.69,
    originalPrice:  33.38,
    discount:       44,
    rating:         4.9,
    reviews:        7067,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'ali-shoe-020',
    name:           'T-Bar Mary Jane Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          29.88,
    originalPrice:  71.15,
    discount:       58,
    rating:         4.7,
    reviews:        12836,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ali-shoe-021',
    name:           'Kids\' Wellies — Polka Dot',
    category:       'shoes',
    subcategory:    'Flats',
    price:          7.8,
    originalPrice:  22.29,
    discount:       65,
    rating:         4.7,
    reviews:        19860,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "wellies", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ali-shoe-022',
    name:           'Slingback Kitten Heels',
    category:       'shoes',
    subcategory:    'Boots',
    price:          54.78,
    originalPrice:  86.95,
    discount:       37,
    rating:         4.2,
    reviews:        8955,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-023',
    name:           'Square-Toe Mules — Croc Effect',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          77.94,
    originalPrice:  106.77,
    discount:       27,
    rating:         4.7,
    reviews:        15415,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-024',
    name:           'Gladiator Sandals',
    category:       'shoes',
    subcategory:    'Sport',
    price:          38.79,
    originalPrice:  57.05,
    discount:       32,
    rating:         4.4,
    reviews:        3702,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-025',
    name:           'Ankle Boots — Stacked Heel',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          22.35,
    originalPrice:  32.39,
    discount:       31,
    rating:         5.0,
    reviews:        19149,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-026',
    name:           'Velvet Court Shoes — Emerald',
    category:       'shoes',
    subcategory:    'Heels',
    price:          42.99,
    originalPrice:  53.74,
    discount:       20,
    rating:         4.4,
    reviews:        5283,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ali-shoe-027',
    name:           'Flip Flops — Foam',
    category:       'shoes',
    subcategory:    'Flats',
    price:          77.27,
    originalPrice:  101.67,
    discount:       24,
    rating:         4.8,
    reviews:        6791,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "flops", "shoes"]
  },
  {
    id:             'ali-shoe-028',
    name:           'Lace-Up Oxford Brogues',
    category:       'shoes',
    subcategory:    'Boots',
    price:          61.22,
    originalPrice:  103.76,
    discount:       41,
    rating:         4.5,
    reviews:        9038,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "brogues", "shoes"]
  },
  {
    id:             'ali-shoe-029',
    name:           'Metallic Strappy Heels',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          50.97,
    originalPrice:  65.35,
    discount:       22,
    rating:         4.9,
    reviews:        6378,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-030',
    name:           'Platform Chelsea Boots',
    category:       'shoes',
    subcategory:    'Sport',
    price:          57.36,
    originalPrice:  110.31,
    discount:       48,
    rating:         4.0,
    reviews:        17995,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-031',
    name:           'Open-Toe Wedge Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          21.43,
    originalPrice:  57.91,
    discount:       63,
    rating:         4.9,
    reviews:        23527,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-032',
    name:           'Moccasin Slippers',
    category:       'shoes',
    subcategory:    'Heels',
    price:          66.99,
    originalPrice:  84.8,
    discount:       21,
    rating:         4.9,
    reviews:        14764,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "slippers", "footwear", "heels", "shoes"]
  },
  {
    id:             'ali-shoe-033',
    name:           'Sporty Slides — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          46.12,
    originalPrice:  70.96,
    discount:       35,
    rating:         4.6,
    reviews:        9735,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "slides", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ali-shoe-034',
    name:           'Peep-Toe Slingbacks',
    category:       'shoes',
    subcategory:    'Boots',
    price:          70.74,
    originalPrice:  96.9,
    discount:       27,
    rating:         4.2,
    reviews:        6645,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "slingbacks"]
  },
  {
    id:             'ali-shoe-035',
    name:           'Classic White Tennis Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          20.24,
    originalPrice:  29.33,
    discount:       31,
    rating:         4.1,
    reviews:        23225,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-036',
    name:           'Dad Trainer — Chunky',
    category:       'shoes',
    subcategory:    'Sport',
    price:          22.18,
    originalPrice:  35.21,
    discount:       37,
    rating:         4.4,
    reviews:        12612,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "trainer", "sport", "shoes"]
  },
  {
    id:             'ali-shoe-037',
    name:           'Espadrille Wedge Mules',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          59.79,
    originalPrice:  94.9,
    discount:       37,
    rating:         4.6,
    reviews:        1204,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'ali-shoe-038',
    name:           'Patent Ankle Strap Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          64.05,
    originalPrice:  83.18,
    discount:       23,
    rating:         4.1,
    reviews:        21813,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ali-shoe-039',
    name:           'Knee High Flat Boots',
    category:       'shoes',
    subcategory:    'Flats',
    price:          30.37,
    originalPrice:  58.4,
    discount:       48,
    rating:         4.6,
    reviews:        14106,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-040',
    name:           'Woven Mule Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          81.39,
    originalPrice:  114.63,
    discount:       29,
    rating:         4.9,
    reviews:        20061,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-041',
    name:           'Men\'s Derby Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          44.04,
    originalPrice:  57.95,
    discount:       24,
    rating:         4.9,
    reviews:        10153,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-042',
    name:           'Snow Boots — Fur Lined',
    category:       'shoes',
    subcategory:    'Sport',
    price:          47.16,
    originalPrice:  82.74,
    discount:       43,
    rating:         4.9,
    reviews:        14496,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ali-shoe-043',
    name:           'Transparent Heeled Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          64.06,
    originalPrice:  94.21,
    discount:       32,
    rating:         4.6,
    reviews:        2808,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-044',
    name:           'Slip-On Canvas Espadrilles',
    category:       'shoes',
    subcategory:    'Heels',
    price:          43.64,
    originalPrice:  77.93,
    discount:       44,
    rating:         4.3,
    reviews:        2295,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'ali-shoe-045',
    name:           'Low Top Leather Sneakers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          42.73,
    originalPrice:  76.31,
    discount:       44,
    rating:         4.3,
    reviews:        20163,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ali-shoe-046',
    name:           'Platform Flip Flop Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          28.61,
    originalPrice:  52.98,
    discount:       46,
    rating:         4.5,
    reviews:        12447,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-047',
    name:           'Ankle Boots — Pointed Toe',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          51.88,
    originalPrice:  105.88,
    discount:       51,
    rating:         4.9,
    reviews:        15727,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ali-shoe-048',
    name:           'Sporty Slides — Women\'s',
    category:       'shoes',
    subcategory:    'Sport',
    price:          34.91,
    originalPrice:  94.34,
    discount:       63,
    rating:         4.7,
    reviews:        9945,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["sneakers", "slides", "footwear", "heels", "sport", "shoes"]
  },
  {
    id:             'ali-shoe-049',
    name:           'Men\'s Boat Shoes — Tan',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          15.95,
    originalPrice:  32.56,
    discount:       51,
    rating:         4.4,
    reviews:        3468,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ali-shoe-050',
    name:           'Kids\' School Shoes — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          20.7,
    originalPrice:  36.97,
    discount:       44,
    rating:         5.0,
    reviews:        11631,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  }
);
