/* ALIEXPRESS — Toys (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-toys-001',
    name:           'STEM Building Blocks Set — 250 Pieces',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          51.55,
    originalPrice:  67.83,
    discount:       24,
    rating:         4.8,
    reviews:        8072,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ali-toys-002',
    name:           'Remote Control Car — Off-Road 4WD',
    category:       'toys',
    subcategory:    'Board Games',
    price:          16.31,
    originalPrice:  36.24,
    discount:       55,
    rating:         4.6,
    reviews:        20118,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "car", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-003',
    name:           'Diamond Painting Kit — Beginner',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          47.16,
    originalPrice:  62.05,
    discount:       24,
    rating:         5.0,
    reviews:        13091,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ali-toys-004',
    name:           'Magnetic Drawing Board',
    category:       'toys',
    subcategory:    'Educational',
    price:          76.04,
    originalPrice:  105.61,
    discount:       28,
    rating:         4.3,
    reviews:        323,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "board", "toys", "educational", "play"]
  },
  {
    id:             'ali-toys-005',
    name:           'Wooden Balance Bike — 3-6 Years',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          23.0,
    originalPrice:  62.15,
    discount:       63,
    rating:         4.7,
    reviews:        13250,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "bike"]
  },
  {
    id:             'ali-toys-006',
    name:           'Interactive Robot Toy',
    category:       'toys',
    subcategory:    'STEM',
    price:          17.3,
    originalPrice:  25.82,
    discount:       33,
    rating:         4.8,
    reviews:        11324,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "toy", "stem"]
  },
  {
    id:             'ali-toys-007',
    name:           'Art & Craft Mega Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          46.93,
    originalPrice:  97.78,
    discount:       52,
    rating:         4.5,
    reviews:        5629,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ali-toys-008',
    name:           'Foam Nerf-Style Blaster',
    category:       'toys',
    subcategory:    'Board Games',
    price:          9.44,
    originalPrice:  24.21,
    discount:       61,
    rating:         4.9,
    reviews:        6417,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "blaster", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-009',
    name:           'Mini Drone — Beginner Friendly',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          65.98,
    originalPrice:  108.16,
    discount:       39,
    rating:         4.4,
    reviews:        2206,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["drone", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ali-toys-010',
    name:           'Kids\' Walkie Talkies — 1km Range',
    category:       'toys',
    subcategory:    'Educational',
    price:          49.59,
    originalPrice:  105.51,
    discount:       53,
    rating:         4.6,
    reviews:        23131,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["talkies", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ali-toys-011',
    name:           'Dollhouse — 3-Storey Wooden',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          37.55,
    originalPrice:  49.41,
    discount:       24,
    rating:         4.1,
    reviews:        15748,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["dollhouse", "kids", "games", "toys", "outdoor", "play"]
  },
  {
    id:             'ali-toys-012',
    name:           'Train Set — 130 Pieces',
    category:       'toys',
    subcategory:    'STEM',
    price:          53.47,
    originalPrice:  109.13,
    discount:       51,
    rating:         4.1,
    reviews:        10997,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ali-toys-013',
    name:           'Slime Making Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          57.18,
    originalPrice:  96.91,
    discount:       41,
    rating:         4.6,
    reviews:        20604,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ali-toys-014',
    name:           'Sensory Sand Tray',
    category:       'toys',
    subcategory:    'Board Games',
    price:          18.62,
    originalPrice:  44.33,
    discount:       58,
    rating:         4.7,
    reviews:        18045,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "tray", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-015',
    name:           'Bubble Machine — Automatic',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          17.2,
    originalPrice:  26.87,
    discount:       36,
    rating:         4.9,
    reviews:        20128,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "puzzles", "play", "machine"]
  },
  {
    id:             'ali-toys-016',
    name:           'Giant Floor Puzzle — 100 Pieces',
    category:       'toys',
    subcategory:    'Educational',
    price:          37.73,
    originalPrice:  85.74,
    discount:       56,
    rating:         5.0,
    reviews:        12534,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "educational", "play", "puzzle"]
  },
  {
    id:             'ali-toys-017',
    name:           'Pop It Fidget Toy Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          25.07,
    originalPrice:  31.34,
    discount:       20,
    rating:         4.6,
    reviews:        23955,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ali-toys-018',
    name:           'Water Balloons — Self-Sealing 100pk',
    category:       'toys',
    subcategory:    'STEM',
    price:          10.91,
    originalPrice:  18.81,
    discount:       42,
    rating:         4.5,
    reviews:        12912,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "balloons", "toys", "play", "stem"]
  },
  {
    id:             'ali-toys-019',
    name:           'Kinetic Sand Set — 3kg',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          50.42,
    originalPrice:  102.89,
    discount:       51,
    rating:         4.3,
    reviews:        24624,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ali-toys-020',
    name:           'Outdoor Trampoline — 10ft',
    category:       'toys',
    subcategory:    'Board Games',
    price:          65.36,
    originalPrice:  105.42,
    discount:       38,
    rating:         4.7,
    reviews:        7018,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "trampoline", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-021',
    name:           'Foam Ball Pit + 200 Balls',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          22.26,
    originalPrice:  55.64,
    discount:       60,
    rating:         4.4,
    reviews:        17130,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "balls", "puzzles", "play"]
  },
  {
    id:             'ali-toys-022',
    name:           'Science Experiment Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          55.05,
    originalPrice:  94.92,
    discount:       42,
    rating:         4.4,
    reviews:        17534,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ali-toys-023',
    name:           'Perler Bead Set — 5000 Pieces',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          67.26,
    originalPrice:  110.26,
    discount:       39,
    rating:         4.0,
    reviews:        8960,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ali-toys-024',
    name:           'Sticker Activity Book',
    category:       'toys',
    subcategory:    'STEM',
    price:          33.33,
    originalPrice:  59.51,
    discount:       44,
    rating:         4.5,
    reviews:        8803,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "book", "games", "toys", "play", "stem"]
  },
  {
    id:             'ali-toys-025',
    name:           'Action Figure Set — 12 Characters',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          24.5,
    originalPrice:  59.76,
    discount:       59,
    rating:         4.8,
    reviews:        17610,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ali-toys-026',
    name:           'Play Kitchen Set',
    category:       'toys',
    subcategory:    'Board Games',
    price:          32.77,
    originalPrice:  40.96,
    discount:       20,
    rating:         4.1,
    reviews:        10433,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "board_games"]
  },
  {
    id:             'ali-toys-027',
    name:           'Magnetic Tiles Set — 60 Pieces',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          17.14,
    originalPrice:  26.78,
    discount:       36,
    rating:         4.9,
    reviews:        3682,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "puzzles", "play", "set"]
  },
  {
    id:             'ali-toys-028',
    name:           'Soft Play Crawl Tunnel',
    category:       'toys',
    subcategory:    'Educational',
    price:          42.95,
    originalPrice:  85.91,
    discount:       50,
    rating:         4.9,
    reviews:        22833,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "educational", "play", "tunnel"]
  },
  {
    id:             'ali-toys-029',
    name:           'Outdoor Swing — Timber Frame',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          15.11,
    originalPrice:  26.05,
    discount:       42,
    rating:         4.2,
    reviews:        13554,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "swing"]
  },
  {
    id:             'ali-toys-030',
    name:           'Bath Toy Set — Squirt Animals',
    category:       'toys',
    subcategory:    'STEM',
    price:          19.31,
    originalPrice:  36.43,
    discount:       47,
    rating:         4.7,
    reviews:        15370,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ali-toys-031',
    name:           'Wooden Stacking Tower',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          13.95,
    originalPrice:  39.85,
    discount:       65,
    rating:         4.5,
    reviews:        6028,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["tower", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ali-toys-032',
    name:           'Finger Painting Kit — Washable',
    category:       'toys',
    subcategory:    'Board Games',
    price:          23.37,
    originalPrice:  61.49,
    discount:       62,
    rating:         4.9,
    reviews:        17495,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-033',
    name:           'Stuffed Animal Bundle — 5 Pack',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          12.54,
    originalPrice:  20.56,
    discount:       39,
    rating:         4.4,
    reviews:        10099,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ali-toys-034',
    name:           'Mini Basketball Hoop — Indoor',
    category:       'toys',
    subcategory:    'Educational',
    price:          62.22,
    originalPrice:  87.64,
    discount:       29,
    rating:         4.5,
    reviews:        16398,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "educational", "hoop", "play"]
  },
  {
    id:             'ali-toys-035',
    name:           'Kids\' Karaoke Machine',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          51.58,
    originalPrice:  64.47,
    discount:       20,
    rating:         4.0,
    reviews:        3033,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "machine"]
  },
  {
    id:             'ali-toys-036',
    name:           'Roller Skates — Adjustable',
    category:       'toys',
    subcategory:    'STEM',
    price:          31.47,
    originalPrice:  76.76,
    discount:       59,
    rating:         4.6,
    reviews:        19132,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skates", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'ali-toys-037',
    name:           'Toy Cash Register',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          44.45,
    originalPrice:  105.84,
    discount:       58,
    rating:         4.3,
    reviews:        11346,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "action_figures", "register"]
  },
  {
    id:             'ali-toys-038',
    name:           'Kids\' Binoculars',
    category:       'toys',
    subcategory:    'Board Games',
    price:          62.39,
    originalPrice:  115.54,
    discount:       46,
    rating:         4.4,
    reviews:        9849,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["binoculars", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-039',
    name:           'Sand Water Table',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          27.61,
    originalPrice:  76.69,
    discount:       64,
    rating:         4.5,
    reviews:        19408,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "table", "puzzles", "play"]
  },
  {
    id:             'ali-toys-040',
    name:           'Lacing & Threading Set',
    category:       'toys',
    subcategory:    'Educational',
    price:          11.46,
    originalPrice:  30.17,
    discount:       62,
    rating:         4.2,
    reviews:        24147,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "educational", "play", "set"]
  },
  {
    id:             'ali-toys-041',
    name:           'Giant Jenga — Outdoor',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          19.28,
    originalPrice:  29.21,
    discount:       34,
    rating:         4.5,
    reviews:        10499,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "jenga"]
  },
  {
    id:             'ali-toys-042',
    name:           'Playdough 12-Colour Set',
    category:       'toys',
    subcategory:    'STEM',
    price:          62.4,
    originalPrice:  100.64,
    discount:       38,
    rating:         4.5,
    reviews:        15655,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'ali-toys-043',
    name:           'Solar System Model Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          12.5,
    originalPrice:  16.89,
    discount:       26,
    rating:         4.9,
    reviews:        9185,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'ali-toys-044',
    name:           'Coding Robot for Kids',
    category:       'toys',
    subcategory:    'Board Games',
    price:          36.79,
    originalPrice:  60.31,
    discount:       39,
    rating:         4.3,
    reviews:        12202,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'ali-toys-045',
    name:           'Fairy Garden Kit',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          23.1,
    originalPrice:  43.59,
    discount:       47,
    rating:         4.9,
    reviews:        13025,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'ali-toys-046',
    name:           'Space Rover Build Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          9.44,
    originalPrice:  26.22,
    discount:       64,
    rating:         4.8,
    reviews:        1363,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'ali-toys-047',
    name:           'Kids\' Archery Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          12.82,
    originalPrice:  17.32,
    discount:       26,
    rating:         4.1,
    reviews:        2446,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'ali-toys-048',
    name:           'Board Game Bundle — 5 Games',
    category:       'toys',
    subcategory:    'STEM',
    price:          76.03,
    originalPrice:  115.19,
    discount:       34,
    rating:         4.6,
    reviews:        10748,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["bundle", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'ali-toys-049',
    name:           'Glow in Dark Stars Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          69.96,
    originalPrice:  104.42,
    discount:       33,
    rating:         4.0,
    reviews:        3347,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'ali-toys-050',
    name:           'Rocket Launcher + Foam Rockets',
    category:       'toys',
    subcategory:    'Board Games',
    price:          52.62,
    originalPrice:  114.4,
    discount:       54,
    rating:         4.3,
    reviews:        14411,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["kids", "games", "toys", "play", "board_games", "rockets"]
  }
);
