/* ALIEXPRESS — Women (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-aliexpress.js index file
*/

window.AliExpressProducts = window.AliExpressProducts || [];

window.AliExpressProducts.push(
  {
    id:             'ali-wome-001',
    name:           'Floral Boho Maxi Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          21.36,
    originalPrice:  36.2,
    discount:       41,
    rating:         4.3,
    reviews:        22482,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000001.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-002',
    name:           'Silk Satin Slip Dress — Midi',
    category:       'women',
    subcategory:    'Tops',
    price:          25.52,
    originalPrice:  32.3,
    discount:       21,
    rating:         4.3,
    reviews:        7071,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000002.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-003',
    name:           'Linen Wide-Leg Trousers',
    category:       'women',
    subcategory:    'Jeans',
    price:          42.15,
    originalPrice:  117.08,
    discount:       64,
    rating:         4.6,
    reviews:        17556,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000003.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "trousers", "women"]
  },
  {
    id:             'ali-wome-004',
    name:           'Ruched Bodycon Mini Dress',
    category:       'women',
    subcategory:    'Skirts',
    price:          40.8,
    originalPrice:  90.67,
    discount:       55,
    rating:         4.8,
    reviews:        15280,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000004.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-005',
    name:           'Cashmere V-Neck Sweater',
    category:       'women',
    subcategory:    'Activewear',
    price:          62.58,
    originalPrice:  86.91,
    discount:       28,
    rating:         4.8,
    reviews:        8900,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000005.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "sweater"]
  },
  {
    id:             'ali-wome-006',
    name:           'Oversized Blazer — Camel',
    category:       'women',
    subcategory:    'Swimwear',
    price:          35.93,
    originalPrice:  94.55,
    discount:       62,
    rating:         4.8,
    reviews:        878,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000006.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "swimwear", "women", "blazer"]
  },
  {
    id:             'ali-wome-007',
    name:           'High-Waist Flare Jeans',
    category:       'women',
    subcategory:    'Outerwear',
    price:          54.53,
    originalPrice:  118.54,
    discount:       54,
    rating:         4.1,
    reviews:        23244,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000007.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "outerwear"]
  },
  {
    id:             'ali-wome-008',
    name:           'Velvet Wrap Blouse',
    category:       'women',
    subcategory:    'Dresses',
    price:          10.1,
    originalPrice:  23.48,
    discount:       57,
    rating:         5.0,
    reviews:        24608,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000008.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "blouse", "women"]
  },
  {
    id:             'ali-wome-009',
    name:           'Tie-Dye Co-ord Set',
    category:       'women',
    subcategory:    'Tops',
    price:          66.73,
    originalPrice:  83.41,
    discount:       20,
    rating:         4.7,
    reviews:        20613,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000009.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "set", "women"]
  },
  {
    id:             'ali-wome-010',
    name:           'Off-Shoulder Summer Top',
    category:       'women',
    subcategory:    'Jeans',
    price:          72.97,
    originalPrice:  98.61,
    discount:       26,
    rating:         4.5,
    reviews:        19058,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000010.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "top"]
  },
  {
    id:             'ali-wome-011',
    name:           'Knit Ribbed Cardigan',
    category:       'women',
    subcategory:    'Skirts',
    price:          6.78,
    originalPrice:  14.43,
    discount:       53,
    rating:         4.1,
    reviews:        6835,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000011.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "cardigan", "clothing", "style", "women"]
  },
  {
    id:             'ali-wome-012',
    name:           'Pleated Midi Skirt — Navy',
    category:       'women',
    subcategory:    'Activewear',
    price:          22.47,
    originalPrice:  37.45,
    discount:       40,
    rating:         4.3,
    reviews:        22423,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000012.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "skirt"]
  },
  {
    id:             'ali-wome-013',
    name:           'Corset Bralette Set',
    category:       'women',
    subcategory:    'Swimwear',
    price:          21.6,
    originalPrice:  40.76,
    discount:       47,
    rating:         5.0,
    reviews:        5867,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000013.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "swimwear", "set", "women"]
  },
  {
    id:             'ali-wome-014',
    name:           'Satin Pyjama Set',
    category:       'women',
    subcategory:    'Outerwear',
    price:          37.32,
    originalPrice:  77.75,
    discount:       52,
    rating:         4.8,
    reviews:        7224,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000014.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "set", "women", "outerwear"]
  },
  {
    id:             'ali-wome-015',
    name:           'Embroidered Kaftan Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          44.27,
    originalPrice:  65.11,
    discount:       32,
    rating:         4.2,
    reviews:        21784,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000015.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-016',
    name:           'Tailored Wide-Leg Trousers',
    category:       'women',
    subcategory:    'Tops',
    price:          25.36,
    originalPrice:  56.36,
    discount:       55,
    rating:         4.4,
    reviews:        24055,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000016.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "trousers", "women"]
  },
  {
    id:             'ali-wome-017',
    name:           'Printed Chiffon Blouse',
    category:       'women',
    subcategory:    'Jeans',
    price:          24.05,
    originalPrice:  37.0,
    discount:       35,
    rating:         4.5,
    reviews:        6945,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000017.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "blouse", "women"]
  },
  {
    id:             'ali-wome-018',
    name:           'Denim Jacket — Vintage Wash',
    category:       'women',
    subcategory:    'Skirts',
    price:          29.04,
    originalPrice:  42.08,
    discount:       31,
    rating:         4.1,
    reviews:        14916,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000018.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "jacket", "fashion", "clothing", "style", "women"]
  },
  {
    id:             'ali-wome-019',
    name:           'Smocked Sundress',
    category:       'women',
    subcategory:    'Activewear',
    price:          83.34,
    originalPrice:  106.84,
    discount:       22,
    rating:         4.6,
    reviews:        24008,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000019.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "sundress", "style", "activewear", "women"]
  },
  {
    id:             'ali-wome-020',
    name:           'Cropped Leather Jacket',
    category:       'women',
    subcategory:    'Swimwear',
    price:          41.5,
    originalPrice:  96.52,
    discount:       57,
    rating:         4.2,
    reviews:        21742,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000020.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["jacket", "fashion", "clothing", "style", "swimwear", "women"]
  },
  {
    id:             'ali-wome-021',
    name:           'Asymmetric Hem Skirt',
    category:       'women',
    subcategory:    'Outerwear',
    price:          12.13,
    originalPrice:  18.11,
    discount:       33,
    rating:         4.4,
    reviews:        11715,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000021.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "skirt"]
  },
  {
    id:             'ali-wome-022',
    name:           'Puff-Sleeve Mini Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          18.98,
    originalPrice:  38.73,
    discount:       51,
    rating:         4.5,
    reviews:        3953,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000022.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-023',
    name:           'Striped Co-ord Shorts Set',
    category:       'women',
    subcategory:    'Tops',
    price:          46.55,
    originalPrice:  93.11,
    discount:       50,
    rating:         4.3,
    reviews:        23306,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000023.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "set", "women"]
  },
  {
    id:             'ali-wome-024',
    name:           'Halter Neck Maxi Dress',
    category:       'women',
    subcategory:    'Jeans',
    price:          28.31,
    originalPrice:  41.63,
    discount:       32,
    rating:         4.5,
    reviews:        16373,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000024.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-025',
    name:           'Floral Print Wrap Dress',
    category:       'women',
    subcategory:    'Skirts',
    price:          27.88,
    originalPrice:  79.66,
    discount:       65,
    rating:         4.4,
    reviews:        24743,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000025.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-026',
    name:           'Sequin Evening Gown',
    category:       'women',
    subcategory:    'Activewear',
    price:          30.27,
    originalPrice:  54.06,
    discount:       44,
    rating:         4.4,
    reviews:        14072,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000026.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "gown", "activewear", "women"]
  },
  {
    id:             'ali-wome-027',
    name:           'Sheer Organza Blouse',
    category:       'women',
    subcategory:    'Swimwear',
    price:          41.65,
    originalPrice:  52.06,
    discount:       20,
    rating:         4.6,
    reviews:        1466,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000027.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "blouse", "swimwear", "women"]
  },
  {
    id:             'ali-wome-028',
    name:           'Rib-Knit Crop Top',
    category:       'women',
    subcategory:    'Outerwear',
    price:          73.95,
    originalPrice:  112.05,
    discount:       34,
    rating:         4.4,
    reviews:        5562,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000028.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "women", "top", "outerwear"]
  },
  {
    id:             'ali-wome-029',
    name:           'Belted Trench Coat',
    category:       'women',
    subcategory:    'Dresses',
    price:          77.89,
    originalPrice:  103.86,
    discount:       25,
    rating:         4.5,
    reviews:        1856,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000029.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "coat", "women"]
  },
  {
    id:             'ali-wome-030',
    name:           'Tiered Ruffled Midi Dress',
    category:       'women',
    subcategory:    'Tops',
    price:          36.99,
    originalPrice:  90.23,
    discount:       59,
    rating:         4.6,
    reviews:        16545,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000030.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-031',
    name:           'Lace Trim Slip Skirt',
    category:       'women',
    subcategory:    'Jeans',
    price:          45.85,
    originalPrice:  69.47,
    discount:       34,
    rating:         4.5,
    reviews:        6726,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000031.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "skirt"]
  },
  {
    id:             'ali-wome-032',
    name:           'Double-Breasted Blazer',
    category:       'women',
    subcategory:    'Skirts',
    price:          14.12,
    originalPrice:  19.61,
    discount:       28,
    rating:         4.3,
    reviews:        8127,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000032.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "blazer"]
  },
  {
    id:             'ali-wome-033',
    name:           'Broderie Anglaise Top',
    category:       'women',
    subcategory:    'Activewear',
    price:          40.13,
    originalPrice:  81.89,
    discount:       51,
    rating:         4.2,
    reviews:        10091,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000033.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "top"]
  },
  {
    id:             'ali-wome-034',
    name:           'Velvet Jumpsuit — Burgundy',
    category:       'women',
    subcategory:    'Swimwear',
    price:          33.04,
    originalPrice:  75.08,
    discount:       56,
    rating:         4.2,
    reviews:        12712,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000034.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jumpsuit", "clothing", "style", "swimwear", "women"]
  },
  {
    id:             'ali-wome-035',
    name:           'Seersucker Shorts Set',
    category:       'women',
    subcategory:    'Outerwear',
    price:          43.81,
    originalPrice:  95.23,
    discount:       54,
    rating:         4.6,
    reviews:        17143,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000035.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "set", "women", "outerwear"]
  },
  {
    id:             'ali-wome-036',
    name:           'Crinkle Cotton Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          5.31,
    originalPrice:  12.34,
    discount:       57,
    rating:         4.6,
    reviews:        5262,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000036.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-037',
    name:           'Cut-Out Bodycon Dress',
    category:       'women',
    subcategory:    'Tops',
    price:          12.17,
    originalPrice:  25.9,
    discount:       53,
    rating:         4.4,
    reviews:        1828,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000037.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "tops", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-038',
    name:           'Paperbag Waist Trousers',
    category:       'women',
    subcategory:    'Jeans',
    price:          7.04,
    originalPrice:  12.13,
    discount:       42,
    rating:         4.4,
    reviews:        21399,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000038.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "trousers", "women"]
  },
  {
    id:             'ali-wome-039',
    name:           'Floral Kimono Robe',
    category:       'women',
    subcategory:    'Skirts',
    price:          68.15,
    originalPrice:  106.48,
    discount:       36,
    rating:         4.4,
    reviews:        12234,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000039.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "robe", "clothing", "style", "women"]
  },
  {
    id:             'ali-wome-040',
    name:           'Suede Fringe Jacket',
    category:       'women',
    subcategory:    'Activewear',
    price:          28.93,
    originalPrice:  82.66,
    discount:       65,
    rating:         5.0,
    reviews:        3803,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000040.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["jacket", "fashion", "clothing", "style", "activewear", "women"]
  },
  {
    id:             'ali-wome-041',
    name:           'Peplum Blouse — Ivory',
    category:       'women',
    subcategory:    'Swimwear',
    price:          45.15,
    originalPrice:  60.2,
    discount:       25,
    rating:         4.2,
    reviews:        8097,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000041.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "blouse", "swimwear", "women"]
  },
  {
    id:             'ali-wome-042',
    name:           'Plisse Pleated Maxi Dress',
    category:       'women',
    subcategory:    'Outerwear',
    price:          12.37,
    originalPrice:  18.19,
    discount:       32,
    rating:         4.3,
    reviews:        14323,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000042.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "dress"]
  },
  {
    id:             'ali-wome-043',
    name:           'Colour-Block Sweater',
    category:       'women',
    subcategory:    'Dresses',
    price:          15.21,
    originalPrice:  35.38,
    discount:       57,
    rating:         4.0,
    reviews:        8922,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000043.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "sweater"]
  },
  {
    id:             'ali-wome-044',
    name:           'Shacket — Oversized Flannel',
    category:       'women',
    subcategory:    'Tops',
    price:          30.86,
    originalPrice:  59.34,
    discount:       48,
    rating:         4.4,
    reviews:        17649,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1485462537746-965f33f47f13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000044.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "shacket", "clothing", "tops", "style", "women"]
  },
  {
    id:             'ali-wome-045',
    name:           'Ruffle Hem Cami Dress',
    category:       'women',
    subcategory:    'Jeans',
    price:          11.71,
    originalPrice:  23.41,
    discount:       50,
    rating:         4.4,
    reviews:        16140,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000045.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "jeans", "clothing", "style", "women", "dress"]
  },
  {
    id:             'ali-wome-046',
    name:           'Button-Front Midi Skirt',
    category:       'women',
    subcategory:    'Skirts',
    price:          24.17,
    originalPrice:  33.11,
    discount:       27,
    rating:         4.9,
    reviews:        1238,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1532781914607-2031eca2f00d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000046.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["skirts", "fashion", "clothing", "style", "women", "skirt"]
  },
  {
    id:             'ali-wome-047',
    name:           'Lurex Knit Dress',
    category:       'women',
    subcategory:    'Activewear',
    price:          12.41,
    originalPrice:  24.82,
    discount:       50,
    rating:         4.8,
    reviews:        9690,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000047.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "activewear", "women", "dress"]
  },
  {
    id:             'ali-wome-048',
    name:           'Broderie Lace Midi Dress',
    category:       'women',
    subcategory:    'Swimwear',
    price:          15.63,
    originalPrice:  27.42,
    discount:       43,
    rating:         4.8,
    reviews:        15262,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000048.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "swimwear", "women", "dress"]
  },
  {
    id:             'ali-wome-049',
    name:           'Polka Dot Wrap Dress',
    category:       'women',
    subcategory:    'Outerwear',
    price:          11.62,
    originalPrice:  23.71,
    discount:       51,
    rating:         5.0,
    reviews:        19739,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000049.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "clothing", "style", "women", "outerwear", "dress"]
  },
  {
    id:             'ali-wome-050',
    name:           'Power Shoulder Blazer Dress',
    category:       'women',
    subcategory:    'Dresses',
    price:          10.87,
    originalPrice:  23.62,
    discount:       54,
    rating:         4.9,
    reviews:        6291,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.aliexpress.com/item/1005000050.html?aff_platform=meowmeow_site',
    marketplace:    'AliExpress',
    marketplaceIcon: 'fas fa-globe',
    tags:           ["fashion", "dresses", "clothing", "style", "women", "dress"]
  }
);
