/* DARAZ — Bags (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-bags-001',
    name:           'Luxury PU Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          46.01,
    originalPrice:  90.22,
    discount:       49,
    rating:         4.6,
    reviews:        8805,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-002',
    name:           'Canvas Tote Bag — Aesthetic Prints',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          26.65,
    originalPrice:  76.14,
    discount:       65,
    rating:         4.6,
    reviews:        24956,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-003',
    name:           'Laptop Backpack — Anti-Theft 15.6"',
    category:       'bags',
    subcategory:    'Totes',
    price:          44.98,
    originalPrice:  84.86,
    discount:       47,
    rating:         4.1,
    reviews:        18945,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "backpack", "totes", "purse"]
  },
  {
    id:             'dar-bags-004',
    name:           'Mini Crossbody Bag — Quilted Chain',
    category:       'bags',
    subcategory:    'Wallets',
    price:          15.54,
    originalPrice:  31.08,
    discount:       50,
    rating:         4.6,
    reviews:        19943,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-005',
    name:           'Rattan Summer Handbag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          38.64,
    originalPrice:  71.56,
    discount:       46,
    rating:         4.4,
    reviews:        24847,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-006',
    name:           'Clear Stadium Bag — PVC',
    category:       'bags',
    subcategory:    'Handbags',
    price:          8.55,
    originalPrice:  23.75,
    discount:       64,
    rating:         4.7,
    reviews:        18692,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-007',
    name:           'Large Slouchy Hobo Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          52.01,
    originalPrice:  65.84,
    discount:       21,
    rating:         4.8,
    reviews:        6598,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-008',
    name:           'Croc-Effect Tote Bag — Beige',
    category:       'bags',
    subcategory:    'Totes',
    price:          10.12,
    originalPrice:  15.33,
    discount:       34,
    rating:         4.9,
    reviews:        22387,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-009',
    name:           'Woven Bucket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          21.75,
    originalPrice:  29.8,
    discount:       27,
    rating:         4.1,
    reviews:        4199,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-010',
    name:           'Belt Bag — Nylon',
    category:       'bags',
    subcategory:    'Clutches',
    price:          31.94,
    originalPrice:  72.6,
    discount:       56,
    rating:         4.8,
    reviews:        20923,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-011',
    name:           'Flap Crossbody Bag — Brown',
    category:       'bags',
    subcategory:    'Handbags',
    price:          29.65,
    originalPrice:  42.36,
    discount:       30,
    rating:         4.3,
    reviews:        16280,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-012',
    name:           'Structured Top Handle Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          34.95,
    originalPrice:  45.39,
    discount:       23,
    rating:         4.1,
    reviews:        5943,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-013',
    name:           'Travel Duffel Bag — Weekender',
    category:       'bags',
    subcategory:    'Totes',
    price:          68.36,
    originalPrice:  97.65,
    discount:       30,
    rating:         4.3,
    reviews:        16871,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-014',
    name:           'Waist Fanny Pack — Black',
    category:       'bags',
    subcategory:    'Wallets',
    price:          21.3,
    originalPrice:  45.32,
    discount:       53,
    rating:         4.8,
    reviews:        22103,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "wallets", "bags", "purse", "pack"]
  },
  {
    id:             'dar-bags-015',
    name:           'Knitted Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          9.0,
    originalPrice:  13.64,
    discount:       34,
    rating:         4.2,
    reviews:        18953,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-016',
    name:           'Mini Camera Bag — Velvet',
    category:       'bags',
    subcategory:    'Handbags',
    price:          56.66,
    originalPrice:  106.9,
    discount:       47,
    rating:         4.2,
    reviews:        7634,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-017',
    name:           'Oversized Shopper Tote',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          39.3,
    originalPrice:  95.86,
    discount:       59,
    rating:         4.2,
    reviews:        7058,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-018',
    name:           'Baguette Bag — Satin',
    category:       'bags',
    subcategory:    'Totes',
    price:          25.13,
    originalPrice:  44.88,
    discount:       44,
    rating:         4.2,
    reviews:        18533,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-019',
    name:           'Backpack Purse — Vegan Leather',
    category:       'bags',
    subcategory:    'Wallets',
    price:          52.33,
    originalPrice:  88.7,
    discount:       41,
    rating:         4.2,
    reviews:        11046,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-020',
    name:           'Transparent Beach Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          33.88,
    originalPrice:  67.75,
    discount:       50,
    rating:         4.9,
    reviews:        15610,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-021',
    name:           'Bamboo Handle Tote',
    category:       'bags',
    subcategory:    'Handbags',
    price:          27.0,
    originalPrice:  55.11,
    discount:       51,
    rating:         4.1,
    reviews:        18308,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-022',
    name:           'Convertible Backpack Handbag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          27.38,
    originalPrice:  41.48,
    discount:       34,
    rating:         4.5,
    reviews:        20259,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-023',
    name:           'Envelope Clutch Bag — Gold',
    category:       'bags',
    subcategory:    'Totes',
    price:          63.58,
    originalPrice:  94.9,
    discount:       33,
    rating:         4.8,
    reviews:        11261,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-024',
    name:           'Micro Mini Bag — Chain Strap',
    category:       'bags',
    subcategory:    'Wallets',
    price:          33.95,
    originalPrice:  55.66,
    discount:       39,
    rating:         4.2,
    reviews:        23611,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-025',
    name:           'Studded Leather Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          46.89,
    originalPrice:  83.73,
    discount:       44,
    rating:         4.3,
    reviews:        3464,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "crossbody", "clutches", "purse"]
  },
  {
    id:             'dar-bags-026',
    name:           'Geometric Structured Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          66.14,
    originalPrice:  104.99,
    discount:       37,
    rating:         4.7,
    reviews:        9124,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-027',
    name:           'Drawstring Bucket Bag — Cord',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          62.48,
    originalPrice:  94.67,
    discount:       34,
    rating:         5.0,
    reviews:        18676,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-028',
    name:           'Vintage Flap Shoulder Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          87.55,
    originalPrice:  118.31,
    discount:       26,
    rating:         4.5,
    reviews:        10241,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-029',
    name:           'Wicker Market Basket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          50.89,
    originalPrice:  68.77,
    discount:       26,
    rating:         4.5,
    reviews:        13012,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-030',
    name:           'Circle Bag — Wooden Handle',
    category:       'bags',
    subcategory:    'Clutches',
    price:          60.46,
    originalPrice:  106.07,
    discount:       43,
    rating:         4.4,
    reviews:        22191,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-031',
    name:           'Satin Evening Clutch — Pearl',
    category:       'bags',
    subcategory:    'Handbags',
    price:          61.08,
    originalPrice:  101.8,
    discount:       40,
    rating:         4.1,
    reviews:        21094,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "handbags", "bags", "clutch", "purse"]
  },
  {
    id:             'dar-bags-032',
    name:           'Doctor Bag — Brown Leather',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          51.88,
    originalPrice:  75.19,
    discount:       31,
    rating:         4.1,
    reviews:        511,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-033',
    name:           'Graffiti Print Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          12.52,
    originalPrice:  29.82,
    discount:       58,
    rating:         4.2,
    reviews:        13263,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-034',
    name:           'Chain Handle Shoulder Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          23.41,
    originalPrice:  65.03,
    discount:       64,
    rating:         4.6,
    reviews:        14089,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-035',
    name:           'PVC Jelly Bag — Transparent',
    category:       'bags',
    subcategory:    'Clutches',
    price:          72.19,
    originalPrice:  118.34,
    discount:       39,
    rating:         5.0,
    reviews:        7428,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-036',
    name:           'Knot Handle Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          31.97,
    originalPrice:  39.96,
    discount:       20,
    rating:         4.0,
    reviews:        2881,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-037',
    name:           'Tassel Fringe Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          31.12,
    originalPrice:  75.91,
    discount:       59,
    rating:         4.7,
    reviews:        1703,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-038',
    name:           'Reversible Tote Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          7.18,
    originalPrice:  18.41,
    discount:       61,
    rating:         4.2,
    reviews:        5308,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-039',
    name:           'Large Raffia Beach Tote',
    category:       'bags',
    subcategory:    'Wallets',
    price:          35.73,
    originalPrice:  99.25,
    discount:       64,
    rating:         4.0,
    reviews:        24214,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-040',
    name:           'Phone Bag — Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          17.84,
    originalPrice:  28.77,
    discount:       38,
    rating:         4.9,
    reviews:        12284,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-041',
    name:           'Chic Mini Backpack',
    category:       'bags',
    subcategory:    'Handbags',
    price:          34.44,
    originalPrice:  60.42,
    discount:       43,
    rating:         4.3,
    reviews:        5922,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "handbags", "bags", "backpack", "purse"]
  },
  {
    id:             'dar-bags-042',
    name:           'Lock Clasp Structured Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          48.06,
    originalPrice:  75.1,
    discount:       36,
    rating:         4.4,
    reviews:        9819,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-043',
    name:           'Rope Handle Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          38.44,
    originalPrice:  101.17,
    discount:       62,
    rating:         4.7,
    reviews:        4214,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-044',
    name:           'Patchwork Denim Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          7.4,
    originalPrice:  16.45,
    discount:       55,
    rating:         4.7,
    reviews:        10653,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'dar-bags-045',
    name:           'Woven Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          39.75,
    originalPrice:  62.11,
    discount:       36,
    rating:         4.4,
    reviews:        8704,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'dar-bags-046',
    name:           'Feather Trim Evening Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          45.37,
    originalPrice:  105.51,
    discount:       57,
    rating:         4.5,
    reviews:        7477,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'dar-bags-047',
    name:           'Nylon Messenger Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          40.53,
    originalPrice:  112.58,
    discount:       64,
    rating:         5.0,
    reviews:        8337,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'dar-bags-048',
    name:           'Half-Moon Crescent Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          49.81,
    originalPrice:  74.35,
    discount:       33,
    rating:         4.7,
    reviews:        6536,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'dar-bags-049',
    name:           'Snakeskin Effect Clutch',
    category:       'bags',
    subcategory:    'Wallets',
    price:          30.31,
    originalPrice:  48.88,
    discount:       38,
    rating:         4.6,
    reviews:        10266,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tote", "handbag", "bags", "clutch", "purse", "wallets"]
  },
  {
    id:             'dar-bags-050',
    name:           'Double Zip Crossbody Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          25.74,
    originalPrice:  47.67,
    discount:       46,
    rating:         4.0,
    reviews:        21012,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/bags-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  }
);
