/* DARAZ — Beauty (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-beau-001',
    name:           'Vitamin C Brightening Serum — 30ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          19.65,
    originalPrice:  54.57,
    discount:       64,
    rating:         4.8,
    reviews:        639,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare"]
  },
  {
    id:             'dar-beau-002',
    name:           'Korean Skincare 5-Piece Set',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          44.88,
    originalPrice:  72.39,
    discount:       38,
    rating:         4.1,
    reviews:        7411,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'dar-beau-003',
    name:           'Rose Quartz Face Roller & Gua Sha Set',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          4.42,
    originalPrice:  12.27,
    discount:       64,
    rating:         4.2,
    reviews:        9089,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-004',
    name:           'Electric Face Massager — Microcurrent',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          55.86,
    originalPrice:  73.5,
    discount:       24,
    rating:         4.8,
    reviews:        2895,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "fragrance", "massager", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-005',
    name:           'Matte Lipstick Collection — 12 Shades',
    category:       'beauty',
    subcategory:    'Nails',
    price:          47.77,
    originalPrice:  82.37,
    discount:       42,
    rating:         4.1,
    reviews:        8405,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "skincare", "collection"]
  },
  {
    id:             'dar-beau-006',
    name:           'Portable Hair Straightener Brush',
    category:       'beauty',
    subcategory:    'Tools',
    price:          55.66,
    originalPrice:  113.59,
    discount:       51,
    rating:         4.7,
    reviews:        23644,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "brush", "beauty", "skincare", "tools"]
  },
  {
    id:             'dar-beau-007',
    name:           'Retinol Night Cream — Anti-Ageing',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          71.43,
    originalPrice:  93.99,
    discount:       24,
    rating:         4.5,
    reviews:        14281,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-008',
    name:           'Hyaluronic Acid Moisturiser — 50ml',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          72.59,
    originalPrice:  117.08,
    discount:       38,
    rating:         4.4,
    reviews:        1928,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare"]
  },
  {
    id:             'dar-beau-009',
    name:           'Waterproof Mascara — Lengthening',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          18.26,
    originalPrice:  32.6,
    discount:       44,
    rating:         4.6,
    reviews:        6506,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "mascara", "beauty", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-010',
    name:           '24K Gold Eye Patches — 60 Pairs',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          61.87,
    originalPrice:  93.75,
    discount:       34,
    rating:         4.4,
    reviews:        13949,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "patches", "skincare"]
  },
  {
    id:             'dar-beau-011',
    name:           'Niacinamide Toner — Pore Minimising',
    category:       'beauty',
    subcategory:    'Nails',
    price:          49.37,
    originalPrice:  73.69,
    discount:       33,
    rating:         4.3,
    reviews:        1889,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "toner", "skincare"]
  },
  {
    id:             'dar-beau-012',
    name:           'Snail Mucin Essence — 100ml',
    category:       'beauty',
    subcategory:    'Tools',
    price:          56.77,
    originalPrice:  118.28,
    discount:       52,
    rating:         4.7,
    reviews:        22156,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "essence", "skincare", "tools"]
  },
  {
    id:             'dar-beau-013',
    name:           'Micellar Cleansing Water — 500ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          34.19,
    originalPrice:  89.98,
    discount:       62,
    rating:         4.2,
    reviews:        3757,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "water", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-014',
    name:           'BHA Salicylic Acid Exfoliant',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          19.31,
    originalPrice:  48.27,
    discount:       60,
    rating:         4.8,
    reviews:        1732,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "exfoliant", "skincare"]
  },
  {
    id:             'dar-beau-015',
    name:           'Natural Lip Oil — Glossy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          89.51,
    originalPrice:  114.76,
    discount:       22,
    rating:         4.2,
    reviews:        14463,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "oil", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-016',
    name:           'BB Cream SPF30 — Tinted',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          76.13,
    originalPrice:  107.23,
    discount:       29,
    rating:         4.4,
    reviews:        5411,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "spf30", "skincare"]
  },
  {
    id:             'dar-beau-017',
    name:           'Under-Eye Concealer — Full Coverage',
    category:       'beauty',
    subcategory:    'Nails',
    price:          19.41,
    originalPrice:  48.52,
    discount:       60,
    rating:         4.3,
    reviews:        23392,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "concealer", "nails", "skincare"]
  },
  {
    id:             'dar-beau-018',
    name:           'Eyeshadow Palette — 18 Shades',
    category:       'beauty',
    subcategory:    'Tools',
    price:          66.88,
    originalPrice:  104.5,
    discount:       36,
    rating:         4.9,
    reviews:        20170,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare", "tools"]
  },
  {
    id:             'dar-beau-019',
    name:           'Setting Powder — Translucent',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          43.73,
    originalPrice:  112.13,
    discount:       61,
    rating:         4.1,
    reviews:        23988,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "powder", "skincare"]
  },
  {
    id:             'dar-beau-020',
    name:           'Hair Mask — Deep Conditioning',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          10.65,
    originalPrice:  25.98,
    discount:       59,
    rating:         4.1,
    reviews:        793,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "mask"]
  },
  {
    id:             'dar-beau-021',
    name:           'Colour-Depositing Purple Shampoo',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          31.81,
    originalPrice:  56.8,
    discount:       44,
    rating:         4.7,
    reviews:        14059,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "shampoo", "haircare"]
  },
  {
    id:             'dar-beau-022',
    name:           'Scalp Serum — Hair Growth',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          25.52,
    originalPrice:  65.44,
    discount:       61,
    rating:         4.7,
    reviews:        22429,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "serum", "skincare"]
  },
  {
    id:             'dar-beau-023',
    name:           'AHA Glycolic Acid Peel Pads',
    category:       'beauty',
    subcategory:    'Nails',
    price:          14.66,
    originalPrice:  20.65,
    discount:       29,
    rating:         4.5,
    reviews:        20599,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "pads", "nails", "skincare"]
  },
  {
    id:             'dar-beau-024',
    name:           'Jade Roller Duo Set',
    category:       'beauty',
    subcategory:    'Tools',
    price:          48.42,
    originalPrice:  69.17,
    discount:       30,
    rating:         4.1,
    reviews:        2931,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "tools"]
  },
  {
    id:             'dar-beau-025',
    name:           'Foundation — 40 Shades',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          32.82,
    originalPrice:  88.7,
    discount:       63,
    rating:         4.2,
    reviews:        4318,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-026',
    name:           'Blush & Bronzer Duo Palette',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          58.35,
    originalPrice:  76.78,
    discount:       24,
    rating:         4.6,
    reviews:        10084,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare"]
  },
  {
    id:             'dar-beau-027',
    name:           'Eyeliner Pen — Waterproof',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          46.52,
    originalPrice:  60.42,
    discount:       23,
    rating:         4.5,
    reviews:        17125,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "pen", "beauty", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-028',
    name:           'Brow Lamination Kit',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          33.17,
    originalPrice:  75.39,
    discount:       56,
    rating:         4.1,
    reviews:        12858,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "kit", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-029',
    name:           'Lip Plumper Gloss — Berry',
    category:       'beauty',
    subcategory:    'Nails',
    price:          50.2,
    originalPrice:  82.3,
    discount:       39,
    rating:         4.3,
    reviews:        11907,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "gloss", "beauty", "nails", "skincare"]
  },
  {
    id:             'dar-beau-030',
    name:           'Self-Tan Mousse — Medium',
    category:       'beauty',
    subcategory:    'Tools',
    price:          63.74,
    originalPrice:  108.04,
    discount:       41,
    rating:         4.8,
    reviews:        18885,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "mousse", "beauty", "skincare", "tools"]
  },
  {
    id:             'dar-beau-031',
    name:           'Vitamin E Body Lotion — 400ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          14.48,
    originalPrice:  19.3,
    discount:       25,
    rating:         4.5,
    reviews:        1073,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "lotion", "skincare"]
  },
  {
    id:             'dar-beau-032',
    name:           'Dry Shampoo Spray',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          30.33,
    originalPrice:  63.18,
    discount:       52,
    rating:         5.0,
    reviews:        3156,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "spray"]
  },
  {
    id:             'dar-beau-033',
    name:           'Sheet Face Mask Set — 10 Pack',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          57.06,
    originalPrice:  83.91,
    discount:       32,
    rating:         4.6,
    reviews:        14988,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-034',
    name:           'Cleansing Balm — Waterproof Makeup',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          54.75,
    originalPrice:  69.31,
    discount:       21,
    rating:         4.4,
    reviews:        14117,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "fragrance", "balm", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-035',
    name:           'SPF50 Sunscreen — Invisible',
    category:       'beauty',
    subcategory:    'Nails',
    price:          31.07,
    originalPrice:  64.72,
    discount:       52,
    rating:         4.7,
    reviews:        5549,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "sunscreen", "nails", "skincare"]
  },
  {
    id:             'dar-beau-036',
    name:           'Lash Growth Serum',
    category:       'beauty',
    subcategory:    'Tools',
    price:          31.97,
    originalPrice:  54.19,
    discount:       41,
    rating:         4.1,
    reviews:        20439,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare", "tools"]
  },
  {
    id:             'dar-beau-037',
    name:           'Collagen Peptide Face Cream',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          29.53,
    originalPrice:  79.82,
    discount:       63,
    rating:         4.1,
    reviews:        11319,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-038',
    name:           'Tea Tree Spot Treatment',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          52.0,
    originalPrice:  89.66,
    discount:       42,
    rating:         5.0,
    reviews:        16230,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "treatment", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-039',
    name:           'Cushion Foundation — Dewy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          58.92,
    originalPrice:  115.53,
    discount:       49,
    rating:         4.5,
    reviews:        18265,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-040',
    name:           'Peptide Eye Cream',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          53.64,
    originalPrice:  105.17,
    discount:       49,
    rating:         4.1,
    reviews:        1805,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "cream", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-041',
    name:           'Coconut Oil Body Scrub',
    category:       'beauty',
    subcategory:    'Nails',
    price:          40.34,
    originalPrice:  77.57,
    discount:       48,
    rating:         4.7,
    reviews:        246,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "scrub", "beauty", "nails", "skincare"]
  },
  {
    id:             'dar-beau-042',
    name:           'Pore Strips — Blackhead Remover',
    category:       'beauty',
    subcategory:    'Tools',
    price:          9.92,
    originalPrice:  13.78,
    discount:       28,
    rating:         4.4,
    reviews:        4520,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "strips", "beauty", "skincare", "tools"]
  },
  {
    id:             'dar-beau-043',
    name:           'CC Cream — Colour Correcting',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          20.65,
    originalPrice:  35.0,
    discount:       41,
    rating:         4.9,
    reviews:        11924,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-044',
    name:           'Gel Liner — Smudge Proof',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          7.32,
    originalPrice:  13.07,
    discount:       44,
    rating:         4.5,
    reviews:        3539,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "liner", "skincare"]
  },
  {
    id:             'dar-beau-045',
    name:           'Ceramide Barrier Repair Moisturiser',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          9.35,
    originalPrice:  25.97,
    discount:       64,
    rating:         4.4,
    reviews:        18215,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare", "haircare"]
  },
  {
    id:             'dar-beau-046',
    name:           'Illuminating Primer',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          49.63,
    originalPrice:  95.45,
    discount:       48,
    rating:         5.0,
    reviews:        7722,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "primer", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'dar-beau-047',
    name:           'Multi-Vitamin Face Oil',
    category:       'beauty',
    subcategory:    'Nails',
    price:          17.28,
    originalPrice:  48.0,
    discount:       64,
    rating:         5.0,
    reviews:        500,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "oil", "skincare"]
  },
  {
    id:             'dar-beau-048',
    name:           'Whipped Body Butter — Shea',
    category:       'beauty',
    subcategory:    'Tools',
    price:          42.89,
    originalPrice:  95.31,
    discount:       55,
    rating:         4.7,
    reviews:        14237,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "butter", "tools"]
  },
  {
    id:             'dar-beau-049',
    name:           'Cruelty-Free Makeup Brush Set',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          35.5,
    originalPrice:  46.1,
    discount:       23,
    rating:         4.8,
    reviews:        13205,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'dar-beau-050',
    name:           'Nail Polish Set — 12 Colours',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          75.21,
    originalPrice:  101.63,
    discount:       26,
    rating:         4.5,
    reviews:        21528,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/beauty-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  }
);
