/* DARAZ — Crafts (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-craf-001',
    name:           'Diamond Painting Kit — Full Drill 40×50',
    category:       'crafts',
    subcategory:    'Painting',
    price:          16.92,
    originalPrice:  48.34,
    discount:       65,
    rating:         4.7,
    reviews:        4434,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-002',
    name:           'Resin Art Kit — UV Resin + Moulds',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          75.52,
    originalPrice:  95.59,
    discount:       21,
    rating:         4.6,
    reviews:        688,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-003',
    name:           'Aesthetic Journaling Kit — Washi Tapes',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          33.69,
    originalPrice:  91.05,
    discount:       63,
    rating:         4.1,
    reviews:        21852,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-004',
    name:           'Watercolour Paint Set — 48 Colours',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          6.97,
    originalPrice:  13.95,
    discount:       50,
    rating:         4.6,
    reviews:        13269,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-005',
    name:           'Macramé Wall Hanging Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          34.13,
    originalPrice:  87.52,
    discount:       61,
    rating:         4.8,
    reviews:        5602,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-006',
    name:           'Embroidery Starter Kit — Floral',
    category:       'crafts',
    subcategory:    'DIY',
    price:          39.47,
    originalPrice:  69.24,
    discount:       43,
    rating:         4.9,
    reviews:        24184,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-007',
    name:           'Lino Printing Starter Set',
    category:       'crafts',
    subcategory:    'Painting',
    price:          37.75,
    originalPrice:  69.9,
    discount:       46,
    rating:         4.4,
    reviews:        2484,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-008',
    name:           'Candle Making Kit — Soy Wax',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          7.41,
    originalPrice:  19.5,
    discount:       62,
    rating:         4.4,
    reviews:        2078,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-009',
    name:           'Pottery Air Dry Clay Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          45.25,
    originalPrice:  113.13,
    discount:       60,
    rating:         4.1,
    reviews:        2410,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-010',
    name:           'Leather Craft Tooling Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          32.4,
    originalPrice:  63.52,
    discount:       49,
    rating:         4.1,
    reviews:        12643,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-011',
    name:           'Cross-Stitch Bookmark Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          37.11,
    originalPrice:  78.96,
    discount:       53,
    rating:         4.2,
    reviews:        9974,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-012',
    name:           'Acrylic Pour Painting Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          16.27,
    originalPrice:  21.7,
    discount:       25,
    rating:         5.0,
    reviews:        12351,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-013',
    name:           'Needle Felting Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          41.25,
    originalPrice:  51.56,
    discount:       20,
    rating:         4.8,
    reviews:        3260,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-014',
    name:           'Calligraphy Pen & Ink Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          20.55,
    originalPrice:  44.68,
    discount:       54,
    rating:         4.4,
    reviews:        3582,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-015',
    name:           'Soap Making Kit — Natural',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          6.7,
    originalPrice:  19.14,
    discount:       65,
    rating:         4.6,
    reviews:        4563,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-016',
    name:           'Origami Paper Set — 200 Sheets',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          6.24,
    originalPrice:  17.83,
    discount:       65,
    rating:         4.1,
    reviews:        19595,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-017',
    name:           'Knitting Starter Kit — Beginner',
    category:       'crafts',
    subcategory:    'Resin',
    price:          69.24,
    originalPrice:  86.55,
    discount:       20,
    rating:         4.1,
    reviews:        9773,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-018',
    name:           'Crochet Hook Set + Yarn Bundle',
    category:       'crafts',
    subcategory:    'DIY',
    price:          39.03,
    originalPrice:  84.84,
    discount:       54,
    rating:         4.0,
    reviews:        3941,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-019',
    name:           'Jewellery Making Kit — Beads',
    category:       'crafts',
    subcategory:    'Painting',
    price:          57.5,
    originalPrice:  115.0,
    discount:       50,
    rating:         4.8,
    reviews:        13235,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-020',
    name:           'Tie-Dye Kit — Spiral',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          30.63,
    originalPrice:  85.08,
    discount:       64,
    rating:         4.3,
    reviews:        15327,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-021',
    name:           'Painting by Numbers — Landscape',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          33.3,
    originalPrice:  92.51,
    discount:       64,
    rating:         4.1,
    reviews:        20995,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["numbers", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-022',
    name:           'Block Printing Ink Set',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          65.01,
    originalPrice:  89.05,
    discount:       27,
    rating:         4.7,
    reviews:        20031,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-023',
    name:           'Scrapbook Kit — 200 Stickers',
    category:       'crafts',
    subcategory:    'Resin',
    price:          24.33,
    originalPrice:  59.34,
    discount:       59,
    rating:         4.1,
    reviews:        11043,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-024',
    name:           'Pressed Flower Art Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          20.93,
    originalPrice:  30.78,
    discount:       32,
    rating:         4.7,
    reviews:        24922,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-025',
    name:           'Glass Painting Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          36.51,
    originalPrice:  104.32,
    discount:       65,
    rating:         4.2,
    reviews:        7101,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-026',
    name:           'Wool Felting Supplies Bundle',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          25.5,
    originalPrice:  52.05,
    discount:       51,
    rating:         4.1,
    reviews:        13277,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-027',
    name:           'Punch Needle Rug Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          30.66,
    originalPrice:  57.84,
    discount:       47,
    rating:         4.6,
    reviews:        10266,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-028',
    name:           'Marbling Paper Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          37.33,
    originalPrice:  71.79,
    discount:       48,
    rating:         4.6,
    reviews:        9660,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-029',
    name:           'Silk Screen Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          15.76,
    originalPrice:  22.52,
    discount:       30,
    rating:         4.7,
    reviews:        15607,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-030',
    name:           'Decoupage Set + Papers',
    category:       'crafts',
    subcategory:    'DIY',
    price:          33.69,
    originalPrice:  93.58,
    discount:       64,
    rating:         4.6,
    reviews:        14517,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["papers", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-031',
    name:           'Weaving Loom Kit — Beginner',
    category:       'crafts',
    subcategory:    'Painting',
    price:          33.81,
    originalPrice:  96.59,
    discount:       65,
    rating:         4.8,
    reviews:        3908,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-032',
    name:           'Zentangle Art Pens Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          79.1,
    originalPrice:  98.87,
    discount:       20,
    rating:         4.6,
    reviews:        22143,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-033',
    name:           'Linoleum Block Carving Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          33.12,
    originalPrice:  82.81,
    discount:       60,
    rating:         4.6,
    reviews:        15148,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-034',
    name:           'Alcohol Ink Art Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          47.46,
    originalPrice:  98.88,
    discount:       52,
    rating:         4.8,
    reviews:        22325,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-035',
    name:           'Mandala Drawing Stencil Set',
    category:       'crafts',
    subcategory:    'Resin',
    price:          69.32,
    originalPrice:  103.46,
    discount:       33,
    rating:         4.4,
    reviews:        11549,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-036',
    name:           'Rubber Stamp Making Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          49.6,
    originalPrice:  88.58,
    discount:       44,
    rating:         4.7,
    reviews:        20018,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-037',
    name:           'Reusable Stencil Set — 40 Piece',
    category:       'crafts',
    subcategory:    'Painting',
    price:          66.72,
    originalPrice:  91.4,
    discount:       27,
    rating:         4.4,
    reviews:        13087,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-038',
    name:           'Air Dry Clay Tool Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          26.52,
    originalPrice:  44.95,
    discount:       41,
    rating:         4.6,
    reviews:        21976,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-039',
    name:           'Mixed Media Art Journal',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          22.86,
    originalPrice:  51.96,
    discount:       56,
    rating:         4.7,
    reviews:        13216,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["journal", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-040',
    name:           'Bookbinding Kit — Hardcover',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          64.27,
    originalPrice:  98.88,
    discount:       35,
    rating:         4.1,
    reviews:        5335,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-041',
    name:           'Batik Wax Resist Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          34.38,
    originalPrice:  46.46,
    discount:       26,
    rating:         4.6,
    reviews:        15888,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-042',
    name:           'Pyrography Wood Burning Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          56.95,
    originalPrice:  103.55,
    discount:       45,
    rating:         4.4,
    reviews:        3048,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-043',
    name:           'Paper Quilling Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          29.6,
    originalPrice:  51.93,
    discount:       43,
    rating:         4.3,
    reviews:        23210,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-044',
    name:           'Shrink Plastic Art Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          17.21,
    originalPrice:  22.06,
    discount:       22,
    rating:         4.4,
    reviews:        11315,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'dar-craf-045',
    name:           'Enamel Painting Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          69.46,
    originalPrice:  110.26,
    discount:       37,
    rating:         4.8,
    reviews:        2793,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-046',
    name:           'Gilding Flakes Set — Gold',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          51.9,
    originalPrice:  76.33,
    discount:       32,
    rating:         4.8,
    reviews:        9408,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-047',
    name:           'Linocut Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          49.36,
    originalPrice:  80.91,
    discount:       39,
    rating:         4.9,
    reviews:        19712,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-048',
    name:           'Botanical Illustration Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          37.28,
    originalPrice:  46.6,
    discount:       20,
    rating:         4.9,
    reviews:        18883,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-049',
    name:           'Copper Tooling Craft Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          9.36,
    originalPrice:  21.28,
    discount:       56,
    rating:         4.7,
    reviews:        20770,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'dar-craf-050',
    name:           'Felt Sewing Starter Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          14.51,
    originalPrice:  36.28,
    discount:       60,
    rating:         4.5,
    reviews:        21391,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/crafts-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  }
);
