/* DARAZ — Electronics (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-elec-001',
    name:           'Smart Watch Pro — Fitness Tracker',
    category:       'electronics',
    subcategory:    'Phones',
    price:          76.53,
    originalPrice:  112.55,
    discount:       32,
    rating:         4.5,
    reviews:        20936,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gadgets", "smart", "pro", "phones"]
  },
  {
    id:             'dar-elec-002',
    name:           'TWS Wireless Earbuds — Noise Cancelling',
    category:       'electronics',
    subcategory:    'Audio',
    price:          18.91,
    originalPrice:  24.88,
    discount:       24,
    rating:         4.7,
    reviews:        16446,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'dar-elec-003',
    name:           'Bluetooth 5.3 Over-Ear Headphones',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          34.55,
    originalPrice:  69.1,
    discount:       50,
    rating:         4.1,
    reviews:        19130,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "headphones"]
  },
  {
    id:             'dar-elec-004',
    name:           'Mini Projector for Home Cinema',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          29.59,
    originalPrice:  51.02,
    discount:       42,
    rating:         4.2,
    reviews:        23671,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "cinema", "cameras", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-005',
    name:           'RGB Mechanical Gaming Keyboard',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          11.11,
    originalPrice:  21.79,
    discount:       49,
    rating:         4.6,
    reviews:        6206,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-006',
    name:           '3-in-1 Wireless Charging Pad — 15W',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          54.41,
    originalPrice:  106.69,
    discount:       49,
    rating:         4.9,
    reviews:        2692,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "pad", "electronics", "accessories", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-007',
    name:           'Smart LED Bulb — Colour Changing WiFi',
    category:       'electronics',
    subcategory:    'Phones',
    price:          11.96,
    originalPrice:  24.91,
    discount:       52,
    rating:         4.8,
    reviews:        12963,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "bulb", "gadgets", "smart", "phones"]
  },
  {
    id:             'dar-elec-008',
    name:           'Xiaomi Power Bank 20000mAh',
    category:       'electronics',
    subcategory:    'Audio',
    price:          33.49,
    originalPrice:  54.9,
    discount:       39,
    rating:         4.1,
    reviews:        10686,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "electronics", "20000mah", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-009',
    name:           'Portable Bluetooth Speaker — Waterproof',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          37.92,
    originalPrice:  58.34,
    discount:       35,
    rating:         4.0,
    reviews:        11866,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "speaker", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-010',
    name:           'Ring Light — 10" Selfie',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          47.72,
    originalPrice:  86.77,
    discount:       45,
    rating:         4.7,
    reviews:        17555,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "light"]
  },
  {
    id:             'dar-elec-011',
    name:           'Gaming Mouse — RGB Backlit',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          33.52,
    originalPrice:  68.4,
    discount:       51,
    rating:         4.2,
    reviews:        11695,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gaming", "gadgets", "mouse", "smart"]
  },
  {
    id:             'dar-elec-012',
    name:           'USB-C Hub — 7 Port',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          17.99,
    originalPrice:  39.98,
    discount:       55,
    rating:         4.0,
    reviews:        13399,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "accessories", "gadgets", "hub", "smart"]
  },
  {
    id:             'dar-elec-013',
    name:           'Webcam HD 1080p — Built-in Mic',
    category:       'electronics',
    subcategory:    'Phones',
    price:          10.34,
    originalPrice:  25.84,
    discount:       60,
    rating:         4.1,
    reviews:        14998,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gadgets", "smart", "1080p", "phones"]
  },
  {
    id:             'dar-elec-014',
    name:           'Smart Plug — Voice Control',
    category:       'electronics',
    subcategory:    'Audio',
    price:          68.9,
    originalPrice:  90.66,
    discount:       24,
    rating:         4.3,
    reviews:        8007,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["plug", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-015',
    name:           'Electric Toothbrush — Rechargeable',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          77.23,
    originalPrice:  108.78,
    discount:       29,
    rating:         4.6,
    reviews:        24036,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "toothbrush", "smart"]
  },
  {
    id:             'dar-elec-016',
    name:           'Noise Cancelling Earbuds',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          52.15,
    originalPrice:  76.69,
    discount:       32,
    rating:         4.1,
    reviews:        7966,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "earbuds"]
  },
  {
    id:             'dar-elec-017',
    name:           'Dash Cam — Front & Rear 4K',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          29.4,
    originalPrice:  43.23,
    discount:       32,
    rating:         4.6,
    reviews:        12522,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "cam"]
  },
  {
    id:             'dar-elec-018',
    name:           'Smart Scale — Body Fat Analysis',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          35.7,
    originalPrice:  51.0,
    discount:       30,
    rating:         4.7,
    reviews:        9865,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "scale", "accessories", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-019',
    name:           'Portable SSD — 1TB',
    category:       'electronics',
    subcategory:    'Phones',
    price:          39.94,
    originalPrice:  81.51,
    discount:       51,
    rating:         4.3,
    reviews:        11514,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gadgets", "ssd", "smart", "phones"]
  },
  {
    id:             'dar-elec-020',
    name:           'HDMI Cable 4K — 2m',
    category:       'electronics',
    subcategory:    'Audio',
    price:          54.96,
    originalPrice:  114.49,
    discount:       52,
    rating:         4.9,
    reviews:        8672,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "4k", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-021',
    name:           'Smart Home Security Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          12.86,
    originalPrice:  17.86,
    discount:       28,
    rating:         4.9,
    reviews:        16774,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "camera"]
  },
  {
    id:             'dar-elec-022',
    name:           'Digital Photo Frame — Wi-Fi',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          6.74,
    originalPrice:  18.71,
    discount:       64,
    rating:         4.9,
    reviews:        23772,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["frame", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-023',
    name:           'Kids\' Tablet — 10" Android',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          52.32,
    originalPrice:  109.01,
    discount:       52,
    rating:         4.7,
    reviews:        966,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "tablet", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-024',
    name:           'Wireless Gaming Controller',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          15.93,
    originalPrice:  20.96,
    discount:       24,
    rating:         4.3,
    reviews:        17977,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "controller"]
  },
  {
    id:             'dar-elec-025',
    name:           'Robot Vacuum Cleaner — Smart Map',
    category:       'electronics',
    subcategory:    'Phones',
    price:          9.97,
    originalPrice:  20.78,
    discount:       52,
    rating:         4.1,
    reviews:        20074,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gadgets", "smart", "cleaner", "phones"]
  },
  {
    id:             'dar-elec-026',
    name:           'Air Purifier — HEPA Filter',
    category:       'electronics',
    subcategory:    'Audio',
    price:          26.93,
    originalPrice:  76.93,
    discount:       65,
    rating:         4.3,
    reviews:        13697,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "electronics", "purifier", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-027',
    name:           'Smart Doorbell — HD Camera',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          9.41,
    originalPrice:  12.07,
    discount:       22,
    rating:         4.4,
    reviews:        22280,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "doorbell"]
  },
  {
    id:             'dar-elec-028',
    name:           'Portable Projector Screen — 120"',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          28.03,
    originalPrice:  70.08,
    discount:       60,
    rating:         4.6,
    reviews:        1382,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["screen", "tech", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-029',
    name:           'Mini Keyboard — Bluetooth',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          43.72,
    originalPrice:  67.26,
    discount:       35,
    rating:         4.2,
    reviews:        21161,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["keyboard", "tech", "electronics", "gaming", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-030',
    name:           'Action Camera — 4K Waterproof',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          53.1,
    originalPrice:  96.54,
    discount:       45,
    rating:         4.4,
    reviews:        9647,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "accessories", "gadgets", "smart", "camera"]
  },
  {
    id:             'dar-elec-031',
    name:           'VR Headset — Standalone',
    category:       'electronics',
    subcategory:    'Phones',
    price:          84.46,
    originalPrice:  117.31,
    discount:       28,
    rating:         4.4,
    reviews:        9361,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'dar-elec-032',
    name:           'Laser Printer — Wireless',
    category:       'electronics',
    subcategory:    'Audio',
    price:          50.86,
    originalPrice:  65.21,
    discount:       22,
    rating:         4.6,
    reviews:        11190,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["printer", "tech", "audio", "electronics", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-033',
    name:           'Smart TV Stick — 4K Streaming',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          8.98,
    originalPrice:  12.14,
    discount:       26,
    rating:         5.0,
    reviews:        16973,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["stick", "tech", "electronics", "smart_home", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-034',
    name:           'Electric Hand Massager',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          35.8,
    originalPrice:  89.5,
    discount:       60,
    rating:         4.8,
    reviews:        5279,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "cameras", "gadgets", "smart", "massager"]
  },
  {
    id:             'dar-elec-035',
    name:           'Foldable Phone Stand Holder',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          16.79,
    originalPrice:  32.93,
    discount:       49,
    rating:         4.1,
    reviews:        11497,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'dar-elec-036',
    name:           'Wireless Earbuds Case — Leather',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          7.54,
    originalPrice:  18.39,
    discount:       59,
    rating:         4.4,
    reviews:        18725,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "accessories", "case", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-037',
    name:           'Gaming Headset — Surround Sound',
    category:       'electronics',
    subcategory:    'Phones',
    price:          17.0,
    originalPrice:  36.18,
    discount:       53,
    rating:         4.3,
    reviews:        18924,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "headset", "gadgets", "smart", "phones"]
  },
  {
    id:             'dar-elec-038',
    name:           'LED Desk Lamp — USB Charging',
    category:       'electronics',
    subcategory:    'Audio',
    price:          61.33,
    originalPrice:  115.71,
    discount:       47,
    rating:         4.8,
    reviews:        16521,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "lamp"]
  },
  {
    id:             'dar-elec-039',
    name:           'Smart Thermostat — Wi-Fi',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          37.73,
    originalPrice:  82.03,
    discount:       54,
    rating:         4.1,
    reviews:        18508,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "thermostat"]
  },
  {
    id:             'dar-elec-040',
    name:           'Portable Power Station — 500W',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          19.16,
    originalPrice:  54.75,
    discount:       65,
    rating:         4.9,
    reviews:        11975,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "station", "cameras", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-041',
    name:           'E-Reader — Backlit 6"',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          34.99,
    originalPrice:  71.41,
    discount:       51,
    rating:         4.7,
    reviews:        8750,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "e-reader"]
  },
  {
    id:             'dar-elec-042',
    name:           'Cable Management Box',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          17.09,
    originalPrice:  43.81,
    discount:       61,
    rating:         4.3,
    reviews:        14437,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "box", "accessories", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-043',
    name:           'Smart Speaker — Voice Assistant',
    category:       'electronics',
    subcategory:    'Phones',
    price:          15.48,
    originalPrice:  35.99,
    discount:       57,
    rating:         4.3,
    reviews:        2753,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "speaker", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'dar-elec-044',
    name:           'Drawing Tablet — A5',
    category:       'electronics',
    subcategory:    'Audio',
    price:          27.53,
    originalPrice:  36.7,
    discount:       25,
    rating:         4.9,
    reviews:        2123,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "tablet", "electronics", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-045',
    name:           'Solar Charger Panel — 20W',
    category:       'electronics',
    subcategory:    'Smart Home',
    price:          22.87,
    originalPrice:  49.72,
    discount:       54,
    rating:         4.4,
    reviews:        23989,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "smart_home", "gadgets", "smart", "panel"]
  },
  {
    id:             'dar-elec-046',
    name:           'USB Microphone — Podcast',
    category:       'electronics',
    subcategory:    'Cameras',
    price:          38.71,
    originalPrice:  52.31,
    discount:       26,
    rating:         4.5,
    reviews:        557,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "microphone", "electronics", "cameras", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-047',
    name:           'Car Phone Holder — Magnetic',
    category:       'electronics',
    subcategory:    'Gaming',
    price:          59.04,
    originalPrice:  101.8,
    discount:       42,
    rating:         4.4,
    reviews:        18945,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "gaming", "gadgets", "smart", "holder"]
  },
  {
    id:             'dar-elec-048',
    name:           'Smart Door Lock — Fingerprint',
    category:       'electronics',
    subcategory:    'Accessories',
    price:          57.21,
    originalPrice:  104.02,
    discount:       45,
    rating:         4.7,
    reviews:        6486,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "electronics", "accessories", "lock", "gadgets", "smart"]
  },
  {
    id:             'dar-elec-049',
    name:           'Dash Cam Hardwire Kit',
    category:       'electronics',
    subcategory:    'Phones',
    price:          16.23,
    originalPrice:  27.05,
    discount:       40,
    rating:         4.4,
    reviews:        8456,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "tech", "electronics", "gadgets", "smart", "phones"]
  },
  {
    id:             'dar-elec-050',
    name:           'Screen Protector — Tempered Glass',
    category:       'electronics',
    subcategory:    'Audio',
    price:          34.6,
    originalPrice:  67.84,
    discount:       49,
    rating:         4.8,
    reviews:        20320,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/electronics-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tech", "audio", "electronics", "gadgets", "smart", "protector"]
  }
);
