/* DARAZ — Flowers (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-flow-001',
    name:           'Luxury Rose Bouquet — 24 Stems',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          46.75,
    originalPrice:  108.72,
    discount:       57,
    rating:         4.9,
    reviews:        1863,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-002',
    name:           'Sunflower & Wildflower Mix Bunch',
    category:       'flowers',
    subcategory:    'Dried',
    price:          21.36,
    originalPrice:  48.55,
    discount:       56,
    rating:         4.3,
    reviews:        1736,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-003',
    name:           'Eternal Preserved Roses — Box',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          75.93,
    originalPrice:  97.34,
    discount:       22,
    rating:         4.8,
    reviews:        10942,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "roses", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-004',
    name:           'Dried Pampas Grass Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          78.69,
    originalPrice:  100.89,
    discount:       22,
    rating:         4.4,
    reviews:        15078,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'dar-flow-005',
    name:           'Tulip Mixed Colours — 15 Stems',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          12.79,
    originalPrice:  20.96,
    discount:       39,
    rating:         4.8,
    reviews:        6311,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "colours", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-006',
    name:           'Orchid Plant — Pink Phalaenopsis',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          35.71,
    originalPrice:  67.37,
    discount:       47,
    rating:         4.3,
    reviews:        3832,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "fresh", "bouquet", "plant"]
  },
  {
    id:             'dar-flow-007',
    name:           'Peony & Rose Arrangement',
    category:       'flowers',
    subcategory:    'Dried',
    price:          15.15,
    originalPrice:  22.61,
    discount:       33,
    rating:         4.5,
    reviews:        8339,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "dried", "arrangement", "bouquet"]
  },
  {
    id:             'dar-flow-008',
    name:           'Lavender Bundle — Dried',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          14.81,
    originalPrice:  29.04,
    discount:       49,
    rating:         4.4,
    reviews:        20310,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "floral", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-009',
    name:           'Succulent Mini Garden Set',
    category:       'flowers',
    subcategory:    'Plants',
    price:          14.86,
    originalPrice:  40.15,
    discount:       63,
    rating:         4.9,
    reviews:        20847,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "set", "bouquet"]
  },
  {
    id:             'dar-flow-010',
    name:           'Hydrangea Arrangement — Blue',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          56.31,
    originalPrice:  84.05,
    discount:       33,
    rating:         4.5,
    reviews:        2638,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "gift_sets", "arrangement", "bouquet"]
  },
  {
    id:             'dar-flow-011',
    name:           'Artificial Rose Garland — 2m',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          37.94,
    originalPrice:  54.99,
    discount:       31,
    rating:         4.1,
    reviews:        10133,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "garland", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-012',
    name:           'Birthday Balloon & Flower Box',
    category:       'flowers',
    subcategory:    'Dried',
    price:          8.62,
    originalPrice:  14.86,
    discount:       42,
    rating:         4.1,
    reviews:        15589,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-013',
    name:           'Spring Daffodil Bunch — Yellow',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          14.18,
    originalPrice:  20.85,
    discount:       32,
    rating:         4.6,
    reviews:        16341,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "bunch", "plants", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-014',
    name:           'Gypsophila (Baby\'s Breath) Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          60.78,
    originalPrice:  108.53,
    discount:       44,
    rating:         4.0,
    reviews:        13778,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'dar-flow-015',
    name:           'Lily & Gerbera Mix Bouquet',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          60.24,
    originalPrice:  92.68,
    discount:       35,
    rating:         4.1,
    reviews:        10839,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-016',
    name:           'Dried Flowers Wreath — 30cm',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          52.47,
    originalPrice:  97.16,
    discount:       46,
    rating:         4.5,
    reviews:        15647,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "wreath", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-017',
    name:           'Cherry Blossom Stem — Artificial',
    category:       'flowers',
    subcategory:    'Dried',
    price:          54.95,
    originalPrice:  101.75,
    discount:       46,
    rating:         4.1,
    reviews:        5738,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "dried", "stem", "bouquet"]
  },
  {
    id:             'dar-flow-018',
    name:           'Faux Eucalyptus Garland',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          77.55,
    originalPrice:  96.94,
    discount:       20,
    rating:         4.8,
    reviews:        16606,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "artificial", "garland", "bouquet"]
  },
  {
    id:             'dar-flow-019',
    name:           'Annual Seeds Garden Pack',
    category:       'flowers',
    subcategory:    'Plants',
    price:          63.41,
    originalPrice:  113.23,
    discount:       44,
    rating:         4.9,
    reviews:        10746,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "bouquet", "pack"]
  },
  {
    id:             'dar-flow-020',
    name:           'Valentine Red Rose Bouquet — 12',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          15.09,
    originalPrice:  32.11,
    discount:       53,
    rating:         4.2,
    reviews:        13463,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-021',
    name:           'Chrysanthemum Spray — Mixed',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          46.31,
    originalPrice:  112.94,
    discount:       59,
    rating:         4.1,
    reviews:        20979,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "bouquet", "fresh", "spray"]
  },
  {
    id:             'dar-flow-022',
    name:           'Lotus Flower Floating Bowl Set',
    category:       'flowers',
    subcategory:    'Dried',
    price:          22.74,
    originalPrice:  46.4,
    discount:       51,
    rating:         4.6,
    reviews:        1996,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "dried", "set", "bouquet"]
  },
  {
    id:             'dar-flow-023',
    name:           'Tropical Foliage Arrangement',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          23.16,
    originalPrice:  66.17,
    discount:       65,
    rating:         4.6,
    reviews:        21825,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "artificial", "arrangement", "bouquet"]
  },
  {
    id:             'dar-flow-024',
    name:           'Bluebell Woodland Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          23.85,
    originalPrice:  43.36,
    discount:       45,
    rating:         4.5,
    reviews:        4223,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'dar-flow-025',
    name:           'Carnation Bouquet — Rainbow',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          68.7,
    originalPrice:  110.81,
    discount:       38,
    rating:         4.7,
    reviews:        3589,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-026',
    name:           'Silk Artificial Orchid Stem',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          30.99,
    originalPrice:  68.87,
    discount:       55,
    rating:         4.9,
    reviews:        20538,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "fresh", "stem", "bouquet"]
  },
  {
    id:             'dar-flow-027',
    name:           'Boxed Infinity Roses — 9 Pack',
    category:       'flowers',
    subcategory:    'Dried',
    price:          10.98,
    originalPrice:  15.91,
    discount:       31,
    rating:         4.6,
    reviews:        5085,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "roses", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-028',
    name:           'Potted Jasmine Plant',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          61.52,
    originalPrice:  116.08,
    discount:       47,
    rating:         4.6,
    reviews:        10897,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "artificial", "bouquet", "plant"]
  },
  {
    id:             'dar-flow-029',
    name:           'Anemone & Ranunculus Mix',
    category:       'flowers',
    subcategory:    'Plants',
    price:          32.29,
    originalPrice:  92.25,
    discount:       65,
    rating:         4.1,
    reviews:        3846,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "mix", "bouquet"]
  },
  {
    id:             'dar-flow-030',
    name:           'Flower Crown Making Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          29.08,
    originalPrice:  42.15,
    discount:       31,
    rating:         4.8,
    reviews:        8680,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-031',
    name:           'Wildflower Meadow Seed Mix',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          35.4,
    originalPrice:  90.78,
    discount:       61,
    rating:         4.2,
    reviews:        23383,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-032',
    name:           'Poppy Bunch — Orange & Red',
    category:       'flowers',
    subcategory:    'Dried',
    price:          26.6,
    originalPrice:  34.1,
    discount:       22,
    rating:         4.0,
    reviews:        1174,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "bunch", "plants", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-033',
    name:           'Wedding Buttonhole Kit — Rose',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          64.87,
    originalPrice:  82.11,
    discount:       21,
    rating:         4.7,
    reviews:        21587,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-034',
    name:           'Dried Protea & Ferns Bundle',
    category:       'flowers',
    subcategory:    'Plants',
    price:          42.02,
    originalPrice:  87.55,
    discount:       52,
    rating:         4.5,
    reviews:        8484,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "floral", "flowers", "plants", "bouquet"]
  },
  {
    id:             'dar-flow-035',
    name:           'Hanging Flower Ball — Silk',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          11.03,
    originalPrice:  17.24,
    discount:       36,
    rating:         4.6,
    reviews:        21047,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["ball", "floral", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-036',
    name:           'Daisy Chain Meadow Bunch',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          31.54,
    originalPrice:  85.24,
    discount:       63,
    rating:         4.6,
    reviews:        19863,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "bunch", "plants", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-037',
    name:           'Moss Terrarium Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          29.38,
    originalPrice:  71.66,
    discount:       59,
    rating:         4.9,
    reviews:        15991,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-038',
    name:           'Pressed Flower Bookmark Set',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          13.34,
    originalPrice:  18.79,
    discount:       29,
    rating:         4.0,
    reviews:        10005,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "artificial", "set", "bouquet"]
  },
  {
    id:             'dar-flow-039',
    name:           'Flower Frog Kenzan Holder',
    category:       'flowers',
    subcategory:    'Plants',
    price:          9.39,
    originalPrice:  17.38,
    discount:       46,
    rating:         4.2,
    reviews:        4636,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "holder", "bouquet"]
  },
  {
    id:             'dar-flow-040',
    name:           'Faux Wisteria Hanging Branch',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          5.09,
    originalPrice:  13.39,
    discount:       62,
    rating:         5.0,
    reviews:        22643,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "branch", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-041',
    name:           'Rose Petal Confetti — Biodegradable',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          68.46,
    originalPrice:  112.23,
    discount:       39,
    rating:         4.2,
    reviews:        22361,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "confetti", "flowers", "plants", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-042',
    name:           'Ikebana Starter Kit',
    category:       'flowers',
    subcategory:    'Dried',
    price:          17.37,
    originalPrice:  43.43,
    discount:       60,
    rating:         4.8,
    reviews:        13756,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-043',
    name:           'Calla Lily Artificial Stems',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          23.34,
    originalPrice:  38.27,
    discount:       39,
    rating:         4.3,
    reviews:        20812,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "stems", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-044',
    name:           'Eucalyptus & White Rose Wreath',
    category:       'flowers',
    subcategory:    'Plants',
    price:          43.45,
    originalPrice:  77.59,
    discount:       44,
    rating:         4.0,
    reviews:        1920,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'dar-flow-045',
    name:           'Floral Foam Arrangement Kit',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          11.97,
    originalPrice:  17.61,
    discount:       32,
    rating:         4.4,
    reviews:        5042,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1455582916367-25f75bfc6710?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "gift_sets", "bouquet"]
  },
  {
    id:             'dar-flow-046',
    name:           'Edible Flower Mix — Microgreens',
    category:       'flowers',
    subcategory:    'Fresh',
    price:          43.81,
    originalPrice:  115.3,
    discount:       62,
    rating:         4.8,
    reviews:        5225,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "mix", "fresh", "bouquet"]
  },
  {
    id:             'dar-flow-047',
    name:           'Flower Subscription Box — Monthly',
    category:       'flowers',
    subcategory:    'Dried',
    price:          12.19,
    originalPrice:  27.09,
    discount:       55,
    rating:         4.5,
    reviews:        19038,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1469259943454-aa100abba749?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "box", "dried", "bouquet"]
  },
  {
    id:             'dar-flow-048',
    name:           'Paper Flower Crafting Kit',
    category:       'flowers',
    subcategory:    'Artificial',
    price:          15.88,
    originalPrice:  24.82,
    discount:       36,
    rating:         4.4,
    reviews:        9347,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "kit", "flowers", "plants", "artificial", "bouquet"]
  },
  {
    id:             'dar-flow-049',
    name:           'Autumn Leaf Wreath — Door',
    category:       'flowers',
    subcategory:    'Plants',
    price:          47.36,
    originalPrice:  91.08,
    discount:       48,
    rating:         4.3,
    reviews:        11367,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "wreath", "bouquet"]
  },
  {
    id:             'dar-flow-050',
    name:           'Festive Poinsettia Plant',
    category:       'flowers',
    subcategory:    'Gift Sets',
    price:          11.85,
    originalPrice:  29.63,
    discount:       60,
    rating:         4.1,
    reviews:        12995,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/flowers-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["floral", "flowers", "plants", "gift_sets", "bouquet", "plant"]
  }
);
