/* DARAZ — Home (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-home-001',
    name:           'Bohemian Throw Pillow Covers — Set of 4',
    category:       'home',
    subcategory:    'Furniture',
    price:          75.88,
    originalPrice:  102.54,
    discount:       26,
    rating:         4.7,
    reviews:        6597,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "furniture", "covers", "decor"]
  },
  {
    id:             'dar-home-002',
    name:           'LED Desk Lamp with USB Charging Port',
    category:       'home',
    subcategory:    'Kitchen',
    price:          51.83,
    originalPrice:  117.79,
    discount:       56,
    rating:         5.0,
    reviews:        703,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "port", "decor"]
  },
  {
    id:             'dar-home-003',
    name:           'Non-Stick Cookware Set — 5 Pieces',
    category:       'home',
    subcategory:    'Decor',
    price:          46.56,
    originalPrice:  95.03,
    discount:       51,
    rating:         4.1,
    reviews:        3803,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-004',
    name:           'Aesthetic Bedding Set — King Size',
    category:       'home',
    subcategory:    'Bedding',
    price:          26.75,
    originalPrice:  53.5,
    discount:       50,
    rating:         4.9,
    reviews:        320,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'dar-home-005',
    name:           'Aesthetic Acrylic Desk Organiser Set',
    category:       'home',
    subcategory:    'Lighting',
    price:          48.15,
    originalPrice:  66.88,
    discount:       28,
    rating:         4.4,
    reviews:        16874,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "lighting", "decor"]
  },
  {
    id:             'dar-home-006',
    name:           'Fairy Lights — 10m USB Warm White',
    category:       'home',
    subcategory:    'Storage',
    price:          10.76,
    originalPrice:  23.92,
    discount:       55,
    rating:         4.1,
    reviews:        4726,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["lights", "storage", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-007',
    name:           'Cute Ceramic Mug Set — 2 Pack',
    category:       'home',
    subcategory:    'Furniture',
    price:          38.24,
    originalPrice:  100.62,
    discount:       62,
    rating:         4.1,
    reviews:        23234,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'dar-home-008',
    name:           'Minimalist Wall Clock — Silent Quartz',
    category:       'home',
    subcategory:    'Kitchen',
    price:          27.09,
    originalPrice:  55.29,
    discount:       51,
    rating:         4.3,
    reviews:        19849,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["clock", "kitchen", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-009',
    name:           'LED Strip Lights — 5m RGB Smart',
    category:       'home',
    subcategory:    'Decor',
    price:          52.82,
    originalPrice:  110.05,
    discount:       52,
    rating:         4.8,
    reviews:        3252,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["lights", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-010',
    name:           'Bamboo Bathroom Organiser',
    category:       'home',
    subcategory:    'Bedding',
    price:          67.8,
    originalPrice:  96.86,
    discount:       30,
    rating:         4.7,
    reviews:        21850,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["organiser", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'dar-home-011',
    name:           'Velvet Storage Ottoman Cube',
    category:       'home',
    subcategory:    'Lighting',
    price:          43.94,
    originalPrice:  109.84,
    discount:       60,
    rating:         4.4,
    reviews:        23231,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "lighting", "cube", "decor"]
  },
  {
    id:             'dar-home-012',
    name:           'Woven Seagrass Basket — Large',
    category:       'home',
    subcategory:    'Storage',
    price:          70.46,
    originalPrice:  95.22,
    discount:       26,
    rating:         4.5,
    reviews:        11317,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "basket", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-013',
    name:           'Floating Wall Shelves — Set of 3',
    category:       'home',
    subcategory:    'Furniture',
    price:          52.42,
    originalPrice:  93.61,
    discount:       44,
    rating:         4.7,
    reviews:        19315,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "decor", "interior", "living", "furniture", "shelves"]
  },
  {
    id:             'dar-home-014',
    name:           'Diffuser & Essential Oil Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          44.79,
    originalPrice:  79.98,
    discount:       44,
    rating:         4.6,
    reviews:        7563,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-015',
    name:           'Faux Fur Throw Blanket — Grey',
    category:       'home',
    subcategory:    'Decor',
    price:          43.98,
    originalPrice:  102.28,
    discount:       57,
    rating:         4.6,
    reviews:        19446,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-016',
    name:           'Boho Macramé Wall Hanging',
    category:       'home',
    subcategory:    'Bedding',
    price:          10.37,
    originalPrice:  14.2,
    discount:       27,
    rating:         4.7,
    reviews:        5078,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "hanging", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'dar-home-017',
    name:           'Vintage Table Lamp — Rattan',
    category:       'home',
    subcategory:    'Lighting',
    price:          21.6,
    originalPrice:  49.09,
    discount:       56,
    rating:         4.7,
    reviews:        16974,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "lamp", "lighting", "decor"]
  },
  {
    id:             'dar-home-018',
    name:           'Glass Candle Holder Set',
    category:       'home',
    subcategory:    'Storage',
    price:          48.7,
    originalPrice:  118.77,
    discount:       59,
    rating:         4.6,
    reviews:        24080,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-019',
    name:           'Kitchen Herb Planter — 3 Pots',
    category:       'home',
    subcategory:    'Furniture',
    price:          34.14,
    originalPrice:  48.77,
    discount:       30,
    rating:         4.9,
    reviews:        18663,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "planter", "living", "furniture", "decor"]
  },
  {
    id:             'dar-home-020',
    name:           'Anti-Fatigue Kitchen Mat',
    category:       'home',
    subcategory:    'Kitchen',
    price:          23.68,
    originalPrice:  62.31,
    discount:       62,
    rating:         4.7,
    reviews:        2453,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "mat", "decor"]
  },
  {
    id:             'dar-home-021',
    name:           'Peel & Stick Wallpaper — Botanical',
    category:       'home',
    subcategory:    'Decor',
    price:          32.67,
    originalPrice:  88.31,
    discount:       63,
    rating:         4.1,
    reviews:        22227,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "wallpaper", "decor"]
  },
  {
    id:             'dar-home-022',
    name:           'Smart Plug Power Strip',
    category:       'home',
    subcategory:    'Bedding',
    price:          10.55,
    originalPrice:  28.51,
    discount:       63,
    rating:         4.2,
    reviews:        15512,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "strip", "bedding", "decor"]
  },
  {
    id:             'dar-home-023',
    name:           'Linen Shower Curtain — White',
    category:       'home',
    subcategory:    'Lighting',
    price:          22.69,
    originalPrice:  61.33,
    discount:       63,
    rating:         4.6,
    reviews:        12511,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "curtain", "lighting", "decor"]
  },
  {
    id:             'dar-home-024',
    name:           'Over-Door Towel Rail',
    category:       'home',
    subcategory:    'Storage',
    price:          44.46,
    originalPrice:  92.63,
    discount:       52,
    rating:         4.9,
    reviews:        24724,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "home", "interior", "living", "rail", "decor"]
  },
  {
    id:             'dar-home-025',
    name:           'Plant Pot Set — Pastel Terracotta',
    category:       'home',
    subcategory:    'Furniture',
    price:          61.54,
    originalPrice:  104.3,
    discount:       41,
    rating:         5.0,
    reviews:        21823,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'dar-home-026',
    name:           'Wooden Serving Board',
    category:       'home',
    subcategory:    'Kitchen',
    price:          47.73,
    originalPrice:  61.99,
    discount:       23,
    rating:         4.1,
    reviews:        11665,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "board", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-027',
    name:           'Spice Rack — Rotating Turntable',
    category:       'home',
    subcategory:    'Decor',
    price:          7.5,
    originalPrice:  12.3,
    discount:       39,
    rating:         4.7,
    reviews:        9205,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "rack", "decor"]
  },
  {
    id:             'dar-home-028',
    name:           'Bed Tray Laptop Desk',
    category:       'home',
    subcategory:    'Bedding',
    price:          26.93,
    originalPrice:  33.66,
    discount:       20,
    rating:         4.4,
    reviews:        16661,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "desk", "bedding", "decor"]
  },
  {
    id:             'dar-home-029',
    name:           'Velvet Curtains — Blackout Grey',
    category:       'home',
    subcategory:    'Lighting',
    price:          23.17,
    originalPrice:  42.91,
    discount:       46,
    rating:         4.1,
    reviews:        1662,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "curtains", "lighting", "decor"]
  },
  {
    id:             'dar-home-030',
    name:           'Decorative Wicker Mirror',
    category:       'home',
    subcategory:    'Storage',
    price:          11.81,
    originalPrice:  17.12,
    discount:       31,
    rating:         4.6,
    reviews:        9761,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "home", "interior", "living", "mirror", "decor"]
  },
  {
    id:             'dar-home-031',
    name:           'Stainless Steel Water Bottle — 1L',
    category:       'home',
    subcategory:    'Furniture',
    price:          41.64,
    originalPrice:  71.79,
    discount:       42,
    rating:         4.6,
    reviews:        8403,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "furniture", "bottle", "decor"]
  },
  {
    id:             'dar-home-032',
    name:           'Bamboo Cutting Board Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          65.52,
    originalPrice:  86.21,
    discount:       24,
    rating:         4.4,
    reviews:        9335,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-033',
    name:           'Shower Caddy — 3 Tier',
    category:       'home',
    subcategory:    'Decor',
    price:          35.67,
    originalPrice:  55.73,
    discount:       36,
    rating:         4.7,
    reviews:        751,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "decor", "interior", "living", "caddy"]
  },
  {
    id:             'dar-home-034',
    name:           'Framed Print Wall Art Set',
    category:       'home',
    subcategory:    'Bedding',
    price:          14.15,
    originalPrice:  22.83,
    discount:       38,
    rating:         4.5,
    reviews:        12071,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'dar-home-035',
    name:           'Laundry Basket — Woven Rope',
    category:       'home',
    subcategory:    'Lighting',
    price:          89.55,
    originalPrice:  111.94,
    discount:       20,
    rating:         4.2,
    reviews:        23872,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["basket", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'dar-home-036',
    name:           'Electric Kettle — Rose Gold',
    category:       'home',
    subcategory:    'Storage',
    price:          25.7,
    originalPrice:  64.25,
    discount:       60,
    rating:         4.7,
    reviews:        1224,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "home", "kettle", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-037',
    name:           'Air Fryer — 5.5L Digital',
    category:       'home',
    subcategory:    'Furniture',
    price:          9.22,
    originalPrice:  25.61,
    discount:       64,
    rating:         4.8,
    reviews:        10901,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "furniture", "fryer", "decor"]
  },
  {
    id:             'dar-home-038',
    name:           'Robot Mop & Vacuum Combo',
    category:       'home',
    subcategory:    'Kitchen',
    price:          60.07,
    originalPrice:  107.27,
    discount:       44,
    rating:         4.9,
    reviews:        11696,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "combo", "decor"]
  },
  {
    id:             'dar-home-039',
    name:           'Weighted Blanket — 8kg',
    category:       'home',
    subcategory:    'Decor',
    price:          61.94,
    originalPrice:  108.66,
    discount:       43,
    rating:         4.0,
    reviews:        7573,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-040',
    name:           'Cordless Stick Vacuum',
    category:       'home',
    subcategory:    'Bedding',
    price:          29.31,
    originalPrice:  59.82,
    discount:       51,
    rating:         4.3,
    reviews:        9183,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["vacuum", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'dar-home-041',
    name:           'Under-Bed Storage Boxes',
    category:       'home',
    subcategory:    'Lighting',
    price:          51.56,
    originalPrice:  83.16,
    discount:       38,
    rating:         4.9,
    reviews:        13750,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["boxes", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'dar-home-042',
    name:           'Memory Foam Pillow — Contour',
    category:       'home',
    subcategory:    'Storage',
    price:          12.51,
    originalPrice:  20.85,
    discount:       40,
    rating:         4.8,
    reviews:        3979,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "pillow", "home", "interior", "living", "decor"]
  },
  {
    id:             'dar-home-043',
    name:           'Ceramic Dinner Set — 16 Piece',
    category:       'home',
    subcategory:    'Furniture',
    price:          71.72,
    originalPrice:  119.54,
    discount:       40,
    rating:         5.0,
    reviews:        4840,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'dar-home-044',
    name:           'Knife Block Set — 7 Piece',
    category:       'home',
    subcategory:    'Kitchen',
    price:          34.19,
    originalPrice:  55.14,
    discount:       38,
    rating:         4.7,
    reviews:        24222,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-045',
    name:           'Bath Mat Set — Non-Slip',
    category:       'home',
    subcategory:    'Decor',
    price:          60.86,
    originalPrice:  108.68,
    discount:       44,
    rating:         4.3,
    reviews:        10746,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'dar-home-046',
    name:           'Smart Colour Bulb Set — 4 Pack',
    category:       'home',
    subcategory:    'Bedding',
    price:          88.13,
    originalPrice:  119.09,
    discount:       26,
    rating:         4.7,
    reviews:        6565,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'dar-home-047',
    name:           'Blackout Roller Blind',
    category:       'home',
    subcategory:    'Lighting',
    price:          73.44,
    originalPrice:  116.57,
    discount:       37,
    rating:         4.4,
    reviews:        4616,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["home", "interior", "living", "lighting", "blind", "decor"]
  },
  {
    id:             'dar-home-048',
    name:           'Essential Oil Diffuser — Ultrasonic',
    category:       'home',
    subcategory:    'Storage',
    price:          47.14,
    originalPrice:  76.04,
    discount:       38,
    rating:         4.1,
    reviews:        17491,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["storage", "home", "interior", "living", "diffuser", "decor"]
  },
  {
    id:             'dar-home-049',
    name:           'Handheld Garment Steamer',
    category:       'home',
    subcategory:    'Furniture',
    price:          49.44,
    originalPrice:  93.28,
    discount:       47,
    rating:         4.9,
    reviews:        18522,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["steamer", "home", "interior", "living", "furniture", "decor"]
  },
  {
    id:             'dar-home-050',
    name:           'Kitchen Towel Set — Cotton',
    category:       'home',
    subcategory:    'Kitchen',
    price:          25.38,
    originalPrice:  35.25,
    discount:       28,
    rating:         4.1,
    reviews:        12926,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/home-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  }
);
