/* DARAZ — Jewelry (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-jewe-001',
    name:           '925 Silver Minimalist Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          23.48,
    originalPrice:  46.97,
    discount:       50,
    rating:         4.4,
    reviews:        21098,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-002',
    name:           'Dainty Layered Gold Chain Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          78.65,
    originalPrice:  107.74,
    discount:       27,
    rating:         4.3,
    reviews:        10607,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-003',
    name:           'Gold Plated Jhumka Earrings Set',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          27.03,
    originalPrice:  48.27,
    discount:       44,
    rating:         4.2,
    reviews:        23562,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'dar-jewe-004',
    name:           'Stacking Rings Set — 10 Piece',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          13.39,
    originalPrice:  38.25,
    discount:       65,
    rating:         4.3,
    reviews:        20036,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'dar-jewe-005',
    name:           'Pearl Stud Earrings — Classic',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          42.68,
    originalPrice:  74.88,
    discount:       43,
    rating:         4.4,
    reviews:        17675,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-006',
    name:           'Statement Hoop Earrings — Gold',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          16.58,
    originalPrice:  40.45,
    discount:       59,
    rating:         4.2,
    reviews:        19868,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-007',
    name:           'Crystal Tennis Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          62.27,
    originalPrice:  111.2,
    discount:       44,
    rating:         4.6,
    reviews:        1776,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-008',
    name:           'Vintage Cameo Brooch',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          40.69,
    originalPrice:  73.99,
    discount:       45,
    rating:         4.2,
    reviews:        4733,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "brooch", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'dar-jewe-009',
    name:           'Turquoise Beaded Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          63.56,
    originalPrice:  90.8,
    discount:       30,
    rating:         4.3,
    reviews:        11779,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-010',
    name:           'Anklet Set — Gold Chain',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          8.44,
    originalPrice:  24.11,
    discount:       65,
    rating:         4.8,
    reviews:        22719,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'dar-jewe-011',
    name:           'Heart Locket Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          35.15,
    originalPrice:  87.88,
    discount:       60,
    rating:         4.5,
    reviews:        19162,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-012',
    name:           'Evil Eye Charm Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          8.79,
    originalPrice:  16.91,
    discount:       48,
    rating:         4.4,
    reviews:        18012,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-013',
    name:           'Opal Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          57.22,
    originalPrice:  78.39,
    discount:       27,
    rating:         4.7,
    reviews:        13131,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-014',
    name:           'Rose Gold Infinity Bracelet',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          61.06,
    originalPrice:  81.42,
    discount:       25,
    rating:         4.4,
    reviews:        12374,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-015',
    name:           'Diamond CZ Stud Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          59.7,
    originalPrice:  90.45,
    discount:       34,
    rating:         4.3,
    reviews:        21142,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-016',
    name:           'Name Initial Letter Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          33.52,
    originalPrice:  42.98,
    discount:       22,
    rating:         4.1,
    reviews:        8209,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-017',
    name:           'Geometric Triangle Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          10.51,
    originalPrice:  16.95,
    discount:       38,
    rating:         4.6,
    reviews:        2701,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-018',
    name:           'Twisted Bangle Set — 5 Pack',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          13.73,
    originalPrice:  28.03,
    discount:       51,
    rating:         4.1,
    reviews:        21902,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'dar-jewe-019',
    name:           'Floral Hair Pins Set',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          41.93,
    originalPrice:  69.88,
    discount:       40,
    rating:         4.0,
    reviews:        24064,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'dar-jewe-020',
    name:           'Moon & Stars Choker',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          13.75,
    originalPrice:  22.54,
    discount:       39,
    rating:         5.0,
    reviews:        10893,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["choker", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-021',
    name:           'Cluster Ring — Pink Tourmaline CZ',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          64.01,
    originalPrice:  84.22,
    discount:       24,
    rating:         4.8,
    reviews:        2516,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["ring", "accessories", "necklaces", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-022',
    name:           'Tassel Drop Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          33.42,
    originalPrice:  43.98,
    discount:       24,
    rating:         4.7,
    reviews:        3254,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-023',
    name:           'Layered Satellite Necklace',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          51.66,
    originalPrice:  82.0,
    discount:       37,
    rating:         4.9,
    reviews:        7682,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "jewelry", "necklace", "earrings", "gold"]
  },
  {
    id:             'dar-jewe-024',
    name:           'Charm Bracelet — Starter',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          52.89,
    originalPrice:  97.95,
    discount:       46,
    rating:         4.1,
    reviews:        20562,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-025',
    name:           'Bar Pendant Necklace — Engraved',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          34.98,
    originalPrice:  81.36,
    discount:       57,
    rating:         4.6,
    reviews:        23578,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-026',
    name:           'Snake Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          55.18,
    originalPrice:  95.13,
    discount:       42,
    rating:         4.6,
    reviews:        5163,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-027',
    name:           'Vintage Pearl Necklace — Multi-Strand',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          29.16,
    originalPrice:  48.6,
    discount:       40,
    rating:         4.4,
    reviews:        6912,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-028',
    name:           'Leaf Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          18.24,
    originalPrice:  39.66,
    discount:       54,
    rating:         4.7,
    reviews:        22358,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-029',
    name:           'Birthstone Ring — Personalised',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          28.41,
    originalPrice:  41.17,
    discount:       31,
    rating:         4.7,
    reviews:        5980,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-030',
    name:           'Celestial Sun Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          39.78,
    originalPrice:  63.15,
    discount:       37,
    rating:         4.0,
    reviews:        6173,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-031',
    name:           'Crystal Choker Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          28.81,
    originalPrice:  73.88,
    discount:       61,
    rating:         4.9,
    reviews:        436,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-032',
    name:           'Emerald CZ Cocktail Ring',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          49.51,
    originalPrice:  67.82,
    discount:       27,
    rating:         4.1,
    reviews:        10440,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-033',
    name:           'Gold Hoop Set — 3 Pairs',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          39.69,
    originalPrice:  59.24,
    discount:       33,
    rating:         4.7,
    reviews:        19947,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'dar-jewe-034',
    name:           'Cuff Bangle — Hammered Gold',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          73.5,
    originalPrice:  98.0,
    discount:       25,
    rating:         4.2,
    reviews:        12347,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "bangle", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-035',
    name:           'Seed Bead Friendship Bracelet',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          57.46,
    originalPrice:  100.8,
    discount:       43,
    rating:         4.3,
    reviews:        23192,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-036',
    name:           'Safety Pin Earrings',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          8.93,
    originalPrice:  17.51,
    discount:       49,
    rating:         4.7,
    reviews:        3262,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-037',
    name:           'Mismatched Statement Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          74.36,
    originalPrice:  109.36,
    discount:       32,
    rating:         4.9,
    reviews:        15859,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-038',
    name:           'Charm Bangle — Pandora Style',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          39.02,
    originalPrice:  48.77,
    discount:       20,
    rating:         5.0,
    reviews:        6551,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "bangle", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'dar-jewe-039',
    name:           'Blue Topaz Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          29.43,
    originalPrice:  50.74,
    discount:       42,
    rating:         4.8,
    reviews:        17354,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-040',
    name:           'Stud Earrings Gift Set',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          38.54,
    originalPrice:  48.17,
    discount:       20,
    rating:         4.8,
    reviews:        2898,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'dar-jewe-041',
    name:           'Ear Cuff — No Piercing Required',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          50.1,
    originalPrice:  69.59,
    discount:       28,
    rating:         4.9,
    reviews:        15850,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "cuff", "gold"]
  },
  {
    id:             'dar-jewe-042',
    name:           'Link Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          11.54,
    originalPrice:  31.19,
    discount:       63,
    rating:         4.2,
    reviews:        5148,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'dar-jewe-043',
    name:           'Freshwater Pearl Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          29.32,
    originalPrice:  68.18,
    discount:       57,
    rating:         4.8,
    reviews:        1755,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-044',
    name:           'Crystal Headband — Bridal',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          9.6,
    originalPrice:  13.92,
    discount:       31,
    rating:         4.1,
    reviews:        2412,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "headband", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-045',
    name:           'Vintage Art Deco Ring',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          48.32,
    originalPrice:  81.89,
    discount:       41,
    rating:         4.5,
    reviews:        11208,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["ring", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-046',
    name:           'Flower Stud Earrings — Enamel',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          24.19,
    originalPrice:  58.99,
    discount:       59,
    rating:         4.9,
    reviews:        15939,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-047',
    name:           'Rhinestone Bib Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          11.76,
    originalPrice:  16.11,
    discount:       27,
    rating:         5.0,
    reviews:        20149,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-048',
    name:           'Asymmetric Dangle Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          29.08,
    originalPrice:  70.92,
    discount:       59,
    rating:         4.8,
    reviews:        19858,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'dar-jewe-049',
    name:           'Gold Plated Coin Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          56.25,
    originalPrice:  90.72,
    discount:       38,
    rating:         4.2,
    reviews:        15206,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'dar-jewe-050',
    name:           'Stackable Thin Band Rings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          15.39,
    originalPrice:  34.98,
    discount:       56,
    rating:         5.0,
    reviews:        11470,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/jewelry-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["rings", "accessories", "anklets", "silver", "jewelry", "gold"]
  }
);
