/* DARAZ — Pets (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-pets-001',
    name:           'Multi-Level Cat Tree with Scratching Post',
    category:       'pets',
    subcategory:    'Dogs',
    price:          50.16,
    originalPrice:  109.04,
    discount:       54,
    rating:         4.4,
    reviews:        10246,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "post", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-002',
    name:           'Cosy Self-Warming Pet Bed — L Size',
    category:       'pets',
    subcategory:    'Cats',
    price:          50.93,
    originalPrice:  94.31,
    discount:       46,
    rating:         4.0,
    reviews:        24070,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "bed", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-003',
    name:           'Interactive Cat Feather Wand Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          29.82,
    originalPrice:  48.88,
    discount:       39,
    rating:         4.8,
    reviews:        3759,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'dar-pets-004',
    name:           'Premium Cat Food — Chicken & Fish 2kg',
    category:       'pets',
    subcategory:    'Fish',
    price:          26.16,
    originalPrice:  59.46,
    discount:       56,
    rating:         4.2,
    reviews:        17734,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "food", "fish", "cat", "animal"]
  },
  {
    id:             'dar-pets-005',
    name:           'GPS Dog Collar Tracker',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          58.68,
    originalPrice:  83.83,
    discount:       30,
    rating:         4.1,
    reviews:        21665,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tracker", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-006',
    name:           'Automatic Pet Feeder — WiFi',
    category:       'pets',
    subcategory:    'Supplies',
    price:          57.81,
    originalPrice:  85.02,
    discount:       32,
    rating:         4.9,
    reviews:        9969,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["feeder", "pets", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'dar-pets-007',
    name:           'Foldable Dog Travel Crate',
    category:       'pets',
    subcategory:    'Dogs',
    price:          7.3,
    originalPrice:  20.27,
    discount:       64,
    rating:         4.7,
    reviews:        21136,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "dogs", "crate", "cat", "animal"]
  },
  {
    id:             'dar-pets-008',
    name:           'Dog Grooming Kit — 5 Piece',
    category:       'pets',
    subcategory:    'Cats',
    price:          83.23,
    originalPrice:  104.04,
    discount:       20,
    rating:         4.4,
    reviews:        17191,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "kit", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-009',
    name:           'Catnip Plush Mouse Toy Set',
    category:       'pets',
    subcategory:    'Birds',
    price:          36.19,
    originalPrice:  82.24,
    discount:       56,
    rating:         4.2,
    reviews:        3466,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "birds", "set", "cat", "animal"]
  },
  {
    id:             'dar-pets-010',
    name:           'Slow Feeder Dog Bowl',
    category:       'pets',
    subcategory:    'Fish',
    price:          28.5,
    originalPrice:  38.0,
    discount:       25,
    rating:         5.0,
    reviews:        20771,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "animal", "fish", "cat", "bowl"]
  },
  {
    id:             'dar-pets-011',
    name:           'Cat Litter Box — Top Entry',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          15.09,
    originalPrice:  30.18,
    discount:       50,
    rating:         4.7,
    reviews:        18248,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-012',
    name:           'Dog Raincoat — Waterproof',
    category:       'pets',
    subcategory:    'Supplies',
    price:          24.44,
    originalPrice:  61.11,
    discount:       60,
    rating:         4.5,
    reviews:        17679,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "supplies", "raincoat", "cat", "animal"]
  },
  {
    id:             'dar-pets-013',
    name:           'Bird Cage Deluxe — 2 Storey',
    category:       'pets',
    subcategory:    'Dogs',
    price:          42.98,
    originalPrice:  93.44,
    discount:       54,
    rating:         4.9,
    reviews:        13704,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "dogs", "deluxe", "cat", "animal"]
  },
  {
    id:             'dar-pets-014',
    name:           'Aquarium LED Light — 30cm',
    category:       'pets',
    subcategory:    'Cats',
    price:          28.36,
    originalPrice:  39.39,
    discount:       28,
    rating:         4.7,
    reviews:        14402,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "light", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-015',
    name:           'Hamster Exercise Wheel — Silent',
    category:       'pets',
    subcategory:    'Birds',
    price:          34.96,
    originalPrice:  53.79,
    discount:       35,
    rating:         4.1,
    reviews:        1128,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "wheel", "birds", "cat", "animal"]
  },
  {
    id:             'dar-pets-016',
    name:           'Puppy Training Pads — 100pk',
    category:       'pets',
    subcategory:    'Fish',
    price:          39.33,
    originalPrice:  91.46,
    discount:       57,
    rating:         4.8,
    reviews:        2957,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "pads", "fish", "cat", "animal"]
  },
  {
    id:             'dar-pets-017',
    name:           'Self-Cleaning Litter Box',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          41.01,
    originalPrice:  78.87,
    discount:       48,
    rating:         5.0,
    reviews:        1335,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-018',
    name:           'Orthopedic Dog Bed — Memory Foam',
    category:       'pets',
    subcategory:    'Supplies',
    price:          59.79,
    originalPrice:  119.58,
    discount:       50,
    rating:         4.3,
    reviews:        13338,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "bed", "supplies", "cat", "animal"]
  },
  {
    id:             'dar-pets-019',
    name:           'Cat Window Perch — Suction Cup',
    category:       'pets',
    subcategory:    'Dogs',
    price:          30.26,
    originalPrice:  38.8,
    discount:       22,
    rating:         4.4,
    reviews:        3033,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "perch", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-020',
    name:           'Retractable Dog Lead — 5m',
    category:       'pets',
    subcategory:    'Cats',
    price:          62.53,
    originalPrice:  91.95,
    discount:       32,
    rating:         4.5,
    reviews:        20480,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "lead", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-021',
    name:           'Pet Carrier Backpack — Breathable',
    category:       'pets',
    subcategory:    'Birds',
    price:          26.25,
    originalPrice:  40.38,
    discount:       35,
    rating:         4.1,
    reviews:        8214,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "birds", "backpack", "cat", "animal"]
  },
  {
    id:             'dar-pets-022',
    name:           'Cat Drinking Fountain — Filtered',
    category:       'pets',
    subcategory:    'Fish',
    price:          36.27,
    originalPrice:  103.63,
    discount:       65,
    rating:         4.1,
    reviews:        5924,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "fountain", "fish", "cat", "animal"]
  },
  {
    id:             'dar-pets-023',
    name:           'Dog Puzzle Toy — IQ Level 2',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          77.94,
    originalPrice:  119.91,
    discount:       35,
    rating:         4.4,
    reviews:        14765,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "small_pets", "toy", "cat", "animal"]
  },
  {
    id:             'dar-pets-024',
    name:           'Plush Squeaky Dog Toy Set',
    category:       'pets',
    subcategory:    'Supplies',
    price:          25.77,
    originalPrice:  71.58,
    discount:       64,
    rating:         4.6,
    reviews:        9235,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "supplies", "set", "cat", "animal"]
  },
  {
    id:             'dar-pets-025',
    name:           'Flea & Tick Collar',
    category:       'pets',
    subcategory:    'Dogs',
    price:          22.05,
    originalPrice:  42.41,
    discount:       48,
    rating:         4.4,
    reviews:        5269,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "collar", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-026',
    name:           'Dental Chews — 30 Pack',
    category:       'pets',
    subcategory:    'Cats',
    price:          9.7,
    originalPrice:  13.47,
    discount:       28,
    rating:         4.8,
    reviews:        13301,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "chews", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-027',
    name:           'Heated Cat Cave Bed',
    category:       'pets',
    subcategory:    'Birds',
    price:          32.36,
    originalPrice:  43.73,
    discount:       26,
    rating:         4.7,
    reviews:        21592,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "bed", "birds", "cat", "animal"]
  },
  {
    id:             'dar-pets-028',
    name:           'Dog Cooling Mat — Gel',
    category:       'pets',
    subcategory:    'Fish',
    price:          35.68,
    originalPrice:  91.48,
    discount:       61,
    rating:         4.3,
    reviews:        6133,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "fish", "mat", "cat", "animal"]
  },
  {
    id:             'dar-pets-029',
    name:           'Pet Stroller — 3 Wheeler',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          66.5,
    originalPrice:  112.72,
    discount:       41,
    rating:         4.7,
    reviews:        20842,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "small_pets", "stroller", "cat", "animal"]
  },
  {
    id:             'dar-pets-030',
    name:           'Rabbit Hutch — 2 Storey',
    category:       'pets',
    subcategory:    'Supplies',
    price:          6.56,
    originalPrice:  13.96,
    discount:       53,
    rating:         4.6,
    reviews:        15478,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "hutch", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'dar-pets-031',
    name:           'Fish Tank Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          50.63,
    originalPrice:  101.26,
    discount:       50,
    rating:         4.5,
    reviews:        17038,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-032',
    name:           'Cat Scratching Pad — Cardboard',
    category:       'pets',
    subcategory:    'Cats',
    price:          16.84,
    originalPrice:  23.07,
    discount:       27,
    rating:         4.2,
    reviews:        4227,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "pad", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-033',
    name:           'Interactive Laser Cat Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          24.18,
    originalPrice:  60.45,
    discount:       60,
    rating:         4.9,
    reviews:        3638,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'dar-pets-034',
    name:           'Dog Harness — No-Pull',
    category:       'pets',
    subcategory:    'Fish',
    price:          64.95,
    originalPrice:  84.35,
    discount:       23,
    rating:         4.7,
    reviews:        6769,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "harness", "fish", "cat", "animal"]
  },
  {
    id:             'dar-pets-035',
    name:           'Pet Camera Monitor',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          29.22,
    originalPrice:  60.87,
    discount:       52,
    rating:         4.5,
    reviews:        24846,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "monitor", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-036',
    name:           'Small Animal Hideout Tunnel',
    category:       'pets',
    subcategory:    'Supplies',
    price:          37.02,
    originalPrice:  46.28,
    discount:       20,
    rating:         4.3,
    reviews:        4987,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "supplies", "tunnel", "cat", "animal"]
  },
  {
    id:             'dar-pets-037',
    name:           'Bird Seed Mix — Premium',
    category:       'pets',
    subcategory:    'Dogs',
    price:          14.72,
    originalPrice:  18.63,
    discount:       21,
    rating:         4.7,
    reviews:        19013,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "mix", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-038',
    name:           'Dog Raincoat — Reflective',
    category:       'pets',
    subcategory:    'Cats',
    price:          68.24,
    originalPrice:  93.48,
    discount:       27,
    rating:         4.3,
    reviews:        20668,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "raincoat", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-039',
    name:           'Cat Toy Ball Track',
    category:       'pets',
    subcategory:    'Birds',
    price:          47.27,
    originalPrice:  72.73,
    discount:       35,
    rating:         4.3,
    reviews:        9898,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "track", "birds", "cat", "animal"]
  },
  {
    id:             'dar-pets-040',
    name:           'Dog Agility Training Set',
    category:       'pets',
    subcategory:    'Fish',
    price:          39.26,
    originalPrice:  51.66,
    discount:       24,
    rating:         4.3,
    reviews:        20824,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "set", "fish", "cat", "animal"]
  },
  {
    id:             'dar-pets-041',
    name:           'Pet First Aid Kit',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          13.22,
    originalPrice:  22.4,
    discount:       41,
    rating:         4.4,
    reviews:        23668,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "kit", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-042',
    name:           'Catnip Spray — Organic',
    category:       'pets',
    subcategory:    'Supplies',
    price:          14.66,
    originalPrice:  30.54,
    discount:       52,
    rating:         4.4,
    reviews:        16799,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "supplies", "spray", "cat", "animal"]
  },
  {
    id:             'dar-pets-043',
    name:           'Dog Snuffle Mat',
    category:       'pets',
    subcategory:    'Dogs',
    price:          66.55,
    originalPrice:  95.07,
    discount:       30,
    rating:         4.7,
    reviews:        13546,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "dogs", "mat", "cat", "animal"]
  },
  {
    id:             'dar-pets-044',
    name:           'Silicone Pet Food Mat',
    category:       'pets',
    subcategory:    'Cats',
    price:          9.18,
    originalPrice:  19.95,
    discount:       54,
    rating:         4.7,
    reviews:        8811,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "mat", "cat", "animal", "cats"]
  },
  {
    id:             'dar-pets-045',
    name:           'Pet Nail Grinder — Quiet',
    category:       'pets',
    subcategory:    'Birds',
    price:          40.56,
    originalPrice:  58.78,
    discount:       31,
    rating:         4.1,
    reviews:        17762,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "birds", "grinder", "cat", "animal"]
  },
  {
    id:             'dar-pets-046',
    name:           'Bird Perch Stand',
    category:       'pets',
    subcategory:    'Fish',
    price:          57.55,
    originalPrice:  91.35,
    discount:       37,
    rating:         4.9,
    reviews:        13902,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "fish", "stand", "cat", "animal"]
  },
  {
    id:             'dar-pets-047',
    name:           'Dog Life Jacket',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          55.36,
    originalPrice:  104.45,
    discount:       47,
    rating:         4.6,
    reviews:        2500,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["jacket", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'dar-pets-048',
    name:           'Cat Collar with Bell',
    category:       'pets',
    subcategory:    'Supplies',
    price:          44.47,
    originalPrice:  76.67,
    discount:       42,
    rating:         4.0,
    reviews:        21360,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "supplies", "bell", "cat", "animal"]
  },
  {
    id:             'dar-pets-049',
    name:           'Kitten Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          80.58,
    originalPrice:  103.31,
    discount:       22,
    rating:         4.7,
    reviews:        24638,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'dar-pets-050',
    name:           'Puppy Welcome Home Set',
    category:       'pets',
    subcategory:    'Cats',
    price:          34.09,
    originalPrice:  61.98,
    discount:       45,
    rating:         4.0,
    reviews:        400,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/pets-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["pets", "dog", "set", "cat", "animal", "cats"]
  }
);
