/* DARAZ — Shoes (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-shoe-001',
    name:           'Women\'s Platform Sneakers — White',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          62.99,
    originalPrice:  95.44,
    discount:       34,
    rating:         4.0,
    reviews:        507,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'dar-shoe-002',
    name:           'Chunky Platform Loafers — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          43.94,
    originalPrice:  72.03,
    discount:       39,
    rating:         4.7,
    reviews:        13498,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes"]
  },
  {
    id:             'dar-shoe-003',
    name:           'Men\'s Casual Sneakers — White',
    category:       'shoes',
    subcategory:    'Flats',
    price:          33.51,
    originalPrice:  81.72,
    discount:       59,
    rating:         4.1,
    reviews:        14840,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'dar-shoe-004',
    name:           'Ankle Strap Block Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          9.4,
    originalPrice:  26.11,
    discount:       64,
    rating:         4.1,
    reviews:        1276,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-005',
    name:           'Bata Comfort Sandals — Women\'s',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          48.0,
    originalPrice:  66.67,
    discount:       28,
    rating:         5.0,
    reviews:        11114,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-006',
    name:           'Chelsea Boots — Tan Leather',
    category:       'shoes',
    subcategory:    'Sport',
    price:          78.21,
    originalPrice:  105.69,
    discount:       26,
    rating:         4.6,
    reviews:        17042,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-007',
    name:           'High Top Canvas Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          35.97,
    originalPrice:  92.22,
    discount:       61,
    rating:         4.9,
    reviews:        14207,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'dar-shoe-008',
    name:           'Stiletto Heeled Mules',
    category:       'shoes',
    subcategory:    'Heels',
    price:          14.53,
    originalPrice:  41.52,
    discount:       65,
    rating:         4.1,
    reviews:        11040,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'dar-shoe-009',
    name:           'Running Trainers — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          27.43,
    originalPrice:  65.3,
    discount:       58,
    rating:         5.0,
    reviews:        19507,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'dar-shoe-010',
    name:           'Strappy Kitten Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          45.71,
    originalPrice:  57.86,
    discount:       21,
    rating:         4.5,
    reviews:        3127,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-011',
    name:           'Slip-On Loafers — Suede',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          20.16,
    originalPrice:  29.64,
    discount:       32,
    rating:         4.4,
    reviews:        4192,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-012',
    name:           'Combat Boots — Lace Up',
    category:       'shoes',
    subcategory:    'Sport',
    price:          32.47,
    originalPrice:  87.77,
    discount:       63,
    rating:         4.4,
    reviews:        22072,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-013',
    name:           'Wedge Espadrilles — Nude',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          72.96,
    originalPrice:  101.33,
    discount:       28,
    rating:         4.3,
    reviews:        8152,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'dar-shoe-014',
    name:           'Pointed Toe Pumps — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          89.05,
    originalPrice:  118.73,
    discount:       25,
    rating:         4.1,
    reviews:        8581,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "pumps"]
  },
  {
    id:             'dar-shoe-015',
    name:           'Kids\' Light-Up Trainers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          27.29,
    originalPrice:  41.99,
    discount:       35,
    rating:         4.4,
    reviews:        19701,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'dar-shoe-016',
    name:           'Hiking Boots — Waterproof',
    category:       'shoes',
    subcategory:    'Boots',
    price:          14.3,
    originalPrice:  23.84,
    discount:       40,
    rating:         4.6,
    reviews:        5349,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-017',
    name:           'Ballet Flats — Blush Pink',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          21.79,
    originalPrice:  44.47,
    discount:       51,
    rating:         4.5,
    reviews:        13460,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-018',
    name:           'Over-Knee Boots — Tan',
    category:       'shoes',
    subcategory:    'Sport',
    price:          51.08,
    originalPrice:  116.08,
    discount:       56,
    rating:         4.4,
    reviews:        3764,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-019',
    name:           'Knit Sock Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          43.16,
    originalPrice:  70.76,
    discount:       39,
    rating:         4.2,
    reviews:        15988,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'dar-shoe-020',
    name:           'T-Bar Mary Jane Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          17.6,
    originalPrice:  43.99,
    discount:       60,
    rating:         4.9,
    reviews:        2791,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'dar-shoe-021',
    name:           'Kids\' Wellies — Polka Dot',
    category:       'shoes',
    subcategory:    'Flats',
    price:          56.6,
    originalPrice:  73.51,
    discount:       23,
    rating:         4.3,
    reviews:        18996,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "wellies", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'dar-shoe-022',
    name:           'Slingback Kitten Heels',
    category:       'shoes',
    subcategory:    'Boots',
    price:          34.11,
    originalPrice:  63.16,
    discount:       46,
    rating:         4.5,
    reviews:        14892,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-023',
    name:           'Square-Toe Mules — Croc Effect',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          6.18,
    originalPrice:  17.16,
    discount:       64,
    rating:         4.2,
    reviews:        9143,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-024',
    name:           'Gladiator Sandals',
    category:       'shoes',
    subcategory:    'Sport',
    price:          46.57,
    originalPrice:  75.11,
    discount:       38,
    rating:         4.8,
    reviews:        5987,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-025',
    name:           'Ankle Boots — Stacked Heel',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          53.42,
    originalPrice:  113.66,
    discount:       53,
    rating:         4.3,
    reviews:        19202,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-026',
    name:           'Velvet Court Shoes — Emerald',
    category:       'shoes',
    subcategory:    'Heels',
    price:          34.41,
    originalPrice:  83.93,
    discount:       59,
    rating:         4.4,
    reviews:        23494,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'dar-shoe-027',
    name:           'Flip Flops — Foam',
    category:       'shoes',
    subcategory:    'Flats',
    price:          40.12,
    originalPrice:  50.15,
    discount:       20,
    rating:         5.0,
    reviews:        6096,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "flops", "shoes"]
  },
  {
    id:             'dar-shoe-028',
    name:           'Lace-Up Oxford Brogues',
    category:       'shoes',
    subcategory:    'Boots',
    price:          39.83,
    originalPrice:  68.67,
    discount:       42,
    rating:         4.2,
    reviews:        3988,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "brogues", "shoes"]
  },
  {
    id:             'dar-shoe-029',
    name:           'Metallic Strappy Heels',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          30.22,
    originalPrice:  39.76,
    discount:       24,
    rating:         4.1,
    reviews:        9188,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-030',
    name:           'Platform Chelsea Boots',
    category:       'shoes',
    subcategory:    'Sport',
    price:          42.12,
    originalPrice:  84.24,
    discount:       50,
    rating:         4.5,
    reviews:        14213,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-031',
    name:           'Open-Toe Wedge Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          46.8,
    originalPrice:  111.42,
    discount:       58,
    rating:         4.7,
    reviews:        557,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-032',
    name:           'Moccasin Slippers',
    category:       'shoes',
    subcategory:    'Heels',
    price:          34.8,
    originalPrice:  80.93,
    discount:       57,
    rating:         4.1,
    reviews:        1450,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "slippers", "footwear", "heels", "shoes"]
  },
  {
    id:             'dar-shoe-033',
    name:           'Sporty Slides — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          93.25,
    originalPrice:  118.04,
    discount:       21,
    rating:         4.6,
    reviews:        23959,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "slides", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'dar-shoe-034',
    name:           'Peep-Toe Slingbacks',
    category:       'shoes',
    subcategory:    'Boots',
    price:          29.54,
    originalPrice:  68.69,
    discount:       57,
    rating:         4.6,
    reviews:        4631,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "slingbacks"]
  },
  {
    id:             'dar-shoe-035',
    name:           'Classic White Tennis Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          16.26,
    originalPrice:  31.88,
    discount:       49,
    rating:         4.9,
    reviews:        8609,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-036',
    name:           'Dad Trainer — Chunky',
    category:       'shoes',
    subcategory:    'Sport',
    price:          78.39,
    originalPrice:  105.93,
    discount:       26,
    rating:         4.9,
    reviews:        14971,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "trainer", "sport", "shoes"]
  },
  {
    id:             'dar-shoe-037',
    name:           'Espadrille Wedge Mules',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          22.18,
    originalPrice:  45.27,
    discount:       51,
    rating:         4.8,
    reviews:        2547,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'dar-shoe-038',
    name:           'Patent Ankle Strap Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          39.59,
    originalPrice:  96.57,
    discount:       59,
    rating:         4.8,
    reviews:        24493,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'dar-shoe-039',
    name:           'Knee High Flat Boots',
    category:       'shoes',
    subcategory:    'Flats',
    price:          31.38,
    originalPrice:  48.27,
    discount:       35,
    rating:         4.1,
    reviews:        5880,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-040',
    name:           'Woven Mule Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          46.58,
    originalPrice:  119.44,
    discount:       61,
    rating:         4.3,
    reviews:        677,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-041',
    name:           'Men\'s Derby Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          18.85,
    originalPrice:  33.66,
    discount:       44,
    rating:         4.4,
    reviews:        8018,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-042',
    name:           'Snow Boots — Fur Lined',
    category:       'shoes',
    subcategory:    'Sport',
    price:          33.04,
    originalPrice:  82.61,
    discount:       60,
    rating:         5.0,
    reviews:        5626,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'dar-shoe-043',
    name:           'Transparent Heeled Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          72.37,
    originalPrice:  103.38,
    discount:       30,
    rating:         4.9,
    reviews:        19070,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-044',
    name:           'Slip-On Canvas Espadrilles',
    category:       'shoes',
    subcategory:    'Heels',
    price:          19.16,
    originalPrice:  26.98,
    discount:       29,
    rating:         4.7,
    reviews:        13957,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'dar-shoe-045',
    name:           'Low Top Leather Sneakers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          47.36,
    originalPrice:  89.36,
    discount:       47,
    rating:         4.6,
    reviews:        10624,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'dar-shoe-046',
    name:           'Platform Flip Flop Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          11.84,
    originalPrice:  21.15,
    discount:       44,
    rating:         4.9,
    reviews:        20808,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-047',
    name:           'Ankle Boots — Pointed Toe',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          47.54,
    originalPrice:  69.91,
    discount:       32,
    rating:         4.5,
    reviews:        4521,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'dar-shoe-048',
    name:           'Sporty Slides — Women\'s',
    category:       'shoes',
    subcategory:    'Sport',
    price:          17.06,
    originalPrice:  21.87,
    discount:       22,
    rating:         4.4,
    reviews:        12994,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["sneakers", "slides", "footwear", "heels", "sport", "shoes"]
  },
  {
    id:             'dar-shoe-049',
    name:           'Men\'s Boat Shoes — Tan',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          52.75,
    originalPrice:  71.28,
    discount:       26,
    rating:         4.7,
    reviews:        5256,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'dar-shoe-050',
    name:           'Kids\' School Shoes — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          9.64,
    originalPrice:  20.95,
    discount:       54,
    rating:         4.5,
    reviews:        10974,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/shoes-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  }
);
