/* DARAZ — Toys (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-toys-001',
    name:           'STEM Building Blocks Set — 250 Pieces',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          38.06,
    originalPrice:  95.14,
    discount:       60,
    rating:         4.1,
    reviews:        2105,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'dar-toys-002',
    name:           'Remote Control Car — Off-Road 4WD',
    category:       'toys',
    subcategory:    'Board Games',
    price:          83.67,
    originalPrice:  105.91,
    discount:       21,
    rating:         4.6,
    reviews:        12980,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "car", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-003',
    name:           'Diamond Painting Kit — Beginner',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          40.24,
    originalPrice:  95.81,
    discount:       58,
    rating:         4.0,
    reviews:        22462,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'dar-toys-004',
    name:           'Magnetic Drawing Board',
    category:       'toys',
    subcategory:    'Educational',
    price:          46.28,
    originalPrice:  92.56,
    discount:       50,
    rating:         4.7,
    reviews:        24164,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "board", "toys", "educational", "play"]
  },
  {
    id:             'dar-toys-005',
    name:           'Wooden Balance Bike — 3-6 Years',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          82.47,
    originalPrice:  117.81,
    discount:       30,
    rating:         4.8,
    reviews:        20266,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "bike"]
  },
  {
    id:             'dar-toys-006',
    name:           'Interactive Robot Toy',
    category:       'toys',
    subcategory:    'STEM',
    price:          43.38,
    originalPrice:  81.84,
    discount:       47,
    rating:         4.3,
    reviews:        5869,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "toy", "stem"]
  },
  {
    id:             'dar-toys-007',
    name:           'Art & Craft Mega Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          54.41,
    originalPrice:  100.75,
    discount:       46,
    rating:         4.7,
    reviews:        4885,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'dar-toys-008',
    name:           'Foam Nerf-Style Blaster',
    category:       'toys',
    subcategory:    'Board Games',
    price:          34.3,
    originalPrice:  42.88,
    discount:       20,
    rating:         4.8,
    reviews:        23901,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "blaster", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-009',
    name:           'Mini Drone — Beginner Friendly',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          16.07,
    originalPrice:  20.87,
    discount:       23,
    rating:         4.8,
    reviews:        9390,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["drone", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'dar-toys-010',
    name:           'Kids\' Walkie Talkies — 1km Range',
    category:       'toys',
    subcategory:    'Educational',
    price:          54.42,
    originalPrice:  98.95,
    discount:       45,
    rating:         4.7,
    reviews:        16311,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["talkies", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'dar-toys-011',
    name:           'Dollhouse — 3-Storey Wooden',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          42.87,
    originalPrice:  63.99,
    discount:       33,
    rating:         4.3,
    reviews:        2349,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["dollhouse", "kids", "games", "toys", "outdoor", "play"]
  },
  {
    id:             'dar-toys-012',
    name:           'Train Set — 130 Pieces',
    category:       'toys',
    subcategory:    'STEM',
    price:          80.44,
    originalPrice:  100.55,
    discount:       20,
    rating:         4.1,
    reviews:        9100,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'dar-toys-013',
    name:           'Slime Making Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          52.44,
    originalPrice:  76.0,
    discount:       31,
    rating:         4.3,
    reviews:        9891,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'dar-toys-014',
    name:           'Sensory Sand Tray',
    category:       'toys',
    subcategory:    'Board Games',
    price:          47.85,
    originalPrice:  81.11,
    discount:       41,
    rating:         4.8,
    reviews:        12199,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "tray", "games", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-015',
    name:           'Bubble Machine — Automatic',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          43.46,
    originalPrice:  90.54,
    discount:       52,
    rating:         4.8,
    reviews:        12137,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "puzzles", "play", "machine"]
  },
  {
    id:             'dar-toys-016',
    name:           'Giant Floor Puzzle — 100 Pieces',
    category:       'toys',
    subcategory:    'Educational',
    price:          65.92,
    originalPrice:  92.84,
    discount:       29,
    rating:         4.9,
    reviews:        15108,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "educational", "play", "puzzle"]
  },
  {
    id:             'dar-toys-017',
    name:           'Pop It Fidget Toy Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          60.26,
    originalPrice:  94.16,
    discount:       36,
    rating:         4.6,
    reviews:        11106,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'dar-toys-018',
    name:           'Water Balloons — Self-Sealing 100pk',
    category:       'toys',
    subcategory:    'STEM',
    price:          24.55,
    originalPrice:  46.33,
    discount:       47,
    rating:         4.3,
    reviews:        15917,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "balloons", "toys", "play", "stem"]
  },
  {
    id:             'dar-toys-019',
    name:           'Kinetic Sand Set — 3kg',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          67.81,
    originalPrice:  102.74,
    discount:       34,
    rating:         4.5,
    reviews:        9664,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'dar-toys-020',
    name:           'Outdoor Trampoline — 10ft',
    category:       'toys',
    subcategory:    'Board Games',
    price:          74.92,
    originalPrice:  110.17,
    discount:       32,
    rating:         4.7,
    reviews:        5882,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "trampoline", "games", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-021',
    name:           'Foam Ball Pit + 200 Balls',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          44.99,
    originalPrice:  74.98,
    discount:       40,
    rating:         4.8,
    reviews:        17829,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "balls", "puzzles", "play"]
  },
  {
    id:             'dar-toys-022',
    name:           'Science Experiment Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          40.87,
    originalPrice:  110.47,
    discount:       63,
    rating:         4.9,
    reviews:        4093,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'dar-toys-023',
    name:           'Perler Bead Set — 5000 Pieces',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          79.52,
    originalPrice:  99.4,
    discount:       20,
    rating:         4.2,
    reviews:        8736,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'dar-toys-024',
    name:           'Sticker Activity Book',
    category:       'toys',
    subcategory:    'STEM',
    price:          39.88,
    originalPrice:  84.86,
    discount:       53,
    rating:         4.5,
    reviews:        24913,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "book", "games", "toys", "play", "stem"]
  },
  {
    id:             'dar-toys-025',
    name:           'Action Figure Set — 12 Characters',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          31.21,
    originalPrice:  70.94,
    discount:       56,
    rating:         4.9,
    reviews:        11349,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'dar-toys-026',
    name:           'Play Kitchen Set',
    category:       'toys',
    subcategory:    'Board Games',
    price:          13.4,
    originalPrice:  21.61,
    discount:       38,
    rating:         4.4,
    reviews:        6512,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "board_games"]
  },
  {
    id:             'dar-toys-027',
    name:           'Magnetic Tiles Set — 60 Pieces',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          36.04,
    originalPrice:  70.66,
    discount:       49,
    rating:         4.3,
    reviews:        12141,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "puzzles", "play", "set"]
  },
  {
    id:             'dar-toys-028',
    name:           'Soft Play Crawl Tunnel',
    category:       'toys',
    subcategory:    'Educational',
    price:          16.89,
    originalPrice:  31.28,
    discount:       46,
    rating:         4.6,
    reviews:        6191,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "educational", "play", "tunnel"]
  },
  {
    id:             'dar-toys-029',
    name:           'Outdoor Swing — Timber Frame',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          25.04,
    originalPrice:  52.17,
    discount:       52,
    rating:         4.3,
    reviews:        9161,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "swing"]
  },
  {
    id:             'dar-toys-030',
    name:           'Bath Toy Set — Squirt Animals',
    category:       'toys',
    subcategory:    'STEM',
    price:          68.36,
    originalPrice:  106.81,
    discount:       36,
    rating:         4.2,
    reviews:        5200,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'dar-toys-031',
    name:           'Wooden Stacking Tower',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          53.78,
    originalPrice:  103.42,
    discount:       48,
    rating:         4.6,
    reviews:        19043,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tower", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'dar-toys-032',
    name:           'Finger Painting Kit — Washable',
    category:       'toys',
    subcategory:    'Board Games',
    price:          58.59,
    originalPrice:  90.14,
    discount:       35,
    rating:         4.2,
    reviews:        5500,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-033',
    name:           'Stuffed Animal Bundle — 5 Pack',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          57.41,
    originalPrice:  86.99,
    discount:       34,
    rating:         4.6,
    reviews:        6163,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'dar-toys-034',
    name:           'Mini Basketball Hoop — Indoor',
    category:       'toys',
    subcategory:    'Educational',
    price:          33.8,
    originalPrice:  91.35,
    discount:       63,
    rating:         4.6,
    reviews:        8033,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "educational", "hoop", "play"]
  },
  {
    id:             'dar-toys-035',
    name:           'Kids\' Karaoke Machine',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          44.2,
    originalPrice:  61.39,
    discount:       28,
    rating:         4.0,
    reviews:        12120,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "machine"]
  },
  {
    id:             'dar-toys-036',
    name:           'Roller Skates — Adjustable',
    category:       'toys',
    subcategory:    'STEM',
    price:          33.87,
    originalPrice:  89.12,
    discount:       62,
    rating:         4.9,
    reviews:        14166,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["skates", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'dar-toys-037',
    name:           'Toy Cash Register',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          51.08,
    originalPrice:  113.52,
    discount:       55,
    rating:         4.5,
    reviews:        12733,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "action_figures", "register"]
  },
  {
    id:             'dar-toys-038',
    name:           'Kids\' Binoculars',
    category:       'toys',
    subcategory:    'Board Games',
    price:          61.67,
    originalPrice:  99.47,
    discount:       38,
    rating:         4.3,
    reviews:        7761,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["binoculars", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-039',
    name:           'Sand Water Table',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          30.65,
    originalPrice:  54.74,
    discount:       44,
    rating:         4.7,
    reviews:        5500,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "table", "puzzles", "play"]
  },
  {
    id:             'dar-toys-040',
    name:           'Lacing & Threading Set',
    category:       'toys',
    subcategory:    'Educational',
    price:          43.44,
    originalPrice:  57.16,
    discount:       24,
    rating:         4.1,
    reviews:        16646,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "educational", "play", "set"]
  },
  {
    id:             'dar-toys-041',
    name:           'Giant Jenga — Outdoor',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          53.7,
    originalPrice:  91.01,
    discount:       41,
    rating:         4.3,
    reviews:        7606,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "jenga"]
  },
  {
    id:             'dar-toys-042',
    name:           'Playdough 12-Colour Set',
    category:       'toys',
    subcategory:    'STEM',
    price:          24.35,
    originalPrice:  62.44,
    discount:       61,
    rating:         4.4,
    reviews:        18272,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'dar-toys-043',
    name:           'Solar System Model Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          38.2,
    originalPrice:  74.91,
    discount:       49,
    rating:         4.4,
    reviews:        4777,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'dar-toys-044',
    name:           'Coding Robot for Kids',
    category:       'toys',
    subcategory:    'Board Games',
    price:          72.63,
    originalPrice:  94.33,
    discount:       23,
    rating:         5.0,
    reviews:        17626,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'dar-toys-045',
    name:           'Fairy Garden Kit',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          15.61,
    originalPrice:  21.39,
    discount:       27,
    rating:         4.1,
    reviews:        19365,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'dar-toys-046',
    name:           'Space Rover Build Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          33.31,
    originalPrice:  67.98,
    discount:       51,
    rating:         4.4,
    reviews:        11301,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'dar-toys-047',
    name:           'Kids\' Archery Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          27.73,
    originalPrice:  71.1,
    discount:       61,
    rating:         4.5,
    reviews:        19184,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'dar-toys-048',
    name:           'Board Game Bundle — 5 Games',
    category:       'toys',
    subcategory:    'STEM',
    price:          44.19,
    originalPrice:  92.07,
    discount:       52,
    rating:         4.3,
    reviews:        24141,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["bundle", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'dar-toys-049',
    name:           'Glow in Dark Stars Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          68.04,
    originalPrice:  111.54,
    discount:       39,
    rating:         4.3,
    reviews:        17818,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'dar-toys-050',
    name:           'Rocket Launcher + Foam Rockets',
    category:       'toys',
    subcategory:    'Board Games',
    price:          32.52,
    originalPrice:  92.9,
    discount:       65,
    rating:         4.1,
    reviews:        24948,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/toys-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["kids", "games", "toys", "play", "board_games", "rockets"]
  }
);
