/* DARAZ — Watches (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-daraz.js index file
*/

window.DarazProducts = window.DarazProducts || [];

window.DarazProducts.push(
  {
    id:             'dar-watc-001',
    name:           'Smart Watch Pro — Fitness Tracker',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          42.36,
    originalPrice:  60.51,
    discount:       30,
    rating:         4.6,
    reviews:        4450,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-1?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "smart_watches", "pro"]
  },
  {
    id:             'dar-watc-002',
    name:           '3-in-1 Wireless Charging Pad',
    category:       'watches',
    subcategory:    'Analog',
    price:          40.12,
    originalPrice:  83.59,
    discount:       52,
    rating:         4.2,
    reviews:        6016,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-2?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "pad", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-003',
    name:           'Minimalist Leather Strap Watch — Rose Gold',
    category:       'watches',
    subcategory:    'Digital',
    price:          47.42,
    originalPrice:  72.96,
    discount:       35,
    rating:         4.7,
    reviews:        9749,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-3?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-004',
    name:           'Chronograph Men\'s Watch — Black',
    category:       'watches',
    subcategory:    'Luxury',
    price:          15.47,
    originalPrice:  36.84,
    discount:       58,
    rating:         4.1,
    reviews:        19861,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-4?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-005',
    name:           'Digital Sports Watch — Waterproof',
    category:       'watches',
    subcategory:    'Sport',
    price:          18.31,
    originalPrice:  24.74,
    discount:       26,
    rating:         4.1,
    reviews:        18000,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-5?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-006',
    name:           'Ladies\' Rose Gold Bracelet Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          37.55,
    originalPrice:  52.15,
    discount:       28,
    rating:         4.9,
    reviews:        5906,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-6?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-007',
    name:           'Fossil-Style Analogue Watch — Silver',
    category:       'watches',
    subcategory:    'Analog',
    price:          27.84,
    originalPrice:  63.27,
    discount:       56,
    rating:         4.8,
    reviews:        15755,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-7?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-008',
    name:           'Smart Watch with ECG Monitor',
    category:       'watches',
    subcategory:    'Digital',
    price:          13.44,
    originalPrice:  37.32,
    discount:       64,
    rating:         4.2,
    reviews:        9525,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-8?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["monitor", "smartwatch", "timepiece", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-009',
    name:           'Retro Wooden Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          23.14,
    originalPrice:  56.44,
    discount:       59,
    rating:         4.1,
    reviews:        12916,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-9?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-010',
    name:           'Kids\' Cartoon Character Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          40.16,
    originalPrice:  89.24,
    discount:       55,
    rating:         5.0,
    reviews:        7230,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-10?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-011',
    name:           'Automatic Self-Winding Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          11.71,
    originalPrice:  23.42,
    discount:       50,
    rating:         4.6,
    reviews:        8867,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-11?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-012',
    name:           'Solar Powered Watch — Men\'s',
    category:       'watches',
    subcategory:    'Analog',
    price:          33.11,
    originalPrice:  91.98,
    discount:       64,
    rating:         4.0,
    reviews:        3485,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-12?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-013',
    name:           'Ultra-Thin Quartz Watch — Gold',
    category:       'watches',
    subcategory:    'Digital',
    price:          35.46,
    originalPrice:  77.09,
    discount:       54,
    rating:         4.8,
    reviews:        437,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-13?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-014',
    name:           'Ceramic White Strap Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          53.91,
    originalPrice:  69.12,
    discount:       22,
    rating:         4.5,
    reviews:        21111,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-14?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-015',
    name:           'Military Tactical Watch — Green',
    category:       'watches',
    subcategory:    'Sport',
    price:          20.66,
    originalPrice:  38.25,
    discount:       46,
    rating:         4.2,
    reviews:        8270,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-15?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-016',
    name:           'Ladies\' Marble Dial Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          26.62,
    originalPrice:  40.96,
    discount:       35,
    rating:         4.4,
    reviews:        4521,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-16?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-017',
    name:           'Dual Time Zone Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          10.88,
    originalPrice:  18.75,
    discount:       42,
    rating:         4.2,
    reviews:        1212,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-17?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-018',
    name:           'Skeleton Mechanical Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          32.86,
    originalPrice:  93.89,
    discount:       65,
    rating:         4.1,
    reviews:        24425,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-18?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-019',
    name:           'Pearl Dial Dress Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          32.31,
    originalPrice:  46.83,
    discount:       31,
    rating:         4.7,
    reviews:        19682,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-19?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-020',
    name:           'Titanium Sports Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          22.54,
    originalPrice:  44.2,
    discount:       49,
    rating:         4.6,
    reviews:        375,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-20?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-021',
    name:           'Fashion Alloy Quartz Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          46.96,
    originalPrice:  114.54,
    discount:       59,
    rating:         4.6,
    reviews:        18279,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-21?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-022',
    name:           'GPS Running Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          33.08,
    originalPrice:  45.32,
    discount:       27,
    rating:         4.1,
    reviews:        1214,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-22?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-023',
    name:           'Smart Band Fitness Tracker',
    category:       'watches',
    subcategory:    'Digital',
    price:          53.35,
    originalPrice:  90.42,
    discount:       41,
    rating:         4.1,
    reviews:        17951,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-23?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["tracker", "smartwatch", "timepiece", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-024',
    name:           'Classic Pocket Watch — Bronze',
    category:       'watches',
    subcategory:    'Luxury',
    price:          44.47,
    originalPrice:  74.11,
    discount:       40,
    rating:         4.2,
    reviews:        11570,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-24?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-025',
    name:           'Mesh Strap Watch — Silver',
    category:       'watches',
    subcategory:    'Sport',
    price:          9.31,
    originalPrice:  22.17,
    discount:       58,
    rating:         4.6,
    reviews:        8660,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-25?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-026',
    name:           'Luminous Hands Dive Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          36.62,
    originalPrice:  77.91,
    discount:       53,
    rating:         4.3,
    reviews:        11555,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-26?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-027',
    name:           'Slim Profile Men\'s Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          21.31,
    originalPrice:  27.32,
    discount:       22,
    rating:         4.0,
    reviews:        3786,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-27?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-028',
    name:           'Heart Rate Monitor Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          53.37,
    originalPrice:  74.12,
    discount:       28,
    rating:         4.9,
    reviews:        9969,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-28?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-029',
    name:           'Minimalist NATO Strap Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          38.78,
    originalPrice:  53.86,
    discount:       28,
    rating:         4.3,
    reviews:        11804,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-29?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-030',
    name:           'Ladies\' Swarovski Crystal Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          19.15,
    originalPrice:  39.9,
    discount:       52,
    rating:         4.5,
    reviews:        14698,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-30?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-031',
    name:           'Square Face Stainless Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          79.12,
    originalPrice:  104.1,
    discount:       24,
    rating:         4.2,
    reviews:        19420,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-31?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-032',
    name:           'Leather Cuff Watch — Brown',
    category:       'watches',
    subcategory:    'Analog',
    price:          42.07,
    originalPrice:  64.72,
    discount:       35,
    rating:         4.2,
    reviews:        19430,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-32?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-033',
    name:           'Smart Watch Kids — Parental Control',
    category:       'watches',
    subcategory:    'Digital',
    price:          39.5,
    originalPrice:  54.11,
    discount:       27,
    rating:         4.8,
    reviews:        24567,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-33?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "kids", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-034',
    name:           'Marble Dial Ladies\' Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          23.73,
    originalPrice:  57.88,
    discount:       59,
    rating:         4.2,
    reviews:        10836,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-34?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-035',
    name:           'Men\'s Big Dial Bold Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          30.14,
    originalPrice:  66.97,
    discount:       55,
    rating:         4.5,
    reviews:        18686,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-35?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-036',
    name:           'Solar Atomic Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          37.58,
    originalPrice:  70.91,
    discount:       47,
    rating:         4.8,
    reviews:        11867,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-36?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-037',
    name:           'Watch Gift Set — His & Hers',
    category:       'watches',
    subcategory:    'Analog',
    price:          74.7,
    originalPrice:  102.33,
    discount:       27,
    rating:         4.2,
    reviews:        9703,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-37?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watches", "wristwatch", "set"]
  },
  {
    id:             'dar-watc-038',
    name:           'Vintage Pilot Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          66.64,
    originalPrice:  86.55,
    discount:       23,
    rating:         4.6,
    reviews:        8812,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-38?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-039',
    name:           'Gold Plated Chain Bracelet Watch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          40.65,
    originalPrice:  72.59,
    discount:       44,
    rating:         4.0,
    reviews:        21621,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-39?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "luxury"]
  },
  {
    id:             'dar-watc-040',
    name:           'Enamel Face Ladies\' Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          68.99,
    originalPrice:  118.95,
    discount:       42,
    rating:         4.6,
    reviews:        11668,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-40?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-041',
    name:           'Men\'s Tourbillon Skeleton Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          19.79,
    originalPrice:  35.98,
    discount:       45,
    rating:         4.6,
    reviews:        23167,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-41?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-042',
    name:           'Resin Sport Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          29.08,
    originalPrice:  44.74,
    discount:       35,
    rating:         4.6,
    reviews:        3902,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-42?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-043',
    name:           'Women\'s Charm Bracelet Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          58.01,
    originalPrice:  107.43,
    discount:       46,
    rating:         4.7,
    reviews:        17656,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-43?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-044',
    name:           'Digital Alarm Stopwatch',
    category:       'watches',
    subcategory:    'Luxury',
    price:          37.64,
    originalPrice:  67.22,
    discount:       44,
    rating:         4.9,
    reviews:        18139,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-44?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "luxury", "stopwatch"]
  },
  {
    id:             'dar-watc-045',
    name:           'Classic Black Dial Men\'s Watch',
    category:       'watches',
    subcategory:    'Sport',
    price:          34.04,
    originalPrice:  45.39,
    discount:       25,
    rating:         4.9,
    reviews:        2878,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548171916-c8fd5d69c4ec?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-45?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  },
  {
    id:             'dar-watc-046',
    name:           'Multi-Function Smart Watch',
    category:       'watches',
    subcategory:    'Smart Watches',
    price:          29.41,
    originalPrice:  75.41,
    discount:       61,
    rating:         4.5,
    reviews:        13681,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-46?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "smart_watches"]
  },
  {
    id:             'dar-watc-047',
    name:           'Womens\' Bangle Watch',
    category:       'watches',
    subcategory:    'Analog',
    price:          56.11,
    originalPrice:  86.33,
    discount:       35,
    rating:         4.9,
    reviews:        19196,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-47?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["analog", "smartwatch", "timepiece", "watch", "watches", "wristwatch"]
  },
  {
    id:             'dar-watc-048',
    name:           'Calatrava Style Dress Watch',
    category:       'watches',
    subcategory:    'Digital',
    price:          16.22,
    originalPrice:  25.74,
    discount:       37,
    rating:         4.8,
    reviews:        14105,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-48?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "digital"]
  },
  {
    id:             'dar-watc-049',
    name:           'Sport Chronograph — Red',
    category:       'watches',
    subcategory:    'Luxury',
    price:          13.57,
    originalPrice:  24.23,
    discount:       44,
    rating:         4.8,
    reviews:        11950,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-49?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watches", "wristwatch", "luxury", "chronograph"]
  },
  {
    id:             'dar-watc-050',
    name:           'Everyday Casual Watch — Unisex',
    category:       'watches',
    subcategory:    'Sport',
    price:          40.29,
    originalPrice:  98.27,
    discount:       59,
    rating:         4.8,
    reviews:        6697,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.daraz.pk/products/watches-product-50?aff_id=MEOW123',
    marketplace:    'Daraz',
    marketplaceIcon: 'fas fa-store',
    tags:           ["smartwatch", "timepiece", "watch", "watches", "wristwatch", "sport"]
  }
);
