/* AMAZON — Beauty (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-beau-001',
    name:           'Vitamin C Brightening Serum — 30ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          66.19,
    originalPrice:  90.67,
    discount:       27,
    rating:         4.9,
    reviews:        6594,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare"]
  },
  {
    id:             'ama-beau-002',
    name:           'Korean Skincare 5-Piece Set',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          21.22,
    originalPrice:  35.96,
    discount:       41,
    rating:         4.5,
    reviews:        12183,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'ama-beau-003',
    name:           'Rose Quartz Face Roller & Gua Sha Set',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          32.32,
    originalPrice:  43.68,
    discount:       26,
    rating:         4.1,
    reviews:        24703,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-004',
    name:           'Electric Face Massager — Microcurrent',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          77.67,
    originalPrice:  110.96,
    discount:       30,
    rating:         4.9,
    reviews:        6116,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "fragrance", "massager", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-005',
    name:           'Matte Lipstick Collection — 12 Shades',
    category:       'beauty',
    subcategory:    'Nails',
    price:          87.11,
    originalPrice:  117.72,
    discount:       26,
    rating:         4.6,
    reviews:        20452,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "skincare", "collection"]
  },
  {
    id:             'ama-beau-006',
    name:           'Portable Hair Straightener Brush',
    category:       'beauty',
    subcategory:    'Tools',
    price:          34.87,
    originalPrice:  68.37,
    discount:       49,
    rating:         4.8,
    reviews:        22037,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "brush", "beauty", "skincare", "tools"]
  },
  {
    id:             'ama-beau-007',
    name:           'Retinol Night Cream — Anti-Ageing',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          24.3,
    originalPrice:  57.85,
    discount:       58,
    rating:         4.4,
    reviews:        16928,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-008',
    name:           'Hyaluronic Acid Moisturiser — 50ml',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          45.69,
    originalPrice:  64.35,
    discount:       29,
    rating:         4.3,
    reviews:        14682,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare"]
  },
  {
    id:             'ama-beau-009',
    name:           'Waterproof Mascara — Lengthening',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          60.01,
    originalPrice:  84.52,
    discount:       29,
    rating:         4.7,
    reviews:        9106,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "mascara", "beauty", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-010',
    name:           '24K Gold Eye Patches — 60 Pairs',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          18.49,
    originalPrice:  41.09,
    discount:       55,
    rating:         4.2,
    reviews:        12322,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "patches", "skincare"]
  },
  {
    id:             'ama-beau-011',
    name:           'Niacinamide Toner — Pore Minimising',
    category:       'beauty',
    subcategory:    'Nails',
    price:          54.81,
    originalPrice:  87.0,
    discount:       37,
    rating:         4.0,
    reviews:        10153,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "toner", "skincare"]
  },
  {
    id:             'ama-beau-012',
    name:           'Snail Mucin Essence — 100ml',
    category:       'beauty',
    subcategory:    'Tools',
    price:          53.56,
    originalPrice:  72.38,
    discount:       26,
    rating:         4.9,
    reviews:        4097,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "essence", "skincare", "tools"]
  },
  {
    id:             'ama-beau-013',
    name:           'Micellar Cleansing Water — 500ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          16.07,
    originalPrice:  24.72,
    discount:       35,
    rating:         4.1,
    reviews:        15015,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "water", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-014',
    name:           'BHA Salicylic Acid Exfoliant',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          30.58,
    originalPrice:  50.13,
    discount:       39,
    rating:         4.3,
    reviews:        3490,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "exfoliant", "skincare"]
  },
  {
    id:             'ama-beau-015',
    name:           'Natural Lip Oil — Glossy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          19.41,
    originalPrice:  46.21,
    discount:       58,
    rating:         4.8,
    reviews:        15157,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "oil", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-016',
    name:           'BB Cream SPF30 — Tinted',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          73.19,
    originalPrice:  97.58,
    discount:       25,
    rating:         4.9,
    reviews:        9675,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "spf30", "skincare"]
  },
  {
    id:             'ama-beau-017',
    name:           'Under-Eye Concealer — Full Coverage',
    category:       'beauty',
    subcategory:    'Nails',
    price:          31.77,
    originalPrice:  55.74,
    discount:       43,
    rating:         4.2,
    reviews:        1464,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "concealer", "nails", "skincare"]
  },
  {
    id:             'ama-beau-018',
    name:           'Eyeshadow Palette — 18 Shades',
    category:       'beauty',
    subcategory:    'Tools',
    price:          14.96,
    originalPrice:  41.55,
    discount:       64,
    rating:         4.9,
    reviews:        3975,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare", "tools"]
  },
  {
    id:             'ama-beau-019',
    name:           'Setting Powder — Translucent',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          52.02,
    originalPrice:  72.25,
    discount:       28,
    rating:         4.4,
    reviews:        3202,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "powder", "skincare"]
  },
  {
    id:             'ama-beau-020',
    name:           'Hair Mask — Deep Conditioning',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          55.62,
    originalPrice:  73.18,
    discount:       24,
    rating:         4.5,
    reviews:        19977,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "mask"]
  },
  {
    id:             'ama-beau-021',
    name:           'Colour-Depositing Purple Shampoo',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          19.66,
    originalPrice:  56.16,
    discount:       65,
    rating:         4.1,
    reviews:        1827,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "shampoo", "haircare"]
  },
  {
    id:             'ama-beau-022',
    name:           'Scalp Serum — Hair Growth',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          45.74,
    originalPrice:  114.35,
    discount:       60,
    rating:         4.5,
    reviews:        11587,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "serum", "skincare"]
  },
  {
    id:             'ama-beau-023',
    name:           'AHA Glycolic Acid Peel Pads',
    category:       'beauty',
    subcategory:    'Nails',
    price:          56.81,
    originalPrice:  101.44,
    discount:       44,
    rating:         4.1,
    reviews:        21005,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "pads", "nails", "skincare"]
  },
  {
    id:             'ama-beau-024',
    name:           'Jade Roller Duo Set',
    category:       'beauty',
    subcategory:    'Tools',
    price:          32.35,
    originalPrice:  61.03,
    discount:       47,
    rating:         4.8,
    reviews:        21822,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "tools"]
  },
  {
    id:             'ama-beau-025',
    name:           'Foundation — 40 Shades',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          18.41,
    originalPrice:  40.91,
    discount:       55,
    rating:         4.9,
    reviews:        12071,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-026',
    name:           'Blush & Bronzer Duo Palette',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          18.3,
    originalPrice:  35.19,
    discount:       48,
    rating:         4.3,
    reviews:        6331,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare"]
  },
  {
    id:             'ama-beau-027',
    name:           'Eyeliner Pen — Waterproof',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          48.34,
    originalPrice:  62.78,
    discount:       23,
    rating:         4.8,
    reviews:        10691,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "pen", "beauty", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-028',
    name:           'Brow Lamination Kit',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          16.02,
    originalPrice:  24.64,
    discount:       35,
    rating:         4.5,
    reviews:        14425,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "kit", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-029',
    name:           'Lip Plumper Gloss — Berry',
    category:       'beauty',
    subcategory:    'Nails',
    price:          45.47,
    originalPrice:  119.65,
    discount:       62,
    rating:         4.4,
    reviews:        7748,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "gloss", "beauty", "nails", "skincare"]
  },
  {
    id:             'ama-beau-030',
    name:           'Self-Tan Mousse — Medium',
    category:       'beauty',
    subcategory:    'Tools',
    price:          28.44,
    originalPrice:  60.52,
    discount:       53,
    rating:         4.3,
    reviews:        21169,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "mousse", "beauty", "skincare", "tools"]
  },
  {
    id:             'ama-beau-031',
    name:           'Vitamin E Body Lotion — 400ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          65.61,
    originalPrice:  113.12,
    discount:       42,
    rating:         4.6,
    reviews:        13167,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "lotion", "skincare"]
  },
  {
    id:             'ama-beau-032',
    name:           'Dry Shampoo Spray',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          13.2,
    originalPrice:  32.2,
    discount:       59,
    rating:         4.6,
    reviews:        20327,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "spray"]
  },
  {
    id:             'ama-beau-033',
    name:           'Sheet Face Mask Set — 10 Pack',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          28.46,
    originalPrice:  72.97,
    discount:       61,
    rating:         4.3,
    reviews:        7902,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-034',
    name:           'Cleansing Balm — Waterproof Makeup',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          84.18,
    originalPrice:  118.57,
    discount:       29,
    rating:         4.7,
    reviews:        10571,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "fragrance", "balm", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-035',
    name:           'SPF50 Sunscreen — Invisible',
    category:       'beauty',
    subcategory:    'Nails',
    price:          66.56,
    originalPrice:  89.95,
    discount:       26,
    rating:         4.1,
    reviews:        20700,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "sunscreen", "nails", "skincare"]
  },
  {
    id:             'ama-beau-036',
    name:           'Lash Growth Serum',
    category:       'beauty',
    subcategory:    'Tools',
    price:          44.62,
    originalPrice:  106.24,
    discount:       58,
    rating:         5.0,
    reviews:        15142,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare", "tools"]
  },
  {
    id:             'ama-beau-037',
    name:           'Collagen Peptide Face Cream',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          52.86,
    originalPrice:  82.6,
    discount:       36,
    rating:         4.8,
    reviews:        19015,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-038',
    name:           'Tea Tree Spot Treatment',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          17.86,
    originalPrice:  29.28,
    discount:       39,
    rating:         4.8,
    reviews:        8891,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "treatment", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-039',
    name:           'Cushion Foundation — Dewy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          18.09,
    originalPrice:  45.23,
    discount:       60,
    rating:         4.0,
    reviews:        20362,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-040',
    name:           'Peptide Eye Cream',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          82.35,
    originalPrice:  111.29,
    discount:       26,
    rating:         4.9,
    reviews:        12333,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "cream", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-041',
    name:           'Coconut Oil Body Scrub',
    category:       'beauty',
    subcategory:    'Nails',
    price:          58.3,
    originalPrice:  97.16,
    discount:       40,
    rating:         4.9,
    reviews:        7011,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "scrub", "beauty", "nails", "skincare"]
  },
  {
    id:             'ama-beau-042',
    name:           'Pore Strips — Blackhead Remover',
    category:       'beauty',
    subcategory:    'Tools',
    price:          50.5,
    originalPrice:  101.0,
    discount:       50,
    rating:         4.7,
    reviews:        4307,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "strips", "beauty", "skincare", "tools"]
  },
  {
    id:             'ama-beau-043',
    name:           'CC Cream — Colour Correcting',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          12.98,
    originalPrice:  16.64,
    discount:       22,
    rating:         4.1,
    reviews:        19189,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-044',
    name:           'Gel Liner — Smudge Proof',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          34.99,
    originalPrice:  68.61,
    discount:       49,
    rating:         4.7,
    reviews:        7162,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "liner", "skincare"]
  },
  {
    id:             'ama-beau-045',
    name:           'Ceramide Barrier Repair Moisturiser',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          17.95,
    originalPrice:  35.89,
    discount:       50,
    rating:         4.1,
    reviews:        884,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare", "haircare"]
  },
  {
    id:             'ama-beau-046',
    name:           'Illuminating Primer',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          41.09,
    originalPrice:  102.72,
    discount:       60,
    rating:         4.7,
    reviews:        23244,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "primer", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'ama-beau-047',
    name:           'Multi-Vitamin Face Oil',
    category:       'beauty',
    subcategory:    'Nails',
    price:          23.15,
    originalPrice:  57.87,
    discount:       60,
    rating:         4.4,
    reviews:        12520,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "oil", "skincare"]
  },
  {
    id:             'ama-beau-048',
    name:           'Whipped Body Butter — Shea',
    category:       'beauty',
    subcategory:    'Tools',
    price:          90.26,
    originalPrice:  112.83,
    discount:       20,
    rating:         4.4,
    reviews:        5253,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "butter", "tools"]
  },
  {
    id:             'ama-beau-049',
    name:           'Cruelty-Free Makeup Brush Set',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          25.4,
    originalPrice:  34.33,
    discount:       26,
    rating:         4.6,
    reviews:        17257,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'ama-beau-050',
    name:           'Nail Polish Set — 12 Colours',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          41.06,
    originalPrice:  62.21,
    discount:       34,
    rating:         4.4,
    reviews:        11465,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0BEAU050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  }
);
