/* AMAZON — Crafts (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-craf-001',
    name:           'Diamond Painting Kit — Full Drill 40×50',
    category:       'crafts',
    subcategory:    'Painting',
    price:          11.62,
    originalPrice:  27.66,
    discount:       58,
    rating:         4.7,
    reviews:        793,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-002',
    name:           'Resin Art Kit — UV Resin + Moulds',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          21.72,
    originalPrice:  46.21,
    discount:       53,
    rating:         4.6,
    reviews:        760,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-003',
    name:           'Aesthetic Journaling Kit — Washi Tapes',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          14.35,
    originalPrice:  41.0,
    discount:       65,
    rating:         4.3,
    reviews:        18536,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-004',
    name:           'Watercolour Paint Set — 48 Colours',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          26.79,
    originalPrice:  34.35,
    discount:       22,
    rating:         4.5,
    reviews:        22422,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-005',
    name:           'Macramé Wall Hanging Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          41.89,
    originalPrice:  99.73,
    discount:       58,
    rating:         4.2,
    reviews:        16001,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-006',
    name:           'Embroidery Starter Kit — Floral',
    category:       'crafts',
    subcategory:    'DIY',
    price:          52.27,
    originalPrice:  106.68,
    discount:       51,
    rating:         4.8,
    reviews:        20311,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-007',
    name:           'Lino Printing Starter Set',
    category:       'crafts',
    subcategory:    'Painting',
    price:          48.0,
    originalPrice:  119.99,
    discount:       60,
    rating:         4.2,
    reviews:        11106,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-008',
    name:           'Candle Making Kit — Soy Wax',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          55.34,
    originalPrice:  76.86,
    discount:       28,
    rating:         4.1,
    reviews:        22726,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-009',
    name:           'Pottery Air Dry Clay Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          59.73,
    originalPrice:  87.84,
    discount:       32,
    rating:         4.1,
    reviews:        750,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-010',
    name:           'Leather Craft Tooling Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          12.99,
    originalPrice:  18.04,
    discount:       28,
    rating:         4.2,
    reviews:        15248,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-011',
    name:           'Cross-Stitch Bookmark Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          12.5,
    originalPrice:  20.84,
    discount:       40,
    rating:         4.1,
    reviews:        22250,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-012',
    name:           'Acrylic Pour Painting Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          20.69,
    originalPrice:  29.14,
    discount:       29,
    rating:         4.8,
    reviews:        21850,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-013',
    name:           'Needle Felting Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          40.64,
    originalPrice:  56.45,
    discount:       28,
    rating:         4.7,
    reviews:        4073,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-014',
    name:           'Calligraphy Pen & Ink Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          36.4,
    originalPrice:  50.55,
    discount:       28,
    rating:         4.4,
    reviews:        3988,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-015',
    name:           'Soap Making Kit — Natural',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          25.07,
    originalPrice:  32.56,
    discount:       23,
    rating:         4.7,
    reviews:        18738,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-016',
    name:           'Origami Paper Set — 200 Sheets',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          45.98,
    originalPrice:  62.98,
    discount:       27,
    rating:         4.1,
    reviews:        10994,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-017',
    name:           'Knitting Starter Kit — Beginner',
    category:       'crafts',
    subcategory:    'Resin',
    price:          79.3,
    originalPrice:  99.13,
    discount:       20,
    rating:         5.0,
    reviews:        15876,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-018',
    name:           'Crochet Hook Set + Yarn Bundle',
    category:       'crafts',
    subcategory:    'DIY',
    price:          66.62,
    originalPrice:  118.96,
    discount:       44,
    rating:         4.1,
    reviews:        6688,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-019',
    name:           'Jewellery Making Kit — Beads',
    category:       'crafts',
    subcategory:    'Painting',
    price:          23.44,
    originalPrice:  58.59,
    discount:       60,
    rating:         4.8,
    reviews:        7955,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-020',
    name:           'Tie-Dye Kit — Spiral',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          15.88,
    originalPrice:  44.1,
    discount:       64,
    rating:         4.5,
    reviews:        3479,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-021',
    name:           'Painting by Numbers — Landscape',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          65.61,
    originalPrice:  85.21,
    discount:       23,
    rating:         4.7,
    reviews:        6985,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["numbers", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-022',
    name:           'Block Printing Ink Set',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          42.28,
    originalPrice:  54.21,
    discount:       22,
    rating:         4.8,
    reviews:        24372,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-023',
    name:           'Scrapbook Kit — 200 Stickers',
    category:       'crafts',
    subcategory:    'Resin',
    price:          58.73,
    originalPrice:  115.15,
    discount:       49,
    rating:         4.3,
    reviews:        5708,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-024',
    name:           'Pressed Flower Art Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          45.47,
    originalPrice:  116.58,
    discount:       61,
    rating:         4.5,
    reviews:        7728,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-025',
    name:           'Glass Painting Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          32.2,
    originalPrice:  61.92,
    discount:       48,
    rating:         4.9,
    reviews:        10711,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-026',
    name:           'Wool Felting Supplies Bundle',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          14.93,
    originalPrice:  24.47,
    discount:       39,
    rating:         4.0,
    reviews:        7294,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bundle", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-027',
    name:           'Punch Needle Rug Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          6.57,
    originalPrice:  14.94,
    discount:       56,
    rating:         4.3,
    reviews:        22696,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-028',
    name:           'Marbling Paper Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          69.39,
    originalPrice:  108.42,
    discount:       36,
    rating:         4.3,
    reviews:        1779,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-029',
    name:           'Silk Screen Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          28.03,
    originalPrice:  51.9,
    discount:       46,
    rating:         4.6,
    reviews:        13741,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-030',
    name:           'Decoupage Set + Papers',
    category:       'crafts',
    subcategory:    'DIY',
    price:          69.43,
    originalPrice:  111.98,
    discount:       38,
    rating:         4.4,
    reviews:        24195,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["papers", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-031',
    name:           'Weaving Loom Kit — Beginner',
    category:       'crafts',
    subcategory:    'Painting',
    price:          55.82,
    originalPrice:  71.56,
    discount:       22,
    rating:         4.5,
    reviews:        1550,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-032',
    name:           'Zentangle Art Pens Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          35.46,
    originalPrice:  101.31,
    discount:       65,
    rating:         4.2,
    reviews:        23724,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-033',
    name:           'Linoleum Block Carving Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          41.7,
    originalPrice:  70.67,
    discount:       41,
    rating:         4.1,
    reviews:        14151,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-034',
    name:           'Alcohol Ink Art Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          65.03,
    originalPrice:  90.32,
    discount:       28,
    rating:         4.6,
    reviews:        8085,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-035',
    name:           'Mandala Drawing Stencil Set',
    category:       'crafts',
    subcategory:    'Resin',
    price:          10.86,
    originalPrice:  17.52,
    discount:       38,
    rating:         4.5,
    reviews:        10934,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-036',
    name:           'Rubber Stamp Making Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          42.49,
    originalPrice:  90.41,
    discount:       53,
    rating:         4.4,
    reviews:        18666,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-037',
    name:           'Reusable Stencil Set — 40 Piece',
    category:       'crafts',
    subcategory:    'Painting',
    price:          38.09,
    originalPrice:  95.22,
    discount:       60,
    rating:         4.4,
    reviews:        12461,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-038',
    name:           'Air Dry Clay Tool Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          22.56,
    originalPrice:  60.96,
    discount:       63,
    rating:         4.8,
    reviews:        13945,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-039',
    name:           'Mixed Media Art Journal',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          22.42,
    originalPrice:  33.46,
    discount:       33,
    rating:         4.4,
    reviews:        6487,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["journal", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-040',
    name:           'Bookbinding Kit — Hardcover',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          52.5,
    originalPrice:  76.08,
    discount:       31,
    rating:         4.3,
    reviews:        14610,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-041',
    name:           'Batik Wax Resist Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          23.42,
    originalPrice:  57.13,
    discount:       59,
    rating:         4.5,
    reviews:        18723,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-042',
    name:           'Pyrography Wood Burning Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          6.88,
    originalPrice:  13.23,
    discount:       48,
    rating:         4.2,
    reviews:        7686,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-043',
    name:           'Paper Quilling Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          19.63,
    originalPrice:  24.85,
    discount:       21,
    rating:         4.0,
    reviews:        11751,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-044',
    name:           'Shrink Plastic Art Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          6.5,
    originalPrice:  17.57,
    discount:       63,
    rating:         4.9,
    reviews:        12365,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'ama-craf-045',
    name:           'Enamel Painting Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          24.08,
    originalPrice:  32.1,
    discount:       25,
    rating:         4.4,
    reviews:        7066,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-046',
    name:           'Gilding Flakes Set — Gold',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          33.06,
    originalPrice:  87.01,
    discount:       62,
    rating:         4.5,
    reviews:        13575,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-047',
    name:           'Linocut Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          64.63,
    originalPrice:  113.39,
    discount:       43,
    rating:         5.0,
    reviews:        7468,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-048',
    name:           'Botanical Illustration Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          20.91,
    originalPrice:  29.04,
    discount:       28,
    rating:         4.5,
    reviews:        8708,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-049',
    name:           'Copper Tooling Craft Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          30.66,
    originalPrice:  42.58,
    discount:       28,
    rating:         4.7,
    reviews:        2188,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'ama-craf-050',
    name:           'Felt Sewing Starter Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          10.48,
    originalPrice:  23.81,
    discount:       56,
    rating:         4.8,
    reviews:        2697,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0CRAF050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  }
);
