/* AMAZON — Home (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-home-001',
    name:           'Bohemian Throw Pillow Covers — Set of 4',
    category:       'home',
    subcategory:    'Furniture',
    price:          28.49,
    originalPrice:  41.9,
    discount:       32,
    rating:         4.2,
    reviews:        11936,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "furniture", "covers", "decor"]
  },
  {
    id:             'ama-home-002',
    name:           'LED Desk Lamp with USB Charging Port',
    category:       'home',
    subcategory:    'Kitchen',
    price:          24.09,
    originalPrice:  66.93,
    discount:       64,
    rating:         4.3,
    reviews:        11062,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "port", "decor"]
  },
  {
    id:             'ama-home-003',
    name:           'Non-Stick Cookware Set — 5 Pieces',
    category:       'home',
    subcategory:    'Decor',
    price:          13.17,
    originalPrice:  37.63,
    discount:       65,
    rating:         4.8,
    reviews:        15298,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-004',
    name:           'Aesthetic Bedding Set — King Size',
    category:       'home',
    subcategory:    'Bedding',
    price:          54.36,
    originalPrice:  110.94,
    discount:       51,
    rating:         4.9,
    reviews:        18957,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ama-home-005',
    name:           'Aesthetic Acrylic Desk Organiser Set',
    category:       'home',
    subcategory:    'Lighting',
    price:          11.77,
    originalPrice:  16.82,
    discount:       30,
    rating:         4.4,
    reviews:        9198,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "lighting", "decor"]
  },
  {
    id:             'ama-home-006',
    name:           'Fairy Lights — 10m USB Warm White',
    category:       'home',
    subcategory:    'Storage',
    price:          26.68,
    originalPrice:  74.11,
    discount:       64,
    rating:         4.7,
    reviews:        10308,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["lights", "storage", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-007',
    name:           'Cute Ceramic Mug Set — 2 Pack',
    category:       'home',
    subcategory:    'Furniture',
    price:          16.14,
    originalPrice:  41.38,
    discount:       61,
    rating:         4.3,
    reviews:        9588,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ama-home-008',
    name:           'Minimalist Wall Clock — Silent Quartz',
    category:       'home',
    subcategory:    'Kitchen',
    price:          21.26,
    originalPrice:  41.68,
    discount:       49,
    rating:         4.9,
    reviews:        1205,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["clock", "kitchen", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-009',
    name:           'LED Strip Lights — 5m RGB Smart',
    category:       'home',
    subcategory:    'Decor',
    price:          22.64,
    originalPrice:  37.11,
    discount:       39,
    rating:         4.7,
    reviews:        13200,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["lights", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-010',
    name:           'Bamboo Bathroom Organiser',
    category:       'home',
    subcategory:    'Bedding',
    price:          24.63,
    originalPrice:  48.29,
    discount:       49,
    rating:         4.9,
    reviews:        12579,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["organiser", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ama-home-011',
    name:           'Velvet Storage Ottoman Cube',
    category:       'home',
    subcategory:    'Lighting',
    price:          27.18,
    originalPrice:  71.52,
    discount:       62,
    rating:         4.3,
    reviews:        6103,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "lighting", "cube", "decor"]
  },
  {
    id:             'ama-home-012',
    name:           'Woven Seagrass Basket — Large',
    category:       'home',
    subcategory:    'Storage',
    price:          79.13,
    originalPrice:  101.45,
    discount:       22,
    rating:         4.8,
    reviews:        5384,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "basket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-013',
    name:           'Floating Wall Shelves — Set of 3',
    category:       'home',
    subcategory:    'Furniture',
    price:          36.31,
    originalPrice:  48.41,
    discount:       25,
    rating:         4.3,
    reviews:        7767,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "decor", "interior", "living", "furniture", "shelves"]
  },
  {
    id:             'ama-home-014',
    name:           'Diffuser & Essential Oil Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          23.63,
    originalPrice:  52.52,
    discount:       55,
    rating:         4.1,
    reviews:        10567,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-015',
    name:           'Faux Fur Throw Blanket — Grey',
    category:       'home',
    subcategory:    'Decor',
    price:          42.37,
    originalPrice:  78.46,
    discount:       46,
    rating:         4.4,
    reviews:        15808,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-016',
    name:           'Boho Macramé Wall Hanging',
    category:       'home',
    subcategory:    'Bedding',
    price:          88.71,
    originalPrice:  119.88,
    discount:       26,
    rating:         5.0,
    reviews:        20774,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "hanging", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ama-home-017',
    name:           'Vintage Table Lamp — Rattan',
    category:       'home',
    subcategory:    'Lighting',
    price:          73.98,
    originalPrice:  98.64,
    discount:       25,
    rating:         4.9,
    reviews:        13801,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "lamp", "lighting", "decor"]
  },
  {
    id:             'ama-home-018',
    name:           'Glass Candle Holder Set',
    category:       'home',
    subcategory:    'Storage',
    price:          7.77,
    originalPrice:  17.27,
    discount:       55,
    rating:         4.3,
    reviews:        18842,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-019',
    name:           'Kitchen Herb Planter — 3 Pots',
    category:       'home',
    subcategory:    'Furniture',
    price:          27.4,
    originalPrice:  36.05,
    discount:       24,
    rating:         4.3,
    reviews:        9981,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "planter", "living", "furniture", "decor"]
  },
  {
    id:             'ama-home-020',
    name:           'Anti-Fatigue Kitchen Mat',
    category:       'home',
    subcategory:    'Kitchen',
    price:          8.59,
    originalPrice:  19.97,
    discount:       57,
    rating:         4.7,
    reviews:        21918,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "mat", "decor"]
  },
  {
    id:             'ama-home-021',
    name:           'Peel & Stick Wallpaper — Botanical',
    category:       'home',
    subcategory:    'Decor',
    price:          45.77,
    originalPrice:  72.65,
    discount:       37,
    rating:         4.8,
    reviews:        13506,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "wallpaper", "decor"]
  },
  {
    id:             'ama-home-022',
    name:           'Smart Plug Power Strip',
    category:       'home',
    subcategory:    'Bedding',
    price:          37.8,
    originalPrice:  71.32,
    discount:       47,
    rating:         4.6,
    reviews:        15054,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "strip", "bedding", "decor"]
  },
  {
    id:             'ama-home-023',
    name:           'Linen Shower Curtain — White',
    category:       'home',
    subcategory:    'Lighting',
    price:          40.7,
    originalPrice:  67.84,
    discount:       40,
    rating:         4.6,
    reviews:        17061,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "curtain", "lighting", "decor"]
  },
  {
    id:             'ama-home-024',
    name:           'Over-Door Towel Rail',
    category:       'home',
    subcategory:    'Storage',
    price:          13.71,
    originalPrice:  20.77,
    discount:       34,
    rating:         5.0,
    reviews:        8202,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "home", "interior", "living", "rail", "decor"]
  },
  {
    id:             'ama-home-025',
    name:           'Plant Pot Set — Pastel Terracotta',
    category:       'home',
    subcategory:    'Furniture',
    price:          21.85,
    originalPrice:  35.82,
    discount:       39,
    rating:         4.2,
    reviews:        3445,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ama-home-026',
    name:           'Wooden Serving Board',
    category:       'home',
    subcategory:    'Kitchen',
    price:          57.26,
    originalPrice:  79.53,
    discount:       28,
    rating:         4.7,
    reviews:        4273,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "board", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-027',
    name:           'Spice Rack — Rotating Turntable',
    category:       'home',
    subcategory:    'Decor',
    price:          27.44,
    originalPrice:  70.35,
    discount:       61,
    rating:         4.5,
    reviews:        23748,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "rack", "decor"]
  },
  {
    id:             'ama-home-028',
    name:           'Bed Tray Laptop Desk',
    category:       'home',
    subcategory:    'Bedding',
    price:          54.83,
    originalPrice:  107.5,
    discount:       49,
    rating:         4.6,
    reviews:        1723,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "desk", "bedding", "decor"]
  },
  {
    id:             'ama-home-029',
    name:           'Velvet Curtains — Blackout Grey',
    category:       'home',
    subcategory:    'Lighting',
    price:          41.67,
    originalPrice:  96.91,
    discount:       57,
    rating:         4.7,
    reviews:        16095,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "curtains", "lighting", "decor"]
  },
  {
    id:             'ama-home-030',
    name:           'Decorative Wicker Mirror',
    category:       'home',
    subcategory:    'Storage',
    price:          36.75,
    originalPrice:  79.9,
    discount:       54,
    rating:         4.5,
    reviews:        716,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "home", "interior", "living", "mirror", "decor"]
  },
  {
    id:             'ama-home-031',
    name:           'Stainless Steel Water Bottle — 1L',
    category:       'home',
    subcategory:    'Furniture',
    price:          18.66,
    originalPrice:  45.51,
    discount:       59,
    rating:         4.1,
    reviews:        10011,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "furniture", "bottle", "decor"]
  },
  {
    id:             'ama-home-032',
    name:           'Bamboo Cutting Board Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          15.92,
    originalPrice:  24.87,
    discount:       36,
    rating:         4.6,
    reviews:        404,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-033',
    name:           'Shower Caddy — 3 Tier',
    category:       'home',
    subcategory:    'Decor',
    price:          53.17,
    originalPrice:  71.85,
    discount:       26,
    rating:         5.0,
    reviews:        24707,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "decor", "interior", "living", "caddy"]
  },
  {
    id:             'ama-home-034',
    name:           'Framed Print Wall Art Set',
    category:       'home',
    subcategory:    'Bedding',
    price:          16.73,
    originalPrice:  36.36,
    discount:       54,
    rating:         4.4,
    reviews:        12276,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ama-home-035',
    name:           'Laundry Basket — Woven Rope',
    category:       'home',
    subcategory:    'Lighting',
    price:          67.51,
    originalPrice:  118.43,
    discount:       43,
    rating:         5.0,
    reviews:        11712,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["basket", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'ama-home-036',
    name:           'Electric Kettle — Rose Gold',
    category:       'home',
    subcategory:    'Storage',
    price:          20.23,
    originalPrice:  49.33,
    discount:       59,
    rating:         4.3,
    reviews:        11114,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "home", "kettle", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-037',
    name:           'Air Fryer — 5.5L Digital',
    category:       'home',
    subcategory:    'Furniture',
    price:          35.5,
    originalPrice:  93.41,
    discount:       62,
    rating:         4.9,
    reviews:        471,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "furniture", "fryer", "decor"]
  },
  {
    id:             'ama-home-038',
    name:           'Robot Mop & Vacuum Combo',
    category:       'home',
    subcategory:    'Kitchen',
    price:          23.93,
    originalPrice:  35.71,
    discount:       33,
    rating:         4.3,
    reviews:        17483,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "combo", "decor"]
  },
  {
    id:             'ama-home-039',
    name:           'Weighted Blanket — 8kg',
    category:       'home',
    subcategory:    'Decor',
    price:          30.25,
    originalPrice:  39.29,
    discount:       23,
    rating:         4.4,
    reviews:        21181,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-040',
    name:           'Cordless Stick Vacuum',
    category:       'home',
    subcategory:    'Bedding',
    price:          26.86,
    originalPrice:  57.15,
    discount:       53,
    rating:         4.0,
    reviews:        9108,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["vacuum", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'ama-home-041',
    name:           'Under-Bed Storage Boxes',
    category:       'home',
    subcategory:    'Lighting',
    price:          52.49,
    originalPrice:  97.2,
    discount:       46,
    rating:         4.8,
    reviews:        1247,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["boxes", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'ama-home-042',
    name:           'Memory Foam Pillow — Contour',
    category:       'home',
    subcategory:    'Storage',
    price:          40.29,
    originalPrice:  83.94,
    discount:       52,
    rating:         4.4,
    reviews:        827,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "pillow", "home", "interior", "living", "decor"]
  },
  {
    id:             'ama-home-043',
    name:           'Ceramic Dinner Set — 16 Piece',
    category:       'home',
    subcategory:    'Furniture',
    price:          42.6,
    originalPrice:  71.0,
    discount:       40,
    rating:         4.6,
    reviews:        9122,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'ama-home-044',
    name:           'Knife Block Set — 7 Piece',
    category:       'home',
    subcategory:    'Kitchen',
    price:          40.53,
    originalPrice:  96.5,
    discount:       58,
    rating:         4.6,
    reviews:        11979,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-045',
    name:           'Bath Mat Set — Non-Slip',
    category:       'home',
    subcategory:    'Decor',
    price:          41.38,
    originalPrice:  86.2,
    discount:       52,
    rating:         4.1,
    reviews:        23357,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'ama-home-046',
    name:           'Smart Colour Bulb Set — 4 Pack',
    category:       'home',
    subcategory:    'Bedding',
    price:          40.39,
    originalPrice:  112.2,
    discount:       64,
    rating:         4.2,
    reviews:        16726,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'ama-home-047',
    name:           'Blackout Roller Blind',
    category:       'home',
    subcategory:    'Lighting',
    price:          21.3,
    originalPrice:  30.43,
    discount:       30,
    rating:         4.0,
    reviews:        11711,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["home", "interior", "living", "lighting", "blind", "decor"]
  },
  {
    id:             'ama-home-048',
    name:           'Essential Oil Diffuser — Ultrasonic',
    category:       'home',
    subcategory:    'Storage',
    price:          29.31,
    originalPrice:  75.16,
    discount:       61,
    rating:         4.0,
    reviews:        16031,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["storage", "home", "interior", "living", "diffuser", "decor"]
  },
  {
    id:             'ama-home-049',
    name:           'Handheld Garment Steamer',
    category:       'home',
    subcategory:    'Furniture',
    price:          39.53,
    originalPrice:  58.13,
    discount:       32,
    rating:         4.1,
    reviews:        19048,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["steamer", "home", "interior", "living", "furniture", "decor"]
  },
  {
    id:             'ama-home-050',
    name:           'Kitchen Towel Set — Cotton',
    category:       'home',
    subcategory:    'Kitchen',
    price:          87.73,
    originalPrice:  116.97,
    discount:       25,
    rating:         4.4,
    reviews:        24655,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0HOME050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  }
);
