/* AMAZON — Jewelry (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-jewe-001',
    name:           '925 Silver Minimalist Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          77.56,
    originalPrice:  96.95,
    discount:       20,
    rating:         4.7,
    reviews:        2300,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-002',
    name:           'Dainty Layered Gold Chain Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          55.9,
    originalPrice:  88.73,
    discount:       37,
    rating:         5.0,
    reviews:        22967,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-003',
    name:           'Gold Plated Jhumka Earrings Set',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          41.58,
    originalPrice:  51.97,
    discount:       20,
    rating:         4.1,
    reviews:        3995,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ama-jewe-004',
    name:           'Stacking Rings Set — 10 Piece',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          27.93,
    originalPrice:  63.48,
    discount:       56,
    rating:         4.1,
    reviews:        8999,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ama-jewe-005',
    name:           'Pearl Stud Earrings — Classic',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          56.32,
    originalPrice:  79.33,
    discount:       29,
    rating:         5.0,
    reviews:        15643,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-006',
    name:           'Statement Hoop Earrings — Gold',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          38.62,
    originalPrice:  68.96,
    discount:       44,
    rating:         4.3,
    reviews:        15889,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-007',
    name:           'Crystal Tennis Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          75.6,
    originalPrice:  98.18,
    discount:       23,
    rating:         4.7,
    reviews:        12403,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-008',
    name:           'Vintage Cameo Brooch',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          22.09,
    originalPrice:  48.03,
    discount:       54,
    rating:         4.5,
    reviews:        7078,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "brooch", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'ama-jewe-009',
    name:           'Turquoise Beaded Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          19.54,
    originalPrice:  32.57,
    discount:       40,
    rating:         4.2,
    reviews:        5906,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-010',
    name:           'Anklet Set — Gold Chain',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          21.01,
    originalPrice:  30.89,
    discount:       32,
    rating:         4.1,
    reviews:        15875,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ama-jewe-011',
    name:           'Heart Locket Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          42.77,
    originalPrice:  61.99,
    discount:       31,
    rating:         4.3,
    reviews:        19313,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-012',
    name:           'Evil Eye Charm Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          57.91,
    originalPrice:  86.44,
    discount:       33,
    rating:         4.6,
    reviews:        21159,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-013',
    name:           'Opal Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          20.39,
    originalPrice:  38.48,
    discount:       47,
    rating:         4.0,
    reviews:        15378,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-014',
    name:           'Rose Gold Infinity Bracelet',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          27.17,
    originalPrice:  39.96,
    discount:       32,
    rating:         4.6,
    reviews:        18065,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-015',
    name:           'Diamond CZ Stud Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          13.1,
    originalPrice:  24.71,
    discount:       47,
    rating:         5.0,
    reviews:        12537,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-016',
    name:           'Name Initial Letter Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          57.85,
    originalPrice:  85.08,
    discount:       32,
    rating:         4.6,
    reviews:        21146,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-017',
    name:           'Geometric Triangle Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          55.88,
    originalPrice:  90.13,
    discount:       38,
    rating:         4.2,
    reviews:        15199,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-018',
    name:           'Twisted Bangle Set — 5 Pack',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          28.7,
    originalPrice:  57.41,
    discount:       50,
    rating:         4.5,
    reviews:        17724,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ama-jewe-019',
    name:           'Floral Hair Pins Set',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          43.89,
    originalPrice:  69.66,
    discount:       37,
    rating:         4.5,
    reviews:        9543,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ama-jewe-020',
    name:           'Moon & Stars Choker',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          22.88,
    originalPrice:  54.48,
    discount:       58,
    rating:         4.3,
    reviews:        21014,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["choker", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-021',
    name:           'Cluster Ring — Pink Tourmaline CZ',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          80.05,
    originalPrice:  102.63,
    discount:       22,
    rating:         4.7,
    reviews:        14663,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["ring", "accessories", "necklaces", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-022',
    name:           'Tassel Drop Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          41.82,
    originalPrice:  63.37,
    discount:       34,
    rating:         4.8,
    reviews:        11986,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-023',
    name:           'Layered Satellite Necklace',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          8.97,
    originalPrice:  16.61,
    discount:       46,
    rating:         4.4,
    reviews:        23038,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "jewelry", "necklace", "earrings", "gold"]
  },
  {
    id:             'ama-jewe-024',
    name:           'Charm Bracelet — Starter',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          16.19,
    originalPrice:  35.19,
    discount:       54,
    rating:         4.5,
    reviews:        8224,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-025',
    name:           'Bar Pendant Necklace — Engraved',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          54.75,
    originalPrice:  97.76,
    discount:       44,
    rating:         4.0,
    reviews:        15327,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-026',
    name:           'Snake Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          54.43,
    originalPrice:  87.79,
    discount:       38,
    rating:         4.4,
    reviews:        7914,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-027',
    name:           'Vintage Pearl Necklace — Multi-Strand',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          48.45,
    originalPrice:  93.18,
    discount:       48,
    rating:         4.4,
    reviews:        14867,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-028',
    name:           'Leaf Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          33.84,
    originalPrice:  82.53,
    discount:       59,
    rating:         4.4,
    reviews:        23465,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-029',
    name:           'Birthstone Ring — Personalised',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          73.43,
    originalPrice:  97.9,
    discount:       25,
    rating:         4.7,
    reviews:        2969,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-030',
    name:           'Celestial Sun Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          21.94,
    originalPrice:  42.2,
    discount:       48,
    rating:         4.6,
    reviews:        24830,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-031',
    name:           'Crystal Choker Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          30.15,
    originalPrice:  77.3,
    discount:       61,
    rating:         4.6,
    reviews:        6107,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-032',
    name:           'Emerald CZ Cocktail Ring',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          14.18,
    originalPrice:  18.66,
    discount:       24,
    rating:         4.6,
    reviews:        11852,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-033',
    name:           'Gold Hoop Set — 3 Pairs',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          80.23,
    originalPrice:  113.0,
    discount:       29,
    rating:         4.6,
    reviews:        14519,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'ama-jewe-034',
    name:           'Cuff Bangle — Hammered Gold',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          14.88,
    originalPrice:  36.3,
    discount:       59,
    rating:         4.3,
    reviews:        7565,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "bangle", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-035',
    name:           'Seed Bead Friendship Bracelet',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          29.79,
    originalPrice:  50.49,
    discount:       41,
    rating:         4.7,
    reviews:        13752,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-036',
    name:           'Safety Pin Earrings',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          46.11,
    originalPrice:  63.17,
    discount:       27,
    rating:         4.9,
    reviews:        17963,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-037',
    name:           'Mismatched Statement Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          65.65,
    originalPrice:  109.41,
    discount:       40,
    rating:         4.8,
    reviews:        18601,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-038',
    name:           'Charm Bangle — Pandora Style',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          35.31,
    originalPrice:  55.17,
    discount:       36,
    rating:         4.7,
    reviews:        7150,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "bangle", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'ama-jewe-039',
    name:           'Blue Topaz Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          14.5,
    originalPrice:  21.64,
    discount:       33,
    rating:         4.8,
    reviews:        8616,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-040',
    name:           'Stud Earrings Gift Set',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          19.55,
    originalPrice:  39.09,
    discount:       50,
    rating:         4.6,
    reviews:        4704,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'ama-jewe-041',
    name:           'Ear Cuff — No Piercing Required',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          49.71,
    originalPrice:  81.49,
    discount:       39,
    rating:         4.6,
    reviews:        12037,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "cuff", "gold"]
  },
  {
    id:             'ama-jewe-042',
    name:           'Link Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          35.59,
    originalPrice:  101.69,
    discount:       65,
    rating:         4.8,
    reviews:        22640,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'ama-jewe-043',
    name:           'Freshwater Pearl Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          32.99,
    originalPrice:  67.32,
    discount:       51,
    rating:         4.0,
    reviews:        14331,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-044',
    name:           'Crystal Headband — Bridal',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          45.94,
    originalPrice:  95.71,
    discount:       52,
    rating:         4.7,
    reviews:        14889,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "headband", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-045',
    name:           'Vintage Art Deco Ring',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          46.25,
    originalPrice:  73.41,
    discount:       37,
    rating:         4.4,
    reviews:        15929,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["ring", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-046',
    name:           'Flower Stud Earrings — Enamel',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          6.01,
    originalPrice:  15.02,
    discount:       60,
    rating:         4.8,
    reviews:        6023,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-047',
    name:           'Rhinestone Bib Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          27.69,
    originalPrice:  50.34,
    discount:       45,
    rating:         4.1,
    reviews:        15332,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-048',
    name:           'Asymmetric Dangle Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          9.68,
    originalPrice:  27.67,
    discount:       65,
    rating:         4.9,
    reviews:        18145,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'ama-jewe-049',
    name:           'Gold Plated Coin Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          73.36,
    originalPrice:  116.44,
    discount:       37,
    rating:         4.1,
    reviews:        10478,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'ama-jewe-050',
    name:           'Stackable Thin Band Rings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          50.67,
    originalPrice:  110.15,
    discount:       54,
    rating:         4.7,
    reviews:        19910,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0JEWE050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["rings", "accessories", "anklets", "silver", "jewelry", "gold"]
  }
);
