/* AMAZON — Kids (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-kids-001',
    name:           'Dinosaur Print Pyjama Set',
    category:       'kids',
    subcategory:    'Girls',
    price:          16.66,
    originalPrice:  28.24,
    discount:       41,
    rating:         4.1,
    reviews:        5432,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-002',
    name:           'Bunny Ear Hooded Sweatshirt',
    category:       'kids',
    subcategory:    'Boys',
    price:          27.24,
    originalPrice:  37.31,
    discount:       27,
    rating:         4.6,
    reviews:        2811,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "sweatshirt", "boys", "girls"]
  },
  {
    id:             'ama-kids-003',
    name:           'Rainbow Tutu Dress',
    category:       'kids',
    subcategory:    'Baby',
    price:          17.63,
    originalPrice:  26.71,
    discount:       34,
    rating:         4.6,
    reviews:        5138,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "baby", "dress", "girls"]
  },
  {
    id:             'ama-kids-004',
    name:           'School Uniform Shirt 3-Pack',
    category:       'kids',
    subcategory:    'School Wear',
    price:          39.73,
    originalPrice:  104.55,
    discount:       62,
    rating:         4.6,
    reviews:        9488,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "3-pack", "boys", "girls"]
  },
  {
    id:             'ama-kids-005',
    name:           'Denim Dungarees — Blue',
    category:       'kids',
    subcategory:    'Toys',
    price:          77.89,
    originalPrice:  106.7,
    discount:       27,
    rating:         4.9,
    reviews:        18513,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "dungarees", "boys", "girls"]
  },
  {
    id:             'ama-kids-006',
    name:           'Floral Smocked Dress',
    category:       'kids',
    subcategory:    'Footwear',
    price:          18.37,
    originalPrice:  39.09,
    discount:       53,
    rating:         4.7,
    reviews:        15835,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "boys", "dress", "girls"]
  },
  {
    id:             'ama-kids-007',
    name:           'Bear Appliqué Knit Jumper',
    category:       'kids',
    subcategory:    'Girls',
    price:          34.25,
    originalPrice:  59.05,
    discount:       42,
    rating:         4.1,
    reviews:        21205,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "jumper", "girls"]
  },
  {
    id:             'ama-kids-008',
    name:           'Cartoon Print T-Shirt Set',
    category:       'kids',
    subcategory:    'Boys',
    price:          33.06,
    originalPrice:  55.1,
    discount:       40,
    rating:         4.9,
    reviews:        16191,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-009',
    name:           'Leggings 5-Pack — Bright Mix',
    category:       'kids',
    subcategory:    'Baby',
    price:          66.43,
    originalPrice:  112.59,
    discount:       41,
    rating:         4.1,
    reviews:        2447,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "5-pack", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-010',
    name:           'Striped Long-Sleeve Tee',
    category:       'kids',
    subcategory:    'School Wear',
    price:          88.71,
    originalPrice:  119.88,
    discount:       26,
    rating:         4.6,
    reviews:        4494,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "boys", "tee", "girls"]
  },
  {
    id:             'ama-kids-011',
    name:           'Sherpa-Lined Puffer Jacket',
    category:       'kids',
    subcategory:    'Toys',
    price:          29.95,
    originalPrice:  63.73,
    discount:       53,
    rating:         4.3,
    reviews:        13096,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "children", "kids", "toys", "boys", "girls"]
  },
  {
    id:             'ama-kids-012',
    name:           'Fairy Wings Costume Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          27.29,
    originalPrice:  34.54,
    discount:       21,
    rating:         4.1,
    reviews:        9515,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-013',
    name:           'Cotton Romper — Newborn',
    category:       'kids',
    subcategory:    'Girls',
    price:          19.38,
    originalPrice:  31.25,
    discount:       38,
    rating:         4.4,
    reviews:        15856,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "romper", "boys", "girls"]
  },
  {
    id:             'ama-kids-014',
    name:           'Velvet Party Dress — Red',
    category:       'kids',
    subcategory:    'Boys',
    price:          17.16,
    originalPrice:  40.85,
    discount:       58,
    rating:         4.3,
    reviews:        19673,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ama-kids-015',
    name:           'Camouflage Cargo Shorts',
    category:       'kids',
    subcategory:    'Baby',
    price:          54.75,
    originalPrice:  73.0,
    discount:       25,
    rating:         4.2,
    reviews:        6237,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "shorts", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-016',
    name:           'Embroidered Denim Jacket',
    category:       'kids',
    subcategory:    'School Wear',
    price:          13.88,
    originalPrice:  17.8,
    discount:       22,
    rating:         4.4,
    reviews:        20668,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "children", "kids", "school_wear", "boys", "girls"]
  },
  {
    id:             'ama-kids-017',
    name:           'Ballet Wrap Cardigan',
    category:       'kids',
    subcategory:    'Toys',
    price:          85.43,
    originalPrice:  109.53,
    discount:       22,
    rating:         4.4,
    reviews:        19142,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "cardigan", "toys", "boys", "girls"]
  },
  {
    id:             'ama-kids-018',
    name:           'Superhero Cape Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          25.47,
    originalPrice:  43.91,
    discount:       42,
    rating:         4.2,
    reviews:        15029,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-019',
    name:           'Floral Swimsuit — UV50+',
    category:       'kids',
    subcategory:    'Girls',
    price:          64.34,
    originalPrice:  90.62,
    discount:       29,
    rating:         5.0,
    reviews:        13176,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "swimsuit", "boys", "girls"]
  },
  {
    id:             'ama-kids-020',
    name:           'Cosy Fleece Onesie — Animal Print',
    category:       'kids',
    subcategory:    'Boys',
    price:          18.57,
    originalPrice:  29.47,
    discount:       37,
    rating:         4.4,
    reviews:        11698,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "onesie", "boys", "girls"]
  },
  {
    id:             'ama-kids-021',
    name:           'Rainbow Knit Cardigan',
    category:       'kids',
    subcategory:    'Baby',
    price:          68.55,
    originalPrice:  116.18,
    discount:       41,
    rating:         5.0,
    reviews:        2840,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "cardigan", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-022',
    name:           'Football Kit Set',
    category:       'kids',
    subcategory:    'School Wear',
    price:          10.62,
    originalPrice:  27.24,
    discount:       61,
    rating:         4.4,
    reviews:        14613,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-023',
    name:           'Tropical Print Board Shorts',
    category:       'kids',
    subcategory:    'Toys',
    price:          15.59,
    originalPrice:  29.99,
    discount:       48,
    rating:         4.4,
    reviews:        15887,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "shorts", "boys", "girls"]
  },
  {
    id:             'ama-kids-024',
    name:           'Tiered Frill Skirt',
    category:       'kids',
    subcategory:    'Footwear',
    price:          39.44,
    originalPrice:  52.58,
    discount:       25,
    rating:         4.6,
    reviews:        7823,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "boys", "skirt", "girls"]
  },
  {
    id:             'ama-kids-025',
    name:           'School Cardigan — Navy',
    category:       'kids',
    subcategory:    'Girls',
    price:          35.72,
    originalPrice:  61.58,
    discount:       42,
    rating:         4.8,
    reviews:        17368,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "cardigan", "boys", "girls"]
  },
  {
    id:             'ama-kids-026',
    name:           'Jungle Print Playsuit',
    category:       'kids',
    subcategory:    'Boys',
    price:          41.97,
    originalPrice:  107.61,
    discount:       61,
    rating:         4.6,
    reviews:        19064,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "playsuit", "girls"]
  },
  {
    id:             'ama-kids-027',
    name:           'Stars & Stripes Hoodie',
    category:       'kids',
    subcategory:    'Baby',
    price:          52.14,
    originalPrice:  73.43,
    discount:       29,
    rating:         4.0,
    reviews:        18573,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["hoodie", "children", "kids", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-028',
    name:           'Princess Dress-Up Gown',
    category:       'kids',
    subcategory:    'School Wear',
    price:          24.09,
    originalPrice:  38.85,
    discount:       38,
    rating:         4.5,
    reviews:        902,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "gown", "boys", "girls"]
  },
  {
    id:             'ama-kids-029',
    name:           'Waterproof Splash Suit',
    category:       'kids',
    subcategory:    'Toys',
    price:          63.86,
    originalPrice:  88.69,
    discount:       28,
    rating:         4.9,
    reviews:        21072,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "boys", "suit", "girls"]
  },
  {
    id:             'ama-kids-030',
    name:           'Gingham Smock Dress',
    category:       'kids',
    subcategory:    'Footwear',
    price:          36.82,
    originalPrice:  73.64,
    discount:       50,
    rating:         4.8,
    reviews:        24519,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "boys", "dress", "girls"]
  },
  {
    id:             'ama-kids-031',
    name:           'Denim Shorts — Distressed',
    category:       'kids',
    subcategory:    'Girls',
    price:          49.01,
    originalPrice:  66.23,
    discount:       26,
    rating:         4.3,
    reviews:        13849,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "shorts", "boys", "girls"]
  },
  {
    id:             'ama-kids-032',
    name:           'Pom-Pom Hat & Scarf Set',
    category:       'kids',
    subcategory:    'Boys',
    price:          39.39,
    originalPrice:  106.47,
    discount:       63,
    rating:         4.8,
    reviews:        2878,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-033',
    name:           'Quilted Vest — Pink',
    category:       'kids',
    subcategory:    'Baby',
    price:          32.24,
    originalPrice:  68.59,
    discount:       53,
    rating:         4.2,
    reviews:        15979,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "vest", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-034',
    name:           'Floral Print Skort',
    category:       'kids',
    subcategory:    'School Wear',
    price:          41.86,
    originalPrice:  80.5,
    discount:       48,
    rating:         4.5,
    reviews:        3936,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "boys", "skort", "girls"]
  },
  {
    id:             'ama-kids-035',
    name:           'Stripe Rib Knit Jumper',
    category:       'kids',
    subcategory:    'Toys',
    price:          44.86,
    originalPrice:  91.55,
    discount:       51,
    rating:         4.1,
    reviews:        19617,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "boys", "jumper", "girls"]
  },
  {
    id:             'ama-kids-036',
    name:           'Cosy Teddy Fleece Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          18.63,
    originalPrice:  47.77,
    discount:       61,
    rating:         4.3,
    reviews:        23220,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-037',
    name:           'Dinosaur Hooded Towel Robe',
    category:       'kids',
    subcategory:    'Girls',
    price:          59.69,
    originalPrice:  86.51,
    discount:       31,
    rating:         4.6,
    reviews:        11820,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "robe", "boys", "girls"]
  },
  {
    id:             'ama-kids-038',
    name:           'Sequin Mermaid Dress',
    category:       'kids',
    subcategory:    'Boys',
    price:          39.72,
    originalPrice:  58.41,
    discount:       32,
    rating:         4.8,
    reviews:        13775,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ama-kids-039',
    name:           'Sports Jogger Set',
    category:       'kids',
    subcategory:    'Baby',
    price:          25.07,
    originalPrice:  45.59,
    discount:       45,
    rating:         4.7,
    reviews:        4941,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "set", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-040',
    name:           'Bunny Embroidery Blouse',
    category:       'kids',
    subcategory:    'School Wear',
    price:          9.64,
    originalPrice:  17.52,
    discount:       45,
    rating:         4.2,
    reviews:        9752,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "blouse", "boys", "girls"]
  },
  {
    id:             'ama-kids-041',
    name:           'Tie-Dye Shorts Set',
    category:       'kids',
    subcategory:    'Toys',
    price:          27.65,
    originalPrice:  51.2,
    discount:       46,
    rating:         4.9,
    reviews:        15605,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-042',
    name:           'Monster Truck Tee',
    category:       'kids',
    subcategory:    'Footwear',
    price:          58.15,
    originalPrice:  84.28,
    discount:       31,
    rating:         4.1,
    reviews:        14925,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "boys", "tee", "girls"]
  },
  {
    id:             'ama-kids-043',
    name:           'Floral Wrap Dress — Baby',
    category:       'kids',
    subcategory:    'Girls',
    price:          11.56,
    originalPrice:  19.26,
    discount:       40,
    rating:         4.4,
    reviews:        20938,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  },
  {
    id:             'ama-kids-044',
    name:           'Patchwork Denim Jacket',
    category:       'kids',
    subcategory:    'Boys',
    price:          14.25,
    originalPrice:  21.93,
    discount:       35,
    rating:         4.3,
    reviews:        13616,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "children", "kids", "boys", "girls"]
  },
  {
    id:             'ama-kids-045',
    name:           'Fruit Print Swimsuit',
    category:       'kids',
    subcategory:    'Baby',
    price:          33.43,
    originalPrice:  42.86,
    discount:       22,
    rating:         4.7,
    reviews:        11939,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "swimsuit", "boys", "baby", "girls"]
  },
  {
    id:             'ama-kids-046',
    name:           'Corduroy Dungarees — Rust',
    category:       'kids',
    subcategory:    'School Wear',
    price:          12.63,
    originalPrice:  33.23,
    discount:       62,
    rating:         4.5,
    reviews:        22535,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471286174890-9c112ff6122b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "school_wear", "dungarees", "boys", "girls"]
  },
  {
    id:             'ama-kids-047',
    name:           'Glitter Tulle Skirt',
    category:       'kids',
    subcategory:    'Toys',
    price:          41.34,
    originalPrice:  59.91,
    discount:       31,
    rating:         5.0,
    reviews:        4155,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "toys", "boys", "skirt", "girls"]
  },
  {
    id:             'ama-kids-048',
    name:           'Animal Print Velour Set',
    category:       'kids',
    subcategory:    'Footwear',
    price:          47.02,
    originalPrice:  102.21,
    discount:       54,
    rating:         4.3,
    reviews:        10658,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576773689115-5cd2b0223523?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "footwear", "set", "boys", "girls"]
  },
  {
    id:             'ama-kids-049',
    name:           'Organic Cotton Babygrow',
    category:       'kids',
    subcategory:    'Girls',
    price:          37.62,
    originalPrice:  51.53,
    discount:       27,
    rating:         4.3,
    reviews:        14888,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "babygrow", "kids", "boys", "girls"]
  },
  {
    id:             'ama-kids-050',
    name:           'Birthday Girl Sash Dress',
    category:       'kids',
    subcategory:    'Boys',
    price:          12.39,
    originalPrice:  28.81,
    discount:       57,
    rating:         4.7,
    reviews:        1466,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0KIDS050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["children", "kids", "boys", "dress", "girls"]
  }
);
