/* AMAZON — Pets (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-pets-001',
    name:           'Multi-Level Cat Tree with Scratching Post',
    category:       'pets',
    subcategory:    'Dogs',
    price:          7.84,
    originalPrice:  15.08,
    discount:       48,
    rating:         4.8,
    reviews:        14100,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "post", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-002',
    name:           'Cosy Self-Warming Pet Bed — L Size',
    category:       'pets',
    subcategory:    'Cats',
    price:          25.07,
    originalPrice:  58.31,
    discount:       57,
    rating:         4.5,
    reviews:        999,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "bed", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-003',
    name:           'Interactive Cat Feather Wand Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          76.61,
    originalPrice:  111.03,
    discount:       31,
    rating:         4.8,
    reviews:        4685,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'ama-pets-004',
    name:           'Premium Cat Food — Chicken & Fish 2kg',
    category:       'pets',
    subcategory:    'Fish',
    price:          31.56,
    originalPrice:  45.08,
    discount:       30,
    rating:         4.6,
    reviews:        20919,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "food", "fish", "cat", "animal"]
  },
  {
    id:             'ama-pets-005',
    name:           'GPS Dog Collar Tracker',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          38.14,
    originalPrice:  90.82,
    discount:       58,
    rating:         4.9,
    reviews:        1316,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["tracker", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-006',
    name:           'Automatic Pet Feeder — WiFi',
    category:       'pets',
    subcategory:    'Supplies',
    price:          21.25,
    originalPrice:  40.09,
    discount:       47,
    rating:         4.4,
    reviews:        1420,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["feeder", "pets", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'ama-pets-007',
    name:           'Foldable Dog Travel Crate',
    category:       'pets',
    subcategory:    'Dogs',
    price:          8.54,
    originalPrice:  17.43,
    discount:       51,
    rating:         4.6,
    reviews:        7384,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "dogs", "crate", "cat", "animal"]
  },
  {
    id:             'ama-pets-008',
    name:           'Dog Grooming Kit — 5 Piece',
    category:       'pets',
    subcategory:    'Cats',
    price:          50.3,
    originalPrice:  81.13,
    discount:       38,
    rating:         4.2,
    reviews:        23138,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "kit", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-009',
    name:           'Catnip Plush Mouse Toy Set',
    category:       'pets',
    subcategory:    'Birds',
    price:          16.01,
    originalPrice:  29.11,
    discount:       45,
    rating:         4.5,
    reviews:        13901,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "birds", "set", "cat", "animal"]
  },
  {
    id:             'ama-pets-010',
    name:           'Slow Feeder Dog Bowl',
    category:       'pets',
    subcategory:    'Fish',
    price:          46.71,
    originalPrice:  80.53,
    discount:       42,
    rating:         4.5,
    reviews:        14248,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "animal", "fish", "cat", "bowl"]
  },
  {
    id:             'ama-pets-011',
    name:           'Cat Litter Box — Top Entry',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          36.9,
    originalPrice:  54.26,
    discount:       32,
    rating:         4.3,
    reviews:        10769,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-012',
    name:           'Dog Raincoat — Waterproof',
    category:       'pets',
    subcategory:    'Supplies',
    price:          54.33,
    originalPrice:  86.24,
    discount:       37,
    rating:         4.4,
    reviews:        5081,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "supplies", "raincoat", "cat", "animal"]
  },
  {
    id:             'ama-pets-013',
    name:           'Bird Cage Deluxe — 2 Storey',
    category:       'pets',
    subcategory:    'Dogs',
    price:          58.72,
    originalPrice:  75.28,
    discount:       22,
    rating:         4.6,
    reviews:        5037,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "dogs", "deluxe", "cat", "animal"]
  },
  {
    id:             'ama-pets-014',
    name:           'Aquarium LED Light — 30cm',
    category:       'pets',
    subcategory:    'Cats',
    price:          42.14,
    originalPrice:  105.34,
    discount:       60,
    rating:         4.6,
    reviews:        24736,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "light", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-015',
    name:           'Hamster Exercise Wheel — Silent',
    category:       'pets',
    subcategory:    'Birds',
    price:          7.01,
    originalPrice:  12.52,
    discount:       44,
    rating:         4.9,
    reviews:        6643,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "wheel", "birds", "cat", "animal"]
  },
  {
    id:             'ama-pets-016',
    name:           'Puppy Training Pads — 100pk',
    category:       'pets',
    subcategory:    'Fish',
    price:          51.39,
    originalPrice:  93.44,
    discount:       45,
    rating:         4.8,
    reviews:        24096,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "pads", "fish", "cat", "animal"]
  },
  {
    id:             'ama-pets-017',
    name:           'Self-Cleaning Litter Box',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          25.94,
    originalPrice:  61.75,
    discount:       58,
    rating:         4.8,
    reviews:        1174,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-018',
    name:           'Orthopedic Dog Bed — Memory Foam',
    category:       'pets',
    subcategory:    'Supplies',
    price:          25.09,
    originalPrice:  33.9,
    discount:       26,
    rating:         4.8,
    reviews:        20867,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "bed", "supplies", "cat", "animal"]
  },
  {
    id:             'ama-pets-019',
    name:           'Cat Window Perch — Suction Cup',
    category:       'pets',
    subcategory:    'Dogs',
    price:          26.87,
    originalPrice:  40.71,
    discount:       34,
    rating:         4.1,
    reviews:        16190,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "perch", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-020',
    name:           'Retractable Dog Lead — 5m',
    category:       'pets',
    subcategory:    'Cats',
    price:          26.29,
    originalPrice:  33.71,
    discount:       22,
    rating:         4.7,
    reviews:        18251,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "lead", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-021',
    name:           'Pet Carrier Backpack — Breathable',
    category:       'pets',
    subcategory:    'Birds',
    price:          48.83,
    originalPrice:  64.25,
    discount:       24,
    rating:         4.5,
    reviews:        21949,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "birds", "backpack", "cat", "animal"]
  },
  {
    id:             'ama-pets-022',
    name:           'Cat Drinking Fountain — Filtered',
    category:       'pets',
    subcategory:    'Fish',
    price:          35.23,
    originalPrice:  55.92,
    discount:       37,
    rating:         4.5,
    reviews:        19038,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "fountain", "fish", "cat", "animal"]
  },
  {
    id:             'ama-pets-023',
    name:           'Dog Puzzle Toy — IQ Level 2',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          41.03,
    originalPrice:  77.42,
    discount:       47,
    rating:         5.0,
    reviews:        5734,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "small_pets", "toy", "cat", "animal"]
  },
  {
    id:             'ama-pets-024',
    name:           'Plush Squeaky Dog Toy Set',
    category:       'pets',
    subcategory:    'Supplies',
    price:          34.21,
    originalPrice:  52.63,
    discount:       35,
    rating:         4.8,
    reviews:        4448,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "supplies", "set", "cat", "animal"]
  },
  {
    id:             'ama-pets-025',
    name:           'Flea & Tick Collar',
    category:       'pets',
    subcategory:    'Dogs',
    price:          39.38,
    originalPrice:  78.75,
    discount:       50,
    rating:         4.2,
    reviews:        24882,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "collar", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-026',
    name:           'Dental Chews — 30 Pack',
    category:       'pets',
    subcategory:    'Cats',
    price:          23.01,
    originalPrice:  39.0,
    discount:       41,
    rating:         4.8,
    reviews:        302,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "chews", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-027',
    name:           'Heated Cat Cave Bed',
    category:       'pets',
    subcategory:    'Birds',
    price:          27.35,
    originalPrice:  38.52,
    discount:       29,
    rating:         4.0,
    reviews:        13484,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "bed", "birds", "cat", "animal"]
  },
  {
    id:             'ama-pets-028',
    name:           'Dog Cooling Mat — Gel',
    category:       'pets',
    subcategory:    'Fish',
    price:          42.16,
    originalPrice:  62.0,
    discount:       32,
    rating:         4.5,
    reviews:        16773,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "fish", "mat", "cat", "animal"]
  },
  {
    id:             'ama-pets-029',
    name:           'Pet Stroller — 3 Wheeler',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          57.4,
    originalPrice:  106.29,
    discount:       46,
    rating:         4.1,
    reviews:        7171,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "small_pets", "stroller", "cat", "animal"]
  },
  {
    id:             'ama-pets-030',
    name:           'Rabbit Hutch — 2 Storey',
    category:       'pets',
    subcategory:    'Supplies',
    price:          13.9,
    originalPrice:  26.23,
    discount:       47,
    rating:         4.3,
    reviews:        8912,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "hutch", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'ama-pets-031',
    name:           'Fish Tank Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          61.28,
    originalPrice:  117.85,
    discount:       48,
    rating:         4.4,
    reviews:        1362,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-032',
    name:           'Cat Scratching Pad — Cardboard',
    category:       'pets',
    subcategory:    'Cats',
    price:          44.98,
    originalPrice:  112.46,
    discount:       60,
    rating:         4.8,
    reviews:        10303,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "pad", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-033',
    name:           'Interactive Laser Cat Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          31.92,
    originalPrice:  86.27,
    discount:       63,
    rating:         4.6,
    reviews:        24949,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'ama-pets-034',
    name:           'Dog Harness — No-Pull',
    category:       'pets',
    subcategory:    'Fish',
    price:          17.22,
    originalPrice:  43.06,
    discount:       60,
    rating:         4.5,
    reviews:        23682,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "harness", "fish", "cat", "animal"]
  },
  {
    id:             'ama-pets-035',
    name:           'Pet Camera Monitor',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          37.7,
    originalPrice:  81.95,
    discount:       54,
    rating:         4.8,
    reviews:        18960,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "monitor", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-036',
    name:           'Small Animal Hideout Tunnel',
    category:       'pets',
    subcategory:    'Supplies',
    price:          38.24,
    originalPrice:  69.53,
    discount:       45,
    rating:         4.6,
    reviews:        15313,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "supplies", "tunnel", "cat", "animal"]
  },
  {
    id:             'ama-pets-037',
    name:           'Bird Seed Mix — Premium',
    category:       'pets',
    subcategory:    'Dogs',
    price:          34.37,
    originalPrice:  54.55,
    discount:       37,
    rating:         4.1,
    reviews:        5600,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "mix", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-038',
    name:           'Dog Raincoat — Reflective',
    category:       'pets',
    subcategory:    'Cats',
    price:          27.73,
    originalPrice:  61.63,
    discount:       55,
    rating:         4.6,
    reviews:        19841,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "raincoat", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-039',
    name:           'Cat Toy Ball Track',
    category:       'pets',
    subcategory:    'Birds',
    price:          12.69,
    originalPrice:  32.53,
    discount:       61,
    rating:         4.5,
    reviews:        17881,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "track", "birds", "cat", "animal"]
  },
  {
    id:             'ama-pets-040',
    name:           'Dog Agility Training Set',
    category:       'pets',
    subcategory:    'Fish',
    price:          31.42,
    originalPrice:  80.57,
    discount:       61,
    rating:         4.7,
    reviews:        12340,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "set", "fish", "cat", "animal"]
  },
  {
    id:             'ama-pets-041',
    name:           'Pet First Aid Kit',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          68.23,
    originalPrice:  93.47,
    discount:       27,
    rating:         5.0,
    reviews:        20283,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "kit", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-042',
    name:           'Catnip Spray — Organic',
    category:       'pets',
    subcategory:    'Supplies',
    price:          12.41,
    originalPrice:  17.99,
    discount:       31,
    rating:         4.8,
    reviews:        3512,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "supplies", "spray", "cat", "animal"]
  },
  {
    id:             'ama-pets-043',
    name:           'Dog Snuffle Mat',
    category:       'pets',
    subcategory:    'Dogs',
    price:          30.39,
    originalPrice:  67.54,
    discount:       55,
    rating:         4.1,
    reviews:        20209,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "dogs", "mat", "cat", "animal"]
  },
  {
    id:             'ama-pets-044',
    name:           'Silicone Pet Food Mat',
    category:       'pets',
    subcategory:    'Cats',
    price:          41.82,
    originalPrice:  104.56,
    discount:       60,
    rating:         4.1,
    reviews:        22307,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "mat", "cat", "animal", "cats"]
  },
  {
    id:             'ama-pets-045',
    name:           'Pet Nail Grinder — Quiet',
    category:       'pets',
    subcategory:    'Birds',
    price:          43.84,
    originalPrice:  71.87,
    discount:       39,
    rating:         4.7,
    reviews:        10111,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "birds", "grinder", "cat", "animal"]
  },
  {
    id:             'ama-pets-046',
    name:           'Bird Perch Stand',
    category:       'pets',
    subcategory:    'Fish',
    price:          24.98,
    originalPrice:  32.87,
    discount:       24,
    rating:         4.0,
    reviews:        3605,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "fish", "stand", "cat", "animal"]
  },
  {
    id:             'ama-pets-047',
    name:           'Dog Life Jacket',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          70.09,
    originalPrice:  101.58,
    discount:       31,
    rating:         5.0,
    reviews:        16043,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["jacket", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'ama-pets-048',
    name:           'Cat Collar with Bell',
    category:       'pets',
    subcategory:    'Supplies',
    price:          32.33,
    originalPrice:  87.39,
    discount:       63,
    rating:         4.2,
    reviews:        6629,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "supplies", "bell", "cat", "animal"]
  },
  {
    id:             'ama-pets-049',
    name:           'Kitten Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          17.62,
    originalPrice:  35.96,
    discount:       51,
    rating:         4.1,
    reviews:        496,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'ama-pets-050',
    name:           'Puppy Welcome Home Set',
    category:       'pets',
    subcategory:    'Cats',
    price:          66.62,
    originalPrice:  95.17,
    discount:       30,
    rating:         4.0,
    reviews:        16845,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0PETS050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["pets", "dog", "set", "cat", "animal", "cats"]
  }
);
