/* AMAZON — Shoes (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-amazon.js index file
*/

window.AmazonProducts = window.AmazonProducts || [];

window.AmazonProducts.push(
  {
    id:             'ama-shoe-001',
    name:           'Women\'s Platform Sneakers — White',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          18.79,
    originalPrice:  37.57,
    discount:       50,
    rating:         4.6,
    reviews:        17041,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE001?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ama-shoe-002',
    name:           'Chunky Platform Loafers — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          75.15,
    originalPrice:  97.6,
    discount:       23,
    rating:         4.5,
    reviews:        15068,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE002?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes"]
  },
  {
    id:             'ama-shoe-003',
    name:           'Men\'s Casual Sneakers — White',
    category:       'shoes',
    subcategory:    'Flats',
    price:          11.9,
    originalPrice:  26.45,
    discount:       55,
    rating:         4.8,
    reviews:        10465,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE003?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ama-shoe-004',
    name:           'Ankle Strap Block Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          42.72,
    originalPrice:  54.08,
    discount:       21,
    rating:         4.1,
    reviews:        2465,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE004?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-005',
    name:           'Bata Comfort Sandals — Women\'s',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          41.84,
    originalPrice:  95.08,
    discount:       56,
    rating:         4.9,
    reviews:        11897,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE005?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-006',
    name:           'Chelsea Boots — Tan Leather',
    category:       'shoes',
    subcategory:    'Sport',
    price:          62.38,
    originalPrice:  90.4,
    discount:       31,
    rating:         4.3,
    reviews:        19214,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE006?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-007',
    name:           'High Top Canvas Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          8.51,
    originalPrice:  14.18,
    discount:       40,
    rating:         4.8,
    reviews:        5549,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE007?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'ama-shoe-008',
    name:           'Stiletto Heeled Mules',
    category:       'shoes',
    subcategory:    'Heels',
    price:          20.98,
    originalPrice:  31.31,
    discount:       33,
    rating:         4.7,
    reviews:        16374,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE008?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'ama-shoe-009',
    name:           'Running Trainers — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          7.1,
    originalPrice:  12.03,
    discount:       41,
    rating:         4.2,
    reviews:        5689,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE009?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'ama-shoe-010',
    name:           'Strappy Kitten Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          10.99,
    originalPrice:  23.38,
    discount:       53,
    rating:         5.0,
    reviews:        4970,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE010?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-011',
    name:           'Slip-On Loafers — Suede',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          78.78,
    originalPrice:  115.85,
    discount:       32,
    rating:         4.2,
    reviews:        16194,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE011?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-012',
    name:           'Combat Boots — Lace Up',
    category:       'shoes',
    subcategory:    'Sport',
    price:          31.36,
    originalPrice:  43.56,
    discount:       28,
    rating:         4.9,
    reviews:        9431,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE012?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-013',
    name:           'Wedge Espadrilles — Nude',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          60.62,
    originalPrice:  118.86,
    discount:       49,
    rating:         4.6,
    reviews:        17608,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE013?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'ama-shoe-014',
    name:           'Pointed Toe Pumps — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          68.81,
    originalPrice:  86.01,
    discount:       20,
    rating:         4.5,
    reviews:        15281,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE014?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "pumps"]
  },
  {
    id:             'ama-shoe-015',
    name:           'Kids\' Light-Up Trainers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          18.11,
    originalPrice:  33.53,
    discount:       46,
    rating:         4.8,
    reviews:        1394,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE015?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'ama-shoe-016',
    name:           'Hiking Boots — Waterproof',
    category:       'shoes',
    subcategory:    'Boots',
    price:          36.04,
    originalPrice:  92.41,
    discount:       61,
    rating:         4.9,
    reviews:        7803,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE016?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-017',
    name:           'Ballet Flats — Blush Pink',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          58.27,
    originalPrice:  75.67,
    discount:       23,
    rating:         4.3,
    reviews:        10531,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE017?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-018',
    name:           'Over-Knee Boots — Tan',
    category:       'shoes',
    subcategory:    'Sport',
    price:          54.15,
    originalPrice:  67.69,
    discount:       20,
    rating:         4.7,
    reviews:        4450,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE018?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-019',
    name:           'Knit Sock Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          16.75,
    originalPrice:  41.87,
    discount:       60,
    rating:         4.8,
    reviews:        18527,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE019?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'ama-shoe-020',
    name:           'T-Bar Mary Jane Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          77.65,
    originalPrice:  104.93,
    discount:       26,
    rating:         4.3,
    reviews:        12031,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE020?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ama-shoe-021',
    name:           'Kids\' Wellies — Polka Dot',
    category:       'shoes',
    subcategory:    'Flats',
    price:          55.09,
    originalPrice:  69.74,
    discount:       21,
    rating:         4.5,
    reviews:        12057,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE021?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "wellies", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ama-shoe-022',
    name:           'Slingback Kitten Heels',
    category:       'shoes',
    subcategory:    'Boots',
    price:          8.83,
    originalPrice:  21.02,
    discount:       58,
    rating:         4.4,
    reviews:        20343,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE022?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-023',
    name:           'Square-Toe Mules — Croc Effect',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          62.87,
    originalPrice:  112.27,
    discount:       44,
    rating:         4.6,
    reviews:        12744,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE023?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-024',
    name:           'Gladiator Sandals',
    category:       'shoes',
    subcategory:    'Sport',
    price:          75.97,
    originalPrice:  97.4,
    discount:       22,
    rating:         4.2,
    reviews:        5604,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE024?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-025',
    name:           'Ankle Boots — Stacked Heel',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          27.36,
    originalPrice:  44.85,
    discount:       39,
    rating:         4.6,
    reviews:        18681,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE025?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-026',
    name:           'Velvet Court Shoes — Emerald',
    category:       'shoes',
    subcategory:    'Heels',
    price:          20.48,
    originalPrice:  31.5,
    discount:       35,
    rating:         4.8,
    reviews:        23107,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE026?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ama-shoe-027',
    name:           'Flip Flops — Foam',
    category:       'shoes',
    subcategory:    'Flats',
    price:          62.23,
    originalPrice:  103.71,
    discount:       40,
    rating:         4.1,
    reviews:        19962,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE027?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "flops", "shoes"]
  },
  {
    id:             'ama-shoe-028',
    name:           'Lace-Up Oxford Brogues',
    category:       'shoes',
    subcategory:    'Boots',
    price:          30.53,
    originalPrice:  39.14,
    discount:       22,
    rating:         4.2,
    reviews:        17077,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE028?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "brogues", "shoes"]
  },
  {
    id:             'ama-shoe-029',
    name:           'Metallic Strappy Heels',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          71.44,
    originalPrice:  111.63,
    discount:       36,
    rating:         4.4,
    reviews:        20269,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE029?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-030',
    name:           'Platform Chelsea Boots',
    category:       'shoes',
    subcategory:    'Sport',
    price:          4.69,
    originalPrice:  13.39,
    discount:       65,
    rating:         4.4,
    reviews:        14708,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE030?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-031',
    name:           'Open-Toe Wedge Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          15.24,
    originalPrice:  22.74,
    discount:       33,
    rating:         4.6,
    reviews:        20625,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE031?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-032',
    name:           'Moccasin Slippers',
    category:       'shoes',
    subcategory:    'Heels',
    price:          26.55,
    originalPrice:  63.22,
    discount:       58,
    rating:         4.7,
    reviews:        14182,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE032?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "slippers", "footwear", "heels", "shoes"]
  },
  {
    id:             'ama-shoe-033',
    name:           'Sporty Slides — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          21.24,
    originalPrice:  33.19,
    discount:       36,
    rating:         4.4,
    reviews:        17741,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE033?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "slides", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ama-shoe-034',
    name:           'Peep-Toe Slingbacks',
    category:       'shoes',
    subcategory:    'Boots',
    price:          39.59,
    originalPrice:  50.76,
    discount:       22,
    rating:         4.1,
    reviews:        624,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE034?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "slingbacks"]
  },
  {
    id:             'ama-shoe-035',
    name:           'Classic White Tennis Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          15.35,
    originalPrice:  43.85,
    discount:       65,
    rating:         4.2,
    reviews:        7796,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE035?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-036',
    name:           'Dad Trainer — Chunky',
    category:       'shoes',
    subcategory:    'Sport',
    price:          42.39,
    originalPrice:  73.09,
    discount:       42,
    rating:         4.1,
    reviews:        20815,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE036?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "trainer", "sport", "shoes"]
  },
  {
    id:             'ama-shoe-037',
    name:           'Espadrille Wedge Mules',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          41.49,
    originalPrice:  96.48,
    discount:       57,
    rating:         4.3,
    reviews:        5444,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE037?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'ama-shoe-038',
    name:           'Patent Ankle Strap Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          47.06,
    originalPrice:  81.13,
    discount:       42,
    rating:         4.5,
    reviews:        13239,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE038?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ama-shoe-039',
    name:           'Knee High Flat Boots',
    category:       'shoes',
    subcategory:    'Flats',
    price:          59.2,
    originalPrice:  74.0,
    discount:       20,
    rating:         4.7,
    reviews:        20056,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE039?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-040',
    name:           'Woven Mule Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          20.43,
    originalPrice:  41.7,
    discount:       51,
    rating:         5.0,
    reviews:        13946,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE040?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-041',
    name:           'Men\'s Derby Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          54.77,
    originalPrice:  74.02,
    discount:       26,
    rating:         4.8,
    reviews:        16118,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE041?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-042',
    name:           'Snow Boots — Fur Lined',
    category:       'shoes',
    subcategory:    'Sport',
    price:          24.44,
    originalPrice:  52.0,
    discount:       53,
    rating:         4.1,
    reviews:        24968,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE042?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'ama-shoe-043',
    name:           'Transparent Heeled Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          22.1,
    originalPrice:  41.69,
    discount:       47,
    rating:         4.2,
    reviews:        13716,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE043?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-044',
    name:           'Slip-On Canvas Espadrilles',
    category:       'shoes',
    subcategory:    'Heels',
    price:          76.46,
    originalPrice:  115.85,
    discount:       34,
    rating:         4.2,
    reviews:        374,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE044?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'ama-shoe-045',
    name:           'Low Top Leather Sneakers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          43.24,
    originalPrice:  56.89,
    discount:       24,
    rating:         4.0,
    reviews:        5112,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE045?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'ama-shoe-046',
    name:           'Platform Flip Flop Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          88.37,
    originalPrice:  119.42,
    discount:       26,
    rating:         4.3,
    reviews:        21102,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE046?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-047',
    name:           'Ankle Boots — Pointed Toe',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          43.13,
    originalPrice:  60.74,
    discount:       29,
    rating:         4.4,
    reviews:        3999,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE047?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'ama-shoe-048',
    name:           'Sporty Slides — Women\'s',
    category:       'shoes',
    subcategory:    'Sport',
    price:          67.85,
    originalPrice:  115.0,
    discount:       41,
    rating:         4.2,
    reviews:        21324,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE048?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["sneakers", "slides", "footwear", "heels", "sport", "shoes"]
  },
  {
    id:             'ama-shoe-049',
    name:           'Men\'s Boat Shoes — Tan',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          60.58,
    originalPrice:  104.45,
    discount:       42,
    rating:         4.7,
    reviews:        24939,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE049?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'ama-shoe-050',
    name:           'Kids\' School Shoes — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          44.84,
    originalPrice:  64.06,
    discount:       30,
    rating:         4.6,
    reviews:        10409,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.amazon.com/dp/B0SHOE050?tag=meowmeow-21',
    marketplace:    'Amazon',
    marketplaceIcon: 'fab fa-amazon',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  }
);
