/* TEMU — Accessories (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-acce-001',
    name:           'Oversized Sunglasses — UV400 Retro',
    category:       'accessories',
    subcategory:    'Hats',
    price:          30.76,
    originalPrice:  49.62,
    discount:       38,
    rating:         4.4,
    reviews:        6313,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "sunglasses", "style", "outfit"]
  },
  {
    id:             'tem-acce-002',
    name:           'Claw Hair Clips Set — 6 Pack Pastel',
    category:       'accessories',
    subcategory:    'Belts',
    price:          23.71,
    originalPrice:  52.68,
    discount:       55,
    rating:         4.1,
    reviews:        13040,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "set", "belts", "outfit"]
  },
  {
    id:             'tem-acce-003',
    name:           'Bucket Hat — Cotton Summer',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          31.97,
    originalPrice:  69.49,
    discount:       54,
    rating:         4.1,
    reviews:        253,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "hat", "style", "outfit"]
  },
  {
    id:             'tem-acce-004',
    name:           'Knitted Beanie — Pom Pom',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          32.52,
    originalPrice:  65.03,
    discount:       50,
    rating:         4.1,
    reviews:        2948,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "beanie", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-005',
    name:           'Leopard Print Headband',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          38.72,
    originalPrice:  75.93,
    discount:       49,
    rating:         4.1,
    reviews:        20378,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "headband", "hair_accessories", "accessories", "style", "outfit"]
  },
  {
    id:             'tem-acce-006',
    name:           'Silk Hair Scrunchie Set — 10 Pack',
    category:       'accessories',
    subcategory:    'Hats',
    price:          34.74,
    originalPrice:  43.42,
    discount:       20,
    rating:         4.4,
    reviews:        20827,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "style", "set", "outfit"]
  },
  {
    id:             'tem-acce-007',
    name:           'Straw Cowboy Hat — Beach',
    category:       'accessories',
    subcategory:    'Belts',
    price:          22.07,
    originalPrice:  63.05,
    discount:       65,
    rating:         4.8,
    reviews:        11232,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hat", "style", "belts", "outfit"]
  },
  {
    id:             'tem-acce-008',
    name:           'Wool Tartan Scarf',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          69.92,
    originalPrice:  112.77,
    discount:       38,
    rating:         4.7,
    reviews:        846,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "scarf", "outfit"]
  },
  {
    id:             'tem-acce-009',
    name:           'Wide Brim Sun Hat — Beach',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          54.35,
    originalPrice:  93.7,
    discount:       42,
    rating:         4.8,
    reviews:        14091,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hat", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-010',
    name:           'Leather Belt — Braided',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          6.3,
    originalPrice:  15.76,
    discount:       60,
    rating:         5.0,
    reviews:        23644,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "belt", "style", "outfit"]
  },
  {
    id:             'tem-acce-011',
    name:           'Men\'s Flat Cap — Herringbone',
    category:       'accessories',
    subcategory:    'Hats',
    price:          22.86,
    originalPrice:  33.13,
    discount:       31,
    rating:         4.7,
    reviews:        6863,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "cap", "style", "outfit"]
  },
  {
    id:             'tem-acce-012',
    name:           'Ladies\' Beret — Wool',
    category:       'accessories',
    subcategory:    'Belts',
    price:          35.81,
    originalPrice:  50.44,
    discount:       29,
    rating:         5.0,
    reviews:        18355,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "belts", "beret", "outfit"]
  },
  {
    id:             'tem-acce-013',
    name:           'Transparent Rain Scarf — Headband',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          67.89,
    originalPrice:  119.11,
    discount:       43,
    rating:         4.2,
    reviews:        12636,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "scarf", "outfit"]
  },
  {
    id:             'tem-acce-014',
    name:           'Men\'s Tie Set — 3 Pack',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          8.82,
    originalPrice:  18.0,
    discount:       51,
    rating:         5.0,
    reviews:        21855,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "set", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-015',
    name:           'Silk Scarf — Floral Print',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          42.45,
    originalPrice:  64.32,
    discount:       34,
    rating:         4.6,
    reviews:        18922,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "scarf", "outfit"]
  },
  {
    id:             'tem-acce-016',
    name:           'Bow Hair Clip — Satin Large',
    category:       'accessories',
    subcategory:    'Hats',
    price:          45.8,
    originalPrice:  81.79,
    discount:       44,
    rating:         4.6,
    reviews:        21872,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "clip", "accessories", "hats", "style", "outfit"]
  },
  {
    id:             'tem-acce-017',
    name:           'Sun Visor Hat — Athletic',
    category:       'accessories',
    subcategory:    'Belts',
    price:          35.8,
    originalPrice:  74.58,
    discount:       52,
    rating:         4.6,
    reviews:        2173,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hat", "style", "belts", "outfit"]
  },
  {
    id:             'tem-acce-018',
    name:           'Cold Weather Ear Muffs',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          41.13,
    originalPrice:  102.83,
    discount:       60,
    rating:         4.6,
    reviews:        3395,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "muffs", "outfit"]
  },
  {
    id:             'tem-acce-019',
    name:           'Velvet Alice Band',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          12.01,
    originalPrice:  20.71,
    discount:       42,
    rating:         4.2,
    reviews:        8309,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "band", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-020',
    name:           'Men\'s Pocket Square Set',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          57.71,
    originalPrice:  72.14,
    discount:       20,
    rating:         4.7,
    reviews:        1847,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "set", "outfit"]
  },
  {
    id:             'tem-acce-021',
    name:           'Wide Brim Floppy Hat — Black',
    category:       'accessories',
    subcategory:    'Hats',
    price:          70.42,
    originalPrice:  97.81,
    discount:       28,
    rating:         4.8,
    reviews:        18483,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "hat", "style", "outfit"]
  },
  {
    id:             'tem-acce-022',
    name:           'Ribbon Choker Set',
    category:       'accessories',
    subcategory:    'Belts',
    price:          65.82,
    originalPrice:  91.42,
    discount:       28,
    rating:         4.6,
    reviews:        2217,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "set", "belts", "outfit"]
  },
  {
    id:             'tem-acce-023',
    name:           'Hair Claw Clips — Marble Effect',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          6.5,
    originalPrice:  17.11,
    discount:       62,
    rating:         4.6,
    reviews:        16797,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "clips", "outfit"]
  },
  {
    id:             'tem-acce-024',
    name:           'Touchscreen Gloves — Thermal',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          52.64,
    originalPrice:  94.0,
    discount:       44,
    rating:         4.2,
    reviews:        22681,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "gloves", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-025',
    name:           'Woven Belt Bag Mini',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          36.31,
    originalPrice:  77.25,
    discount:       53,
    rating:         4.8,
    reviews:        7194,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "mini", "outfit"]
  },
  {
    id:             'tem-acce-026',
    name:           'Suspenders — Braces Set',
    category:       'accessories',
    subcategory:    'Hats',
    price:          22.93,
    originalPrice:  43.26,
    discount:       47,
    rating:         4.8,
    reviews:        3487,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["suspenders", "fashion", "accessories", "hats", "style", "outfit"]
  },
  {
    id:             'tem-acce-027',
    name:           'Neck Gaiter — Multifunctional',
    category:       'accessories',
    subcategory:    'Belts',
    price:          29.38,
    originalPrice:  36.73,
    discount:       20,
    rating:         4.2,
    reviews:        7446,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "gaiter", "accessories", "style", "belts", "outfit"]
  },
  {
    id:             'tem-acce-028',
    name:           'Swim Cap — Silicone',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          18.14,
    originalPrice:  38.6,
    discount:       53,
    rating:         4.0,
    reviews:        13135,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "cap", "style", "outfit"]
  },
  {
    id:             'tem-acce-029',
    name:           'Boho Headband — Knot',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          69.07,
    originalPrice:  106.26,
    discount:       35,
    rating:         4.8,
    reviews:        10944,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "headband", "accessories", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-030',
    name:           'Baseball Cap — Embroidered',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          22.26,
    originalPrice:  54.29,
    discount:       59,
    rating:         4.5,
    reviews:        17594,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "cap", "style", "outfit"]
  },
  {
    id:             'tem-acce-031',
    name:           'Insulated Gloves — Waterproof',
    category:       'accessories',
    subcategory:    'Hats',
    price:          60.4,
    originalPrice:  81.62,
    discount:       26,
    rating:         4.6,
    reviews:        15926,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "gloves", "style", "outfit"]
  },
  {
    id:             'tem-acce-032',
    name:           'Merino Wool Socks — 5 Pack',
    category:       'accessories',
    subcategory:    'Belts',
    price:          18.23,
    originalPrice:  37.97,
    discount:       52,
    rating:         4.7,
    reviews:        11685,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "socks", "belts", "outfit"]
  },
  {
    id:             'tem-acce-033',
    name:           'Head Wrap — African Print',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          22.74,
    originalPrice:  47.38,
    discount:       52,
    rating:         4.5,
    reviews:        4965,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["wrap", "fashion", "accessories", "sunglasses", "style", "outfit"]
  },
  {
    id:             'tem-acce-034',
    name:           'Gradient Tinted Glasses',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          56.41,
    originalPrice:  92.47,
    discount:       39,
    rating:         4.2,
    reviews:        8313,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "scarves", "glasses", "outfit"]
  },
  {
    id:             'tem-acce-035',
    name:           'Sherpa Lined Beanie — Oversized',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          59.11,
    originalPrice:  101.92,
    discount:       42,
    rating:         4.8,
    reviews:        7523,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "beanie", "outfit"]
  },
  {
    id:             'tem-acce-036',
    name:           'Silk Pillowcase Hair Turban',
    category:       'accessories',
    subcategory:    'Hats',
    price:          49.49,
    originalPrice:  115.09,
    discount:       57,
    rating:         4.2,
    reviews:        23223,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "turban", "hats", "style", "outfit"]
  },
  {
    id:             'tem-acce-037',
    name:           'Rainbow Stripe Socks Set',
    category:       'accessories',
    subcategory:    'Belts',
    price:          48.04,
    originalPrice:  84.28,
    discount:       43,
    rating:         4.9,
    reviews:        2310,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "set", "belts", "outfit"]
  },
  {
    id:             'tem-acce-038',
    name:           'Retro Square Sunglasses',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          48.07,
    originalPrice:  75.11,
    discount:       36,
    rating:         4.5,
    reviews:        5186,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "outfit"]
  },
  {
    id:             'tem-acce-039',
    name:           'Thin Knit Beret — Grey',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          65.27,
    originalPrice:  108.79,
    discount:       40,
    rating:         4.7,
    reviews:        3566,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "style", "scarves", "beret", "outfit"]
  },
  {
    id:             'tem-acce-040',
    name:           'Winter Hat + Scarf + Gloves Set',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          84.46,
    originalPrice:  111.13,
    discount:       24,
    rating:         4.8,
    reviews:        23522,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "set", "outfit"]
  },
  {
    id:             'tem-acce-041',
    name:           'Face Visor — Full Coverage',
    category:       'accessories',
    subcategory:    'Hats',
    price:          13.62,
    originalPrice:  28.98,
    discount:       53,
    rating:         4.6,
    reviews:        18890,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["visor", "fashion", "accessories", "hats", "style", "outfit"]
  },
  {
    id:             'tem-acce-042',
    name:           'Headband Wig Grip Band',
    category:       'accessories',
    subcategory:    'Belts',
    price:          28.13,
    originalPrice:  52.09,
    discount:       46,
    rating:         4.0,
    reviews:        7682,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "band", "style", "belts", "outfit"]
  },
  {
    id:             'tem-acce-043',
    name:           'Sun Hat — Packable Straw',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          64.3,
    originalPrice:  119.07,
    discount:       46,
    rating:         4.4,
    reviews:        14789,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "hat", "style", "outfit"]
  },
  {
    id:             'tem-acce-044',
    name:           'Satin Hair Bonnet — XL',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          24.1,
    originalPrice:  46.35,
    discount:       48,
    rating:         5.0,
    reviews:        11155,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "bonnet", "accessories", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-045',
    name:           'Hair Rings & Cuffs Set',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          61.13,
    originalPrice:  91.24,
    discount:       33,
    rating:         4.7,
    reviews:        22757,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "set", "outfit"]
  },
  {
    id:             'tem-acce-046',
    name:           'Neck Pillow — Travel Memory Foam',
    category:       'accessories',
    subcategory:    'Hats',
    price:          22.2,
    originalPrice:  60.0,
    discount:       63,
    rating:         4.1,
    reviews:        2553,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "hats", "pillow", "style", "outfit"]
  },
  {
    id:             'tem-acce-047',
    name:           'Gym Headband — Sweat Wicking',
    category:       'accessories',
    subcategory:    'Belts',
    price:          32.1,
    originalPrice:  55.35,
    discount:       42,
    rating:         4.8,
    reviews:        23781,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "headband", "accessories", "style", "belts", "outfit"]
  },
  {
    id:             'tem-acce-048',
    name:           'Faux Fur Stole Wrap',
    category:       'accessories',
    subcategory:    'Sunglasses',
    price:          46.07,
    originalPrice:  109.69,
    discount:       58,
    rating:         4.6,
    reviews:        5153,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["wrap", "fashion", "accessories", "sunglasses", "style", "outfit"]
  },
  {
    id:             'tem-acce-049',
    name:           'Oversized Sunglasses — UV400 Retro Pro',
    category:       'accessories',
    subcategory:    'Scarves',
    price:          67.71,
    originalPrice:  84.64,
    discount:       20,
    rating:         4.6,
    reviews:        12232,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620283085439-39620a1e21c4?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "accessories", "sunglasses", "style", "scarves", "outfit"]
  },
  {
    id:             'tem-acce-050',
    name:           'Claw Hair Clips Set — 6 Pack Pastel Plus',
    category:       'accessories',
    subcategory:    'Hair Accessories',
    price:          4.82,
    originalPrice:  12.68,
    discount:       62,
    rating:         4.2,
    reviews:        4231,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1609174216159-b3a87c11b1d5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=accessories+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["fashion", "hair_accessories", "accessories", "style", "set", "outfit"]
  }
);
