/* TEMU — Bags (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-bags-001',
    name:           'Luxury PU Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          11.57,
    originalPrice:  16.77,
    discount:       31,
    rating:         4.8,
    reviews:        3240,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-002',
    name:           'Canvas Tote Bag — Aesthetic Prints',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          5.4,
    originalPrice:  14.6,
    discount:       63,
    rating:         4.8,
    reviews:        16783,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-003',
    name:           'Laptop Backpack — Anti-Theft 15.6"',
    category:       'bags',
    subcategory:    'Totes',
    price:          24.87,
    originalPrice:  37.68,
    discount:       34,
    rating:         4.8,
    reviews:        22899,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "backpack", "totes", "purse"]
  },
  {
    id:             'tem-bags-004',
    name:           'Mini Crossbody Bag — Quilted Chain',
    category:       'bags',
    subcategory:    'Wallets',
    price:          8.37,
    originalPrice:  19.02,
    discount:       56,
    rating:         4.4,
    reviews:        7779,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-005',
    name:           'Rattan Summer Handbag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          65.89,
    originalPrice:  94.13,
    discount:       30,
    rating:         4.2,
    reviews:        4863,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-006',
    name:           'Clear Stadium Bag — PVC',
    category:       'bags',
    subcategory:    'Handbags',
    price:          29.63,
    originalPrice:  42.33,
    discount:       30,
    rating:         4.7,
    reviews:        2871,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-007',
    name:           'Large Slouchy Hobo Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          39.2,
    originalPrice:  54.44,
    discount:       28,
    rating:         4.6,
    reviews:        1480,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-008',
    name:           'Croc-Effect Tote Bag — Beige',
    category:       'bags',
    subcategory:    'Totes',
    price:          16.77,
    originalPrice:  29.94,
    discount:       44,
    rating:         4.2,
    reviews:        23581,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-009',
    name:           'Woven Bucket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          65.01,
    originalPrice:  106.58,
    discount:       39,
    rating:         4.7,
    reviews:        18835,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-010',
    name:           'Belt Bag — Nylon',
    category:       'bags',
    subcategory:    'Clutches',
    price:          18.78,
    originalPrice:  32.94,
    discount:       43,
    rating:         4.5,
    reviews:        2483,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-011',
    name:           'Flap Crossbody Bag — Brown',
    category:       'bags',
    subcategory:    'Handbags',
    price:          46.89,
    originalPrice:  80.84,
    discount:       42,
    rating:         4.3,
    reviews:        4115,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-012',
    name:           'Structured Top Handle Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          17.67,
    originalPrice:  35.34,
    discount:       50,
    rating:         4.1,
    reviews:        7821,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-013',
    name:           'Travel Duffel Bag — Weekender',
    category:       'bags',
    subcategory:    'Totes',
    price:          20.76,
    originalPrice:  27.32,
    discount:       24,
    rating:         4.1,
    reviews:        20722,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-014',
    name:           'Waist Fanny Pack — Black',
    category:       'bags',
    subcategory:    'Wallets',
    price:          14.46,
    originalPrice:  25.83,
    discount:       44,
    rating:         4.7,
    reviews:        21374,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "wallets", "bags", "purse", "pack"]
  },
  {
    id:             'tem-bags-015',
    name:           'Knitted Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          54.09,
    originalPrice:  106.05,
    discount:       49,
    rating:         4.6,
    reviews:        6637,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-016',
    name:           'Mini Camera Bag — Velvet',
    category:       'bags',
    subcategory:    'Handbags',
    price:          41.69,
    originalPrice:  74.44,
    discount:       44,
    rating:         4.9,
    reviews:        255,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-017',
    name:           'Oversized Shopper Tote',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          18.41,
    originalPrice:  32.88,
    discount:       44,
    rating:         4.7,
    reviews:        5630,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-018',
    name:           'Baguette Bag — Satin',
    category:       'bags',
    subcategory:    'Totes',
    price:          85.08,
    originalPrice:  109.08,
    discount:       22,
    rating:         4.6,
    reviews:        3182,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-019',
    name:           'Backpack Purse — Vegan Leather',
    category:       'bags',
    subcategory:    'Wallets',
    price:          86.6,
    originalPrice:  112.47,
    discount:       23,
    rating:         4.5,
    reviews:        17019,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-020',
    name:           'Transparent Beach Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          20.0,
    originalPrice:  32.79,
    discount:       39,
    rating:         4.8,
    reviews:        16006,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-021',
    name:           'Bamboo Handle Tote',
    category:       'bags',
    subcategory:    'Handbags',
    price:          68.92,
    originalPrice:  107.69,
    discount:       36,
    rating:         4.1,
    reviews:        22796,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-022',
    name:           'Convertible Backpack Handbag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          11.71,
    originalPrice:  16.26,
    discount:       28,
    rating:         4.0,
    reviews:        15546,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-023',
    name:           'Envelope Clutch Bag — Gold',
    category:       'bags',
    subcategory:    'Totes',
    price:          43.04,
    originalPrice:  102.47,
    discount:       58,
    rating:         4.8,
    reviews:        18875,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-024',
    name:           'Micro Mini Bag — Chain Strap',
    category:       'bags',
    subcategory:    'Wallets',
    price:          17.89,
    originalPrice:  22.64,
    discount:       21,
    rating:         4.3,
    reviews:        3597,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-025',
    name:           'Studded Leather Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          37.15,
    originalPrice:  68.8,
    discount:       46,
    rating:         4.6,
    reviews:        3698,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "crossbody", "clutches", "purse"]
  },
  {
    id:             'tem-bags-026',
    name:           'Geometric Structured Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          39.16,
    originalPrice:  68.71,
    discount:       43,
    rating:         4.9,
    reviews:        21940,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-027',
    name:           'Drawstring Bucket Bag — Cord',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          54.75,
    originalPrice:  96.05,
    discount:       43,
    rating:         4.2,
    reviews:        5589,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-028',
    name:           'Vintage Flap Shoulder Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          33.5,
    originalPrice:  44.08,
    discount:       24,
    rating:         4.1,
    reviews:        10088,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-029',
    name:           'Wicker Market Basket Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          55.56,
    originalPrice:  77.16,
    discount:       28,
    rating:         4.1,
    reviews:        9999,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-030',
    name:           'Circle Bag — Wooden Handle',
    category:       'bags',
    subcategory:    'Clutches',
    price:          52.44,
    originalPrice:  81.93,
    discount:       36,
    rating:         4.1,
    reviews:        5701,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-031',
    name:           'Satin Evening Clutch — Pearl',
    category:       'bags',
    subcategory:    'Handbags',
    price:          20.91,
    originalPrice:  58.07,
    discount:       64,
    rating:         4.7,
    reviews:        22168,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "handbags", "bags", "clutch", "purse"]
  },
  {
    id:             'tem-bags-032',
    name:           'Doctor Bag — Brown Leather',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          16.6,
    originalPrice:  29.12,
    discount:       43,
    rating:         4.9,
    reviews:        2578,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-033',
    name:           'Graffiti Print Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          86.81,
    originalPrice:  118.92,
    discount:       27,
    rating:         4.8,
    reviews:        15608,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-034',
    name:           'Chain Handle Shoulder Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          64.35,
    originalPrice:  110.95,
    discount:       42,
    rating:         4.2,
    reviews:        24460,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-035',
    name:           'PVC Jelly Bag — Transparent',
    category:       'bags',
    subcategory:    'Clutches',
    price:          17.75,
    originalPrice:  23.36,
    discount:       24,
    rating:         5.0,
    reviews:        13957,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-036',
    name:           'Knot Handle Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          69.98,
    originalPrice:  87.48,
    discount:       20,
    rating:         4.5,
    reviews:        4250,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-037',
    name:           'Tassel Fringe Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          66.04,
    originalPrice:  88.05,
    discount:       25,
    rating:         4.7,
    reviews:        5514,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-038',
    name:           'Reversible Tote Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          17.84,
    originalPrice:  31.86,
    discount:       44,
    rating:         4.6,
    reviews:        2641,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-039',
    name:           'Large Raffia Beach Tote',
    category:       'bags',
    subcategory:    'Wallets',
    price:          56.35,
    originalPrice:  108.36,
    discount:       48,
    rating:         4.0,
    reviews:        13231,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-040',
    name:           'Phone Bag — Crossbody',
    category:       'bags',
    subcategory:    'Clutches',
    price:          52.08,
    originalPrice:  68.52,
    discount:       24,
    rating:         4.2,
    reviews:        3418,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-041',
    name:           'Chic Mini Backpack',
    category:       'bags',
    subcategory:    'Handbags',
    price:          7.46,
    originalPrice:  17.35,
    discount:       57,
    rating:         4.1,
    reviews:        2771,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "handbags", "bags", "backpack", "purse"]
  },
  {
    id:             'tem-bags-042',
    name:           'Lock Clasp Structured Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          61.05,
    originalPrice:  109.02,
    discount:       44,
    rating:         4.5,
    reviews:        24072,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-043',
    name:           'Rope Handle Tote',
    category:       'bags',
    subcategory:    'Totes',
    price:          84.42,
    originalPrice:  105.52,
    discount:       20,
    rating:         4.7,
    reviews:        17711,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-044',
    name:           'Patchwork Denim Bag',
    category:       'bags',
    subcategory:    'Wallets',
    price:          28.58,
    originalPrice:  50.14,
    discount:       43,
    rating:         4.6,
    reviews:        1914,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "purse", "wallets"]
  },
  {
    id:             'tem-bags-045',
    name:           'Woven Leather Shoulder Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          32.45,
    originalPrice:  67.6,
    discount:       52,
    rating:         4.6,
    reviews:        2014,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  },
  {
    id:             'tem-bags-046',
    name:           'Feather Trim Evening Bag',
    category:       'bags',
    subcategory:    'Handbags',
    price:          71.69,
    originalPrice:  105.43,
    discount:       32,
    rating:         4.3,
    reviews:        1654,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1590739293931-a5e85e8b0ef5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "handbags", "bags", "purse"]
  },
  {
    id:             'tem-bags-047',
    name:           'Nylon Messenger Bag',
    category:       'bags',
    subcategory:    'Backpacks',
    price:          38.8,
    originalPrice:  74.61,
    discount:       48,
    rating:         4.8,
    reviews:        4899,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "backpacks", "purse"]
  },
  {
    id:             'tem-bags-048',
    name:           'Half-Moon Crescent Bag',
    category:       'bags',
    subcategory:    'Totes',
    price:          13.99,
    originalPrice:  32.54,
    discount:       57,
    rating:         4.6,
    reviews:        1553,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "totes", "purse"]
  },
  {
    id:             'tem-bags-049',
    name:           'Snakeskin Effect Clutch',
    category:       'bags',
    subcategory:    'Wallets',
    price:          27.04,
    originalPrice:  73.07,
    discount:       63,
    rating:         4.5,
    reviews:        23590,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tote", "handbag", "bags", "clutch", "purse", "wallets"]
  },
  {
    id:             'tem-bags-050',
    name:           'Double Zip Crossbody Bag',
    category:       'bags',
    subcategory:    'Clutches',
    price:          19.11,
    originalPrice:  25.82,
    discount:       26,
    rating:         4.3,
    reviews:        10870,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=bags+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bag", "tote", "handbag", "bags", "clutches", "purse"]
  }
);
