/* TEMU — Beauty (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-beau-001',
    name:           'Vitamin C Brightening Serum — 30ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          12.83,
    originalPrice:  31.3,
    discount:       59,
    rating:         4.6,
    reviews:        12592,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare"]
  },
  {
    id:             'tem-beau-002',
    name:           'Korean Skincare 5-Piece Set',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          30.81,
    originalPrice:  75.15,
    discount:       59,
    rating:         4.9,
    reviews:        5042,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'tem-beau-003',
    name:           'Rose Quartz Face Roller & Gua Sha Set',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          52.98,
    originalPrice:  75.69,
    discount:       30,
    rating:         4.3,
    reviews:        15397,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-004',
    name:           'Electric Face Massager — Microcurrent',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          40.18,
    originalPrice:  59.97,
    discount:       33,
    rating:         4.1,
    reviews:        2418,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "fragrance", "massager", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-005',
    name:           'Matte Lipstick Collection — 12 Shades',
    category:       'beauty',
    subcategory:    'Nails',
    price:          9.47,
    originalPrice:  13.93,
    discount:       32,
    rating:         4.1,
    reviews:        23572,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "skincare", "collection"]
  },
  {
    id:             'tem-beau-006',
    name:           'Portable Hair Straightener Brush',
    category:       'beauty',
    subcategory:    'Tools',
    price:          12.01,
    originalPrice:  21.44,
    discount:       44,
    rating:         4.9,
    reviews:        3415,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "brush", "beauty", "skincare", "tools"]
  },
  {
    id:             'tem-beau-007',
    name:           'Retinol Night Cream — Anti-Ageing',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          22.65,
    originalPrice:  51.48,
    discount:       56,
    rating:         5.0,
    reviews:        17376,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-008',
    name:           'Hyaluronic Acid Moisturiser — 50ml',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          13.78,
    originalPrice:  19.41,
    discount:       29,
    rating:         5.0,
    reviews:        4808,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare"]
  },
  {
    id:             'tem-beau-009',
    name:           'Waterproof Mascara — Lengthening',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          13.13,
    originalPrice:  25.74,
    discount:       49,
    rating:         4.8,
    reviews:        14540,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "mascara", "beauty", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-010',
    name:           '24K Gold Eye Patches — 60 Pairs',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          23.36,
    originalPrice:  41.71,
    discount:       44,
    rating:         4.9,
    reviews:        23876,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "patches", "skincare"]
  },
  {
    id:             'tem-beau-011',
    name:           'Niacinamide Toner — Pore Minimising',
    category:       'beauty',
    subcategory:    'Nails',
    price:          19.75,
    originalPrice:  28.22,
    discount:       30,
    rating:         4.1,
    reviews:        7749,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "toner", "skincare"]
  },
  {
    id:             'tem-beau-012',
    name:           'Snail Mucin Essence — 100ml',
    category:       'beauty',
    subcategory:    'Tools',
    price:          24.3,
    originalPrice:  48.61,
    discount:       50,
    rating:         4.7,
    reviews:        2359,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "essence", "skincare", "tools"]
  },
  {
    id:             'tem-beau-013',
    name:           'Micellar Cleansing Water — 500ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          37.26,
    originalPrice:  70.3,
    discount:       47,
    rating:         4.3,
    reviews:        15561,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "water", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-014',
    name:           'BHA Salicylic Acid Exfoliant',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          83.3,
    originalPrice:  109.6,
    discount:       24,
    rating:         4.6,
    reviews:        12165,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "exfoliant", "skincare"]
  },
  {
    id:             'tem-beau-015',
    name:           'Natural Lip Oil — Glossy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          19.59,
    originalPrice:  35.61,
    discount:       45,
    rating:         4.2,
    reviews:        21526,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "oil", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-016',
    name:           'BB Cream SPF30 — Tinted',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          21.64,
    originalPrice:  52.79,
    discount:       59,
    rating:         4.5,
    reviews:        4156,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "spf30", "skincare"]
  },
  {
    id:             'tem-beau-017',
    name:           'Under-Eye Concealer — Full Coverage',
    category:       'beauty',
    subcategory:    'Nails',
    price:          29.11,
    originalPrice:  61.94,
    discount:       53,
    rating:         4.4,
    reviews:        22210,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "concealer", "nails", "skincare"]
  },
  {
    id:             'tem-beau-018',
    name:           'Eyeshadow Palette — 18 Shades',
    category:       'beauty',
    subcategory:    'Tools',
    price:          67.19,
    originalPrice:  97.38,
    discount:       31,
    rating:         4.2,
    reviews:        22860,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare", "tools"]
  },
  {
    id:             'tem-beau-019',
    name:           'Setting Powder — Translucent',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          7.99,
    originalPrice:  18.59,
    discount:       57,
    rating:         4.3,
    reviews:        19967,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "powder", "skincare"]
  },
  {
    id:             'tem-beau-020',
    name:           'Hair Mask — Deep Conditioning',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          16.9,
    originalPrice:  27.71,
    discount:       39,
    rating:         4.5,
    reviews:        21835,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "mask"]
  },
  {
    id:             'tem-beau-021',
    name:           'Colour-Depositing Purple Shampoo',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          77.96,
    originalPrice:  99.95,
    discount:       22,
    rating:         4.7,
    reviews:        18825,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "shampoo", "haircare"]
  },
  {
    id:             'tem-beau-022',
    name:           'Scalp Serum — Hair Growth',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          21.4,
    originalPrice:  61.15,
    discount:       65,
    rating:         4.9,
    reviews:        7711,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "fragrance", "beauty", "serum", "skincare"]
  },
  {
    id:             'tem-beau-023',
    name:           'AHA Glycolic Acid Peel Pads',
    category:       'beauty',
    subcategory:    'Nails',
    price:          59.53,
    originalPrice:  83.85,
    discount:       29,
    rating:         4.2,
    reviews:        22915,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "pads", "nails", "skincare"]
  },
  {
    id:             'tem-beau-024',
    name:           'Jade Roller Duo Set',
    category:       'beauty',
    subcategory:    'Tools',
    price:          6.33,
    originalPrice:  15.06,
    discount:       58,
    rating:         4.7,
    reviews:        8667,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "tools"]
  },
  {
    id:             'tem-beau-025',
    name:           'Foundation — 40 Shades',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          52.21,
    originalPrice:  77.93,
    discount:       33,
    rating:         4.3,
    reviews:        1753,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-026',
    name:           'Blush & Bronzer Duo Palette',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          33.03,
    originalPrice:  86.93,
    discount:       62,
    rating:         4.6,
    reviews:        507,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "palette", "skincare"]
  },
  {
    id:             'tem-beau-027',
    name:           'Eyeliner Pen — Waterproof',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          25.44,
    originalPrice:  41.7,
    discount:       39,
    rating:         4.4,
    reviews:        2690,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "pen", "beauty", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-028',
    name:           'Brow Lamination Kit',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          36.95,
    originalPrice:  52.79,
    discount:       30,
    rating:         4.4,
    reviews:        19789,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "kit", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-029',
    name:           'Lip Plumper Gloss — Berry',
    category:       'beauty',
    subcategory:    'Nails',
    price:          17.9,
    originalPrice:  34.43,
    discount:       48,
    rating:         4.8,
    reviews:        14195,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "gloss", "beauty", "nails", "skincare"]
  },
  {
    id:             'tem-beau-030',
    name:           'Self-Tan Mousse — Medium',
    category:       'beauty',
    subcategory:    'Tools',
    price:          29.07,
    originalPrice:  58.15,
    discount:       50,
    rating:         4.2,
    reviews:        18643,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "mousse", "beauty", "skincare", "tools"]
  },
  {
    id:             'tem-beau-031',
    name:           'Vitamin E Body Lotion — 400ml',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          8.79,
    originalPrice:  15.7,
    discount:       44,
    rating:         4.7,
    reviews:        17435,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "lotion", "skincare"]
  },
  {
    id:             'tem-beau-032',
    name:           'Dry Shampoo Spray',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          71.24,
    originalPrice:  100.34,
    discount:       29,
    rating:         4.5,
    reviews:        16764,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "spray"]
  },
  {
    id:             'tem-beau-033',
    name:           'Sheet Face Mask Set — 10 Pack',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          30.22,
    originalPrice:  48.74,
    discount:       38,
    rating:         4.9,
    reviews:        22213,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-034',
    name:           'Cleansing Balm — Waterproof Makeup',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          57.46,
    originalPrice:  97.39,
    discount:       41,
    rating:         4.7,
    reviews:        19818,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "fragrance", "balm", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-035',
    name:           'SPF50 Sunscreen — Invisible',
    category:       'beauty',
    subcategory:    'Nails',
    price:          49.41,
    originalPrice:  62.55,
    discount:       21,
    rating:         4.8,
    reviews:        14636,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "sunscreen", "nails", "skincare"]
  },
  {
    id:             'tem-beau-036',
    name:           'Lash Growth Serum',
    category:       'beauty',
    subcategory:    'Tools',
    price:          16.06,
    originalPrice:  45.9,
    discount:       65,
    rating:         4.2,
    reviews:        10199,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "serum", "skincare", "tools"]
  },
  {
    id:             'tem-beau-037',
    name:           'Collagen Peptide Face Cream',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          13.11,
    originalPrice:  29.8,
    discount:       56,
    rating:         4.7,
    reviews:        23762,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-038',
    name:           'Tea Tree Spot Treatment',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          39.92,
    originalPrice:  55.44,
    discount:       28,
    rating:         4.8,
    reviews:        23126,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "treatment", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-039',
    name:           'Cushion Foundation — Dewy Finish',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          29.32,
    originalPrice:  44.43,
    discount:       34,
    rating:         4.9,
    reviews:        23191,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "foundation", "beauty", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-040',
    name:           'Peptide Eye Cream',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          23.72,
    originalPrice:  46.51,
    discount:       49,
    rating:         4.3,
    reviews:        18443,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "cream", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-041',
    name:           'Coconut Oil Body Scrub',
    category:       'beauty',
    subcategory:    'Nails',
    price:          27.91,
    originalPrice:  54.73,
    discount:       49,
    rating:         4.2,
    reviews:        10244,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "scrub", "beauty", "nails", "skincare"]
  },
  {
    id:             'tem-beau-042',
    name:           'Pore Strips — Blackhead Remover',
    category:       'beauty',
    subcategory:    'Tools',
    price:          45.8,
    originalPrice:  67.36,
    discount:       32,
    rating:         4.5,
    reviews:        6990,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "strips", "beauty", "skincare", "tools"]
  },
  {
    id:             'tem-beau-043',
    name:           'CC Cream — Colour Correcting',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          55.79,
    originalPrice:  111.58,
    discount:       50,
    rating:         4.8,
    reviews:        23421,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "cream", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-044',
    name:           'Gel Liner — Smudge Proof',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          18.09,
    originalPrice:  29.66,
    discount:       39,
    rating:         4.8,
    reviews:        12814,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1586495777744-4e6232bf11a5?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "liner", "skincare"]
  },
  {
    id:             'tem-beau-045',
    name:           'Ceramide Barrier Repair Moisturiser',
    category:       'beauty',
    subcategory:    'Haircare',
    price:          19.98,
    originalPrice:  47.56,
    discount:       58,
    rating:         4.4,
    reviews:        24601,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "moisturiser", "skincare", "haircare"]
  },
  {
    id:             'tem-beau-046',
    name:           'Illuminating Primer',
    category:       'beauty',
    subcategory:    'Fragrance',
    price:          61.82,
    originalPrice:  104.78,
    discount:       41,
    rating:         4.1,
    reviews:        13722,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "primer", "fragrance", "beauty", "skincare"]
  },
  {
    id:             'tem-beau-047',
    name:           'Multi-Vitamin Face Oil',
    category:       'beauty',
    subcategory:    'Nails',
    price:          62.28,
    originalPrice:  84.16,
    discount:       26,
    rating:         4.1,
    reviews:        3963,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "nails", "oil", "skincare"]
  },
  {
    id:             'tem-beau-048',
    name:           'Whipped Body Butter — Shea',
    category:       'beauty',
    subcategory:    'Tools',
    price:          53.01,
    originalPrice:  96.38,
    discount:       45,
    rating:         4.0,
    reviews:        23236,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "skincare", "butter", "tools"]
  },
  {
    id:             'tem-beau-049',
    name:           'Cruelty-Free Makeup Brush Set',
    category:       'beauty',
    subcategory:    'Skincare',
    price:          29.71,
    originalPrice:  74.28,
    discount:       60,
    rating:         4.5,
    reviews:        12477,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  },
  {
    id:             'tem-beau-050',
    name:           'Nail Polish Set — 12 Colours',
    category:       'beauty',
    subcategory:    'Makeup',
    price:          29.48,
    originalPrice:  79.68,
    discount:       63,
    rating:         4.2,
    reviews:        10222,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=beauty+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["makeup", "cosmetics", "beauty", "set", "skincare"]
  }
);
