/* TEMU — Crafts (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-craf-001',
    name:           'Diamond Painting Kit — Full Drill 40×50',
    category:       'crafts',
    subcategory:    'Painting',
    price:          44.87,
    originalPrice:  70.11,
    discount:       36,
    rating:         4.8,
    reviews:        17907,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-002',
    name:           'Resin Art Kit — UV Resin + Moulds',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          11.89,
    originalPrice:  17.49,
    discount:       32,
    rating:         4.7,
    reviews:        12276,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-003',
    name:           'Aesthetic Journaling Kit — Washi Tapes',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          17.61,
    originalPrice:  41.93,
    discount:       58,
    rating:         4.2,
    reviews:        12700,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-004',
    name:           'Watercolour Paint Set — 48 Colours',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          29.35,
    originalPrice:  57.54,
    discount:       49,
    rating:         4.8,
    reviews:        22756,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-005',
    name:           'Macramé Wall Hanging Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          37.51,
    originalPrice:  51.38,
    discount:       27,
    rating:         4.5,
    reviews:        21336,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-006',
    name:           'Embroidery Starter Kit — Floral',
    category:       'crafts',
    subcategory:    'DIY',
    price:          26.64,
    originalPrice:  33.72,
    discount:       21,
    rating:         4.7,
    reviews:        7401,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-007',
    name:           'Lino Printing Starter Set',
    category:       'crafts',
    subcategory:    'Painting',
    price:          10.03,
    originalPrice:  13.03,
    discount:       23,
    rating:         4.3,
    reviews:        16807,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-008',
    name:           'Candle Making Kit — Soy Wax',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          83.42,
    originalPrice:  104.28,
    discount:       20,
    rating:         4.8,
    reviews:        18192,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-009',
    name:           'Pottery Air Dry Clay Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          54.47,
    originalPrice:  93.91,
    discount:       42,
    rating:         4.2,
    reviews:        8082,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-010',
    name:           'Leather Craft Tooling Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          37.97,
    originalPrice:  99.92,
    discount:       62,
    rating:         4.2,
    reviews:        12561,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-011',
    name:           'Cross-Stitch Bookmark Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          29.41,
    originalPrice:  43.25,
    discount:       32,
    rating:         4.2,
    reviews:        23141,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-012',
    name:           'Acrylic Pour Painting Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          6.58,
    originalPrice:  16.86,
    discount:       61,
    rating:         4.7,
    reviews:        10808,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-013',
    name:           'Needle Felting Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          53.63,
    originalPrice:  107.26,
    discount:       50,
    rating:         4.5,
    reviews:        17856,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-014',
    name:           'Calligraphy Pen & Ink Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          7.59,
    originalPrice:  12.86,
    discount:       41,
    rating:         4.6,
    reviews:        17822,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-015',
    name:           'Soap Making Kit — Natural',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          76.85,
    originalPrice:  105.27,
    discount:       27,
    rating:         4.3,
    reviews:        12516,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-016',
    name:           'Origami Paper Set — 200 Sheets',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          68.74,
    originalPrice:  94.17,
    discount:       27,
    rating:         4.7,
    reviews:        15818,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-017',
    name:           'Knitting Starter Kit — Beginner',
    category:       'crafts',
    subcategory:    'Resin',
    price:          41.4,
    originalPrice:  79.62,
    discount:       48,
    rating:         4.5,
    reviews:        19738,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-018',
    name:           'Crochet Hook Set + Yarn Bundle',
    category:       'crafts',
    subcategory:    'DIY',
    price:          45.92,
    originalPrice:  95.66,
    discount:       52,
    rating:         4.1,
    reviews:        17849,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bundle", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-019',
    name:           'Jewellery Making Kit — Beads',
    category:       'crafts',
    subcategory:    'Painting',
    price:          12.62,
    originalPrice:  15.78,
    discount:       20,
    rating:         5.0,
    reviews:        4815,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-020',
    name:           'Tie-Dye Kit — Spiral',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          54.34,
    originalPrice:  118.12,
    discount:       54,
    rating:         4.7,
    reviews:        4262,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-021',
    name:           'Painting by Numbers — Landscape',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          34.04,
    originalPrice:  44.79,
    discount:       24,
    rating:         4.4,
    reviews:        16443,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["numbers", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-022',
    name:           'Block Printing Ink Set',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          23.88,
    originalPrice:  49.76,
    discount:       52,
    rating:         4.2,
    reviews:        12510,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-023',
    name:           'Scrapbook Kit — 200 Stickers',
    category:       'crafts',
    subcategory:    'Resin',
    price:          64.4,
    originalPrice:  89.44,
    discount:       28,
    rating:         4.8,
    reviews:        18779,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-024',
    name:           'Pressed Flower Art Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          23.72,
    originalPrice:  42.36,
    discount:       44,
    rating:         4.3,
    reviews:        1406,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-025',
    name:           'Glass Painting Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          39.07,
    originalPrice:  111.62,
    discount:       65,
    rating:         4.2,
    reviews:        7505,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-026',
    name:           'Wool Felting Supplies Bundle',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          52.89,
    originalPrice:  99.79,
    discount:       47,
    rating:         4.2,
    reviews:        11939,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bundle", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-027',
    name:           'Punch Needle Rug Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          70.03,
    originalPrice:  114.8,
    discount:       39,
    rating:         4.1,
    reviews:        19254,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-028',
    name:           'Marbling Paper Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          64.66,
    originalPrice:  104.29,
    discount:       38,
    rating:         4.0,
    reviews:        13983,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-029',
    name:           'Silk Screen Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          78.12,
    originalPrice:  107.02,
    discount:       27,
    rating:         4.9,
    reviews:        18856,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-030',
    name:           'Decoupage Set + Papers',
    category:       'crafts',
    subcategory:    'DIY',
    price:          47.19,
    originalPrice:  112.36,
    discount:       58,
    rating:         4.6,
    reviews:        17946,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["papers", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-031',
    name:           'Weaving Loom Kit — Beginner',
    category:       'crafts',
    subcategory:    'Painting',
    price:          20.01,
    originalPrice:  40.02,
    discount:       50,
    rating:         4.3,
    reviews:        22498,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-032',
    name:           'Zentangle Art Pens Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          56.28,
    originalPrice:  106.18,
    discount:       47,
    rating:         4.3,
    reviews:        2657,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-033',
    name:           'Linoleum Block Carving Set',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          38.13,
    originalPrice:  108.93,
    discount:       65,
    rating:         4.8,
    reviews:        16318,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-034',
    name:           'Alcohol Ink Art Kit',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          48.59,
    originalPrice:  65.66,
    discount:       26,
    rating:         4.1,
    reviews:        11575,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-035',
    name:           'Mandala Drawing Stencil Set',
    category:       'crafts',
    subcategory:    'Resin',
    price:          72.76,
    originalPrice:  90.95,
    discount:       20,
    rating:         5.0,
    reviews:        13258,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-036',
    name:           'Rubber Stamp Making Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          81.17,
    originalPrice:  105.42,
    discount:       23,
    rating:         4.8,
    reviews:        21345,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-037',
    name:           'Reusable Stencil Set — 40 Piece',
    category:       'crafts',
    subcategory:    'Painting',
    price:          49.68,
    originalPrice:  118.28,
    discount:       58,
    rating:         4.2,
    reviews:        23668,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["painting", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-038',
    name:           'Air Dry Clay Tool Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          60.49,
    originalPrice:  85.2,
    discount:       29,
    rating:         4.9,
    reviews:        1720,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-039',
    name:           'Mixed Media Art Journal',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          32.74,
    originalPrice:  69.67,
    discount:       53,
    rating:         4.3,
    reviews:        5363,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["journal", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-040',
    name:           'Bookbinding Kit — Hardcover',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          77.49,
    originalPrice:  101.96,
    discount:       24,
    rating:         4.9,
    reviews:        3783,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-041',
    name:           'Batik Wax Resist Kit',
    category:       'crafts',
    subcategory:    'Resin',
    price:          35.09,
    originalPrice:  100.26,
    discount:       65,
    rating:         4.9,
    reviews:        10612,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-042',
    name:           'Pyrography Wood Burning Set',
    category:       'crafts',
    subcategory:    'DIY',
    price:          38.25,
    originalPrice:  109.3,
    discount:       65,
    rating:         4.0,
    reviews:        9502,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["diy", "art", "creative", "set", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-043',
    name:           'Paper Quilling Starter Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          26.05,
    originalPrice:  45.7,
    discount:       43,
    rating:         4.0,
    reviews:        20078,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-044',
    name:           'Shrink Plastic Art Kit',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          34.62,
    originalPrice:  54.1,
    discount:       36,
    rating:         4.0,
    reviews:        4250,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "crafts", "DIY", "sewing"]
  },
  {
    id:             'tem-craf-045',
    name:           'Enamel Painting Kit',
    category:       'crafts',
    subcategory:    'Knitting',
    price:          27.61,
    originalPrice:  40.01,
    discount:       31,
    rating:         4.4,
    reviews:        17099,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "art", "creative", "knitting", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-046',
    name:           'Gilding Flakes Set — Gold',
    category:       'crafts',
    subcategory:    'Paper Crafts',
    price:          32.33,
    originalPrice:  64.65,
    discount:       50,
    rating:         4.4,
    reviews:        10319,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "paper_crafts", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-047',
    name:           'Linocut Printing Starter',
    category:       'crafts',
    subcategory:    'Resin',
    price:          6.7,
    originalPrice:  18.1,
    discount:       63,
    rating:         5.0,
    reviews:        20424,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["starter", "art", "creative", "resin", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-048',
    name:           'Botanical Illustration Kit',
    category:       'crafts',
    subcategory:    'DIY',
    price:          28.94,
    originalPrice:  43.85,
    discount:       34,
    rating:         4.9,
    reviews:        15294,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "diy", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-049',
    name:           'Copper Tooling Craft Kit',
    category:       'crafts',
    subcategory:    'Painting',
    price:          46.29,
    originalPrice:  63.41,
    discount:       27,
    rating:         4.0,
    reviews:        11575,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "painting", "art", "creative", "crafts", "DIY"]
  },
  {
    id:             'tem-craf-050',
    name:           'Felt Sewing Starter Set',
    category:       'crafts',
    subcategory:    'Sewing',
    price:          48.23,
    originalPrice:  98.42,
    discount:       51,
    rating:         4.4,
    reviews:        24854,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=crafts+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["art", "creative", "set", "crafts", "DIY", "sewing"]
  }
);
