/* TEMU — Home (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-home-001',
    name:           'Bohemian Throw Pillow Covers — Set of 4',
    category:       'home',
    subcategory:    'Furniture',
    price:          56.54,
    originalPrice:  85.66,
    discount:       34,
    rating:         4.6,
    reviews:        1052,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "furniture", "covers", "decor"]
  },
  {
    id:             'tem-home-002',
    name:           'LED Desk Lamp with USB Charging Port',
    category:       'home',
    subcategory:    'Kitchen',
    price:          46.09,
    originalPrice:  115.22,
    discount:       60,
    rating:         4.5,
    reviews:        10525,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "port", "decor"]
  },
  {
    id:             'tem-home-003',
    name:           'Non-Stick Cookware Set — 5 Pieces',
    category:       'home',
    subcategory:    'Decor',
    price:          64.4,
    originalPrice:  97.57,
    discount:       34,
    rating:         4.3,
    reviews:        23758,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-004',
    name:           'Aesthetic Bedding Set — King Size',
    category:       'home',
    subcategory:    'Bedding',
    price:          71.1,
    originalPrice:  106.12,
    discount:       33,
    rating:         4.3,
    reviews:        4138,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'tem-home-005',
    name:           'Aesthetic Acrylic Desk Organiser Set',
    category:       'home',
    subcategory:    'Lighting',
    price:          58.33,
    originalPrice:  112.18,
    discount:       48,
    rating:         4.5,
    reviews:        350,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "lighting", "decor"]
  },
  {
    id:             'tem-home-006',
    name:           'Fairy Lights — 10m USB Warm White',
    category:       'home',
    subcategory:    'Storage',
    price:          35.68,
    originalPrice:  54.89,
    discount:       35,
    rating:         4.1,
    reviews:        8852,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["lights", "storage", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-007',
    name:           'Cute Ceramic Mug Set — 2 Pack',
    category:       'home',
    subcategory:    'Furniture',
    price:          19.44,
    originalPrice:  30.86,
    discount:       37,
    rating:         4.9,
    reviews:        2691,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'tem-home-008',
    name:           'Minimalist Wall Clock — Silent Quartz',
    category:       'home',
    subcategory:    'Kitchen',
    price:          48.96,
    originalPrice:  119.42,
    discount:       59,
    rating:         4.7,
    reviews:        23214,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["clock", "kitchen", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-009',
    name:           'LED Strip Lights — 5m RGB Smart',
    category:       'home',
    subcategory:    'Decor',
    price:          37.5,
    originalPrice:  52.08,
    discount:       28,
    rating:         4.7,
    reviews:        9689,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["lights", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-010',
    name:           'Bamboo Bathroom Organiser',
    category:       'home',
    subcategory:    'Bedding',
    price:          33.71,
    originalPrice:  48.85,
    discount:       31,
    rating:         4.7,
    reviews:        2064,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["organiser", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'tem-home-011',
    name:           'Velvet Storage Ottoman Cube',
    category:       'home',
    subcategory:    'Lighting',
    price:          78.42,
    originalPrice:  113.65,
    discount:       31,
    rating:         4.8,
    reviews:        12951,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "lighting", "cube", "decor"]
  },
  {
    id:             'tem-home-012',
    name:           'Woven Seagrass Basket — Large',
    category:       'home',
    subcategory:    'Storage',
    price:          6.06,
    originalPrice:  13.18,
    discount:       54,
    rating:         4.8,
    reviews:        13159,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "basket", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-013',
    name:           'Floating Wall Shelves — Set of 3',
    category:       'home',
    subcategory:    'Furniture',
    price:          58.39,
    originalPrice:  87.15,
    discount:       33,
    rating:         4.0,
    reviews:        11667,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "decor", "interior", "living", "furniture", "shelves"]
  },
  {
    id:             'tem-home-014',
    name:           'Diffuser & Essential Oil Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          13.19,
    originalPrice:  21.27,
    discount:       38,
    rating:         4.8,
    reviews:        14943,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-015',
    name:           'Faux Fur Throw Blanket — Grey',
    category:       'home',
    subcategory:    'Decor',
    price:          22.37,
    originalPrice:  39.95,
    discount:       44,
    rating:         4.2,
    reviews:        14600,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-016',
    name:           'Boho Macramé Wall Hanging',
    category:       'home',
    subcategory:    'Bedding',
    price:          93.7,
    originalPrice:  118.61,
    discount:       21,
    rating:         4.9,
    reviews:        15585,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "hanging", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'tem-home-017',
    name:           'Vintage Table Lamp — Rattan',
    category:       'home',
    subcategory:    'Lighting',
    price:          8.3,
    originalPrice:  16.94,
    discount:       51,
    rating:         4.1,
    reviews:        9123,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "lamp", "lighting", "decor"]
  },
  {
    id:             'tem-home-018',
    name:           'Glass Candle Holder Set',
    category:       'home',
    subcategory:    'Storage',
    price:          11.26,
    originalPrice:  26.8,
    discount:       58,
    rating:         4.2,
    reviews:        10252,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-019',
    name:           'Kitchen Herb Planter — 3 Pots',
    category:       'home',
    subcategory:    'Furniture',
    price:          51.63,
    originalPrice:  109.85,
    discount:       53,
    rating:         4.1,
    reviews:        6994,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "planter", "living", "furniture", "decor"]
  },
  {
    id:             'tem-home-020',
    name:           'Anti-Fatigue Kitchen Mat',
    category:       'home',
    subcategory:    'Kitchen',
    price:          10.1,
    originalPrice:  15.3,
    discount:       34,
    rating:         4.4,
    reviews:        6592,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "mat", "decor"]
  },
  {
    id:             'tem-home-021',
    name:           'Peel & Stick Wallpaper — Botanical',
    category:       'home',
    subcategory:    'Decor',
    price:          12.52,
    originalPrice:  16.69,
    discount:       25,
    rating:         4.7,
    reviews:        22256,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "wallpaper", "decor"]
  },
  {
    id:             'tem-home-022',
    name:           'Smart Plug Power Strip',
    category:       'home',
    subcategory:    'Bedding',
    price:          28.76,
    originalPrice:  65.37,
    discount:       56,
    rating:         4.5,
    reviews:        10345,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "strip", "bedding", "decor"]
  },
  {
    id:             'tem-home-023',
    name:           'Linen Shower Curtain — White',
    category:       'home',
    subcategory:    'Lighting',
    price:          64.88,
    originalPrice:  91.38,
    discount:       29,
    rating:         4.9,
    reviews:        5273,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "curtain", "lighting", "decor"]
  },
  {
    id:             'tem-home-024',
    name:           'Over-Door Towel Rail',
    category:       'home',
    subcategory:    'Storage',
    price:          89.0,
    originalPrice:  114.1,
    discount:       22,
    rating:         4.1,
    reviews:        19811,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "home", "interior", "living", "rail", "decor"]
  },
  {
    id:             'tem-home-025',
    name:           'Plant Pot Set — Pastel Terracotta',
    category:       'home',
    subcategory:    'Furniture',
    price:          12.27,
    originalPrice:  23.15,
    discount:       47,
    rating:         4.3,
    reviews:        3812,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'tem-home-026',
    name:           'Wooden Serving Board',
    category:       'home',
    subcategory:    'Kitchen',
    price:          34.73,
    originalPrice:  65.53,
    discount:       47,
    rating:         4.9,
    reviews:        1799,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "board", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-027',
    name:           'Spice Rack — Rotating Turntable',
    category:       'home',
    subcategory:    'Decor',
    price:          31.94,
    originalPrice:  81.89,
    discount:       61,
    rating:         4.3,
    reviews:        3202,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "rack", "decor"]
  },
  {
    id:             'tem-home-028',
    name:           'Bed Tray Laptop Desk',
    category:       'home',
    subcategory:    'Bedding',
    price:          37.32,
    originalPrice:  69.12,
    discount:       46,
    rating:         4.0,
    reviews:        13403,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "desk", "bedding", "decor"]
  },
  {
    id:             'tem-home-029',
    name:           'Velvet Curtains — Blackout Grey',
    category:       'home',
    subcategory:    'Lighting',
    price:          93.29,
    originalPrice:  116.61,
    discount:       20,
    rating:         4.3,
    reviews:        3553,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "curtains", "lighting", "decor"]
  },
  {
    id:             'tem-home-030',
    name:           'Decorative Wicker Mirror',
    category:       'home',
    subcategory:    'Storage',
    price:          48.59,
    originalPrice:  86.77,
    discount:       44,
    rating:         4.7,
    reviews:        12661,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "home", "interior", "living", "mirror", "decor"]
  },
  {
    id:             'tem-home-031',
    name:           'Stainless Steel Water Bottle — 1L',
    category:       'home',
    subcategory:    'Furniture',
    price:          55.2,
    originalPrice:  81.18,
    discount:       32,
    rating:         4.9,
    reviews:        7006,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "furniture", "bottle", "decor"]
  },
  {
    id:             'tem-home-032',
    name:           'Bamboo Cutting Board Set',
    category:       'home',
    subcategory:    'Kitchen',
    price:          55.04,
    originalPrice:  100.07,
    discount:       45,
    rating:         4.5,
    reviews:        21980,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-033',
    name:           'Shower Caddy — 3 Tier',
    category:       'home',
    subcategory:    'Decor',
    price:          41.76,
    originalPrice:  68.46,
    discount:       39,
    rating:         4.8,
    reviews:        18339,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "decor", "interior", "living", "caddy"]
  },
  {
    id:             'tem-home-034',
    name:           'Framed Print Wall Art Set',
    category:       'home',
    subcategory:    'Bedding',
    price:          22.92,
    originalPrice:  55.91,
    discount:       59,
    rating:         4.1,
    reviews:        5878,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'tem-home-035',
    name:           'Laundry Basket — Woven Rope',
    category:       'home',
    subcategory:    'Lighting',
    price:          16.98,
    originalPrice:  44.69,
    discount:       62,
    rating:         4.8,
    reviews:        19737,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["basket", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'tem-home-036',
    name:           'Electric Kettle — Rose Gold',
    category:       'home',
    subcategory:    'Storage',
    price:          44.86,
    originalPrice:  72.36,
    discount:       38,
    rating:         4.8,
    reviews:        6477,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "home", "kettle", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-037',
    name:           'Air Fryer — 5.5L Digital',
    category:       'home',
    subcategory:    'Furniture',
    price:          10.77,
    originalPrice:  13.99,
    discount:       23,
    rating:         4.0,
    reviews:        985,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "furniture", "fryer", "decor"]
  },
  {
    id:             'tem-home-038',
    name:           'Robot Mop & Vacuum Combo',
    category:       'home',
    subcategory:    'Kitchen',
    price:          14.92,
    originalPrice:  36.4,
    discount:       59,
    rating:         4.5,
    reviews:        16495,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "combo", "decor"]
  },
  {
    id:             'tem-home-039',
    name:           'Weighted Blanket — 8kg',
    category:       'home',
    subcategory:    'Decor',
    price:          54.91,
    originalPrice:  105.6,
    discount:       48,
    rating:         4.2,
    reviews:        9263,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["blanket", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-040',
    name:           'Cordless Stick Vacuum',
    category:       'home',
    subcategory:    'Bedding',
    price:          36.73,
    originalPrice:  51.73,
    discount:       29,
    rating:         4.8,
    reviews:        12400,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["vacuum", "home", "interior", "living", "bedding", "decor"]
  },
  {
    id:             'tem-home-041',
    name:           'Under-Bed Storage Boxes',
    category:       'home',
    subcategory:    'Lighting',
    price:          24.22,
    originalPrice:  48.44,
    discount:       50,
    rating:         4.6,
    reviews:        6476,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["boxes", "home", "interior", "living", "lighting", "decor"]
  },
  {
    id:             'tem-home-042',
    name:           'Memory Foam Pillow — Contour',
    category:       'home',
    subcategory:    'Storage',
    price:          60.33,
    originalPrice:  83.79,
    discount:       28,
    rating:         4.4,
    reviews:        2679,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "pillow", "home", "interior", "living", "decor"]
  },
  {
    id:             'tem-home-043',
    name:           'Ceramic Dinner Set — 16 Piece',
    category:       'home',
    subcategory:    'Furniture',
    price:          22.26,
    originalPrice:  34.24,
    discount:       35,
    rating:         4.8,
    reviews:        4797,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "furniture", "decor"]
  },
  {
    id:             'tem-home-044',
    name:           'Knife Block Set — 7 Piece',
    category:       'home',
    subcategory:    'Kitchen',
    price:          38.75,
    originalPrice:  54.58,
    discount:       29,
    rating:         4.0,
    reviews:        12097,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-045',
    name:           'Bath Mat Set — Non-Slip',
    category:       'home',
    subcategory:    'Decor',
    price:          45.26,
    originalPrice:  119.1,
    discount:       62,
    rating:         4.1,
    reviews:        14095,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "decor"]
  },
  {
    id:             'tem-home-046',
    name:           'Smart Colour Bulb Set — 4 Pack',
    category:       'home',
    subcategory:    'Bedding',
    price:          53.38,
    originalPrice:  73.12,
    discount:       27,
    rating:         4.7,
    reviews:        23339,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "set", "bedding", "decor"]
  },
  {
    id:             'tem-home-047',
    name:           'Blackout Roller Blind',
    category:       'home',
    subcategory:    'Lighting',
    price:          41.52,
    originalPrice:  68.06,
    discount:       39,
    rating:         4.9,
    reviews:        19539,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["home", "interior", "living", "lighting", "blind", "decor"]
  },
  {
    id:             'tem-home-048',
    name:           'Essential Oil Diffuser — Ultrasonic',
    category:       'home',
    subcategory:    'Storage',
    price:          79.15,
    originalPrice:  101.47,
    discount:       22,
    rating:         4.1,
    reviews:        4272,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["storage", "home", "interior", "living", "diffuser", "decor"]
  },
  {
    id:             'tem-home-049',
    name:           'Handheld Garment Steamer',
    category:       'home',
    subcategory:    'Furniture',
    price:          69.43,
    originalPrice:  91.35,
    discount:       24,
    rating:         5.0,
    reviews:        21854,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["steamer", "home", "interior", "living", "furniture", "decor"]
  },
  {
    id:             'tem-home-050',
    name:           'Kitchen Towel Set — Cotton',
    category:       'home',
    subcategory:    'Kitchen',
    price:          55.59,
    originalPrice:  102.95,
    discount:       46,
    rating:         4.9,
    reviews:        13846,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=home+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kitchen", "home", "interior", "living", "set", "decor"]
  }
);
