/* TEMU — Jewelry (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-jewe-001',
    name:           '925 Silver Minimalist Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          70.91,
    originalPrice:  105.84,
    discount:       33,
    rating:         4.2,
    reviews:        20472,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-002',
    name:           'Dainty Layered Gold Chain Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          40.37,
    originalPrice:  54.56,
    discount:       26,
    rating:         4.8,
    reviews:        21627,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-003',
    name:           'Gold Plated Jhumka Earrings Set',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          26.07,
    originalPrice:  66.85,
    discount:       61,
    rating:         4.6,
    reviews:        5079,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'tem-jewe-004',
    name:           'Stacking Rings Set — 10 Piece',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          75.72,
    originalPrice:  105.16,
    discount:       28,
    rating:         5.0,
    reviews:        1617,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'tem-jewe-005',
    name:           'Pearl Stud Earrings — Classic',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          33.09,
    originalPrice:  67.53,
    discount:       51,
    rating:         4.6,
    reviews:        23311,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-006',
    name:           'Statement Hoop Earrings — Gold',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          68.79,
    originalPrice:  110.95,
    discount:       38,
    rating:         4.9,
    reviews:        14664,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-007',
    name:           'Crystal Tennis Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          68.85,
    originalPrice:  118.7,
    discount:       42,
    rating:         4.2,
    reviews:        15924,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-008',
    name:           'Vintage Cameo Brooch',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          43.47,
    originalPrice:  73.68,
    discount:       41,
    rating:         4.3,
    reviews:        5923,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "brooch", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'tem-jewe-009',
    name:           'Turquoise Beaded Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          31.05,
    originalPrice:  69.01,
    discount:       55,
    rating:         4.9,
    reviews:        11552,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-010',
    name:           'Anklet Set — Gold Chain',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          5.67,
    originalPrice:  13.83,
    discount:       59,
    rating:         4.7,
    reviews:        543,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'tem-jewe-011',
    name:           'Heart Locket Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          9.9,
    originalPrice:  27.5,
    discount:       64,
    rating:         4.7,
    reviews:        15039,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-012',
    name:           'Evil Eye Charm Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          22.96,
    originalPrice:  57.39,
    discount:       60,
    rating:         4.4,
    reviews:        542,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-013',
    name:           'Opal Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          26.46,
    originalPrice:  75.61,
    discount:       65,
    rating:         4.1,
    reviews:        20296,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-014',
    name:           'Rose Gold Infinity Bracelet',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          33.63,
    originalPrice:  50.95,
    discount:       34,
    rating:         4.1,
    reviews:        18723,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-015',
    name:           'Diamond CZ Stud Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          21.94,
    originalPrice:  27.43,
    discount:       20,
    rating:         4.3,
    reviews:        24571,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-016',
    name:           'Name Initial Letter Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          55.01,
    originalPrice:  79.73,
    discount:       31,
    rating:         4.8,
    reviews:        21713,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-017',
    name:           'Geometric Triangle Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          5.31,
    originalPrice:  12.94,
    discount:       59,
    rating:         4.7,
    reviews:        882,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-018',
    name:           'Twisted Bangle Set — 5 Pack',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          38.84,
    originalPrice:  59.76,
    discount:       35,
    rating:         4.3,
    reviews:        21224,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'tem-jewe-019',
    name:           'Floral Hair Pins Set',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          26.51,
    originalPrice:  46.5,
    discount:       43,
    rating:         4.9,
    reviews:        17606,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'tem-jewe-020',
    name:           'Moon & Stars Choker',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          70.08,
    originalPrice:  97.33,
    discount:       28,
    rating:         4.9,
    reviews:        6685,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["choker", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-021',
    name:           'Cluster Ring — Pink Tourmaline CZ',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          74.91,
    originalPrice:  97.28,
    discount:       23,
    rating:         4.3,
    reviews:        4519,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["ring", "accessories", "necklaces", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-022',
    name:           'Tassel Drop Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          34.56,
    originalPrice:  90.96,
    discount:       62,
    rating:         4.8,
    reviews:        18259,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-023',
    name:           'Layered Satellite Necklace',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          30.11,
    originalPrice:  49.36,
    discount:       39,
    rating:         4.2,
    reviews:        16755,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "jewelry", "necklace", "earrings", "gold"]
  },
  {
    id:             'tem-jewe-024',
    name:           'Charm Bracelet — Starter',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          35.13,
    originalPrice:  90.07,
    discount:       61,
    rating:         4.2,
    reviews:        8440,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-025',
    name:           'Bar Pendant Necklace — Engraved',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          60.43,
    originalPrice:  116.21,
    discount:       48,
    rating:         4.2,
    reviews:        21156,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-026',
    name:           'Snake Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          42.87,
    originalPrice:  97.43,
    discount:       56,
    rating:         4.8,
    reviews:        7685,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-027',
    name:           'Vintage Pearl Necklace — Multi-Strand',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          52.13,
    originalPrice:  91.45,
    discount:       43,
    rating:         4.1,
    reviews:        4487,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-028',
    name:           'Leaf Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          84.0,
    originalPrice:  116.67,
    discount:       28,
    rating:         4.2,
    reviews:        22824,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-029',
    name:           'Birthstone Ring — Personalised',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          21.01,
    originalPrice:  50.03,
    discount:       58,
    rating:         4.1,
    reviews:        20350,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-030',
    name:           'Celestial Sun Earrings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          78.42,
    originalPrice:  117.05,
    discount:       33,
    rating:         5.0,
    reviews:        12964,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-031',
    name:           'Crystal Choker Necklace',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          48.15,
    originalPrice:  68.78,
    discount:       30,
    rating:         4.5,
    reviews:        13583,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-032',
    name:           'Emerald CZ Cocktail Ring',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          59.71,
    originalPrice:  104.76,
    discount:       43,
    rating:         4.6,
    reviews:        5084,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "ring", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-033',
    name:           'Gold Hoop Set — 3 Pairs',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          51.21,
    originalPrice:  65.66,
    discount:       22,
    rating:         4.4,
    reviews:        1848,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "jewelry", "earrings", "set", "gold"]
  },
  {
    id:             'tem-jewe-034',
    name:           'Cuff Bangle — Hammered Gold',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          32.68,
    originalPrice:  74.27,
    discount:       56,
    rating:         4.9,
    reviews:        24966,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "bangle", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-035',
    name:           'Seed Bead Friendship Bracelet',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          75.32,
    originalPrice:  119.56,
    discount:       37,
    rating:         4.4,
    reviews:        21740,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-036',
    name:           'Safety Pin Earrings',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          37.5,
    originalPrice:  55.15,
    discount:       32,
    rating:         4.5,
    reviews:        9748,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-037',
    name:           'Mismatched Statement Earrings',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          34.38,
    originalPrice:  68.75,
    discount:       50,
    rating:         4.7,
    reviews:        19670,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-038',
    name:           'Charm Bangle — Pandora Style',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          34.78,
    originalPrice:  59.96,
    discount:       42,
    rating:         4.7,
    reviews:        1890,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "bangle", "silver", "jewelry", "earrings", "gold"]
  },
  {
    id:             'tem-jewe-039',
    name:           'Blue Topaz Pendant Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          56.04,
    originalPrice:  90.39,
    discount:       38,
    rating:         4.5,
    reviews:        16819,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-040',
    name:           'Stud Earrings Gift Set',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          44.72,
    originalPrice:  68.8,
    discount:       35,
    rating:         4.4,
    reviews:        12656,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "anklets", "silver", "jewelry", "set", "gold"]
  },
  {
    id:             'tem-jewe-041',
    name:           'Ear Cuff — No Piercing Required',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          34.08,
    originalPrice:  51.63,
    discount:       34,
    rating:         4.0,
    reviews:        20231,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "jewelry", "cuff", "gold"]
  },
  {
    id:             'tem-jewe-042',
    name:           'Link Chain Bracelet',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          58.06,
    originalPrice:  93.65,
    discount:       38,
    rating:         4.7,
    reviews:        22334,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "bracelet", "gold"]
  },
  {
    id:             'tem-jewe-043',
    name:           'Freshwater Pearl Drop Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          37.2,
    originalPrice:  77.51,
    discount:       52,
    rating:         4.2,
    reviews:        1363,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-044',
    name:           'Crystal Headband — Bridal',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          88.58,
    originalPrice:  112.13,
    discount:       21,
    rating:         4.1,
    reviews:        16879,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "headband", "accessories", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-045',
    name:           'Vintage Art Deco Ring',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          60.49,
    originalPrice:  112.01,
    discount:       46,
    rating:         4.2,
    reviews:        16908,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["ring", "accessories", "anklets", "silver", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-046',
    name:           'Flower Stud Earrings — Enamel',
    category:       'jewelry',
    subcategory:    'Necklaces',
    price:          31.57,
    originalPrice:  53.5,
    discount:       41,
    rating:         4.4,
    reviews:        16137,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "necklaces", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-047',
    name:           'Rhinestone Bib Necklace',
    category:       'jewelry',
    subcategory:    'Rings',
    price:          35.02,
    originalPrice:  71.47,
    discount:       51,
    rating:         4.6,
    reviews:        7156,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-048',
    name:           'Asymmetric Dangle Earrings',
    category:       'jewelry',
    subcategory:    'Earrings',
    price:          71.33,
    originalPrice:  90.29,
    discount:       21,
    rating:         4.8,
    reviews:        9780,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["accessories", "silver", "earrings", "jewelry", "gold"]
  },
  {
    id:             'tem-jewe-049',
    name:           'Gold Plated Coin Necklace',
    category:       'jewelry',
    subcategory:    'Bracelets',
    price:          24.04,
    originalPrice:  38.78,
    discount:       38,
    rating:         4.6,
    reviews:        7781,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bracelets", "accessories", "silver", "jewelry", "necklace", "gold"]
  },
  {
    id:             'tem-jewe-050',
    name:           'Stackable Thin Band Rings',
    category:       'jewelry',
    subcategory:    'Anklets',
    price:          41.21,
    originalPrice:  84.1,
    discount:       51,
    rating:         4.5,
    reviews:        11143,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=jewelry+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["rings", "accessories", "anklets", "silver", "jewelry", "gold"]
  }
);
