/* TEMU — Men (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-men-001',
    name:           'Slim Fit Oxford Shirt — White',
    category:       'men',
    subcategory:    'Shirts',
    price:          27.01,
    originalPrice:  51.95,
    discount:       48,
    rating:         4.7,
    reviews:        6902,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shirt"]
  },
  {
    id:             'tem-men-002',
    name:           'Classic Polo Shirt — 5 Colours',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          54.65,
    originalPrice:  68.31,
    discount:       20,
    rating:         4.2,
    reviews:        15927,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "shirt"]
  },
  {
    id:             'tem-men-003',
    name:           'Men\'s Shalwar Kameez — Eid Edition',
    category:       'men',
    subcategory:    'Pants',
    price:          63.72,
    originalPrice:  115.85,
    discount:       45,
    rating:         4.9,
    reviews:        13244,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "kameez"]
  },
  {
    id:             'tem-men-004',
    name:           'Slim Fit Joggers — Stretch Fabric',
    category:       'men',
    subcategory:    'Suits',
    price:          10.92,
    originalPrice:  23.75,
    discount:       54,
    rating:         4.7,
    reviews:        6013,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "joggers"]
  },
  {
    id:             'tem-men-005',
    name:           'Oversized Graphic Tee',
    category:       'men',
    subcategory:    'Activewear',
    price:          10.76,
    originalPrice:  14.35,
    discount:       25,
    rating:         4.4,
    reviews:        22342,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "activewear", "tee"]
  },
  {
    id:             'tem-men-006',
    name:           'Linen Shirt — Short Sleeve',
    category:       'men',
    subcategory:    'Shorts',
    price:          7.26,
    originalPrice:  19.1,
    discount:       62,
    rating:         4.6,
    reviews:        16241,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "shirt"]
  },
  {
    id:             'tem-men-007',
    name:           'Cargo Trousers — Olive',
    category:       'men',
    subcategory:    'Outerwear',
    price:          54.65,
    originalPrice:  95.88,
    discount:       43,
    rating:         4.7,
    reviews:        10325,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "trousers", "outerwear"]
  },
  {
    id:             'tem-men-008',
    name:           'Chino Slim Fit Trousers',
    category:       'men',
    subcategory:    'Shirts',
    price:          39.44,
    originalPrice:  98.6,
    discount:       60,
    rating:         4.1,
    reviews:        8223,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "trousers"]
  },
  {
    id:             'tem-men-009',
    name:           'Zip-Up Hoodie — Grey Marl',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          55.02,
    originalPrice:  103.81,
    discount:       47,
    rating:         4.2,
    reviews:        11048,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["hoodie", "men", "fashion", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'tem-men-010',
    name:           'Merino Wool Crew Neck Jumper',
    category:       'men',
    subcategory:    'Pants',
    price:          50.87,
    originalPrice:  69.69,
    discount:       27,
    rating:         4.2,
    reviews:        13810,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "jumper"]
  },
  {
    id:             'tem-men-011',
    name:           'Denim Jacket — Dark Wash',
    category:       'men',
    subcategory:    'Suits',
    price:          88.74,
    originalPrice:  112.33,
    discount:       21,
    rating:         4.3,
    reviews:        2912,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "suits", "casual", "clothing"]
  },
  {
    id:             'tem-men-012',
    name:           'Puffer Gilet — Navy',
    category:       'men',
    subcategory:    'Activewear',
    price:          31.22,
    originalPrice:  42.77,
    discount:       27,
    rating:         4.0,
    reviews:        2004,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "gilet", "casual", "clothing", "activewear"]
  },
  {
    id:             'tem-men-013',
    name:           'Formal Dress Shirt — French Cuff',
    category:       'men',
    subcategory:    'Shorts',
    price:          67.56,
    originalPrice:  86.61,
    discount:       22,
    rating:         4.2,
    reviews:        23777,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "shirt"]
  },
  {
    id:             'tem-men-014',
    name:           'Tuxedo Suit — Black',
    category:       'men',
    subcategory:    'Outerwear',
    price:          52.84,
    originalPrice:  112.42,
    discount:       53,
    rating:         4.5,
    reviews:        16773,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "suit"]
  },
  {
    id:             'tem-men-015',
    name:           'Bomber Jacket — Khaki',
    category:       'men',
    subcategory:    'Shirts',
    price:          69.48,
    originalPrice:  102.18,
    discount:       32,
    rating:         4.9,
    reviews:        13857,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "shirts", "casual", "clothing"]
  },
  {
    id:             'tem-men-016',
    name:           'Relaxed Fit Linen Trousers',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          39.97,
    originalPrice:  83.27,
    discount:       52,
    rating:         4.2,
    reviews:        16311,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "trousers"]
  },
  {
    id:             'tem-men-017',
    name:           'Henley Shirt — Long Sleeve',
    category:       'men',
    subcategory:    'Pants',
    price:          19.58,
    originalPrice:  39.16,
    discount:       50,
    rating:         4.1,
    reviews:        21436,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "shirt"]
  },
  {
    id:             'tem-men-018',
    name:           'Sherpa Fleece Jacket',
    category:       'men',
    subcategory:    'Suits',
    price:          54.69,
    originalPrice:  81.63,
    discount:       33,
    rating:         4.1,
    reviews:        11938,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "suits", "casual", "clothing"]
  },
  {
    id:             'tem-men-019',
    name:           'Roll-Neck Knit Jumper',
    category:       'men',
    subcategory:    'Activewear',
    price:          47.65,
    originalPrice:  103.59,
    discount:       54,
    rating:         4.3,
    reviews:        3320,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "activewear", "jumper"]
  },
  {
    id:             'tem-men-020',
    name:           'Slim Fit Suit — Charcoal',
    category:       'men',
    subcategory:    'Shorts',
    price:          47.41,
    originalPrice:  91.17,
    discount:       48,
    rating:         4.3,
    reviews:        16482,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "suit"]
  },
  {
    id:             'tem-men-021',
    name:           'Basketball Shorts',
    category:       'men',
    subcategory:    'Outerwear',
    price:          14.81,
    originalPrice:  28.48,
    discount:       48,
    rating:         4.9,
    reviews:        24912,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "outerwear"]
  },
  {
    id:             'tem-men-022',
    name:           'Running Tights — Full Length',
    category:       'men',
    subcategory:    'Shirts',
    price:          29.97,
    originalPrice:  41.06,
    discount:       27,
    rating:         4.1,
    reviews:        23664,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "tights"]
  },
  {
    id:             'tem-men-023',
    name:           'Tech Fleece Tracksuit',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          41.48,
    originalPrice:  109.17,
    discount:       62,
    rating:         4.2,
    reviews:        20113,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "t-shirts", "tracksuit"]
  },
  {
    id:             'tem-men-024',
    name:           'Waterproof Hiking Jacket',
    category:       'men',
    subcategory:    'Pants',
    price:          75.02,
    originalPrice:  102.77,
    discount:       27,
    rating:         4.2,
    reviews:        15826,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "pants", "casual", "clothing"]
  },
  {
    id:             'tem-men-025',
    name:           'Flannel Plaid Shirt',
    category:       'men',
    subcategory:    'Suits',
    price:          33.93,
    originalPrice:  91.7,
    discount:       63,
    rating:         4.7,
    reviews:        9044,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "shirt"]
  },
  {
    id:             'tem-men-026',
    name:           'Muscle Fit T-Shirt Pack x5',
    category:       'men',
    subcategory:    'Activewear',
    price:          49.98,
    originalPrice:  111.07,
    discount:       55,
    rating:         4.3,
    reviews:        24795,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "x5", "activewear"]
  },
  {
    id:             'tem-men-027',
    name:           'Tweed Blazer — Herringbone',
    category:       'men',
    subcategory:    'Shorts',
    price:          32.98,
    originalPrice:  46.45,
    discount:       29,
    rating:         4.4,
    reviews:        2925,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "blazer"]
  },
  {
    id:             'tem-men-028',
    name:           'Leather Biker Jacket',
    category:       'men',
    subcategory:    'Outerwear',
    price:          22.94,
    originalPrice:  30.18,
    discount:       24,
    rating:         4.5,
    reviews:        891,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "outerwear"]
  },
  {
    id:             'tem-men-029',
    name:           'Velour Tracksuit — Navy',
    category:       'men',
    subcategory:    'Shirts',
    price:          20.37,
    originalPrice:  27.16,
    discount:       25,
    rating:         4.5,
    reviews:        15913,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "tracksuit"]
  },
  {
    id:             'tem-men-030',
    name:           'Peacoat — Camel',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          48.22,
    originalPrice:  69.89,
    discount:       31,
    rating:         4.0,
    reviews:        7771,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["peacoat", "men", "fashion", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'tem-men-031',
    name:           'Lightweight Rain Mac',
    category:       'men',
    subcategory:    'Pants',
    price:          38.63,
    originalPrice:  85.85,
    discount:       55,
    rating:         4.7,
    reviews:        1037,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "mac"]
  },
  {
    id:             'tem-men-032',
    name:           'Military Overshirt',
    category:       'men',
    subcategory:    'Suits',
    price:          72.28,
    originalPrice:  114.73,
    discount:       37,
    rating:         4.1,
    reviews:        979,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "overshirt"]
  },
  {
    id:             'tem-men-033',
    name:           'Chelsea Boot Cut Jeans',
    category:       'men',
    subcategory:    'Activewear',
    price:          41.54,
    originalPrice:  71.62,
    discount:       42,
    rating:         4.1,
    reviews:        11887,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "jeans", "casual", "clothing", "activewear"]
  },
  {
    id:             'tem-men-034',
    name:           'Structured Chore Coat',
    category:       'men',
    subcategory:    'Shorts',
    price:          56.47,
    originalPrice:  117.64,
    discount:       52,
    rating:         4.2,
    reviews:        13136,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "coat"]
  },
  {
    id:             'tem-men-035',
    name:           'Striped Rugby Shirt',
    category:       'men',
    subcategory:    'Outerwear',
    price:          26.43,
    originalPrice:  34.77,
    discount:       24,
    rating:         4.2,
    reviews:        20766,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "shirt"]
  },
  {
    id:             'tem-men-036',
    name:           'Longline Parka — Black',
    category:       'men',
    subcategory:    'Shirts',
    price:          34.76,
    originalPrice:  93.95,
    discount:       63,
    rating:         4.9,
    reviews:        21592,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "parka"]
  },
  {
    id:             'tem-men-037',
    name:           'Slim Taper Jeans — Indigo',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          32.97,
    originalPrice:  48.48,
    discount:       32,
    rating:         4.9,
    reviews:        19364,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "jeans", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'tem-men-038',
    name:           'Quarter Zip Sweatshirt',
    category:       'men',
    subcategory:    'Pants',
    price:          39.21,
    originalPrice:  105.98,
    discount:       63,
    rating:         4.5,
    reviews:        20165,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "sweatshirt"]
  },
  {
    id:             'tem-men-039',
    name:           'Hawaiian Short Sleeve Shirt',
    category:       'men',
    subcategory:    'Suits',
    price:          53.09,
    originalPrice:  100.17,
    discount:       47,
    rating:         4.4,
    reviews:        24840,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "shirt"]
  },
  {
    id:             'tem-men-040',
    name:           'Pleated Formal Trousers',
    category:       'men',
    subcategory:    'Activewear',
    price:          69.44,
    originalPrice:  103.64,
    discount:       33,
    rating:         4.3,
    reviews:        9857,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "trousers", "activewear"]
  },
  {
    id:             'tem-men-041',
    name:           'Corduroy Shirt Jacket',
    category:       'men',
    subcategory:    'Shorts',
    price:          40.25,
    originalPrice:  87.51,
    discount:       54,
    rating:         4.6,
    reviews:        12867,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "shorts"]
  },
  {
    id:             'tem-men-042',
    name:           'Ribbed Knit Turtleneck',
    category:       'men',
    subcategory:    'Outerwear',
    price:          49.39,
    originalPrice:  93.18,
    discount:       47,
    rating:         4.6,
    reviews:        9599,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "outerwear", "turtleneck"]
  },
  {
    id:             'tem-men-043',
    name:           'Cargo Shorts',
    category:       'men',
    subcategory:    'Shirts',
    price:          18.78,
    originalPrice:  49.41,
    discount:       62,
    rating:         4.4,
    reviews:        6717,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shorts"]
  },
  {
    id:             'tem-men-044',
    name:           'Double Breasted Waistcoat',
    category:       'men',
    subcategory:    'T-Shirts',
    price:          46.27,
    originalPrice:  82.62,
    discount:       44,
    rating:         4.4,
    reviews:        24750,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "waistcoat", "casual", "clothing", "t-shirts"]
  },
  {
    id:             'tem-men-045',
    name:           'Pique Polo — Long Sleeve',
    category:       'men',
    subcategory:    'Pants',
    price:          21.52,
    originalPrice:  37.76,
    discount:       43,
    rating:         4.1,
    reviews:        21470,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "pants", "casual", "clothing", "polo"]
  },
  {
    id:             'tem-men-046',
    name:           'Slim Fit Tuxedo Trousers',
    category:       'men',
    subcategory:    'Suits',
    price:          20.92,
    originalPrice:  53.64,
    discount:       61,
    rating:         4.3,
    reviews:        19990,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "suits", "casual", "clothing", "trousers"]
  },
  {
    id:             'tem-men-047',
    name:           'Padded Quilted Jacket',
    category:       'men',
    subcategory:    'Activewear',
    price:          57.07,
    originalPrice:  80.38,
    discount:       29,
    rating:         4.0,
    reviews:        1949,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "jacket", "fashion", "casual", "clothing", "activewear"]
  },
  {
    id:             'tem-men-048',
    name:           'Lounge Set — Cotton',
    category:       'men',
    subcategory:    'Shorts',
    price:          26.03,
    originalPrice:  41.99,
    discount:       38,
    rating:         4.9,
    reviews:        23602,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "shorts", "set"]
  },
  {
    id:             'tem-men-049',
    name:           'Stretch Slim Chinos',
    category:       'men',
    subcategory:    'Outerwear',
    price:          47.34,
    originalPrice:  61.48,
    discount:       23,
    rating:         4.3,
    reviews:        6500,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1602810319428-019690571b5b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "casual", "clothing", "chinos", "outerwear"]
  },
  {
    id:             'tem-men-050',
    name:           'Relaxed Fit Jogger Shorts',
    category:       'men',
    subcategory:    'Shirts',
    price:          49.93,
    originalPrice:  84.63,
    discount:       41,
    rating:         5.0,
    reviews:        9326,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=men+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["men", "fashion", "shirts", "casual", "clothing", "shorts"]
  }
);
