/* TEMU — Pets (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-pets-001',
    name:           'Multi-Level Cat Tree with Scratching Post',
    category:       'pets',
    subcategory:    'Dogs',
    price:          76.03,
    originalPrice:  108.62,
    discount:       30,
    rating:         4.2,
    reviews:        3016,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "post", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-002',
    name:           'Cosy Self-Warming Pet Bed — L Size',
    category:       'pets',
    subcategory:    'Cats',
    price:          40.84,
    originalPrice:  55.95,
    discount:       27,
    rating:         4.6,
    reviews:        2804,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "bed", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-003',
    name:           'Interactive Cat Feather Wand Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          31.13,
    originalPrice:  69.17,
    discount:       55,
    rating:         4.1,
    reviews:        8087,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'tem-pets-004',
    name:           'Premium Cat Food — Chicken & Fish 2kg',
    category:       'pets',
    subcategory:    'Fish',
    price:          38.7,
    originalPrice:  94.39,
    discount:       59,
    rating:         4.7,
    reviews:        20931,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "food", "fish", "cat", "animal"]
  },
  {
    id:             'tem-pets-005',
    name:           'GPS Dog Collar Tracker',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          28.01,
    originalPrice:  45.91,
    discount:       39,
    rating:         4.9,
    reviews:        2026,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tracker", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-006',
    name:           'Automatic Pet Feeder — WiFi',
    category:       'pets',
    subcategory:    'Supplies',
    price:          10.77,
    originalPrice:  18.26,
    discount:       41,
    rating:         4.1,
    reviews:        8806,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["feeder", "pets", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'tem-pets-007',
    name:           'Foldable Dog Travel Crate',
    category:       'pets',
    subcategory:    'Dogs',
    price:          21.57,
    originalPrice:  29.15,
    discount:       26,
    rating:         4.1,
    reviews:        15155,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "dogs", "crate", "cat", "animal"]
  },
  {
    id:             'tem-pets-008',
    name:           'Dog Grooming Kit — 5 Piece',
    category:       'pets',
    subcategory:    'Cats',
    price:          38.57,
    originalPrice:  65.38,
    discount:       41,
    rating:         4.5,
    reviews:        6895,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "kit", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-009',
    name:           'Catnip Plush Mouse Toy Set',
    category:       'pets',
    subcategory:    'Birds',
    price:          39.89,
    originalPrice:  56.98,
    discount:       30,
    rating:         4.1,
    reviews:        17572,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "birds", "set", "cat", "animal"]
  },
  {
    id:             'tem-pets-010',
    name:           'Slow Feeder Dog Bowl',
    category:       'pets',
    subcategory:    'Fish',
    price:          17.95,
    originalPrice:  44.88,
    discount:       60,
    rating:         4.1,
    reviews:        6583,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "animal", "fish", "cat", "bowl"]
  },
  {
    id:             'tem-pets-011',
    name:           'Cat Litter Box — Top Entry',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          59.39,
    originalPrice:  102.39,
    discount:       42,
    rating:         4.9,
    reviews:        22450,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-012',
    name:           'Dog Raincoat — Waterproof',
    category:       'pets',
    subcategory:    'Supplies',
    price:          53.12,
    originalPrice:  66.4,
    discount:       20,
    rating:         4.5,
    reviews:        14898,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "supplies", "raincoat", "cat", "animal"]
  },
  {
    id:             'tem-pets-013',
    name:           'Bird Cage Deluxe — 2 Storey',
    category:       'pets',
    subcategory:    'Dogs',
    price:          31.92,
    originalPrice:  72.54,
    discount:       56,
    rating:         4.0,
    reviews:        6321,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "dogs", "deluxe", "cat", "animal"]
  },
  {
    id:             'tem-pets-014',
    name:           'Aquarium LED Light — 30cm',
    category:       'pets',
    subcategory:    'Cats',
    price:          12.01,
    originalPrice:  27.29,
    discount:       56,
    rating:         5.0,
    reviews:        9254,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "light", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-015',
    name:           'Hamster Exercise Wheel — Silent',
    category:       'pets',
    subcategory:    'Birds',
    price:          39.88,
    originalPrice:  68.75,
    discount:       42,
    rating:         4.6,
    reviews:        2781,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "wheel", "birds", "cat", "animal"]
  },
  {
    id:             'tem-pets-016',
    name:           'Puppy Training Pads — 100pk',
    category:       'pets',
    subcategory:    'Fish',
    price:          41.86,
    originalPrice:  65.41,
    discount:       36,
    rating:         4.3,
    reviews:        16965,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "pads", "fish", "cat", "animal"]
  },
  {
    id:             'tem-pets-017',
    name:           'Self-Cleaning Litter Box',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          20.13,
    originalPrice:  37.99,
    discount:       47,
    rating:         4.6,
    reviews:        9080,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "box", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-018',
    name:           'Orthopedic Dog Bed — Memory Foam',
    category:       'pets',
    subcategory:    'Supplies',
    price:          31.33,
    originalPrice:  51.36,
    discount:       39,
    rating:         4.4,
    reviews:        6350,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "bed", "supplies", "cat", "animal"]
  },
  {
    id:             'tem-pets-019',
    name:           'Cat Window Perch — Suction Cup',
    category:       'pets',
    subcategory:    'Dogs',
    price:          89.38,
    originalPrice:  113.14,
    discount:       21,
    rating:         4.9,
    reviews:        10527,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "perch", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-020',
    name:           'Retractable Dog Lead — 5m',
    category:       'pets',
    subcategory:    'Cats',
    price:          28.11,
    originalPrice:  61.1,
    discount:       54,
    rating:         4.5,
    reviews:        3747,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "lead", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-021',
    name:           'Pet Carrier Backpack — Breathable',
    category:       'pets',
    subcategory:    'Birds',
    price:          34.0,
    originalPrice:  70.83,
    discount:       52,
    rating:         4.6,
    reviews:        18487,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "birds", "backpack", "cat", "animal"]
  },
  {
    id:             'tem-pets-022',
    name:           'Cat Drinking Fountain — Filtered',
    category:       'pets',
    subcategory:    'Fish',
    price:          14.07,
    originalPrice:  25.58,
    discount:       45,
    rating:         4.2,
    reviews:        10096,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "fountain", "fish", "cat", "animal"]
  },
  {
    id:             'tem-pets-023',
    name:           'Dog Puzzle Toy — IQ Level 2',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          9.04,
    originalPrice:  24.44,
    discount:       63,
    rating:         4.9,
    reviews:        14652,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "small_pets", "toy", "cat", "animal"]
  },
  {
    id:             'tem-pets-024',
    name:           'Plush Squeaky Dog Toy Set',
    category:       'pets',
    subcategory:    'Supplies',
    price:          42.26,
    originalPrice:  68.16,
    discount:       38,
    rating:         4.2,
    reviews:        12594,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "supplies", "set", "cat", "animal"]
  },
  {
    id:             'tem-pets-025',
    name:           'Flea & Tick Collar',
    category:       'pets',
    subcategory:    'Dogs',
    price:          71.78,
    originalPrice:  107.13,
    discount:       33,
    rating:         4.4,
    reviews:        10080,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "collar", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-026',
    name:           'Dental Chews — 30 Pack',
    category:       'pets',
    subcategory:    'Cats',
    price:          11.58,
    originalPrice:  25.17,
    discount:       54,
    rating:         4.3,
    reviews:        23660,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "chews", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-027',
    name:           'Heated Cat Cave Bed',
    category:       'pets',
    subcategory:    'Birds',
    price:          11.58,
    originalPrice:  15.44,
    discount:       25,
    rating:         4.7,
    reviews:        11499,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "bed", "birds", "cat", "animal"]
  },
  {
    id:             'tem-pets-028',
    name:           'Dog Cooling Mat — Gel',
    category:       'pets',
    subcategory:    'Fish',
    price:          61.14,
    originalPrice:  119.89,
    discount:       49,
    rating:         4.1,
    reviews:        18219,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "fish", "mat", "cat", "animal"]
  },
  {
    id:             'tem-pets-029',
    name:           'Pet Stroller — 3 Wheeler',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          71.73,
    originalPrice:  93.16,
    discount:       23,
    rating:         4.6,
    reviews:        18405,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "small_pets", "stroller", "cat", "animal"]
  },
  {
    id:             'tem-pets-030',
    name:           'Rabbit Hutch — 2 Storey',
    category:       'pets',
    subcategory:    'Supplies',
    price:          90.71,
    originalPrice:  116.29,
    discount:       22,
    rating:         4.6,
    reviews:        6851,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "hutch", "dog", "supplies", "cat", "animal"]
  },
  {
    id:             'tem-pets-031',
    name:           'Fish Tank Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          32.6,
    originalPrice:  65.2,
    discount:       50,
    rating:         5.0,
    reviews:        2003,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-032',
    name:           'Cat Scratching Pad — Cardboard',
    category:       'pets',
    subcategory:    'Cats',
    price:          15.36,
    originalPrice:  41.52,
    discount:       63,
    rating:         4.1,
    reviews:        12353,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "pad", "dog", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-033',
    name:           'Interactive Laser Cat Toy',
    category:       'pets',
    subcategory:    'Birds',
    price:          47.17,
    originalPrice:  61.26,
    discount:       23,
    rating:         4.2,
    reviews:        14033,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "birds", "toy", "cat", "animal"]
  },
  {
    id:             'tem-pets-034',
    name:           'Dog Harness — No-Pull',
    category:       'pets',
    subcategory:    'Fish',
    price:          49.85,
    originalPrice:  95.86,
    discount:       48,
    rating:         4.5,
    reviews:        15044,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "harness", "fish", "cat", "animal"]
  },
  {
    id:             'tem-pets-035',
    name:           'Pet Camera Monitor',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          73.06,
    originalPrice:  97.42,
    discount:       25,
    rating:         4.1,
    reviews:        1711,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "monitor", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-036',
    name:           'Small Animal Hideout Tunnel',
    category:       'pets',
    subcategory:    'Supplies',
    price:          12.31,
    originalPrice:  20.18,
    discount:       39,
    rating:         4.5,
    reviews:        14497,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "supplies", "tunnel", "cat", "animal"]
  },
  {
    id:             'tem-pets-037',
    name:           'Bird Seed Mix — Premium',
    category:       'pets',
    subcategory:    'Dogs',
    price:          20.28,
    originalPrice:  37.55,
    discount:       46,
    rating:         4.4,
    reviews:        21505,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "mix", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-038',
    name:           'Dog Raincoat — Reflective',
    category:       'pets',
    subcategory:    'Cats',
    price:          10.75,
    originalPrice:  27.57,
    discount:       61,
    rating:         4.7,
    reviews:        23092,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "raincoat", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-039',
    name:           'Cat Toy Ball Track',
    category:       'pets',
    subcategory:    'Birds',
    price:          22.61,
    originalPrice:  38.98,
    discount:       42,
    rating:         4.1,
    reviews:        16541,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "track", "birds", "cat", "animal"]
  },
  {
    id:             'tem-pets-040',
    name:           'Dog Agility Training Set',
    category:       'pets',
    subcategory:    'Fish',
    price:          14.36,
    originalPrice:  21.76,
    discount:       34,
    rating:         4.7,
    reviews:        876,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "set", "fish", "cat", "animal"]
  },
  {
    id:             'tem-pets-041',
    name:           'Pet First Aid Kit',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          11.96,
    originalPrice:  19.6,
    discount:       39,
    rating:         4.0,
    reviews:        7324,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "kit", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-042',
    name:           'Catnip Spray — Organic',
    category:       'pets',
    subcategory:    'Supplies',
    price:          24.89,
    originalPrice:  44.45,
    discount:       44,
    rating:         4.6,
    reviews:        22070,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "supplies", "spray", "cat", "animal"]
  },
  {
    id:             'tem-pets-043',
    name:           'Dog Snuffle Mat',
    category:       'pets',
    subcategory:    'Dogs',
    price:          29.6,
    originalPrice:  61.67,
    discount:       52,
    rating:         4.2,
    reviews:        21710,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "dogs", "mat", "cat", "animal"]
  },
  {
    id:             'tem-pets-044',
    name:           'Silicone Pet Food Mat',
    category:       'pets',
    subcategory:    'Cats',
    price:          48.97,
    originalPrice:  116.59,
    discount:       58,
    rating:         5.0,
    reviews:        13458,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "mat", "cat", "animal", "cats"]
  },
  {
    id:             'tem-pets-045',
    name:           'Pet Nail Grinder — Quiet',
    category:       'pets',
    subcategory:    'Birds',
    price:          5.43,
    originalPrice:  13.93,
    discount:       61,
    rating:         4.2,
    reviews:        16976,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "birds", "grinder", "cat", "animal"]
  },
  {
    id:             'tem-pets-046',
    name:           'Bird Perch Stand',
    category:       'pets',
    subcategory:    'Fish',
    price:          13.25,
    originalPrice:  21.37,
    discount:       38,
    rating:         4.7,
    reviews:        11616,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "fish", "stand", "cat", "animal"]
  },
  {
    id:             'tem-pets-047',
    name:           'Dog Life Jacket',
    category:       'pets',
    subcategory:    'Small Pets',
    price:          27.31,
    originalPrice:  63.52,
    discount:       57,
    rating:         4.4,
    reviews:        16443,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["jacket", "pets", "dog", "small_pets", "cat", "animal"]
  },
  {
    id:             'tem-pets-048',
    name:           'Cat Collar with Bell',
    category:       'pets',
    subcategory:    'Supplies',
    price:          29.2,
    originalPrice:  64.88,
    discount:       55,
    rating:         4.1,
    reviews:        7771,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "supplies", "bell", "cat", "animal"]
  },
  {
    id:             'tem-pets-049',
    name:           'Kitten Starter Kit',
    category:       'pets',
    subcategory:    'Dogs',
    price:          12.15,
    originalPrice:  25.85,
    discount:       53,
    rating:         4.8,
    reviews:        2867,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "kit", "dog", "dogs", "cat", "animal"]
  },
  {
    id:             'tem-pets-050',
    name:           'Puppy Welcome Home Set',
    category:       'pets',
    subcategory:    'Cats',
    price:          31.45,
    originalPrice:  50.72,
    discount:       38,
    rating:         4.3,
    reviews:        17736,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=pets+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["pets", "dog", "set", "cat", "animal", "cats"]
  }
);
