/* TEMU — Shoes (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-shoe-001',
    name:           'Women\'s Platform Sneakers — White',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          40.54,
    originalPrice:  69.9,
    discount:       42,
    rating:         4.0,
    reviews:        12989,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'tem-shoe-002',
    name:           'Chunky Platform Loafers — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          62.86,
    originalPrice:  99.77,
    discount:       37,
    rating:         4.9,
    reviews:        18665,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes"]
  },
  {
    id:             'tem-shoe-003',
    name:           'Men\'s Casual Sneakers — White',
    category:       'shoes',
    subcategory:    'Flats',
    price:          63.95,
    originalPrice:  116.28,
    discount:       45,
    rating:         4.3,
    reviews:        17278,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'tem-shoe-004',
    name:           'Ankle Strap Block Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          15.65,
    originalPrice:  26.53,
    discount:       41,
    rating:         4.7,
    reviews:        16441,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-005',
    name:           'Bata Comfort Sandals — Women\'s',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          34.71,
    originalPrice:  68.06,
    discount:       49,
    rating:         4.3,
    reviews:        6908,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-006',
    name:           'Chelsea Boots — Tan Leather',
    category:       'shoes',
    subcategory:    'Sport',
    price:          18.89,
    originalPrice:  30.46,
    discount:       38,
    rating:         4.4,
    reviews:        4398,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-007',
    name:           'High Top Canvas Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          28.08,
    originalPrice:  40.12,
    discount:       30,
    rating:         4.4,
    reviews:        20724,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'tem-shoe-008',
    name:           'Stiletto Heeled Mules',
    category:       'shoes',
    subcategory:    'Heels',
    price:          6.65,
    originalPrice:  17.49,
    discount:       62,
    rating:         4.6,
    reviews:        3015,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'tem-shoe-009',
    name:           'Running Trainers — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          18.89,
    originalPrice:  49.7,
    discount:       62,
    rating:         4.9,
    reviews:        10740,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'tem-shoe-010',
    name:           'Strappy Kitten Heel Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          36.67,
    originalPrice:  55.56,
    discount:       34,
    rating:         4.3,
    reviews:        5612,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-011',
    name:           'Slip-On Loafers — Suede',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          10.0,
    originalPrice:  24.38,
    discount:       59,
    rating:         4.4,
    reviews:        14157,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["loafers", "sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-012',
    name:           'Combat Boots — Lace Up',
    category:       'shoes',
    subcategory:    'Sport',
    price:          40.83,
    originalPrice:  69.21,
    discount:       41,
    rating:         4.9,
    reviews:        15865,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-013',
    name:           'Wedge Espadrilles — Nude',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          37.19,
    originalPrice:  82.65,
    discount:       55,
    rating:         4.4,
    reviews:        19122,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'tem-shoe-014',
    name:           'Pointed Toe Pumps — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          34.1,
    originalPrice:  79.31,
    discount:       57,
    rating:         4.9,
    reviews:        9786,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "pumps"]
  },
  {
    id:             'tem-shoe-015',
    name:           'Kids\' Light-Up Trainers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          38.79,
    originalPrice:  76.05,
    discount:       49,
    rating:         4.9,
    reviews:        11259,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "trainers", "shoes"]
  },
  {
    id:             'tem-shoe-016',
    name:           'Hiking Boots — Waterproof',
    category:       'shoes',
    subcategory:    'Boots',
    price:          28.96,
    originalPrice:  74.26,
    discount:       61,
    rating:         4.8,
    reviews:        20025,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-017',
    name:           'Ballet Flats — Blush Pink',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          16.47,
    originalPrice:  36.61,
    discount:       55,
    rating:         4.3,
    reviews:        23958,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-018',
    name:           'Over-Knee Boots — Tan',
    category:       'shoes',
    subcategory:    'Sport',
    price:          25.03,
    originalPrice:  62.57,
    discount:       60,
    rating:         5.0,
    reviews:        4405,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-019',
    name:           'Knit Sock Trainers',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          27.92,
    originalPrice:  39.89,
    discount:       30,
    rating:         4.6,
    reviews:        19792,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "trainers", "shoes"]
  },
  {
    id:             'tem-shoe-020',
    name:           'T-Bar Mary Jane Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          31.33,
    originalPrice:  74.6,
    discount:       58,
    rating:         4.7,
    reviews:        22496,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'tem-shoe-021',
    name:           'Kids\' Wellies — Polka Dot',
    category:       'shoes',
    subcategory:    'Flats',
    price:          53.15,
    originalPrice:  115.55,
    discount:       54,
    rating:         4.7,
    reviews:        18736,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "wellies", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'tem-shoe-022',
    name:           'Slingback Kitten Heels',
    category:       'shoes',
    subcategory:    'Boots',
    price:          17.59,
    originalPrice:  34.5,
    discount:       49,
    rating:         4.3,
    reviews:        6115,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-023',
    name:           'Square-Toe Mules — Croc Effect',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          14.4,
    originalPrice:  31.99,
    discount:       55,
    rating:         4.7,
    reviews:        6489,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-024',
    name:           'Gladiator Sandals',
    category:       'shoes',
    subcategory:    'Sport',
    price:          79.71,
    originalPrice:  102.19,
    discount:       22,
    rating:         4.9,
    reviews:        6467,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-025',
    name:           'Ankle Boots — Stacked Heel',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          48.21,
    originalPrice:  79.04,
    discount:       39,
    rating:         4.3,
    reviews:        24635,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-026',
    name:           'Velvet Court Shoes — Emerald',
    category:       'shoes',
    subcategory:    'Heels',
    price:          65.03,
    originalPrice:  106.6,
    discount:       39,
    rating:         4.8,
    reviews:        13844,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'tem-shoe-027',
    name:           'Flip Flops — Foam',
    category:       'shoes',
    subcategory:    'Flats',
    price:          11.97,
    originalPrice:  15.54,
    discount:       23,
    rating:         4.1,
    reviews:        9001,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "flops", "shoes"]
  },
  {
    id:             'tem-shoe-028',
    name:           'Lace-Up Oxford Brogues',
    category:       'shoes',
    subcategory:    'Boots',
    price:          43.04,
    originalPrice:  107.61,
    discount:       60,
    rating:         4.7,
    reviews:        23297,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "brogues", "shoes"]
  },
  {
    id:             'tem-shoe-029',
    name:           'Metallic Strappy Heels',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          44.9,
    originalPrice:  106.9,
    discount:       58,
    rating:         4.0,
    reviews:        24553,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-030',
    name:           'Platform Chelsea Boots',
    category:       'shoes',
    subcategory:    'Sport',
    price:          17.75,
    originalPrice:  45.5,
    discount:       61,
    rating:         4.3,
    reviews:        8172,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-031',
    name:           'Open-Toe Wedge Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          77.98,
    originalPrice:  108.3,
    discount:       28,
    rating:         4.0,
    reviews:        17548,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-032',
    name:           'Moccasin Slippers',
    category:       'shoes',
    subcategory:    'Heels',
    price:          67.86,
    originalPrice:  90.48,
    discount:       25,
    rating:         5.0,
    reviews:        2293,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "slippers", "footwear", "heels", "shoes"]
  },
  {
    id:             'tem-shoe-033',
    name:           'Sporty Slides — Men\'s',
    category:       'shoes',
    subcategory:    'Flats',
    price:          27.91,
    originalPrice:  64.9,
    discount:       57,
    rating:         4.5,
    reviews:        22656,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "slides", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'tem-shoe-034',
    name:           'Peep-Toe Slingbacks',
    category:       'shoes',
    subcategory:    'Boots',
    price:          41.63,
    originalPrice:  109.56,
    discount:       62,
    rating:         4.2,
    reviews:        22895,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "slingbacks"]
  },
  {
    id:             'tem-shoe-035',
    name:           'Classic White Tennis Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          5.83,
    originalPrice:  14.58,
    discount:       60,
    rating:         4.2,
    reviews:        9994,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-036',
    name:           'Dad Trainer — Chunky',
    category:       'shoes',
    subcategory:    'Sport',
    price:          23.97,
    originalPrice:  54.48,
    discount:       56,
    rating:         4.1,
    reviews:        23950,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "trainer", "sport", "shoes"]
  },
  {
    id:             'tem-shoe-037',
    name:           'Espadrille Wedge Mules',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          37.73,
    originalPrice:  82.03,
    discount:       54,
    rating:         4.1,
    reviews:        22359,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "mules", "shoes"]
  },
  {
    id:             'tem-shoe-038',
    name:           'Patent Ankle Strap Heels',
    category:       'shoes',
    subcategory:    'Heels',
    price:          31.23,
    originalPrice:  53.85,
    discount:       42,
    rating:         4.7,
    reviews:        6644,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'tem-shoe-039',
    name:           'Knee High Flat Boots',
    category:       'shoes',
    subcategory:    'Flats',
    price:          66.44,
    originalPrice:  110.74,
    discount:       40,
    rating:         4.9,
    reviews:        18335,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-040',
    name:           'Woven Mule Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          29.46,
    originalPrice:  41.5,
    discount:       29,
    rating:         4.3,
    reviews:        6870,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-041',
    name:           'Men\'s Derby Shoes',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          17.04,
    originalPrice:  43.69,
    discount:       61,
    rating:         4.3,
    reviews:        5770,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-042',
    name:           'Snow Boots — Fur Lined',
    category:       'shoes',
    subcategory:    'Sport',
    price:          65.64,
    originalPrice:  96.53,
    discount:       32,
    rating:         4.9,
    reviews:        6132,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "sport", "boots", "shoes"]
  },
  {
    id:             'tem-shoe-043',
    name:           'Transparent Heeled Sandals',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          61.34,
    originalPrice:  85.2,
    discount:       28,
    rating:         4.2,
    reviews:        16988,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-044',
    name:           'Slip-On Canvas Espadrilles',
    category:       'shoes',
    subcategory:    'Heels',
    price:          60.7,
    originalPrice:  90.6,
    discount:       33,
    rating:         4.3,
    reviews:        7310,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "espadrilles", "footwear", "heels", "shoes"]
  },
  {
    id:             'tem-shoe-045',
    name:           'Low Top Leather Sneakers',
    category:       'shoes',
    subcategory:    'Flats',
    price:          16.71,
    originalPrice:  23.21,
    discount:       28,
    rating:         4.4,
    reviews:        22755,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "flats", "shoes"]
  },
  {
    id:             'tem-shoe-046',
    name:           'Platform Flip Flop Sandals',
    category:       'shoes',
    subcategory:    'Boots',
    price:          79.37,
    originalPrice:  113.38,
    discount:       30,
    rating:         4.2,
    reviews:        12542,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-047',
    name:           'Ankle Boots — Pointed Toe',
    category:       'shoes',
    subcategory:    'Sandals',
    price:          59.12,
    originalPrice:  96.91,
    discount:       39,
    rating:         4.5,
    reviews:        13091,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "footwear", "heels", "boots", "shoes", "sandals"]
  },
  {
    id:             'tem-shoe-048',
    name:           'Sporty Slides — Women\'s',
    category:       'shoes',
    subcategory:    'Sport',
    price:          18.62,
    originalPrice:  42.31,
    discount:       56,
    rating:         4.7,
    reviews:        1951,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["sneakers", "slides", "footwear", "heels", "sport", "shoes"]
  },
  {
    id:             'tem-shoe-049',
    name:           'Men\'s Boat Shoes — Tan',
    category:       'shoes',
    subcategory:    'Sneakers',
    price:          33.49,
    originalPrice:  95.69,
    discount:       65,
    rating:         4.6,
    reviews:        20857,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  },
  {
    id:             'tem-shoe-050',
    name:           'Kids\' School Shoes — Black',
    category:       'shoes',
    subcategory:    'Heels',
    price:          16.63,
    originalPrice:  30.8,
    discount:       46,
    rating:         4.1,
    reviews:        20696,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=shoes+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["footwear", "heels", "sneakers", "shoes"]
  }
);
