/* TEMU — Toys (50 products)
   Auto-generated for affiliate-main.js
   Loaded by affiliate-temu.js index file
*/

window.TemuProducts = window.TemuProducts || [];

window.TemuProducts.push(
  {
    id:             'tem-toys-001',
    name:           'STEM Building Blocks Set — 250 Pieces',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          34.97,
    originalPrice:  81.32,
    discount:       57,
    rating:         4.4,
    reviews:        3611,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+1&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'tem-toys-002',
    name:           'Remote Control Car — Off-Road 4WD',
    category:       'toys',
    subcategory:    'Board Games',
    price:          52.26,
    originalPrice:  75.74,
    discount:       31,
    rating:         4.8,
    reviews:        869,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+2&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "car", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-003',
    name:           'Diamond Painting Kit — Beginner',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          57.55,
    originalPrice:  94.34,
    discount:       39,
    rating:         4.5,
    reviews:        9544,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+3&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'tem-toys-004',
    name:           'Magnetic Drawing Board',
    category:       'toys',
    subcategory:    'Educational',
    price:          45.11,
    originalPrice:  69.4,
    discount:       35,
    rating:         4.7,
    reviews:        13919,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+4&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "board", "toys", "educational", "play"]
  },
  {
    id:             'tem-toys-005',
    name:           'Wooden Balance Bike — 3-6 Years',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          38.14,
    originalPrice:  56.92,
    discount:       33,
    rating:         4.1,
    reviews:        16895,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+5&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "bike"]
  },
  {
    id:             'tem-toys-006',
    name:           'Interactive Robot Toy',
    category:       'toys',
    subcategory:    'STEM',
    price:          66.46,
    originalPrice:  110.76,
    discount:       40,
    rating:         4.7,
    reviews:        3405,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+6&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "toy", "stem"]
  },
  {
    id:             'tem-toys-007',
    name:           'Art & Craft Mega Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          19.4,
    originalPrice:  41.27,
    discount:       53,
    rating:         4.6,
    reviews:        17143,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+7&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'tem-toys-008',
    name:           'Foam Nerf-Style Blaster',
    category:       'toys',
    subcategory:    'Board Games',
    price:          40.17,
    originalPrice:  58.22,
    discount:       31,
    rating:         4.4,
    reviews:        21221,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+8&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "blaster", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-009',
    name:           'Mini Drone — Beginner Friendly',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          16.3,
    originalPrice:  39.76,
    discount:       59,
    rating:         4.9,
    reviews:        16249,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+9&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["drone", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'tem-toys-010',
    name:           'Kids\' Walkie Talkies — 1km Range',
    category:       'toys',
    subcategory:    'Educational',
    price:          76.13,
    originalPrice:  118.95,
    discount:       36,
    rating:         4.7,
    reviews:        19680,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+10&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["talkies", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'tem-toys-011',
    name:           'Dollhouse — 3-Storey Wooden',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          16.35,
    originalPrice:  24.4,
    discount:       33,
    rating:         4.8,
    reviews:        17067,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+11&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["dollhouse", "kids", "games", "toys", "outdoor", "play"]
  },
  {
    id:             'tem-toys-012',
    name:           'Train Set — 130 Pieces',
    category:       'toys',
    subcategory:    'STEM',
    price:          36.84,
    originalPrice:  83.72,
    discount:       56,
    rating:         4.1,
    reviews:        11392,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+12&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'tem-toys-013',
    name:           'Slime Making Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          34.29,
    originalPrice:  71.44,
    discount:       52,
    rating:         4.6,
    reviews:        23021,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+13&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'tem-toys-014',
    name:           'Sensory Sand Tray',
    category:       'toys',
    subcategory:    'Board Games',
    price:          31.0,
    originalPrice:  83.79,
    discount:       63,
    rating:         4.6,
    reviews:        18590,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+14&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "tray", "games", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-015',
    name:           'Bubble Machine — Automatic',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          28.4,
    originalPrice:  56.8,
    discount:       50,
    rating:         4.1,
    reviews:        8784,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+15&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "puzzles", "play", "machine"]
  },
  {
    id:             'tem-toys-016',
    name:           'Giant Floor Puzzle — 100 Pieces',
    category:       'toys',
    subcategory:    'Educational',
    price:          38.32,
    originalPrice:  100.83,
    discount:       62,
    rating:         4.4,
    reviews:        11695,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+16&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "educational", "play", "puzzle"]
  },
  {
    id:             'tem-toys-017',
    name:           'Pop It Fidget Toy Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          46.39,
    originalPrice:  72.48,
    discount:       36,
    rating:         4.5,
    reviews:        6013,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+17&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'tem-toys-018',
    name:           'Water Balloons — Self-Sealing 100pk',
    category:       'toys',
    subcategory:    'STEM',
    price:          31.37,
    originalPrice:  64.02,
    discount:       51,
    rating:         4.7,
    reviews:        9690,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+18&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "balloons", "toys", "play", "stem"]
  },
  {
    id:             'tem-toys-019',
    name:           'Kinetic Sand Set — 3kg',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          5.97,
    originalPrice:  17.05,
    discount:       65,
    rating:         4.6,
    reviews:        21804,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+19&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'tem-toys-020',
    name:           'Outdoor Trampoline — 10ft',
    category:       'toys',
    subcategory:    'Board Games',
    price:          51.64,
    originalPrice:  71.72,
    discount:       28,
    rating:         4.8,
    reviews:        24330,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+20&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "trampoline", "games", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-021',
    name:           'Foam Ball Pit + 200 Balls',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          79.21,
    originalPrice:  108.51,
    discount:       27,
    rating:         4.5,
    reviews:        6274,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+21&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "balls", "puzzles", "play"]
  },
  {
    id:             'tem-toys-022',
    name:           'Science Experiment Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          65.43,
    originalPrice:  89.63,
    discount:       27,
    rating:         4.6,
    reviews:        13425,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+22&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'tem-toys-023',
    name:           'Perler Bead Set — 5000 Pieces',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          12.57,
    originalPrice:  24.65,
    discount:       49,
    rating:         4.0,
    reviews:        10125,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+23&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'tem-toys-024',
    name:           'Sticker Activity Book',
    category:       'toys',
    subcategory:    'STEM',
    price:          35.5,
    originalPrice:  88.76,
    discount:       60,
    rating:         4.2,
    reviews:        11403,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+24&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "book", "games", "toys", "play", "stem"]
  },
  {
    id:             'tem-toys-025',
    name:           'Action Figure Set — 12 Characters',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          48.87,
    originalPrice:  103.98,
    discount:       53,
    rating:         4.8,
    reviews:        3926,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+25&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'tem-toys-026',
    name:           'Play Kitchen Set',
    category:       'toys',
    subcategory:    'Board Games',
    price:          11.56,
    originalPrice:  30.43,
    discount:       62,
    rating:         4.7,
    reviews:        18634,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+26&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "board_games"]
  },
  {
    id:             'tem-toys-027',
    name:           'Magnetic Tiles Set — 60 Pieces',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          12.44,
    originalPrice:  15.95,
    discount:       22,
    rating:         4.4,
    reviews:        10036,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+27&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "puzzles", "play", "set"]
  },
  {
    id:             'tem-toys-028',
    name:           'Soft Play Crawl Tunnel',
    category:       'toys',
    subcategory:    'Educational',
    price:          25.27,
    originalPrice:  49.54,
    discount:       49,
    rating:         4.3,
    reviews:        18866,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+28&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "educational", "play", "tunnel"]
  },
  {
    id:             'tem-toys-029',
    name:           'Outdoor Swing — Timber Frame',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          7.25,
    originalPrice:  12.95,
    discount:       44,
    rating:         4.8,
    reviews:        16026,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+29&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "swing"]
  },
  {
    id:             'tem-toys-030',
    name:           'Bath Toy Set — Squirt Animals',
    category:       'toys',
    subcategory:    'STEM',
    price:          15.99,
    originalPrice:  31.35,
    discount:       49,
    rating:         4.3,
    reviews:        13947,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+30&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'tem-toys-031',
    name:           'Wooden Stacking Tower',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          41.22,
    originalPrice:  114.5,
    discount:       64,
    rating:         4.4,
    reviews:        12906,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+31&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["tower", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'tem-toys-032',
    name:           'Finger Painting Kit — Washable',
    category:       'toys',
    subcategory:    'Board Games',
    price:          44.85,
    originalPrice:  99.66,
    discount:       55,
    rating:         4.3,
    reviews:        24647,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+32&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-033',
    name:           'Stuffed Animal Bundle — 5 Pack',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          34.95,
    originalPrice:  65.95,
    discount:       47,
    rating:         4.1,
    reviews:        20534,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+33&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bundle", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'tem-toys-034',
    name:           'Mini Basketball Hoop — Indoor',
    category:       'toys',
    subcategory:    'Educational',
    price:          42.74,
    originalPrice:  118.72,
    discount:       64,
    rating:         4.3,
    reviews:        4609,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+34&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "educational", "hoop", "play"]
  },
  {
    id:             'tem-toys-035',
    name:           'Kids\' Karaoke Machine',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          47.1,
    originalPrice:  71.37,
    discount:       34,
    rating:         4.1,
    reviews:        2846,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+35&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "machine"]
  },
  {
    id:             'tem-toys-036',
    name:           'Roller Skates — Adjustable',
    category:       'toys',
    subcategory:    'STEM',
    price:          16.66,
    originalPrice:  23.8,
    discount:       30,
    rating:         4.8,
    reviews:        15559,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+36&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["skates", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'tem-toys-037',
    name:           'Toy Cash Register',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          39.45,
    originalPrice:  80.52,
    discount:       51,
    rating:         4.6,
    reviews:        7761,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+37&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "action_figures", "register"]
  },
  {
    id:             'tem-toys-038',
    name:           'Kids\' Binoculars',
    category:       'toys',
    subcategory:    'Board Games',
    price:          31.1,
    originalPrice:  57.6,
    discount:       46,
    rating:         4.7,
    reviews:        7482,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+38&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["binoculars", "kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-039',
    name:           'Sand Water Table',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          16.96,
    originalPrice:  36.08,
    discount:       53,
    rating:         4.4,
    reviews:        9699,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+39&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "table", "puzzles", "play"]
  },
  {
    id:             'tem-toys-040',
    name:           'Lacing & Threading Set',
    category:       'toys',
    subcategory:    'Educational',
    price:          16.15,
    originalPrice:  23.41,
    discount:       31,
    rating:         4.6,
    reviews:        16820,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+40&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "educational", "play", "set"]
  },
  {
    id:             'tem-toys-041',
    name:           'Giant Jenga — Outdoor',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          19.45,
    originalPrice:  44.21,
    discount:       56,
    rating:         5.0,
    reviews:        8512,
    badge:          'new',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+41&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "jenga"]
  },
  {
    id:             'tem-toys-042',
    name:           'Playdough 12-Colour Set',
    category:       'toys',
    subcategory:    'STEM',
    price:          49.87,
    originalPrice:  69.26,
    discount:       28,
    rating:         4.2,
    reviews:        17298,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+42&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "stem"]
  },
  {
    id:             'tem-toys-043',
    name:           'Solar System Model Kit',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          67.02,
    originalPrice:  91.81,
    discount:       27,
    rating:         4.3,
    reviews:        18811,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+43&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "play", "action_figures"]
  },
  {
    id:             'tem-toys-044',
    name:           'Coding Robot for Kids',
    category:       'toys',
    subcategory:    'Board Games',
    price:          42.27,
    originalPrice:  69.3,
    discount:       39,
    rating:         4.5,
    reviews:        12189,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+44&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "board_games"]
  },
  {
    id:             'tem-toys-045',
    name:           'Fairy Garden Kit',
    category:       'toys',
    subcategory:    'Puzzles',
    price:          64.8,
    originalPrice:  115.72,
    discount:       44,
    rating:         5.0,
    reviews:        16792,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+45&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "puzzles", "play"]
  },
  {
    id:             'tem-toys-046',
    name:           'Space Rover Build Kit',
    category:       'toys',
    subcategory:    'Educational',
    price:          17.56,
    originalPrice:  27.44,
    discount:       36,
    rating:         4.8,
    reviews:        12469,
    badge:          'hot',
    image:          'https://images.unsplash.com/photo-1484824823219-7eb73c1ea19c?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+46&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kit", "kids", "games", "toys", "educational", "play"]
  },
  {
    id:             'tem-toys-047',
    name:           'Kids\' Archery Set',
    category:       'toys',
    subcategory:    'Outdoor',
    price:          13.16,
    originalPrice:  27.42,
    discount:       52,
    rating:         4.1,
    reviews:        18396,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+47&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "outdoor", "play", "set"]
  },
  {
    id:             'tem-toys-048',
    name:           'Board Game Bundle — 5 Games',
    category:       'toys',
    subcategory:    'STEM',
    price:          53.78,
    originalPrice:  109.76,
    discount:       51,
    rating:         5.0,
    reviews:        14381,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+48&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["bundle", "kids", "games", "toys", "play", "stem"]
  },
  {
    id:             'tem-toys-049',
    name:           'Glow in Dark Stars Set',
    category:       'toys',
    subcategory:    'Action Figures',
    price:          11.06,
    originalPrice:  22.13,
    discount:       50,
    rating:         4.5,
    reviews:        12564,
    badge:          'sale',
    image:          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+49&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "set", "action_figures"]
  },
  {
    id:             'tem-toys-050',
    name:           'Rocket Launcher + Foam Rockets',
    category:       'toys',
    subcategory:    'Board Games',
    price:          53.88,
    originalPrice:  117.14,
    discount:       54,
    rating:         4.6,
    reviews:        299,
    badge:          'bestseller',
    image:          'https://images.unsplash.com/photo-1582387890485-18c770ade9c6?w=400&h=400&fit=crop&auto=format',
    url:            'https://www.temu.com/search?query=toys+product+50&refer_aff_src=meowmeow',
    marketplace:    'Temu',
    marketplaceIcon: 'fas fa-shopping-bag',
    tags:           ["kids", "games", "toys", "play", "board_games", "rockets"]
  }
);
